import Link from "next/link";
import { CheckCircle2, CircleAlert, ExternalLink, Settings2, ShieldCheck } from "lucide-react";
import { requireCreator } from "@/lib/dal";
import { appUrl } from "@/lib/app-url";

export default async function RecoveryPassSettingsPage() {
  const creator = await requireCreator();
  const active = Boolean(creator.recovery_pass_enabled && creator.public_profile_enabled && creator.public_slug);
  const publicUrl = creator.public_slug ? `${appUrl().replace(/\/$/, "")}/${creator.public_slug}` : null;
  return <><header><p className="eyebrow">Settings</p><h1 className="mt-2 text-3xl font-semibold">Recovery Pass</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-zinc-400">Review creator-side Recovery Pass status and open the canonical controls that power it.</p></header><section className="surface mt-8 rounded-2xl p-6 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-5"><div className="flex gap-4"><span className={`grid size-11 place-items-center rounded-xl ${active ? "bg-emerald-400/10 text-emerald-300" : "bg-amber-400/10 text-amber-200"}`}>{active ? <CheckCircle2 aria-hidden size={20}/> : <CircleAlert aria-hidden size={20}/>}</span><div><p className="text-sm text-zinc-500">Current status</p><h2 className="mt-1 text-xl font-semibold">{active ? "Active and published" : "Action required"}</h2><p className="mt-2 max-w-xl text-sm leading-6 text-zinc-400">{active ? "Your permanent creator identity and Recovery Pass are available to your audience." : "Complete your creator identity and publishing setup before sharing your Recovery Pass."}</p></div></div>{publicUrl && <a href={publicUrl} target="_blank" rel="noopener noreferrer" className="button button-secondary min-h-11">View Recovery Pass <ExternalLink aria-hidden size={15}/></a>}</div></section><div className="mt-6 grid gap-4 sm:grid-cols-2"><Link href="/dashboard/creator-page" className="surface rounded-2xl p-6 transition hover:border-violet-300/20 focus-visible:outline focus-visible:outline-2 focus-visible:outline-violet-400"><ShieldCheck aria-hidden className="text-violet-300"/><h2 className="mt-5 font-semibold">Identity and sharing</h2><p className="mt-2 text-sm leading-6 text-zinc-500">Edit the Recovery Pass identity, preview readiness, and use the existing sharing controls.</p></Link><Link href="/dashboard/platforms" className="surface rounded-2xl p-6 transition hover:border-violet-300/20 focus-visible:outline focus-visible:outline-2 focus-visible:outline-violet-400"><Settings2 aria-hidden className="text-violet-300"/><h2 className="mt-5 font-semibold">Recovery destinations</h2><p className="mt-2 text-sm leading-6 text-zinc-500">Manage the real Main and Recovery accounts available to your audience.</p></Link></div></>;
}
