begin;
select plan(30);
select has_table('public','creator_authenticity_manifests','manifest projections exist');
select has_table('public','creator_continuity_statements','continuity statements exist');
select has_table('public','authenticity_network_subscriptions','network subscriptions exist');
select has_table('public','authenticity_network_deliveries','network deliveries exist');
select ok((select relforcerowsecurity from pg_class where oid='public.creator_authenticity_manifests'::regclass),'manifest FORCE RLS');
select ok((select relforcerowsecurity from pg_class where oid='public.creator_continuity_statements'::regclass),'continuity FORCE RLS');
select ok((select relforcerowsecurity from pg_class where oid='public.authenticity_network_subscriptions'::regclass),'subscription FORCE RLS');
select ok((select relforcerowsecurity from pg_class where oid='public.authenticity_network_deliveries'::regclass),'delivery FORCE RLS');
select policies_are('public','creator_authenticity_manifests',array['creator manifest reads'],'manifest creator isolation');
select policies_are('public','creator_continuity_statements',array['creator continuity reads'],'continuity creator isolation');
select policies_are('public','authenticity_network_subscriptions',array['developer subscription deletes','developer subscription inserts','developer subscription reads','developer subscription updates'],'subscription ownership policies');
select policies_are('public','authenticity_network_deliveries',array['developer delivery reads'],'delivery ownership policy');
select table_privs_are('public','creator_authenticity_manifests','anon',array[]::text[],'no anonymous manifest writes');
select table_privs_are('public','creator_continuity_statements','anon',array[]::text[],'no anonymous continuity writes');
select table_privs_are('public','authenticity_network_subscriptions','anon',array[]::text[],'no anonymous subscriptions');
select table_privs_are('public','authenticity_network_deliveries','anon',array[]::text[],'no anonymous deliveries');
select function_privs_are('public','store_authenticity_manifest',array['uuid','bigint','bigint','jsonb','text','timestamptz'],'authenticated',array[]::text[],'manifest issuance is worker-only');
select function_privs_are('public','store_continuity_statement',array['uuid','text','text','uuid','uuid','text','text','text','bigint','jsonb','text','text','text','timestamptz','timestamptz'],'authenticated',array[]::text[],'continuity issuance is worker-only');
select function_privs_are('public','claim_authenticity_network_deliveries',array['integer','uuid'],'authenticated',array[]::text[],'delivery claiming is worker-only');
select function_privs_are('public','store_authenticity_manifest',array['uuid','bigint','bigint','jsonb','text','timestamptz'],'service_role',array['EXECUTE'],'service role stores manifests');
select function_privs_are('public','store_continuity_statement',array['uuid','text','text','uuid','uuid','text','text','text','bigint','jsonb','text','text','text','timestamptz','timestamptz'],'service_role',array['EXECUTE'],'service role stores statements');
select function_privs_are('public','claim_authenticity_network_deliveries',array['integer','uuid'],'service_role',array['EXECUTE'],'service role claims deliveries');
select function_privs_are('public','claim_authenticity_domain_discovery',array['integer','uuid'],'authenticated',array[]::text[],'domain discovery claiming is worker-only');
select function_privs_are('public','claim_authenticity_domain_discovery',array['integer','uuid'],'service_role',array['EXECUTE'],'service role claims domain checks');
select col_has_check('public','creator_authenticity_manifests','manifest_version','manifest version constrained');
select col_has_check('public','creator_continuity_statements','statement_version','statement version constrained');
select col_has_check('public','creator_continuity_statements','statement_type','statement types constrained');
select col_has_check('public','creator_continuity_statements','reason_code','safe reasons constrained');
select col_has_check('public','authenticity_network_subscriptions','status','subscription status constrained');
select col_has_check('public','authenticity_network_deliveries','status','delivery status constrained');
select * from finish();
rollback;
