begin;select plan(44);
select has_table('public','creator_identity_profiles','identity profiles exist');select has_table('public','creator_identity_accounts','identity accounts exist');select has_table('public','creator_identity_domains','identity domains exist');select has_table('public','creator_identity_relationships','identity relationships exist');select has_table('public','creator_identity_events','append-only identity events exist');
select has_function('public','sync_identity_account_from_connection',array['uuid'],'connection sync RPC exists');select has_function('public','sync_identity_account_from_emergency_replacement',array['uuid'],'replacement sync RPC exists');select has_function('public','get_public_creator_identity_graph',array['text'],'safe public graph RPC exists');select has_function('public','claim_identity_accounts',array['integer','uuid'],'worker claim RPC exists');
select ok((select relforcerowsecurity from pg_class where oid='public.creator_identity_profiles'::regclass),'profile RLS forced');select ok((select relforcerowsecurity from pg_class where oid='public.creator_identity_accounts'::regclass),'account RLS forced');select ok((select relforcerowsecurity from pg_class where oid='public.creator_identity_domains'::regclass),'domain RLS forced');select ok((select relforcerowsecurity from pg_class where oid='public.creator_identity_relationships'::regclass),'relationship RLS forced');select ok((select relforcerowsecurity from pg_class where oid='public.creator_identity_events'::regclass),'event RLS forced');
select table_privs_are('public','creator_identity_accounts','anon',array[]::text[],'anonymous has no account table privileges');select table_privs_are('public','creator_identity_events','anon',array[]::text[],'anonymous has no event privileges');select function_privs_are('public','claim_identity_accounts',array['integer','uuid'],'service_role',array['EXECUTE'],'worker claim is service-role only');
insert into auth.users(instance_id,id,aud,role,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at,confirmation_token,recovery_token,email_change_token_new,email_change)values
('00000000-0000-0000-0000-000000000000','a6000000-0000-4000-8000-000000000001','authenticated','authenticated','identity-owner@example.com',crypt('pw',gen_salt('bf')),now(),'{}','{}',now(),now(),'','','',''),
('00000000-0000-0000-0000-000000000000','a6000000-0000-4000-8000-000000000002','authenticated','authenticated','identity-other@example.com',crypt('pw',gen_salt('bf')),now(),'{}','{}',now(),now(),'','','','');
update public.creators set display_name='Identity Creator',public_slug='identity-creator',public_profile_enabled=true where owner_user_id='a6000000-0000-4000-8000-000000000001';update public.creators set public_slug='identity-other'where owner_user_id='a6000000-0000-4000-8000-000000000002';select set_config('tests.identity_creator',(select id::text from public.creators where public_slug='identity-creator'),true);
set local role authenticated;select set_config('request.jwt.claim.sub','a6000000-0000-4000-8000-000000000001',true);select set_config('request.jwt.claims','{"sub":"a6000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select lives_ok($$select public.ensure_creator_identity_profile()$$,'owner ensures identity profile');select is((select count(*)::integer from public.creator_identity_profiles),1,'one identity profile is visible');select is(public.ensure_creator_identity_profile(),(select id from public.creator_identity_profiles),'profile ensure is idempotent');select throws_ok($$insert into public.creator_identity_profiles(creator_id,public_display_name)values(current_setting('tests.identity_creator')::uuid,'Duplicate')$$,'42501',null,'direct browser profile insert is denied');
reset role;insert into public.connected_accounts(id,creator_id,platform,account_type,label,url,is_primary,external_account_id,external_account_name,external_account_url,connection_health,provider_status)values('a6100000-0000-4000-8000-000000000001',current_setting('tests.identity_creator')::uuid,'youtube','official','@old-handle','https://youtube.com/channel/stable',true,'stable-channel','Identity Creator','https://youtube.com/channel/stable','healthy','ready');
set local role service_role;select set_config('request.jwt.claim.role','service_role',true);select lives_ok($$select public.sync_identity_account_from_connection('a6100000-0000-4000-8000-000000000001')$$,'service syncs connected identity');select is((select count(*)::integer from public.creator_identity_accounts),1,'one identity account created');select is((select verification_status from public.creator_identity_accounts),'verified','authoritative connection creates verified identity');select lives_ok($$select public.sync_identity_account_from_connection('a6100000-0000-4000-8000-000000000001')$$,'duplicate sync is idempotent');select is((select count(*)::integer from public.creator_identity_accounts),1,'duplicate sync does not duplicate account');
update public.connected_accounts set label='@new-handle'where id='a6100000-0000-4000-8000-000000000001';select lives_ok($$select public.sync_identity_account_from_connection('a6100000-0000-4000-8000-000000000001')$$,'handle change sync succeeds');select is((select count(*)::integer from public.creator_identity_accounts),1,'handle change preserves identity record');select is((select display_handle from public.creator_identity_accounts),'@new-handle','handle metadata updates');select is((select count(*)::integer from public.creator_identity_events where event_type='handle_changed'),1,'handle change is audited');
select throws_ok($$update public.creator_identity_accounts set official=true,verification_status='pending'$$,'23514',null,'official requires verified');select throws_ok($$update public.creator_identity_accounts set primary_for_provider=true,verification_status='pending'$$,'23514',null,'primary requires verified');
reset role;set local role authenticated;select set_config('request.jwt.claim.sub','a6000000-0000-4000-8000-000000000001',true);select set_config('request.jwt.claims','{"sub":"a6000000-0000-4000-8000-000000000001","role":"authenticated"}',true);select lives_ok($$select public.set_identity_account_presentation((select id from public.creator_identity_accounts),true,true,true)$$,'owner marks verified identity official and primary');select ok((select official and primary_for_provider and public_visible from public.creator_identity_accounts),'presentation flags persist');
select set_config('request.jwt.claim.sub','a6000000-0000-4000-8000-000000000002',true);select set_config('request.jwt.claims','{"sub":"a6000000-0000-4000-8000-000000000002","role":"authenticated"}',true);select is((select count(*)::integer from public.creator_identity_accounts),0,'other creator cannot read identity');select throws_ok($$select public.set_identity_account_presentation((select id from public.creator_identity_accounts),true,true,true)$$,'42501','access denied','cross-creator mutation fails');
reset role;set local role service_role;select set_config('request.jwt.claim.role','service_role',true);select lives_ok($$select public.apply_identity_provider_sync((select id from public.creator_identity_accounts),'stable-channel','@new-handle','Identity Creator','https://youtube.com/channel/stable','revoked','grant_revoked')$$,'authoritative revocation applies');select ok((select verification_status='revoked'and not official and not primary_for_provider and not public_visible from public.creator_identity_accounts),'revoked account loses presentation');select throws_ok($$update public.creator_identity_events set source='tampered'$$,'55000','emergency history is immutable','identity events are append-only');
select is((public.get_public_creator_identity_graph('identity-creator')->'accounts')::text,'[]','revoked account hidden from public graph');select ok(public.get_public_creator_identity_graph('identity-creator')::text!~'source_connection_id|metadata|stable_provider_account_id|last_sync_error','public graph excludes internal identity fields');select is(public.get_public_creator_identity_graph('identity-other'),null::jsonb,'hidden creator has no public graph');
select throws_ok($$insert into public.creator_identity_domains(identity_profile_id,creator_id,hostname,canonical_url)values((select id from public.creator_identity_profiles),current_setting('tests.identity_creator')::uuid,'Example.COM','https://example.com')$$,'23514',null,'domain hostnames must be normalized');select function_privs_are('public','sync_identity_account_from_connection',array['uuid'],'authenticated',array[]::text[],'browser cannot execute authoritative sync');
select * from finish();rollback;
