begin;
select plan(30);
select has_table('public','creator_ecosystem_destinations','ecosystem destinations project into canonical identity');
select has_table('public','creator_ecosystem_relationships','ecosystem relationships exist');
select has_table('public','ecosystem_verification_records','verification history exists');
select has_table('public','ecosystem_events','append-only ecosystem events exist');
select ok((select relforcerowsecurity from pg_class where oid='public.creator_ecosystem_destinations'::regclass),'destination FORCE RLS');
select ok((select relforcerowsecurity from pg_class where oid='public.creator_ecosystem_relationships'::regclass),'relationship FORCE RLS');
select ok((select relforcerowsecurity from pg_class where oid='public.ecosystem_verification_records'::regclass),'verification FORCE RLS');
select ok((select relforcerowsecurity from pg_class where oid='public.ecosystem_events'::regclass),'event FORCE RLS');
select policies_are('public','creator_ecosystem_destinations',array['creator ecosystem destination reads'],'creator-isolated destination reads');
select policies_are('public','creator_ecosystem_relationships',array['creator ecosystem relationship reads'],'creator-isolated relationship reads');
select policies_are('public','ecosystem_verification_records',array['creator ecosystem verification reads'],'creator-isolated verification reads');
select policies_are('public','ecosystem_events',array['creator ecosystem event reads'],'creator-isolated event reads');
select table_privs_are('public','creator_ecosystem_destinations','anon',array[]::text[],'anonymous cannot write destinations');
select table_privs_are('public','ecosystem_verification_records','authenticated',array['SELECT'],'creators cannot directly write verification records');
select table_privs_are('public','ecosystem_events','authenticated',array['SELECT'],'events are append-only for creators');
select function_privs_are('public','verify_ecosystem_destination',array['uuid','text','text','text','timestamptz'],'authenticated',array[]::text[],'creators cannot self-verify');
select function_privs_are('public','verify_ecosystem_destination',array['uuid','text','text','text','timestamptz'],'service_role',array['EXECUTE'],'worker verifies destinations');
select function_privs_are('public','revoke_ecosystem_destination',array['uuid','text'],'authenticated',array[]::text[],'creators cannot authoritatively revoke');
select function_privs_are('public','claim_ecosystem_sync',array['integer','uuid'],'authenticated',array[]::text[],'sync claims are worker-only');
select function_privs_are('public','claim_ecosystem_sync',array['integer','uuid'],'service_role',array['EXECUTE'],'service role claims sync work');
select function_privs_are('public','ensure_ecosystem_destination',array['text','text','text','text','text','text','text','uuid','uuid','jsonb'],'authenticated',array[]::text[],'stable identity synchronization is worker-only');
select function_privs_are('public','import_ecosystem_destination',array['text','text','text','text','text'],'authenticated',array['EXECUTE'],'creator can only manually import');
select function_privs_are('public','set_ecosystem_destination_presentation',array['uuid','boolean','boolean'],'authenticated',array['EXECUTE'],'creator can control presentation');
select function_privs_are('public','get_public_creator_ecosystem_graph',array['text'],'anon',array['EXECUTE'],'safe public graph is anonymous');
select col_has_check('public','creator_ecosystem_destinations','destination_type','destination types constrained');
select col_has_check('public','creator_ecosystem_destinations','verification_status','verification status constrained');
select col_has_check('public','creator_ecosystem_destinations','canonical_url','HTTPS canonical URL constrained');
select ok((select indexdef like'CREATE UNIQUE INDEX%'from pg_indexes where schemaname='public'and indexname='ecosystem_stable_identity_idx'),'stable provider identities are unique');
select ok((select indexdef like'CREATE UNIQUE INDEX%'from pg_indexes where schemaname='public'and indexname='ecosystem_one_primary_type_idx'),'one primary per destination type');
select trigger_is('public','ecosystem_events','ecosystem_events_immutable','public','prevent_emergency_history_mutation','events reject mutation');
select*from finish();
rollback;
