begin;
select plan(24);
select has_table('public','ecosystem_sync_observations','normalized observations exist');
select has_table('public','ecosystem_automation_incidents','correlated incidents exist');
select has_table('public','ecosystem_automation_actions','append-only action audit exists');
select has_column('public','creator_ecosystem_destinations','automation_enabled','destination automation control exists');
select has_column('public','creator_ecosystem_destinations','current_fingerprint','destination fingerprint exists');
select has_column('public','creator_ecosystem_destinations','sync_lease_expires_at','automation lease exists');
select ok((select relforcerowsecurity from pg_class where oid='public.ecosystem_sync_observations'::regclass),'observation FORCE RLS');
select ok((select relforcerowsecurity from pg_class where oid='public.ecosystem_automation_incidents'::regclass),'incident FORCE RLS');
select ok((select relforcerowsecurity from pg_class where oid='public.ecosystem_automation_actions'::regclass),'action FORCE RLS');
select policies_are('public','ecosystem_sync_observations',array['creator automation observation reads'],'creator-isolated observations');
select policies_are('public','ecosystem_automation_incidents',array['creator automation incident reads'],'creator-isolated incidents');
select policies_are('public','ecosystem_automation_actions',array['creator automation action reads'],'creator-isolated actions');
select table_privs_are('public','ecosystem_sync_observations','anon',array[]::text[],'anonymous cannot read or write observations');
select table_privs_are('public','ecosystem_sync_observations','authenticated',array['SELECT'],'browser cannot create authoritative observations');
select table_privs_are('public','ecosystem_automation_actions','authenticated',array['SELECT'],'browser cannot write audit actions');
select function_privs_are('public','claim_ecosystem_automation_destinations',array['integer','text'],'authenticated',array[]::text[],'claims are worker-only');
select function_privs_are('public','claim_ecosystem_automation_destinations',array['integer','text'],'service_role',array['EXECUTE'],'service role claims work');
select function_privs_are('public','ingest_ecosystem_observation',array['uuid','text','text','text','text','text','text','jsonb','boolean','timestamptz'],'authenticated',array[]::text[],'creator cannot ingest provider evidence');
select function_privs_are('public','ingest_ecosystem_observation',array['uuid','text','text','text','text','text','text','jsonb','boolean','timestamptz'],'service_role',array['EXECUTE'],'worker ingests observations');
select function_privs_are('public','process_ecosystem_observation',array['uuid','text','text','boolean','boolean','boolean','boolean','boolean','boolean','boolean','timestamptz'],'authenticated',array[]::text[],'policy processing is worker-only');
select function_privs_are('public','pause_ecosystem_automation',array['uuid','text'],'authenticated',array['EXECUTE'],'creator may pause');
select function_privs_are('public','resume_ecosystem_automation',array['uuid'],'authenticated',array['EXECUTE'],'creator may resume');
select trigger_is('public','ecosystem_automation_actions','ecosystem_actions_immutable','public','prevent_emergency_history_mutation','actions are append-only');
select ok((select indexdef like'CREATE UNIQUE INDEX%'from pg_indexes where schemaname='public'and indexname='ecosystem_incident_open_correlation_idx'),'one unresolved correlated incident');
select*from finish();
rollback;
