begin;
select plan(25);
select has_table('public','emergency_account_verifications','verification records exist');
select has_table('public','emergency_authorization_sessions','authorization sessions exist');
select has_column('public','emergency_account_verifications','external_account_id','stable identity stored');
select has_column('public','emergency_account_verifications','challenge_hash','challenge hash stored');
select has_column('public','emergency_account_verifications','next_revalidation_at','revalidation schedule stored');
select has_column('public','emergency_replacement_accounts','active_verification_id','replacement binds current verification');
select has_column('public','emergency_approvals','snapshot_hash','approval binds snapshot hash');
select has_column('public','emergency_approvals','policy_version','approval binds policy version');
select has_column('public','emergency_alert_snapshots','verification_id','snapshot binds verification');
select has_column('public','emergency_alert_snapshots','content_hash','snapshot binds content hash');
select has_column('public','emergency_alert_snapshots','destination_hash','snapshot binds destination hash');
select has_function('public','emergency_snapshot_hash',array['uuid'],'deterministic snapshot hash exists');
select has_function('public','consume_emergency_authorization',array['uuid','text','uuid','integer'],'atomic authorization consumption exists');
select has_function('public','activate_emergency',array['uuid','uuid'],'atomic authorized activation exists');
select has_function('public','claim_emergency_verifications',array['integer','uuid'],'bounded lease claiming exists');
select has_function('public','apply_emergency_revalidation',array['uuid','text','text','text','text','text'],'revalidation result RPC exists');
select has_function('public','revoke_emergency_verification',array['uuid','uuid'],'creator revocation RPC exists');
select ok((select relforcerowsecurity from pg_class where oid='public.emergency_account_verifications'::regclass),'verification RLS is forced');
select ok((select relforcerowsecurity from pg_class where oid='public.emergency_authorization_sessions'::regclass),'authorization RLS is forced');
select table_privs_are('public','emergency_account_verifications','anon',array[]::text[],'anonymous users cannot read evidence');
select table_privs_are('public','emergency_authorization_sessions','anon',array[]::text[],'anonymous users cannot read authorizations');
select function_privs_are('public','claim_emergency_verifications',array['integer','uuid'],'service_role',array['EXECUTE'],'worker claim is service-role only');
select function_privs_are('public','apply_emergency_revalidation',array['uuid','text','text','text','text','text'],'service_role',array['EXECUTE'],'revalidation mutation is service-role only');
select function_privs_are('public','record_emergency_verification',array['uuid','text','text','text','text','text','uuid','jsonb'],'service_role',array['EXECUTE'],'authoritative verification is service-role only');
select ok(exists(select 1 from pg_indexes where schemaname='public' and indexname='emergency_verification_one_active_method_idx'),'only one active method verification is indexed');
select * from finish();rollback;
