begin;
select plan(28);
select has_table('public','emergency_templates','templates exist');
select has_table('public','emergency_plans','plans exist');
select has_table('public','emergency_drills','drills exist');
select has_column('public','creator_emergencies','source_template_id','emergencies retain a template source reference');
select has_column('public','creator_emergencies','source_plan_id','emergencies retain a plan source reference');
select has_function('public','create_prepared_emergency',array['uuid','uuid','uuid','text'],'prepared creation RPC exists');
select ok((select relforcerowsecurity from pg_class where oid='public.emergency_templates'::regclass),'template RLS is forced');
select ok((select relforcerowsecurity from pg_class where oid='public.emergency_plans'::regclass),'plan RLS is forced');
select ok((select relforcerowsecurity from pg_class where oid='public.emergency_drills'::regclass),'drill RLS is forced');
select table_privs_are('public','emergency_templates','anon',array[]::text[],'anon cannot read templates');
select table_privs_are('public','emergency_plans','anon',array[]::text[],'anon cannot read plans');
select table_privs_are('public','emergency_drills','anon',array[]::text[],'anon cannot read drills');

insert into auth.users(instance_id,id,aud,role,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at,confirmation_token,recovery_token,email_change_token_new,email_change) values
('00000000-0000-0000-0000-000000000000','f5000000-0000-4000-8000-000000000001','authenticated','authenticated','prepared-owner@example.com',crypt('pw',gen_salt('bf')),now(),'{}','{}',now(),now(),'','','',''),
('00000000-0000-0000-0000-000000000000','f5000000-0000-4000-8000-000000000002','authenticated','authenticated','prepared-other@example.com',crypt('pw',gen_salt('bf')),now(),'{}','{}',now(),now(),'','','','');
update public.creators set public_slug='prepared-owner',public_profile_enabled=true,recovery_pass_enabled=true where owner_user_id='f5000000-0000-4000-8000-000000000001';
select set_config('tests.prepared_creator',(select id::text from public.creators where public_slug='prepared-owner'),true);
insert into public.connected_accounts(id,creator_id,platform,account_type,label,url,is_primary) values('f5100000-0000-4000-8000-000000000001',current_setting('tests.prepared_creator')::uuid,'youtube','official','@main','https://youtube.com/@main',true);
set local role authenticated;select set_config('request.jwt.claim.sub','f5000000-0000-4000-8000-000000000001',true);select set_config('request.jwt.claim.role','authenticated',true);select set_config('request.jwt.claims','{"sub":"f5000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into public.emergency_templates(creator_id,name,emergency_type,severity,title_template,message_template,default_affected_account_id,created_by) values(current_setting('tests.prepared_creator')::uuid,'Account recovery','account_hacked','important','Original title','Original message','f5100000-0000-4000-8000-000000000001','f5000000-0000-4000-8000-000000000001');
select is((select count(*)::integer from public.emergency_templates),1,'owner creates and reads a template');
select throws_ok($$insert into public.emergency_templates(creator_id,name,emergency_type,severity,title_template,message_template,created_by) values(current_setting('tests.prepared_creator')::uuid,'account RECOVERY','account_hacked','important','x','x','f5000000-0000-4000-8000-000000000001')$$,'23505',null,'template names are case-insensitively unique');
select set_config('tests.template_id',(select id::text from public.emergency_templates),true);
insert into public.emergency_plans(creator_id,template_id,name,affected_account_id,emergency_type,severity,title,message,proposed_replacement_url,readiness_status,created_by) values(current_setting('tests.prepared_creator')::uuid,current_setting('tests.template_id')::uuid,'Primary compromise','f5100000-0000-4000-8000-000000000001','account_hacked','important','Snapshot title','Snapshot message','https://example.com/proposed','ready','f5000000-0000-4000-8000-000000000001');
reset role;set local role service_role;select set_config('request.jwt.claim.role','service_role',true);
update public.emergency_plans set readiness_status='ready',last_validated_at=now();
reset role;set local role authenticated;select set_config('request.jwt.claim.role','authenticated',true);select set_config('request.jwt.claim.sub','f5000000-0000-4000-8000-000000000001',true);select set_config('request.jwt.claims','{"sub":"f5000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select is((select readiness_status from public.emergency_plans),'ready','owner creates a ready plan');
select ok((select proposed_replacement_url is not null from public.emergency_plans),'proposed replacement is stored only as private plan data');
select is((select count(*)::integer from public.emergency_replacement_accounts),0,'proposed replacement is not verification');
select set_config('tests.plan_id',(select id::text from public.emergency_plans),true);
select lives_ok($$select public.create_prepared_emergency(current_setting('tests.plan_id')::uuid,null,null,'prepared-request-1')$$,'incident is created from ready plan');
select is((select title from public.creator_emergencies),'Snapshot title','incident copies plan title');
update public.emergency_plans set title='Changed later' where id=current_setting('tests.plan_id')::uuid;
select is((select title from public.creator_emergencies),'Snapshot title','later plan edits do not mutate incident');
select is((select count(*)::integer from public.emergency_events where event_type='created_from_plan'),1,'prepared creation is append-only audited');
select is((select public.create_prepared_emergency(current_setting('tests.plan_id')::uuid,null,null,'prepared-request-1')),(select id from public.creator_emergencies),'creation retries are idempotent');
insert into public.emergency_drills(creator_id,source_plan_id,status,started_by) values(current_setting('tests.prepared_creator')::uuid,current_setting('tests.plan_id')::uuid,'draft','f5000000-0000-4000-8000-000000000001');
select is((select count(*)::integer from public.emergency_drills),1,'owner creates a drill');
select is((select count(*)::integer from public.creator_emergencies where lifecycle_status='active'),0,'drills never activate emergencies');
select set_config('request.jwt.claim.sub','f5000000-0000-4000-8000-000000000002',true);select set_config('request.jwt.claims','{"sub":"f5000000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select is((select count(*)::integer from public.emergency_templates),0,'other creator cannot read templates');
select is((select count(*)::integer from public.emergency_plans),0,'other creator cannot read plans');
select is((select count(*)::integer from public.emergency_drills),0,'other creator cannot read drills');
create temporary table denied_change as with changed as(update public.emergency_plans set notes='intrusion' returning 1) select count(*)::integer total from changed;
select is((select total from denied_change),0,'other creator cannot mutate plans');
select * from finish();rollback;
