begin;
select plan(25);
select has_table('public','provider_content_sources','provider sources reuse normalized ingestion');
select has_table('public','podcast_feed_ownership_challenges','feed challenges exist');
select has_table('public','twitch_eventsub_subscriptions','EventSub lifecycle exists');
select ok((select relforcerowsecurity from pg_class where oid='public.provider_content_sources'::regclass),'source FORCE RLS');
select ok((select relforcerowsecurity from pg_class where oid='public.podcast_feed_ownership_challenges'::regclass),'challenge FORCE RLS');
select ok((select relforcerowsecurity from pg_class where oid='public.twitch_eventsub_subscriptions'::regclass),'EventSub FORCE RLS');
select policies_are('public','provider_content_sources',array['creator provider source reads'],'creator source isolation');
select policies_are('public','podcast_feed_ownership_challenges',array['creator feed challenge reads'],'creator challenge isolation');
select policies_are('public','twitch_eventsub_subscriptions',array['creator eventsub reads'],'creator EventSub isolation');
select table_privs_are('public','provider_content_sources','anon',array[]::text[],'anonymous cannot access sources');
select table_privs_are('public','podcast_feed_ownership_challenges','anon',array[]::text[],'anonymous cannot access challenges');
select table_privs_are('public','twitch_eventsub_subscriptions','authenticated',array['SELECT'],'browser cannot set webhook state');
select table_privs_are('public','provider_content_sources','authenticated',array['SELECT'],'browser cannot set stable sources or cursors');
select function_privs_are('public','claim_provider_content_sources',array['integer','uuid'],'authenticated',array[]::text[],'source claims are worker-only');
select function_privs_are('public','claim_provider_content_sources',array['integer','uuid'],'service_role',array['EXECUTE'],'worker claims sources');
select function_privs_are('public','complete_podcast_feed_challenge',array['uuid','text','integer'],'authenticated',array[]::text[],'browser cannot self-verify feed');
select function_privs_are('public','complete_podcast_feed_challenge',array['uuid','text','integer'],'service_role',array['EXECUTE'],'worker completes feed proof');
select function_privs_are('public','mark_provider_source_sync',array['uuid','boolean','text','text','timestamptz'],'authenticated',array[]::text[],'browser cannot write detection cursors');
select col_is_pk('public','provider_content_sources','id','source primary key');
select col_is_pk('public','podcast_feed_ownership_challenges','id','challenge primary key');
select col_is_pk('public','twitch_eventsub_subscriptions','id','subscription primary key');
select ok((select indexdef like'CREATE UNIQUE INDEX%'from pg_indexes where schemaname='public'and indexname='provider_content_sources_provider_stable_source_id_key'),'provider stable source uniqueness');
select ok((select indexdef like'CREATE UNIQUE INDEX%'from pg_indexes where schemaname='public'and indexname='podcast_feed_pending_challenge_idx'),'one pending feed challenge');
select col_has_check('public','provider_content_sources','source_type','source types constrained');
select col_has_check('public','podcast_feed_ownership_challenges','status','challenge lifecycle constrained');
select*from finish();
rollback;
