begin;select plan(37);
select has_table('public','provider_product_entitlements','product entitlements exist');
select has_table('public','provider_stream_checkpoints','X stream checkpoints exist');
select hasnt_table('public','provider_identity_resolutions','no speculative identity-resolution table');
select ok((select relforcerowsecurity from pg_class where oid='public.provider_product_entitlements'::regclass),'entitlement FORCE RLS');
select ok((select relforcerowsecurity from pg_class where oid='public.provider_stream_checkpoints'::regclass),'stream checkpoint FORCE RLS');
select policies_are('public','provider_product_entitlements',array['authenticated entitlement reads'],'entitlement read policy');
select policies_are('public','provider_stream_checkpoints',array[]::text[],'stream state is service only');
select table_privs_are('public','provider_product_entitlements','anon',array[]::text[],'anonymous cannot access entitlements');
select table_privs_are('public','provider_product_entitlements','authenticated',array['SELECT'],'browser cannot approve entitlements');
select table_privs_are('public','provider_stream_checkpoints','authenticated',array[]::text[],'browser cannot access stream cursors');
select function_privs_are('public','claim_expansion_three_connections',array['integer','uuid'],'authenticated',array[]::text[],'claims are service-only');
select function_privs_are('public','claim_expansion_three_connections',array['integer','uuid'],'service_role',array['EXECUTE'],'worker may claim');
select col_is_pk('public','provider_product_entitlements','id','entitlement primary key');
select col_is_pk('public','provider_stream_checkpoints','id','checkpoint primary key');
select col_has_check('public','provider_product_entitlements','status','entitlement state constrained');
select col_has_check('public','provider_stream_checkpoints','status','stream state constrained');
select is(public.trust_provider_family('x'),'x','X family');
select is(public.trust_provider_family('linkedin'),'linkedin','LinkedIn family');
select is(public.trust_provider_family('threads'),'meta','Threads shares Meta family');
select is(public.trust_provider_family('instagram'),'meta','Instagram remains Meta family');
select is(public.trust_provider_family('facebook'),'meta','Facebook remains Meta family');
select is((select status from public.provider_product_entitlements limit 1),null,'entitlements never default to an approved row');

insert into auth.users(instance_id,id,aud,role,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at,confirmation_token,recovery_token,email_change_token_new,email_change)values('00000000-0000-0000-0000-000000000000','84000000-0000-4000-8000-000000000001','authenticated','authenticated','stage84@example.com',crypt('pw',gen_salt('bf')),now(),'{}','{}',now(),now(),'','','','');
update public.creators set display_name='Stage 8.4',public_slug='stage-84'where owner_user_id='84000000-0000-4000-8000-000000000001';
insert into public.connected_accounts(id,creator_id,platform,account_type,label,url,is_public,external_account_id,external_account_name,external_account_url,provider_status,connection_health,watch_enabled,auto_create_drafts,auto_send)select'84000000-0000-4000-8000-000000000010',id,'x','official','X','https://x.com/oldname',true,'12345','X Creator','https://x.com/oldname','ready','healthy',true,true,false from public.creators where public_slug='stage-84';
set local role service_role;select set_config('request.jwt.claim.role','service_role',true);
select lives_ok($$select public.select_provider_asset('84000000-0000-4000-8000-000000000010','x','x_account','12345','','X Creator','oldname','https://x.com/oldname','{"oauthAuthority":true}')$$,'service selects X account');
select is((select count(*)::integer from public.provider_asset_bindings where provider='x'),1,'one selected X asset');
select is((select count(*)::integer from public.provider_content_sources where provider='x'),1,'selection creates one X source');
select is((select approval_required from public.provider_asset_bindings where provider='x'),true,'approval required by default');
select is((select public_visible from public.provider_asset_bindings where provider='x'),true,'verified selected asset may be public');
select lives_ok($$select public.select_provider_asset('84000000-0000-4000-8000-000000000010','x','x_account','12345','','X Creator','newname','https://x.com/newname','{"oauthAuthority":true}')$$,'username change preserves X stable ID');
select is((select stable_asset_id from public.provider_asset_bindings where provider='x'),'12345','X stable user ID remains anchored');
select is((select display_handle from public.provider_asset_bindings where provider='x'),'newname','X username safely changes');
select throws_ok($$select public.select_provider_asset('84000000-0000-4000-8000-000000000010','x','x_account','67890','','Conflict','other','https://x.com/other','{}')$$,'23505',null,'stable connection ID mismatch is protected');
select lives_ok($$select count(*) from public.claim_expansion_three_connections(20,'84000000-0000-4000-8000-000000000099')$$,'worker claims due approved-provider connections');
select is((select lease_owner from public.connected_accounts where id='84000000-0000-4000-8000-000000000010'),'84000000-0000-4000-8000-000000000099'::uuid,'claim records lease owner');
select is((select auto_send from public.connected_accounts where id='84000000-0000-4000-8000-000000000010'),false,'provider connection never enables auto-send');
reset role;
select is((select count(*)::integer from public.creator_emergencies),0,'provider setup does not activate emergency');
select is((select count(*)::integer from public.update_deliveries),0,'provider setup does not queue delivery');
select is((select count(*)::integer from public.provider_product_entitlements where status='approved'),0,'entitlements never default approved');
select*from finish();rollback;
