begin;
select plan(18);
select has_table('public','creator_authenticity_profiles','profiles table exists');
select has_table('public','creator_authenticity_assertions','assertions table exists');
select has_table('public','creator_authenticity_events','append-only events table exists');
select has_table('public','creator_authenticity_views','aggregate views table exists');
select has_table('public','authenticity_signing_keys','public keys table exists');
select col_is_unique('public','creator_authenticity_profiles','creator_id','one profile per creator');
select col_is_unique('public','creator_authenticity_profiles','identity_profile_id','one profile per identity');
select policies_are('public','creator_authenticity_profiles',array['creator authenticity profile reads'],'profile RLS is creator scoped');
select policies_are('public','creator_authenticity_assertions',array['creator authenticity assertion reads'],'assertion RLS is creator scoped');
select policies_are('public','creator_authenticity_events',array['creator authenticity event reads'],'event RLS is creator scoped');
select policies_are('public','creator_authenticity_views',array['creator authenticity analytics reads'],'analytics RLS is creator scoped');
select function_privs_are('public','get_public_creator_authenticity',array['text'],'anon',array['EXECUTE'],'safe public RPC is callable');
select function_privs_are('public','claim_authenticity_issuance',array['integer','uuid'],'anon',array[]::text[],'anon cannot claim issuance');
select function_privs_are('public','store_authenticity_assertion',array['uuid','bigint','bigint','text','text','jsonb','text','text','text','timestamptz','timestamptz'],'authenticated',array[]::text[],'creators cannot issue assertions');
select table_privs_are('public','creator_authenticity_assertions','anon',array[]::text[],'anon has no direct assertion access');
select table_privs_are('public','creator_authenticity_assertions','authenticated',array['SELECT'],'creator assertion rows are read-only');
select table_privs_are('public','creator_authenticity_events','authenticated',array['SELECT'],'events are append-only to creators');
select table_privs_are('public','creator_authenticity_views','anon',array[]::text[],'analytics has no anonymous table access');
select * from finish();
rollback;
