begin;set local role postgres;set local search_path=public,extensions;select plan(16);
select has_table('public','creator_billing_subscriptions','billing subscription table exists');
select has_table('public','stripe_webhook_events','webhook replay ledger exists');
select ok((select relforcerowsecurity from pg_class where oid='public.creator_billing_subscriptions'::regclass),'billing RLS forced');
select ok((select relforcerowsecurity from pg_class where oid='public.stripe_webhook_events'::regclass),'event RLS forced');
select table_privs_are('public','creator_billing_subscriptions','authenticated',array[]::text[],'creator cannot read provider identifiers directly');
select table_privs_are('public','stripe_webhook_events','authenticated',array[]::text[],'creator cannot inspect webhook ledger');
select has_function('public','apply_stripe_subscription_event',array['text','text','bigint','uuid','text','text','text','text','text','timestamp with time zone','timestamp with time zone','boolean','timestamp with time zone','timestamp with time zone'],'atomic webhook projection exists');
select col_is_unique('public','creator_billing_subscriptions','stripe_customer_id','customer unique');
select col_is_unique('public','creator_billing_subscriptions','stripe_subscription_id','subscription unique');
insert into auth.users(id,email)values('91140000-0000-4000-8000-000000000001','billing@example.test');select set_config('tests.billing_creator',(select id::text from public.creators where owner_user_id='91140000-0000-4000-8000-000000000001'),true);
select set_config('request.jwt.claim.role','service_role',true);
select ok(public.apply_stripe_subscription_event('evt_stage1114active','customer.subscription.updated',100,current_setting('tests.billing_creator')::uuid,'cus_stage1114','sub_stage1114','price_monthly','monthly','active',now(),now()+interval'1 month',false,null,null),'active event applied');
select is((select plan from public.creator_plan_entitlements where creator_id=current_setting('tests.billing_creator')::uuid),'pro','active grants Pro');
select is(public.apply_stripe_subscription_event('evt_stage1114active','customer.subscription.updated',100,current_setting('tests.billing_creator')::uuid,'cus_stage1114','sub_stage1114','price_monthly','monthly','active',now(),now()+interval'1 month',false,null,null),false,'duplicate event ignored');
select is(public.apply_stripe_subscription_event('evt_stage1114old','customer.subscription.updated',99,current_setting('tests.billing_creator')::uuid,'cus_stage1114','sub_stage1114','price_monthly','monthly','past_due',now(),now()+interval'1 month',false,null,null),false,'older event cannot overwrite state');
select is((select plan from public.creator_plan_entitlements where creator_id=current_setting('tests.billing_creator')::uuid),'pro','out of order event preserves Pro');
select ok(public.apply_stripe_subscription_event('evt_stage1114failed','invoice.payment_failed',101,current_setting('tests.billing_creator')::uuid,'cus_stage1114','sub_stage1114','price_monthly','monthly','past_due',now(),now()+interval'1 month',false,null,null),'new failure applied');
select is((select plan from public.creator_plan_entitlements where creator_id=current_setting('tests.billing_creator')::uuid),'free','past due revokes Pro without deleting data');
select * from finish();rollback;
