/* eslint-disable @next/next/no-html-link-for-pages */
import type { Metadata } from "next";
import { ContactForm } from "@/components/contact-form";
import { Logo } from "@/components/logo";
import { PublicFooter } from "@/components/public-footer";
import { CONTACT_EMAIL, SUPPORT_EMAIL, isContactTopic } from "@/lib/contact-form-contract";
export const metadata: Metadata = { title: "Contact & Support", description: "Contact AudienceOwn for account, product, privacy, security, legal, or business questions.", alternates: { canonical: "/contact" } };
export default async function Page({ searchParams }: { searchParams: Promise<{ topic?: string | string[] }> }) {
  const requestedTopic = (await searchParams).topic;
  const initialTopic = isContactTopic(requestedTopic) ? requestedTopic : "";
  return <main className="min-h-screen bg-[#07070b] text-white"><div className="mx-auto max-w-6xl px-5 py-10 lg:px-8 lg:py-16"><Logo/><div className="mt-14 grid gap-8 lg:grid-cols-[minmax(0,1.45fr)_minmax(280px,.55fr)] lg:items-start"><section><p className="eyebrow">Contact &amp; support</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.04em] sm:text-5xl">How can we help?</h1><p className="mt-4 max-w-2xl text-lg leading-8 text-zinc-400">Tell us what you need help with and we’ll route your request to the right AudienceOwn team.</p><div className="mt-8"><ContactForm initialTopic={initialTopic}/></div></section><aside className="space-y-5 lg:sticky lg:top-8"><section className="surface rounded-2xl p-6"><h2 className="font-semibold">Email us directly</h2><dl className="mt-4 space-y-4 text-sm text-zinc-400"><div><dt>Account or product support</dt><dd className="mt-1 break-words"><a className="text-violet-300 hover:text-violet-200" href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a></dd></div><div><dt>General, privacy, legal, or business</dt><dd className="mt-1 break-words"><a className="text-violet-300 hover:text-violet-200" href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a></dd></div></dl></section><section className="surface rounded-2xl p-6"><h2 className="font-semibold">Include in your request</h2><ul className="mt-3 list-disc space-y-2 pl-5 text-sm leading-6 text-zinc-400"><li>Your AudienceOwn handle, if applicable</li><li>What you were trying to do and what happened instead</li><li>A relevant date or time, if useful</li><li>A screenshot if it helps</li><li>The platform involved, when relevant</li></ul></section><section className="surface rounded-2xl p-6"><h2 className="font-semibold">Security reminder</h2><p className="mt-3 text-sm leading-6 text-zinc-400">Never send passwords, confirmation codes, OAuth tokens, API keys, or payment card details.</p><div className="mt-4 text-sm"><a className="text-violet-300 hover:text-violet-200" href="/privacy">Privacy</a></div></section></aside></div></div><PublicFooter/></main>;
}
