import Link from "next/link";
import { Activity, AlertTriangle, ArrowUpRight, Check, CircleDashed, Globe2, HeartPulse, Radio, Shield, ShieldCheck, Siren, Users } from "lucide-react";
import { FaDiscord, FaFacebook, FaInstagram, FaLinkedin, FaPinterest, FaSnapchat, FaSpotify, FaThreads, FaTiktok, FaTwitch, FaYoutube, FaXTwitter } from "react-icons/fa6";
import type { CreatorDashboardData } from "@/lib/dashboard/creator-dashboard";
import { formatCompactAudience } from "@/lib/dashboard/format-compact-number";
import { DashboardRefresh } from "./dashboard-refresh";

const panel = "rounded-2xl border border-white/[0.08] bg-[linear-gradient(145deg,rgba(24,24,33,.96),rgba(10,10,16,.98))] shadow-[0_18px_55px_rgba(0,0,0,.24)] transition duration-200 hover:-translate-y-0.5 hover:border-white/[0.15] motion-reduce:transform-none motion-reduce:transition-none";
const focus = "focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-violet-400";
const icons: Record<string, React.ComponentType<{ className?: string; style?: React.CSSProperties }>> = { youtube: FaYoutube, instagram: FaInstagram, tiktok: FaTiktok, x: FaXTwitter, spotify: FaSpotify, twitch: FaTwitch, linkedin: FaLinkedin, facebook: FaFacebook, snapchat: FaSnapchat, threads: FaThreads, pinterest: FaPinterest, discord: FaDiscord };
const relative = (value: string, calculatedAt: string) => { const minutes = Math.max(0, Math.round((new Date(calculatedAt).getTime() - new Date(value).getTime()) / 60_000)); return minutes < 1 ? "Just now" : minutes < 60 ? `${minutes}m ago` : minutes < 1440 ? `${Math.floor(minutes / 60)}h ago` : `${Math.floor(minutes / 1440)}d ago`; };
const metric = (value: number | null) => value === null ? "—" : new Intl.NumberFormat().format(value);

function Ring({ value, label, color = "#8b5cf6" }: { value: number; label: string; color?: string }) {
  return <div className="relative grid h-16 w-16 shrink-0 place-items-center rounded-full" style={{ background: `conic-gradient(${color} ${value * 3.6}deg,rgba(255,255,255,.08) 0)` }} aria-label={`${label}: ${value}%`}><div className="grid h-12 w-12 place-items-center rounded-full bg-[#111119] text-sm font-semibold">{value}%</div></div>;
}

function Kpi({ label, value, exact, support, tone, icon: Icon, progress, href }: { label: string; value: string; exact: string; support: string; tone: string; icon: React.ComponentType<{ size?: number }>; progress?: number; href?: string }) {
  return <article aria-label={`${label}: ${exact}`} className={`${panel} relative min-h-40 overflow-hidden p-5`}><div aria-hidden className={`absolute -right-10 -top-12 h-28 w-28 rounded-full blur-3xl ${tone}`}/><div className="relative flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-[11px] font-medium uppercase tracking-[.13em] text-zinc-500">{label}</p><p className="mt-3 text-3xl font-semibold tracking-tight">{value}</p></div>{progress === undefined ? <span className="rounded-xl border border-white/10 bg-white/[0.06] p-2.5 shadow-[0_0_24px_rgba(139,92,246,.16)]"><Icon size={19}/></span> : <Ring value={progress} label={label}/>}</div><p className="relative mt-3 text-xs leading-5 text-zinc-400">{support}</p>{href && <Link href={href} className={`${focus} relative mt-2 inline-block text-[11px] text-violet-300`}>View full checklist</Link>}</article>;
}

function Pill({ children, tone = "neutral" }: { children: React.ReactNode; tone?: "good" | "warning" | "neutral" | "danger" }) {
  const styles = tone === "good" ? "border-emerald-400/20 bg-emerald-400/10 text-emerald-300" : tone === "warning" ? "border-amber-400/20 bg-amber-400/10 text-amber-300" : tone === "danger" ? "border-red-400/20 bg-red-400/10 text-red-300" : "border-white/10 bg-white/[0.05] text-zinc-400";
  return <span className={`rounded-full border px-2 py-0.5 text-[10px] font-medium ${styles}`}>{children}</span>;
}

export function CreatorCommandDashboard({ data, showRefresh = true }: { data: CreatorDashboardData; showRefresh?: boolean }) {
  const protectedCount = data.audience.protectedFans === null ? null : formatCompactAudience(data.audience.protectedFans);
  const riskCount = data.audience.fansAtRisk === null ? null : formatCompactAudience(data.audience.fansAtRisk);
  const completeCount = data.recoveryReadiness.checklist.filter((item) => item.status === "complete").length;
  const completion = Math.round(completeCount / Math.max(1, data.recoveryReadiness.checklist.length) * 100);
  const liveMetrics = data.liveRecovery ? [["Fans targeted", data.liveRecovery.metrics.fansTargeted.value], ["Alerts sent", data.liveRecovery.metrics.alertsSent.value], ["Alerts opened", data.liveRecovery.metrics.alertsOpened.value], ["Recovery page visits", data.liveRecovery.metrics.recoveryPageVisits.value], ["Follow clicks", data.liveRecovery.metrics.followClicks.value], ["Migration rate", data.liveRecovery.metrics.migrationRate.value]] as const : [["Fans targeted", null], ["Alerts sent", null], ["Alerts opened", null], ["Recovery page visits", null], ["Follow clicks", null], ["Migration rate", null]] as const;
  return <div className="space-y-5 text-zinc-100">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-violet-300">Welcome back, {data.creator.displayName}</p><h1 className="mt-1 text-3xl font-semibold tracking-tight sm:text-4xl">Creator Dashboard</h1><p className="mt-2 text-sm text-zinc-400">Your audience protection command center.</p><p className="mt-2 text-xs text-zinc-600">Last synchronized <time dateTime={data.calculatedAt}>{new Date(data.calculatedAt).toLocaleString()}</time></p></div>{showRefresh && <DashboardRefresh/>}</header>

    <section aria-label="Audience protection metrics" className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      <Kpi label="Audience Protection Score" value={`${data.protection.score}%`} exact={`${data.protection.score} percent`} support={`${data.protection.state} · ${data.protection.explanation}`} tone="bg-violet-600/30" icon={Shield} progress={data.protection.score}/>
      <Kpi label="Protected Fans" value={protectedCount?.compact ?? "—"} exact={protectedCount ? `${protectedCount.exact} protected fans` : "Protected fans unavailable"} support={data.audience.protectedFans === 0 ? "Protect your first fan" : "Fans with a usable Recovery Pass"} tone="bg-emerald-500/25" icon={ShieldCheck}/>
      <Kpi label="Fans At Risk" value={riskCount?.compact ?? "—"} exact={riskCount ? `${riskCount.exact} known fans at risk` : "Known fans at risk unavailable"} support={riskCount ? "Known fans without a usable recovery connection" : "External audience total not yet available"} tone="bg-amber-500/25" icon={AlertTriangle}/>
      <Kpi label="Recovery Readiness" value={`${completeCount} of ${data.recoveryReadiness.checklist.length}`} exact={`${completeCount} of ${data.recoveryReadiness.checklist.length} checklist items complete`} support={`Checklist completion · ${completion}% · ${data.recoveryReadiness.state}`} tone="bg-blue-500/25" icon={Activity} progress={completion} href="/dashboard/emergency"/>
    </section>

    <section className="grid gap-5 xl:grid-cols-3"><article className={`${panel} p-5 xl:col-span-2`}><div className="flex items-center justify-between gap-3"><div><p className="text-[11px] uppercase tracking-[.13em] text-zinc-500">Connected reach</p><h2 className="mt-1 text-lg font-semibold">Platform Breakdown</h2></div><Link href="/dashboard/platforms" className={`${focus} text-xs text-violet-300 hover:text-violet-200`}>View all platforms</Link></div>
      <div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-4">{data.platforms.slice(0, 8).map((platform) => { const Icon = icons[platform.provider] ?? Globe2; const state = platform.accessLimited ? "Access limited" : platform.verified ? "Verified" : platform.connected ? "Connected" : "Not connected"; const audience = platform.audienceCount === null ? null : formatCompactAudience(platform.audienceCount); return <Link key={platform.provider} href="/dashboard/platforms" aria-label={`${platform.label}: ${state}`} className={`${focus} group min-h-32 rounded-xl border border-white/[0.07] bg-black/20 p-3 hover:bg-white/[0.04]`}><div className="flex items-start justify-between gap-2"><span className={`grid h-10 w-10 place-items-center rounded-xl border border-white/[0.07] ${platform.connected ? "bg-white/[0.07]" : "bg-white/[0.025] opacity-55"}`} style={{ boxShadow: platform.connected ? `0 0 24px ${platform.color}25` : undefined }}><Icon aria-hidden className="text-xl" style={{ color: platform.connected ? platform.color : "#71717a" }}/></span>{platform.connected && <span className={`mt-1 h-2 w-2 rounded-full ${platform.accessLimited ? "bg-amber-400" : "bg-emerald-400"}`} aria-label={state}/>}</div><strong className="mt-3 block text-sm">{platform.label}</strong><p className="mt-0.5 text-[11px] text-zinc-400">{state}</p><p aria-label={audience ? `${audience.exact} ${platform.audienceUnit ?? "audience"}` : undefined} className={`mt-2 truncate text-[10px] ${platform.connected ? "text-zinc-600" : "text-violet-300"}`}>{platform.connected ? audience ? `${audience.compact} ${platform.audienceUnit ?? "audience"}` : "Audience count unavailable" : "Connect →"}</p>{platform.updatedAt && <p className="mt-1 truncate text-[10px] text-zinc-700">Synced {relative(platform.updatedAt, data.calculatedAt)}</p>}</Link>; })}</div></article>
      <article className={`${panel} flex min-h-64 flex-col p-5`}><div className="flex justify-between"><div><p className="text-[11px] uppercase tracking-[.13em] text-zinc-500">Audience activity</p><h2 className="mt-1 text-lg font-semibold">Recent Opt-ins</h2></div><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-400/10 text-emerald-300"><Users size={18}/></span></div>{data.recentOptIns.length ? <ul className="mt-4 space-y-3">{data.recentOptIns.map((item) => <li key={item.id} className="flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-full bg-emerald-400/10 text-emerald-300"><Check size={14}/></span><span className="min-w-0 flex-1"><strong className="block text-sm">{item.displayLabel}</strong><Pill>{item.sourceLabel ?? "Recovery Pass"}</Pill></span><time dateTime={item.occurredAt} className="text-xs text-zinc-600">{relative(item.occurredAt, data.calculatedAt)}</time></li>)}</ul> : <div className="flex flex-1 flex-col justify-center py-5"><p className="text-3xl font-semibold">0</p><p className="mt-1 text-sm text-zinc-300">new protected fans today</p><p className="mt-3 text-xs leading-5 text-zinc-500">Share your Recovery Pass to begin protecting your audience.</p></div>}<Link href={`/c/${data.creator.handle}`} className={`${focus} mt-auto inline-flex items-center gap-1 text-xs text-violet-300`}>Share Recovery Pass <ArrowUpRight size={13}/></Link></article></section>

    <section className="grid gap-5 xl:grid-cols-12"><article className={`${panel} p-5 xl:col-span-5`}><div className="flex items-center justify-between gap-4"><div><p className="text-[11px] uppercase tracking-[.13em] text-zinc-500">Preparation</p><h2 className="mt-1 text-lg font-semibold">Recovery Readiness Checklist</h2><p className="mt-1 text-xs text-zinc-500">{completeCount} of {data.recoveryReadiness.checklist.length} complete</p></div><Ring value={completion} label="Checklist completion" color="#22c55e"/></div><ul className="mt-4 space-y-1.5">{data.recoveryReadiness.checklist.map((item) => { const complete = item.status === "complete"; const attention = item.status === "attention"; const unavailable = item.status === "unavailable"; const label = complete ? "Complete" : attention ? "Attention" : unavailable ? "Not configured" : "Pending"; const tone = complete ? "good" as const : attention ? "danger" as const : unavailable ? "neutral" as const : "warning" as const; return <li key={item.key}><Link href={item.href} className={`${focus} flex items-center gap-3 rounded-lg border border-transparent px-2 py-2 text-sm hover:border-white/[0.06] hover:bg-white/[0.03]`}><span className={`grid h-7 w-7 place-items-center rounded-full ${complete ? "bg-emerald-400/10 text-emerald-300" : attention ? "bg-red-400/10 text-red-300" : unavailable ? "bg-white/[0.05] text-zinc-500" : "bg-amber-400/10 text-amber-300"}`}>{complete ? <Check size={14}/> : <CircleDashed size={14}/>}</span><span className="flex-1">{item.label}</span><Pill tone={tone}>{label}</Pill></Link></li>; })}</ul><Link href="/dashboard/emergency" className={`${focus} mt-4 inline-flex items-center gap-1 text-xs text-violet-300`}>View full checklist <ArrowUpRight size={13}/></Link></article>
      <article className={`${panel} overflow-hidden p-5 xl:col-span-3`}><div className="flex items-center justify-between"><div><p className="text-[11px] uppercase tracking-[.13em] text-zinc-500">Audience</p><h2 className="mt-1 text-lg font-semibold">Audience Health</h2></div><span className="rounded-xl bg-emerald-400/10 p-2.5 text-emerald-300"><HeartPulse size={18}/></span></div><dl className="mt-4 space-y-2.5 text-sm"><div className="flex justify-between"><dt className="text-zinc-500">Protected</dt><dd>{metric(data.audience.protectedFans)}</dd></div><div className="flex justify-between"><dt className="text-zinc-500">At risk</dt><dd>{metric(data.audience.fansAtRisk)}</dd></div><div className="flex justify-between"><dt className="text-zinc-500">Protected ratio</dt><dd>{data.audience.protectedRatio === null ? "—" : `${Math.round(data.audience.protectedRatio)}%`}</dd></div></dl>{data.audience.trend.length < 2 ? <div className="mt-5"><div aria-hidden className="h-16 rounded-lg border border-white/[0.05] bg-[linear-gradient(rgba(255,255,255,.035)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.035)_1px,transparent_1px)] bg-[size:20px_20px]"><div className="h-full bg-[linear-gradient(135deg,transparent_45%,rgba(139,92,246,.12)_50%,transparent_55%)]"/></div><p className="mt-3 text-xs leading-5 text-zinc-500">Trend starts after your first protected fans</p></div> : <div className="mt-5 flex h-16 items-end gap-1" aria-label={`${data.audience.trend.length} daily audience snapshots`}>{data.audience.trend.map((point) => <span key={point.date} className="min-w-1 flex-1 rounded-t bg-violet-500/60" style={{ height: `${Math.max(8, data.audience.protectedFans ? point.protected / data.audience.protectedFans * 100 : 8)}%` }}/>)}</div>}</article>
      <article className={`${panel} p-5 xl:col-span-4`}><div className="flex items-center justify-between"><div><p className="text-[11px] uppercase tracking-[.13em] text-zinc-500">Trust signals</p><h2 className="mt-1 text-lg font-semibold">Identity &amp; Authenticity</h2></div><span className="rounded-xl bg-violet-400/10 p-2.5 text-violet-300"><ShieldCheck size={18}/></span></div><dl className="mt-4 space-y-3 text-sm"><div className="flex items-center justify-between gap-3"><dt className="text-zinc-500">Identity confidence</dt><dd><Pill tone={data.identity.verifiedAccounts ? "good" : "neutral"}>{data.identity.trustState.replaceAll("_", " ")}</Pill></dd></div><div className="flex items-center justify-between gap-3"><dt className="text-zinc-500">Authenticity</dt><dd><Pill tone={data.identity.authenticityState === "Issued" ? "good" : "neutral"}>{data.identity.authenticityState}</Pill></dd></div><div className="flex items-center justify-between gap-3"><dt className="text-zinc-500">Monitoring</dt><dd><Pill tone={data.identity.monitoringState === "Healthy" ? "good" : "warning"}>{data.identity.monitoringState}</Pill></dd></div><div className="flex items-center justify-between"><dt className="text-zinc-500">Verified accounts</dt><dd className="font-semibold">{data.identity.verifiedAccounts}</dd></div></dl><Link href="/dashboard/identity" className={`${focus} mt-5 inline-flex items-center gap-1 text-xs text-violet-300`}>Review identity <ArrowUpRight size={13}/></Link></article></section>

    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><article className={`${panel} p-5`}><div className="flex items-center justify-between"><span className="rounded-xl bg-blue-400/10 p-2.5 text-blue-300"><Globe2 size={18}/></span><Pill>{data.ecosystem.health}</Pill></div><h2 className="mt-3 font-semibold">Ecosystem Health</h2><dl className="mt-4 grid grid-cols-3 gap-2 text-center"><div><dd className="text-xl font-semibold">{data.ecosystem.verifiedDestinations}</dd><dt className="mt-1 text-[10px] text-zinc-500">Verified</dt></div><div><dd className="text-xl font-semibold">{data.ecosystem.activeAutomations}</dd><dt className="mt-1 text-[10px] text-zinc-500">Automations</dt></div><div><dd className="text-xl font-semibold">{data.ecosystem.openIncidents}</dd><dt className="mt-1 text-[10px] text-zinc-500">Incidents</dt></div></dl><p className="mt-4 text-[11px] text-zinc-600">Last sync: {data.ecosystem.lastSyncAt ? new Date(data.ecosystem.lastSyncAt).toLocaleString() : "Not yet synced"}</p><Link href="/dashboard/ecosystem" className={`${focus} mt-4 inline-block text-xs text-violet-300`}>View ecosystem</Link></article>
      <article className={`${panel} p-5`}><div className="flex items-center justify-between"><span className={`rounded-xl p-2.5 ${data.emergency.activeEmergencyId ? "bg-red-400/10 text-red-300" : "bg-emerald-400/10 text-emerald-300"}`}><Siren size={18}/></span><Pill tone={data.emergency.activeEmergencyId ? "danger" : "good"}>{data.emergency.activeEmergencyId ? "Live" : data.emergency.status}</Pill></div><h2 className="mt-3 font-semibold">Emergency Status</h2><p className="mt-4 text-sm">Recovery Pass <span className={data.emergency.recoveryPassActive ? "text-emerald-300" : "text-zinc-500"}>{data.emergency.recoveryPassActive ? "active" : "inactive"}</span></p>{data.emergency.activeEmergencyId ? <><p className="mt-2 text-xs capitalize text-zinc-500">Severity: {data.emergency.severity ?? "Not classified"}</p><p className="mt-2 text-xs text-zinc-500">Activated: {data.emergency.activatedAt ? new Date(data.emergency.activatedAt).toLocaleString() : "Time unavailable"}</p></> : <><p className="mt-2 text-xs text-zinc-500">Active emergencies: 0</p><p className="mt-2 text-xs text-zinc-500">Last drill: {data.emergency.lastDrillAt ? new Date(data.emergency.lastDrillAt).toLocaleDateString() : "Not run"}</p></>}<Link href="/dashboard/emergency" className={`${focus} mt-4 inline-block text-xs text-violet-300`}>{data.emergency.activeEmergencyId ? "View Emergency" : "Run Drill Now"}</Link></article>
      <article className={`${panel} p-5`}><div className="flex items-center justify-between"><span className={`rounded-xl p-2.5 ${data.liveRecovery ? "bg-red-400/10 text-red-300" : "bg-white/[0.05] text-zinc-500"}`}><Radio size={18}/></span>{data.liveRecovery ? <Pill tone="danger">Live</Pill> : <Pill>Inactive</Pill>}</div><h2 className="mt-3 font-semibold">Live Recovery Analytics</h2><dl className="mt-4 grid grid-cols-3 gap-x-2 gap-y-3">{liveMetrics.map(([label, value]) => <div key={label}><dt className="text-[10px] text-zinc-600">{label}</dt><dd className="mt-0.5 text-sm font-medium">{value === null ? "—" : value}</dd></div>)}</dl><p className="mt-3 text-[11px] text-zinc-500">{data.liveRecovery ? "Active recovery incident" : "No active recovery incident"}</p><Link href="/dashboard/analytics/recovery" className={`${focus} mt-3 inline-block text-xs text-violet-300`}>View history</Link></article>
      <article className={`${panel} overflow-hidden border-violet-500/20 bg-[radial-gradient(circle_at_top_right,rgba(124,58,237,.3),transparent_55%),linear-gradient(145deg,#181224,#0c0c12)] p-5`}><p className="text-[11px] uppercase tracking-[.13em] text-violet-300">Next best action</p><h2 className="mt-3 text-lg font-semibold">{data.nextAction.label}</h2><p className="mt-2 text-sm leading-6 text-zinc-400">{data.nextAction.description}</p><Link href={data.nextAction.href} className={`${focus} mt-5 inline-flex items-center gap-2 rounded-lg bg-violet-600 px-3 py-2 text-sm font-medium hover:bg-violet-500`}>Take action <ArrowUpRight size={14}/></Link></article></section>
  </div>;
}
