import{readFileSync}from"node:fs";import{describe,expect,it}from"vitest";const s=(p:string)=>readFileSync(p,"utf8");
describe("Stripe billing",()=>{
it("keeps the configured prices allowlisted",()=>{const checkout=s("app/api/billing/checkout/route.ts"),config=s("lib/billing/stripe.ts");expect(checkout).toContain('z.enum(["monthly","yearly"])');expect(checkout).not.toMatch(/price:\s*(?:body|parsed\.data\.price)/);expect(config).toContain("STRIPE_PRO_MONTHLY_PRICE_ID");expect(config).toContain("STRIPE_PRO_YEARLY_PRICE_ID");});
it("fails closed unless keys and canonical Prices agree on mode, amount, cadence, activity, and Product",()=>{const checkout=s("app/api/billing/checkout/route.ts"),config=s("lib/billing/stripe.ts");expect(config).toContain('/^sk_(test|live)_/');expect(config).toContain("monthly.livemode===expectedLive");expect(config).toContain("yearly.livemode===expectedLive");expect(config).toContain("monthly.unit_amount===canonicalProDisplayPrices.monthly.unitAmount");expect(config).toContain("yearly.unit_amount===canonicalProDisplayPrices.yearly.unitAmount");expect(config).toContain('monthly.recurring?.interval==="month"');expect(config).toContain('yearly.recurring?.interval==="year"');expect(config).toContain("productId(monthly)===productId(yearly)");expect(checkout).toContain('error:"billing_configuration_mismatch"');expect(checkout).toContain('error:"billing_not_configured"');});
it("uses hosted checkout and customer reuse",()=>{const x=s("app/api/billing/checkout/route.ts");expect(x).toContain('mode:"subscription"');expect(x).toContain("stripe.customers.create");expect(x).toContain("stripe_customer_id");expect(x).toContain('manage_billing');});
it("verifies raw signed webhooks and handles required lifecycle events",()=>{const x=s("app/api/billing/stripe/webhook/route.ts");expect(x).toContain("constructEvent(await request.text()");for(const event of["checkout.session.completed","invoice.paid","invoice.payment_failed","customer.subscription."])expect(x).toContain(event);});
it("keeps success webhook-authoritative",()=>{const x=s("components/billing-confirmation.tsx");expect(x).toContain("webhook-confirmed");expect(x).toContain("still confirming");expect(x).not.toContain("session_id");});
it("creates only creator-owned portal sessions with safe action diagnostics",()=>{const x=s("app/api/billing/portal/route.ts");expect(x).toContain("getCreator");expect(x).toContain("billingRecord(creator.id)");expect(x).toContain("portalCreationSucceeded");expect(x).toContain("safeStripeErrorCode");expect(x).not.toContain("request.json");expect(x).not.toContain("customerId:");expect(x).not.toContain("subscriptionId:");});
it("reads display amounts from the allowlisted canonical Stripe Prices",()=>{const pricing=s("lib/billing/pricing.ts"),workspace=s("components/plans-billing-workspace.tsx");expect(pricing).toContain("stripe.prices.retrieve(monthlyId)");expect(pricing).toContain("stripe.prices.retrieve(yearlyId)");expect(pricing).toContain("yearly.unitAmount/annualMonthly");expect(pricing).toContain("configuredCanonicalPricing");expect(workspace).not.toMatch(/unitAmount:\s*(?:1200|12000)|const monthlyPrice|const yearlyPrice/);});
it("returns checkout and portal sessions to the authenticated plans workspace",()=>{expect(s("app/api/billing/checkout/route.ts")).toContain('cancel_url:`${base}/dashboard/settings/plans`');expect(s("app/api/billing/portal/route.ts")).toContain('return_url:`${base}/dashboard/settings/plans`');});
it("projects events atomically and in order",()=>{const x=s("supabase/migrations/20260901000000_stripe_billing.sql");expect(x).toContain("stripe_webhook_events");expect(x).toContain("last_stripe_event_created");expect(x).toContain("excluded.last_stripe_event_created>=");expect(x).toContain("on conflict do nothing");});
});
