import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";
import { ConnectedPlatformCard, type ConnectedPlatformCardData } from "@/components/connected-platform-card";
import { connectionHealthDescriptions, providerAuthorizationLabel, relativeProviderUpdate } from "@/lib/social-providers/connection-health";

const healthy:ConnectedPlatformCardData={id:"youtube-main",provider:"youtube",providerName:"YouTube",accountName:"Creator Channel",role:"Main Account",connectionType:"oauth",health:"healthy",authorization:"Authorization active",lastSync:"Last synced 8 minutes ago",stale:false,permission:"Read-only access",publicUrl:"https://youtube.com/@creator",connectedAt:"2026-08-01T12:00:00Z"};

describe("Connected Platforms experience",()=>{
  it("renders a healthy authorized account with plain-language permission and synchronization",()=>{const html=renderToStaticMarkup(<ConnectedPlatformCard connection={healthy}/>);expect(html).toContain("Healthy");expect(html).toContain("Synchronization is working normally.");expect(html).toContain("Authorization active");expect(html).toContain("Last synced 8 minutes ago");expect(html).toContain("Read-only access");expect(html).toContain("cannot upload, edit, delete, or manage your channel");});
  it("shows manual accounts as connected while keeping authorization capability separate",()=>{const manual:ConnectedPlatformCardData={...healthy,id:"manual-backup",provider:"instagram",providerName:"Instagram",accountName:"@backup",role:"Backup Account",connectionType:"manual",health:"manual",authorization:"No authorization",lastSync:null,stale:false,permission:null,publicUrl:"https://instagram.com/backup",connectedAt:null};const html=renderToStaticMarkup(<ConnectedPlatformCard connection={manual}/>);expect(html).toContain("Manual account");expect(html).toContain("Manual connection");expect(html).toContain("Connected");expect(html).toContain("No authorization");expect(html).toContain("Edit or remove");expect(html).not.toContain("Last successful sync");expect(html).not.toContain("Permission level");});
  it("makes reconnect required prominent and preserves the exact account role and target",()=>{const main=renderToStaticMarkup(<ConnectedPlatformCard connection={{...healthy,health:"action_required",authorization:"Reconnect required"}}/>),backup=renderToStaticMarkup(<ConnectedPlatformCard connection={{...healthy,id:"youtube-backup",role:"Backup Account",health:"action_required",authorization:"Reconnect required"}}/>);expect(main).toContain("Action required");expect(main).toContain("Reconnect YouTube");expect(main).toContain('href="/api/integrations/youtube/connect?role=official&amp;connectionId=youtube-main"');expect(backup).toContain('href="/api/integrations/youtube/connect?role=backup&amp;connectionId=youtube-backup"');});
  it("renders disconnected and stale explanations without internal errors",()=>{const html=renderToStaticMarkup(<ConnectedPlatformCard connection={{...healthy,health:"disconnected",authorization:"Reconnect required",stale:true}}/>);expect(html).toContain("Disconnected");expect(html).toContain("Synchronization and authorized access are stopped.");expect(html).toContain("may not be current");expect(html).not.toMatch(/token|scope|last_connection_error/i);});
  it("supports multiple provider account cards with unique accessible headings",()=>{const html=renderToStaticMarkup(<>{[healthy,{...healthy,id:"youtube-backup",accountName:"Backup Channel",role:"Backup Account"}].map((item)=><ConnectedPlatformCard key={item.id} connection={item}/>)}</>);expect(html).toContain('aria-labelledby="connection-youtube-main"');expect(html).toContain('aria-labelledby="connection-youtube-backup"');expect(html).toContain("Main Account");expect(html).toContain("Backup Account");});
  it("uses human synchronization language and shared authorization labels",()=>{const now=Date.parse("2026-08-07T12:00:00Z");expect(relativeProviderUpdate("2026-08-07T11:52:00Z",now)).toBe("Last synced 8 minutes ago");expect(relativeProviderUpdate("2026-08-06T08:00:00Z",now)).toBe("Last synced yesterday");expect(providerAuthorizationLabel("healthy")).toBe("Authorization active");expect(providerAuthorizationLabel("action_required")).toBe("Reconnect required");expect(providerAuthorizationLabel("healthy","cleanup_pending")).toBe("Pending cleanup");expect(connectionHealthDescriptions.syncing).toContain("updating");});
  it("includes responsive, focus, and reduced-motion affordances",()=>{const html=renderToStaticMarkup(<ConnectedPlatformCard connection={healthy}/>);expect(html).toContain("sm:grid-cols-2");expect(html).toContain("focus-visible:outline-2");expect(html).toContain("motion-reduce:transition-none");expect(html).toContain("Connection details");});
});
