import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { buildCreatorInsightNarrationInput, buildCreatorInsightNarrationPrompt, CreatorInsightNarrationPreParseError, creatorInsightNarrationFingerprint, getNarratedCreatorInsight, resetCreatorInsightNarrationCacheForTests, validateCreatorInsightNarration } from "@/lib/dashboard/creator-insight-narration";
import type { CreatorInsight } from "@/lib/dashboard/creator-insights";

const growth: CreatorInsight = { id: "recovery-growth-7d", category: "growth", priority: "medium", tone: "positive", title: "Your protected audience is growing", message: "24 new people have joined your recovery network in the last 7 days.", action: { label: "View growth", href: "/dashboard/audience" }, metadata: { protectedAudience: 318, growth7d: 24 } };
const stable: CreatorInsight = { id: "stable-recovery-network", category: "stability", priority: "low", tone: "neutral", title: "Your recovery network is ready", message: "Keep your Recovery Pass visible so new followers can join your backup network.", action: { label: "View audience", href: "/dashboard/audience" }, metadata: { protectedAudience: 318, growth7d: 0 } };
const connection: CreatorInsight = { id: "connection-instagram", category: "connection", priority: "critical", tone: "warning", title: "Instagram needs your attention", message: "Restore this connection. Your existing recovery destinations remain intact.", action: { label: "Manage accounts", href: "/dashboard/platforms" }, metadata: { provider: "instagram" } };
const original = { enabled: process.env.CREATOR_INSIGHT_NARRATION_ENABLED, key: process.env.OPENAI_API_KEY, model: process.env.OPENAI_CREATOR_INSIGHT_MODEL };
function enable() { process.env.CREATOR_INSIGHT_NARRATION_ENABLED = "true"; process.env.OPENAI_API_KEY = "test-key"; process.env.OPENAI_CREATOR_INSIGHT_MODEL = "test-model"; }

beforeEach(() => { resetCreatorInsightNarrationCacheForTests(); vi.spyOn(console, "info").mockImplementation(() => undefined); vi.spyOn(console, "warn").mockImplementation(() => undefined); });
afterEach(() => { vi.restoreAllMocks(); if (original.enabled === undefined) delete process.env.CREATOR_INSIGHT_NARRATION_ENABLED; else process.env.CREATOR_INSIGHT_NARRATION_ENABLED = original.enabled; if (original.key === undefined) delete process.env.OPENAI_API_KEY; else process.env.OPENAI_API_KEY = original.key; if (original.model === undefined) delete process.env.OPENAI_CREATOR_INSIGHT_MODEL; else process.env.OPENAI_CREATOR_INSIGHT_MODEL = original.model; });

describe("creator insight narration", () => {
  it("does not call a provider while narration is disabled", async () => { delete process.env.CREATOR_INSIGHT_NARRATION_ENABLED; const request = vi.fn(); expect(await getNarratedCreatorInsight(growth, { request })).toEqual(growth); expect(request).not.toHaveBeenCalled(); });
  it("falls back safely when required configuration is missing", async () => { process.env.CREATOR_INSIGHT_NARRATION_ENABLED = "true"; delete process.env.OPENAI_API_KEY; delete process.env.OPENAI_CREATOR_INSIGHT_MODEL; const request = vi.fn(); expect(await getNarratedCreatorInsight(growth, { request })).toEqual(growth); expect(request).not.toHaveBeenCalled(); expect(console.warn).toHaveBeenCalledWith(expect.stringContaining('"reason":"missing_configuration"')); });
  it("accepts valid structured copy while preserving authoritative fields and action", async () => { enable(); const narrated = await getNarratedCreatorInsight(growth, { request: vi.fn().mockResolvedValue({ title: "Momentum is building", message: "24 new people joined this week, bringing your protected audience to 318." }) }); expect(narrated).toMatchObject({ title: "Momentum is building", category: "growth", priority: "medium", tone: "positive", action: growth.action, metadata: growth.metadata }); });
  it("accepts the conservative V1 replacement for the real smoke-test input", () => { expect(validateCreatorInsightNarration(buildCreatorInsightNarrationInput(growth), { title: "Your recovery network is gaining momentum", message: "24 new people joined your recovery network in the last 7 days." })).toEqual({ ok: true, value: { title: "Your recovery network is gaining momentum", message: "24 new people joined your recovery network in the last 7 days." } }); });
  it("treats numbers in authoritative deterministic copy as allowed without permitting invented numbers", () => { const input = buildCreatorInsightNarrationInput(growth); expect(validateCreatorInsightNarration(input, { title: growth.title, message: growth.message })).toMatchObject({ ok: true }); expect(validateCreatorInsightNarration(input, { title: growth.title, message: "24 new people joined your recovery network in the last 8 days." })).toEqual({ ok: false, reason: "unsupported_number" }); });
  it("bypasses critical and warning insights without calling the narrator", async () => { enable(); const request = vi.fn(); expect(await getNarratedCreatorInsight(connection, { request })).toEqual(connection); const destination = { ...connection, id: "destination-backup", category: "recovery" as const, metadata: { provider: "youtube", state: "revoked" } }; expect(await getNarratedCreatorInsight(destination, { request })).toEqual(destination); expect(request).not.toHaveBeenCalled(); });
  it("rejects malformed output and falls back", async () => { enable(); expect(await getNarratedCreatorInsight(growth, { request: vi.fn().mockResolvedValue({ title: "Only a title" }) })).toEqual(growth); });
  it("makes one request per uncached evaluation and never retries a rejected response", async () => { enable(); const request = vi.fn().mockResolvedValue({ title: "YouTube growth is exploding", message: "25 new subscribers joined this week." }); expect(await getNarratedCreatorInsight(growth, { request })).toEqual(growth); expect(request).toHaveBeenCalledTimes(1); expect(console.warn).toHaveBeenCalledWith(expect.stringContaining('"reason":"unsupported_number"')); });
  it("rejects unsupported numbers", () => { expect(validateCreatorInsightNarration(buildCreatorInsightNarrationInput(growth), { title: "Momentum is building", message: "25 new people joined your recovery network." })).toEqual({ ok: false, reason: "unsupported_number" }); });
  it("rejects unsupported providers", () => { expect(validateCreatorInsightNarration(buildCreatorInsightNarrationInput(growth), { title: "YouTube momentum", message: "24 new people joined your recovery network." })).toEqual({ ok: false, reason: "unsupported_provider" }); });
  it("rejects engagement and stable-state growth claims", () => { const delivered: CreatorInsight = { ...growth, id: "delivered-update", category: "updates", metadata: { deliveredCount: 100 }, title: "100 confirmed deliveries" }; expect(validateCreatorInsightNarration(buildCreatorInsightNarrationInput(delivered), { title: "Your update connected", message: "100 people opened your update." })).toEqual({ ok: false, reason: "unsupported_claim" }); expect(validateCreatorInsightNarration(buildCreatorInsightNarrationInput(stable), { title: "Your network is growing quickly", message: "318 people are protected." })).toEqual({ ok: false, reason: "unsupported_claim" }); });
  it("rejects invented time claims", () => { expect(validateCreatorInsightNarration(buildCreatorInsightNarrationInput(stable), { title: "Your network is ready today", message: "318 people are part of your protected audience." })).toEqual({ ok: false, reason: "unsupported_claim" }); });
  it("falls back on timeout and provider failure", async () => { enable(); expect(await getNarratedCreatorInsight(growth, { request: vi.fn().mockRejectedValue(new DOMException("timed out", "AbortError")) })).toEqual(growth); expect(console.warn).toHaveBeenCalledWith(expect.stringContaining('"reason":"timeout"')); vi.mocked(console.warn).mockClear(); expect(await getNarratedCreatorInsight(growth, { request: vi.fn().mockRejectedValue(new Error("provider failed")) })).toEqual(growth); expect(console.warn).toHaveBeenCalledWith(expect.stringContaining('"reason":"provider_error"')); });
  it.each(["refusal", "incomplete", "missing_output", "parse_failed"] as const)("observes sanitized %s pre-parse fallback", async (reason) => { enable(); const observations: Array<{ stage: string; validation?: { accepted: boolean; reason?: string } }> = []; expect(await getNarratedCreatorInsight(growth, { request: vi.fn().mockRejectedValue(new CreatorInsightNarrationPreParseError(reason)), observer: (value) => observations.push(value) })).toEqual(growth); expect(observations).toEqual([expect.objectContaining({ stage: "fallback", providerRequestCount: 1, validation: { accepted: false, reason } })]); expect(console.warn).toHaveBeenCalledWith(expect.stringContaining(`"reason":"${reason}"`)); });
  it("forwards safe provider-completed metadata before parsed output", async () => { enable(); const observations: Array<{ stage: string; provider?: unknown }> = []; const request = vi.fn(async (_input, options) => { options.onProviderCompleted?.({ responseStatus: "completed", hasStructuredText: true, hasRefusal: false }); return { title: "Your recovery network is gaining momentum", message: "24 new people joined your recovery network in the last 7 days." }; }); await getNarratedCreatorInsight(growth, { request, observer: (value) => observations.push(value) }); expect(observations.slice(0, 3)).toEqual([expect.objectContaining({ stage: "provider_completed", fingerprint: expect.stringMatching(/^[a-f0-9]{12}$/), provider: { responseStatus: "completed", hasStructuredText: true, hasRefusal: false } }), expect.objectContaining({ stage: "parsed" }), expect.objectContaining({ stage: "validated", validation: { accepted: true } })]); });
  it("caches validated narration by fingerprint", async () => { enable(); const request = vi.fn().mockResolvedValue({ title: "Momentum is building", message: "24 new people joined this week, bringing your protected audience to 318." }); const first = await getNarratedCreatorInsight(growth, { request, now: 100 }); const second = await getNarratedCreatorInsight(growth, { request, now: 101 }); expect(first).toEqual(second); expect(request).toHaveBeenCalledTimes(1); expect(console.info).toHaveBeenCalledWith(expect.stringContaining('"cacheHit":true')); });
  it("observes parsed, validated, and cache-hit safe data", async () => { enable(); const observations: unknown[] = []; const observer = (value: unknown) => observations.push(value); const output = { title: "Your recovery network is gaining momentum", message: "24 new people joined your recovery network in the last 7 days." }; await getNarratedCreatorInsight(growth, { request: vi.fn().mockResolvedValue(output), observer, now: 100 }); await getNarratedCreatorInsight(growth, { observer, now: 101 }); expect(observations).toEqual([expect.objectContaining({ stage: "parsed", cacheHit: false, providerRequestCount: 1, parsed: output }), expect.objectContaining({ stage: "validated", cacheHit: false, validation: { accepted: true }, parsed: output }), expect.objectContaining({ stage: "cache_hit", cacheHit: true, providerRequestCount: 0, validation: { accepted: true }, parsed: output })]); const serialized = JSON.stringify(observations).toLowerCase(); for (const forbidden of ["api_key", "prompt", "header", "email", "phone", "cookie", "access_token", "refresh_token", "supabase", "dashboarddata"]) expect(serialized).not.toContain(forbidden); });
  it("observes rejection without caching and makes one request per invocation", async () => { enable(); const observations: Array<{ stage: string; validation?: { accepted: boolean; reason?: string } }> = []; const request = vi.fn().mockResolvedValue({ title: "Growth", message: "25 people joined." }); expect(await getNarratedCreatorInsight(growth, { request, observer: (value) => observations.push(value) })).toEqual(growth); expect(request).toHaveBeenCalledTimes(1); expect(observations).toContainEqual(expect.objectContaining({ stage: "validated", validation: { accepted: false, reason: "unsupported_number" } })); expect(observations).toContainEqual(expect.objectContaining({ stage: "fallback", validation: { accepted: false, reason: "unsupported_number" } })); const nextRequest = vi.fn().mockResolvedValue({ title: "Your recovery network is gaining momentum", message: "24 new people joined your recovery network in the last 7 days." }); await getNarratedCreatorInsight(growth, { request: nextRequest }); expect(nextRequest).toHaveBeenCalledTimes(1); });
  it("isolates observer return values and exceptions from narration", async () => { enable(); const output = { title: "Your recovery network is gaining momentum", message: "24 new people joined your recovery network in the last 7 days." }; const changed = await getNarratedCreatorInsight(growth, { request: vi.fn().mockResolvedValue(output), observer: () => ({ title: "Changed", message: "Changed" }) }); expect(changed).toMatchObject(output); resetCreatorInsightNarrationCacheForTests(); const throwing = await getNarratedCreatorInsight(growth, { request: vi.fn().mockResolvedValue(output), observer: () => { throw new Error("observer failed"); } }); expect(throwing).toMatchObject(output); });
  it("creates stable fingerprints that change with facts", () => { const input = buildCreatorInsightNarrationInput(growth); expect(creatorInsightNarrationFingerprint(input)).toBe(creatorInsightNarrationFingerprint({ ...input, facts: { growth7d: 24, protectedAudience: 318 } })); expect(creatorInsightNarrationFingerprint(input)).not.toBe(creatorInsightNarrationFingerprint({ ...input, facts: { ...input.facts, growth7d: 25 } })); });
  it("builds a minimized aggregate-only input without dashboard or PII fields", () => { const serialized = JSON.stringify(buildCreatorInsightNarrationInput(growth)).toLowerCase(); for (const forbidden of ["email", "phone", "fanname", "access_token", "refresh_token", "cookie", "oauth", "supabase", "creatorid", "dashboarddata"]) expect(serialized).not.toContain(forbidden); });
  it("constrains the narrator to explicit facts, exact numbers, exact timing, and category semantics", () => { const prompt = buildCreatorInsightNarrationPrompt(buildCreatorInsightNarrationInput(growth)); expect(prompt.system).toContain("controlled rephraser"); expect(prompt.system).toContain("Do not perform arithmetic"); expect(prompt.system).toContain("copy the deterministic wording"); expect(prompt.user).toContain("- growth7d = 24"); expect(prompt.user).toContain("- period = last 7 days"); expect(prompt.user).not.toContain("undefined"); expect(prompt.user).toContain("Preserve the exact phrase 'last 7 days'"); });
  it("rejects markup, URLs, emoji, excess length, and extra fields", () => { const input = buildCreatorInsightNarrationInput(growth); for (const output of [{ title: "<b>Growth</b>", message: "24 joined." }, { title: "**Growth**", message: "24 joined." }, { title: "Growth 🚀", message: "24 joined." }, { title: "Growth", message: "Visit https://example.com" }, { title: "x".repeat(81), message: "24 joined." }, { title: "Growth", message: "24 joined.", action: "/bad" }]) expect(validateCreatorInsightNarration(input, output)).toMatchObject({ ok: false }); });
});
