import{describe,expect,it}from"vitest";import{evaluateIdentityAccountPolicy,normalizeIdentityHostname,sameCanonicalIdentity,stableIdentityChanged}from"@/lib/identity/policy";import{parsePublicIdentityGraph,visibleIdentityAccounts}from"@/lib/identity/public";import{isDeliveryWorkerAuthorized}from"@/lib/delivery-worker-auth";
const graph={creator:{slug:"creator",displayName:"Creator"},identityStatus:"verified",accounts:[{provider:"youtube",displayHandle:"@creator",displayName:"Creator",canonicalProfileUrl:"https://youtube.com/channel/stable",accountKind:"channel",verificationStatus:"verified",official:true,primary:true,verifiedAt:"2026-01-01T00:00:00Z"}],domains:[{hostname:"creator.example",canonicalUrl:"https://creator.example",official:true,primary:true,verifiedAt:"2026-01-01T00:00:00Z"}],relationships:[],lastUpdatedAt:"2026-01-01T00:00:00Z"}as const;
describe("creator identity graph",()=>{
it("anchors canonical identity to provider and stable ID",()=>{expect(sameCanonicalIdentity({provider:"youtube",stableProviderAccountId:"1"},{provider:"youtube",stableProviderAccountId:"1"})).toBe(true);expect(sameCanonicalIdentity({provider:"youtube",stableProviderAccountId:"1"},{provider:"youtube",stableProviderAccountId:"2"})).toBe(false);});
it("distinguishes stable-ID changes from handle changes",()=>{expect(stableIdentityChanged("stable","stable")).toBe(false);expect(stableIdentityChanged("old","new")).toBe(true);});
it("requires verified accounts for official and primary presentation",()=>{expect(evaluateIdentityAccountPolicy({verificationStatus:"pending",official:true,primary:true,publicVisible:true,canonicalUrl:"https://x.com/a"}).blockers).toContain("verified_account_required");});
it("rejects public non-HTTPS destinations",()=>{expect(evaluateIdentityAccountPolicy({verificationStatus:"verified",official:false,primary:false,publicVisible:true,canonicalUrl:"http://example.test"}).blockers).toContain("public_url_must_be_https");});
it("keeps revoked and archived accounts inactive",()=>{expect(evaluateIdentityAccountPolicy({verificationStatus:"revoked",official:false,primary:false,publicVisible:false,canonicalUrl:"https://example.test"}).allowed).toBe(false);expect(evaluateIdentityAccountPolicy({verificationStatus:"archived",official:false,primary:false,publicVisible:false,canonicalUrl:"https://example.test"}).allowed).toBe(false);});
it("normalizes domains without accepting unsafe host forms",()=>{expect(normalizeIdentityHostname("Creator.Example.")).toBe("creator.example");expect(()=>normalizeIdentityHostname("localhost")).toThrow("domain_invalid");});
it("parses deterministic safe public graphs",()=>{expect(parsePublicIdentityGraph(graph)?.accounts[0].provider).toBe("youtube");expect(parsePublicIdentityGraph({creator:{}})).toBeNull();});
it("filters public accounts to verified HTTPS identities",()=>{const parsed=parsePublicIdentityGraph(graph)!;expect(visibleIdentityAccounts(parsed)).toHaveLength(1);expect(visibleIdentityAccounts({...parsed,accounts:[{...parsed.accounts[0],canonicalProfileUrl:"http://unsafe.test"}]})).toHaveLength(0);});
it("authenticates identity workers with the shared constant-time convention",()=>{expect(isDeliveryWorkerAuthorized("Bearer identity-secret","identity-secret")).toBe(true);expect(isDeliveryWorkerAuthorized("Bearer wrong","identity-secret")).toBe(false);expect(isDeliveryWorkerAuthorized(null,"identity-secret")).toBe(false);});
it("contains no trust score in the Stage 6 public contract",()=>{expect(JSON.stringify(graph)).not.toContain("trustScore");});
});
