import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { readFileSync } from "node:fs";
import { discordGuildAuthority } from "@/lib/providers/discord-authority";
import { getSocialProvider, listOAuthProviderRegistry } from "@/lib/social-providers/registry";
import { providerConnectionCapability } from "@/lib/social-providers/connection-capabilities";
import { createOAuthState,validateOAuthState } from "@/lib/social-providers/oauth";

const original={...process.env},redirect="https://audienceown.com/api/integrations/discord/callback",source=(path:string)=>readFileSync(path,"utf8"),json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json"}});
beforeEach(()=>{process.env.SOCIAL_OAUTH_STATE_SECRET="state-secret";process.env.DISCORD_CLIENT_ID="client";process.env.DISCORD_CLIENT_SECRET="secret";process.env.DISCORD_REDIRECT_URI=redirect;});
afterEach(()=>{process.env={...original};vi.restoreAllMocks();});
describe("Discord OAuth stage 11.9",()=>{
  it("launches with guild selection, approximate members, refresh, and revocation",()=>{expect(listOAuthProviderRegistry().find(item=>item.id==="discord")).toMatchObject({oauthImplemented:true,connectPath:"/api/integrations/discord/connect",audienceMetricSupported:true,assetSelectionSupported:true,refreshSupported:true,disconnectSupported:true});expect(getSocialProvider("discord").requestedScopes).toEqual(["identify","guilds"]);});
  it("builds the exact confidential authorization request without PKCE or unnecessary scopes",async()=>{const adapter=getSocialProvider("discord"),url=new URL((await adapter.createAuthorizationUrl!({state:"signed",codeChallenge:"ignored"})).url),scopes=url.searchParams.get("scope")?.split(" ")??[],forbidden=["email","connections","guilds.join","guilds.members.read","role_connections.write","webhook.incoming","bot","applications.commands","messages.read","activities.read","activities.write","dm_channels.read","relationships.read","voice"];expect(adapter.pkce).toBe(false);expect(url.origin+url.pathname).toBe("https://discord.com/oauth2/authorize");expect(url.searchParams.get("client_id")).toBe("client");expect(url.searchParams.get("redirect_uri")).toBe(redirect);expect(url.searchParams.get("response_type")).toBe("code");expect(url.searchParams.get("state")).toBe("signed");expect(scopes).toEqual(["identify","guilds"]);expect(scopes).not.toEqual(expect.arrayContaining(forbidden));expect(url.searchParams.has("code_challenge")).toBe(false);expect(url.searchParams.has("code_challenge_method")).toBe(false);});
  it("posts an exact form-encoded token exchange without a verifier",async()=>{const fetchMock=vi.fn().mockResolvedValue(json({access_token:"access",refresh_token:"refresh",expires_in:3600,token_type:"Bearer",scope:"identify guilds"}));vi.stubGlobal("fetch",fetchMock);await getSocialProvider("discord").exchangeAuthorizationCode!({code:"authorization-code",codeVerifier:"ignored"});const[url,init]=fetchMock.mock.calls[0],body=init.body as URLSearchParams;expect(url).toBe("https://discord.com/api/oauth2/token");expect(init).toMatchObject({method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"}});expect(body.get("grant_type")).toBe("authorization_code");expect(body.get("code")).toBe("authorization-code");expect(body.get("redirect_uri")).toBe(redirect);expect(body.get("client_id")).toBe("client");expect(body.get("client_secret")).toBe("secret");expect(body.has("code_verifier")).toBe(false);});
  it("maps only the stable current-user snowflake to external_account_id and tolerates optional metadata",async()=>{const fetchMock=vi.fn().mockResolvedValue(json({id:"80351110224678912",username:{malformed:true},global_name:null,avatar:42}));vi.stubGlobal("fetch",fetchMock);const identity=await getSocialProvider("discord").fetchIdentity!({accessToken:"access"});expect(fetchMock.mock.calls[0][0]).toBe("https://discord.com/api/v10/users/@me");expect(fetchMock.mock.calls[0][1]).toMatchObject({headers:{authorization:"Bearer access"}});expect(identity).toMatchObject({externalAccountId:"80351110224678912",displayName:"Discord user",metadata:{identityType:"authorizing_user",username:null,globalName:null,avatar:null}});expect(identity.externalAccountId).not.toBe(identity.displayName);});
  it("enforces signed state, nonce, expiry, provider, creator, user, role, reconnect, and official bindings",()=>{const payload={provider:"discord" as const,creatorId:"creator",userId:"user",nonce:"nonce",role:"backup" as const,connectionId:"00000000-0000-4000-8000-000000000310",protectedOfficialAccountId:"00000000-0000-4000-8000-000000000311",expiresAt:2000},state=createOAuthState(payload);expect(validateOAuthState(state,"discord","nonce",1999)).toEqual({ok:true,state:payload});expect(validateOAuthState(state,"discord","wrong",1999)).toMatchObject({ok:false,reason:"nonce_mismatch"});expect(validateOAuthState(state,"discord","nonce",2001)).toMatchObject({ok:false,reason:"state_expired"});expect(validateOAuthState(state,"snapchat","nonce",1999)).toMatchObject({ok:false,reason:"provider_mismatch"});expect(validateOAuthState(`${state}x`,"discord","nonce",1999)).toMatchObject({ok:false,reason:"state_signature_invalid"});});
  it.each(["DISCORD_CLIENT_ID","DISCORD_CLIENT_SECRET","DISCORD_REDIRECT_URI"])("is implemented but not connectable when %s is missing",name=>{delete process.env[name];const adapter=getSocialProvider("discord");expect(adapter.readiness?.()).toMatchObject({configured:false,connectionAvailable:false,missingConfiguration:expect.arrayContaining([name])});expect(providerConnectionCapability(adapter)).toMatchObject({implementationStatus:"implemented",configurationStatus:"missing",connectable:false,oauthStatus:"not_configured"});});
  it("accepts only ownership or effective management authority",()=>{expect(discordGuildAuthority({id:"12345",name:"Owned",owner:true}).authorityRole).toBe("owner");expect(discordGuildAuthority({id:"12346",name:"Admin",permissions:String(1<<3)}).guildAuthority).toBe(true);expect(discordGuildAuthority({id:"12347",name:"Manager",permissions:String(1<<5)}).authorityRole).toBe("manage_guild");expect(discordGuildAuthority({id:"12348",name:"Member",permissions:"0"}).guildAuthority).toBe(false);});
  it("discovers only authorized guilds through the exact Bearer endpoint",async()=>{const fetchMock=vi.fn().mockResolvedValueOnce(json([{id:"12345",name:"Community",icon:null,owner:true,permissions:"0",approximate_member_count:42},{id:"12346",name:"Membership only",owner:false,permissions:"0"}]));vi.stubGlobal("fetch",fetchMock);const assets=await getSocialProvider("discord").discoverAssets!({accessToken:"token"});expect(fetchMock.mock.calls[0][0]).toBe("https://discord.com/api/v10/users/@me/guilds?limit=200&with_counts=true");expect(fetchMock.mock.calls[0][1]).toMatchObject({headers:{authorization:"Bearer token"}});expect(assets).toEqual([expect.objectContaining({stableSourceId:"12345",canonicalUrl:"https://discord.com/",metadata:expect.objectContaining({approximateMemberCount:42,authorityValidated:true,publicInviteRequired:true})})]);});
  it("keeps guild selection separate from the canonical Discord user and preserves shared protections",()=>{const callback=source("app/api/integrations/[provider]/callback/route.ts"),selection=source("lib/providers/discord-oauth-server.ts"),connect=source("app/api/integrations/[provider]/connect/route.ts");expect(callback).toContain("target.external_account_id!==identity.externalAccountId");expect(callback).toContain("selectedGuildId");expect(callback).toContain('raw==="discord"');expect(callback).toContain('raw==="discord"');expect(selection).not.toContain("external_account_id:guildId");expect(selection).toContain("selectedGuildId:guildId");expect(selection).toContain('contains("provider_metadata",{selectedGuildId:guildId})');expect(callback).toContain("encryptSocialSecret(tokens.accessToken)");expect(callback).toContain("reconnect_mismatch");expect(callback).toContain("already_connected");expect(connect).toContain("canCreateProviderConnection");expect(connect).toContain("protectedOfficialAccountId");});
  it("handles callback denial, missing code, invalid state, and consumes the nonce cookie without leaking secrets",()=>{const callback=source("app/api/integrations/[provider]/callback/route.ts"),provider=source("lib/social-providers/providers/discord.ts"),env=source(".env.example");expect(callback).toContain("store.delete(`social_oauth_${raw}`)");expect(callback).toContain('reason:"nonce_cookie_missing"');expect(callback).toContain("validateOAuthState(stateValue,raw,saved.nonce)");expect(callback).toContain("authorization_failed");expect(callback).toContain("if(!code||!admin||!adapter.exchangeAuthorizationCode");expect(callback).toContain('new URL("/dashboard/platforms?social=discord:no_eligible_guilds",oauthCallbackOrigin(request))');expect(callback).not.toContain('new URL("/dashboard/platforms?social=discord:no_eligible_guilds",request.url)');expect(env).toContain("DISCORD_REDIRECT_URI=https://audienceown.com/api/integrations/discord/callback");expect(provider).not.toMatch(/console\.(log|info|warn|error)/);});
});
