import{describe,expect,it}from"vitest";import{evaluateTrust,providerFamily,publicTrustCopy}from"@/lib/identity/trust-policy";import{mayDisplayVerifiedTrust,parsePublicTrust}from"@/lib/identity/public";
const now=new Date("2026-08-15T12:00:00.000Z"),verifiedAt="2026-08-15T11:00:00.000Z";
const youtube={id:"yt",kind:"account"as const,provider:"youtube",verificationStatus:"verified",official:true,stableId:"channel-1",revalidatedAt:verifiedAt};
describe("explainable identity trust",()=>{
 it("groups related providers into one family",()=>{expect(providerFamily("instagram")).toBe("meta");expect(providerFamily("facebook")).toBe("meta");expect(providerFamily("youtube")).toBe("google");});
 it("requires independent families for strongly verified",()=>{const related=evaluateTrust([{...youtube,id:"fb",provider:"facebook",stableId:"fb-1"},{...youtube,id:"ig",provider:"instagram",stableId:"ig-1"}],{now});expect(related.trustState).toBe("verified");const independent=evaluateTrust([youtube,{id:"domain",kind:"domain",verificationStatus:"verified",official:true,verifiedAt}],{now});expect(independent.trustState).toBe("strongly_verified");});
 it("deduplicates the same stable provider identity",()=>{const result=evaluateTrust([youtube,{...youtube,id:"duplicate"}],{now});expect(result.signals).toHaveLength(1);});
 it("degrades stale evidence to needs attention",()=>{const result=evaluateTrust([youtube,{id:"domain",kind:"domain",verificationStatus:"verified",official:true,verifiedAt}],{now,providerFreshnessHours:.5});expect(result.trustState).toBe("needs_attention");expect(result.warnings).toContain("verification_stale");});
 it("never lets revoked evidence contribute positively",()=>{const result=evaluateTrust([{...youtube,verificationStatus:"revoked"}],{now});expect(result.trustState).toBe("restricted");expect(result.internalScore).toBe(0);});
 it("lets an active emergency replacement use its shorter freshness window",()=>{const result=evaluateTrust([{...youtube,id:"replacement",kind:"emergency",emergencyActive:true,revalidatedAt:"2026-08-14T10:00:00.000Z"}],{now,emergencyFreshnessHours:24});expect(result.trustState).toBe("unverified");expect(result.signals[0].state).toBe("stale");});
 it("generates specific deterministic recommendations",()=>{const result=evaluateTrust([],{now});expect(result.recommendations.map(r=>r.code)).toEqual(["verify_primary_account","verify_domain"]);});
 it("keeps internal score separate from public serialization",()=>{const result=evaluateTrust([youtube],{now});const trust={state:result.trustState,label:publicTrustCopy[result.trustState].label,summary:publicTrustCopy[result.trustState].summary,signals:[],lastEvaluatedAt:result.evaluatedAt};expect(JSON.stringify(trust)).not.toContain("internalScore");expect(parsePublicTrust(trust)?.state).toBe("verified");});
 it("suppresses verified presentation for restricted trust",()=>{expect(mayDisplayVerifiedTrust({state:"restricted",label:"Unavailable",summary:"Unavailable",signals:[],lastEvaluatedAt:null})).toBe(false);expect(mayDisplayVerifiedTrust({state:"verified",label:"Verified",summary:"Verified",signals:[],lastEvaluatedAt:null})).toBe(true);});
 it("rejects unsafe public shapes containing no valid contract",()=>{expect(parsePublicTrust({state:"verified",label:"Verified",summary:"ok",signals:"secret",lastEvaluatedAt:null})).toBeNull();});
});
