import{describe,expect,it}from"vitest";import{accountMonitoringFingerprint,domainMonitoringFingerprint}from"@/lib/identity/monitoring-fingerprint";import{classifyIdentityObservation,preciseAccountChanges}from"@/lib/identity/monitoring-policy";import{isDeliveryWorkerAuthorized}from"@/lib/delivery-worker-auth";
const account={provider:"youtube",stableProviderAccountId:"channel-1",displayHandle:"@Creator",displayName:"Creator",canonicalProfileUrl:"https://youtube.com/channel/channel-1",verificationStatus:"verified",official:true,publicVisible:true,primaryForProvider:true,providerHealthState:"healthy"};
describe("continuous identity monitoring",()=>{
 it("creates deterministic normalized account fingerprints",()=>{expect(accountMonitoringFingerprint(account)).toBe(accountMonitoringFingerprint({...account,displayHandle:" @creator "}));});
 it("creates deterministic domain fingerprints without volatile data",()=>{const input={hostname:"EXAMPLE.COM",canonicalUrl:"https://example.com",verificationStatus:"verified",dnsVerificationState:"verified",httpsVerificationState:"verified"};expect(domainMonitoringFingerprint(input)).toBe(domainMonitoringFingerprint({...input,hostname:"example.com"}));});
 it("classifies handle changes precisely without replacement",()=>{expect(preciseAccountChanges({stableId:"1",handle:"old",name:"Name",url:"https://x.test/1"},{stableId:"1",handle:"new",name:"Name",url:"https://x.test/1"})).toEqual(["account_handle_changed"]);expect(classifyIdentityObservation("account_handle_changed",{official:true}).severity).toBe("low");});
 it("makes stable-ID mismatches critical and suppresses presentation",()=>{expect(preciseAccountChanges({stableId:"1",handle:"old",name:"Name",url:"https://x.test/1"},{stableId:"2",handle:"new",name:"Other",url:"https://x.test/2"})).toEqual(["stable_identity_mismatch"]);const result=classifyIdentityObservation("stable_identity_mismatch");expect(result.severity).toBe("critical");expect(result.publicBadgeSuppressionRequired).toBe(true);expect(result.emergencyDraftAllowed).toBe(true);});
 it("does not escalate a first transient outage",()=>{expect(classifyIdentityObservation("sync_failure",{failureCount:1}).severity).toBe("informational");expect(classifyIdentityObservation("sync_failure",{failureCount:3}).severity).toBe("medium");});
 it("revokes presentation and triggers trust response for revoked grants",()=>{const result=classifyIdentityObservation("provider_grant_revoked",{official:true});expect(result.accountStateChange).toBe("revoked");expect(result.trustReevaluationRequired).toBe(true);expect(result.creatorNotificationRequired).toBe(true);});
 it("treats primary domain failures as high risk",()=>{const result=classifyIdentityObservation("domain_verification_failed",{primary:true});expect(result.severity).toBe("high");expect(result.publicBadgeSuppressionRequired).toBe(true);});
 it("never allows emergency drafting for invalidated active replacements",()=>{expect(classifyIdentityObservation("emergency_replacement_invalidated",{activeEmergency:true}).emergencyDraftAllowed).toBe(false);});
 it("requires an exact configured monitor worker bearer secret",()=>{expect(isDeliveryWorkerAuthorized("Bearer monitor-secret","monitor-secret")).toBe(true);expect(isDeliveryWorkerAuthorized("Bearer wrong","monitor-secret")).toBe(false);expect(isDeliveryWorkerAuthorized(null,undefined)).toBe(false);});
});
