import {afterEach,beforeEach,describe,expect,it,vi} from "vitest";
import {readFileSync} from "node:fs";
import {exchangeLinkedInCode,fetchLinkedInIdentity,discoverLinkedInOrganizations} from "@/lib/providers/linkedin";
import {providerConnectionCapability} from "@/lib/social-providers/connection-capabilities";
import {getSocialProvider,listOAuthProviderRegistry} from "@/lib/social-providers/registry";
import {createOAuthState,validateOAuthState} from "@/lib/social-providers/oauth";
import {providerAudienceCapabilities} from "@/lib/platform-audience/capabilities";
import {canProtectBackup} from "@/lib/social-providers/account-relationships";

const original={...process.env},source=(path:string)=>readFileSync(path,"utf8");
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json"}});
describe("Stage 11.7 LinkedIn OAuth",()=>{
  beforeEach(()=>{Object.assign(process.env,{SOCIAL_OAUTH_STATE_SECRET:"state",LINKEDIN_CLIENT_ID:"client",LINKEDIN_CLIENT_SECRET:"secret",LINKEDIN_REDIRECT_URI:"https://audienceown.com/api/integrations/linkedin/callback"});vi.restoreAllMocks();});
  afterEach(()=>{process.env={...original};vi.restoreAllMocks();});

  it("publishes a configured member OAuth connection with honest capabilities",()=>{expect(listOAuthProviderRegistry().find(item=>item.id==="linkedin")).toMatchObject({oauthImplemented:true,configuration:"configured",connectPath:"/api/integrations/linkedin/connect",audienceMetricSupported:false,assetSelectionSupported:false,refreshSupported:false,disconnectSupported:false});expect(providerConnectionCapability(getSocialProvider("linkedin"))).toMatchObject({implementationStatus:"implemented",configurationStatus:"configured",connectable:true,connectPath:"/api/integrations/linkedin/connect",supportsAudienceMetrics:false,audienceUnit:null});});
  it("requires complete configuration and an HTTPS redirect",()=>{delete process.env.LINKEDIN_CLIENT_SECRET;expect(providerConnectionCapability(getSocialProvider("linkedin"))).toMatchObject({configurationStatus:"missing",connectable:false});process.env.LINKEDIN_CLIENT_SECRET="secret";process.env.LINKEDIN_REDIRECT_URI="http://localhost:3000/api/integrations/linkedin/callback";expect(providerConnectionCapability(getSocialProvider("linkedin"))).toMatchObject({configurationStatus:"invalid",connectable:false});});
  it("uses authorization code OAuth with the exact callback and least-privilege OIDC scopes",async()=>{const adapter=getSocialProvider("linkedin"),url=new URL((await adapter.createAuthorizationUrl!({state:"signed"})).url);expect(url.origin+url.pathname).toBe("https://www.linkedin.com/oauth/v2/authorization");expect(url.searchParams.get("response_type")).toBe("code");expect(url.searchParams.get("redirect_uri")).toBe(process.env.LINKEDIN_REDIRECT_URI);expect(url.searchParams.get("scope")).toBe("openid profile");expect(url.searchParams.has("client_secret")).toBe(false);expect(url.searchParams.has("email")).toBe(false);});
  it("exchanges the code confidentially and accepts LinkedIn's token response without a refresh token",async()=>{const fetch=vi.spyOn(globalThis,"fetch").mockResolvedValueOnce(json({access_token:"access",expires_in:5184000,scope:"openid profile",token_type:"Bearer",id_token:"ignored-not-decoded"}));await expect(exchangeLinkedInCode("authorization-code")).resolves.toMatchObject({accessToken:"access",refreshToken:null,grantedScopes:["openid","profile"]});expect(fetch.mock.calls[0][0]).toBe("https://www.linkedin.com/oauth/v2/accessToken");const body=fetch.mock.calls[0][1]?.body as URLSearchParams;expect(body.get("client_secret")).toBe("secret");expect(body.get("redirect_uri")).toBe(process.env.LINKEDIN_REDIRECT_URI);});
  it("rejects malformed token responses",async()=>{vi.spyOn(console,"warn").mockImplementation(()=>{});vi.spyOn(globalThis,"fetch").mockResolvedValueOnce(json({expires_in:5184000,id_token:"untrusted"}));await expect(exchangeLinkedInCode("code")).rejects.toMatchObject({code:"malformed_provider_object",provider:"linkedin"});});
  it("normalizes stable member sub without inventing a vanity URL or metric",async()=>{vi.spyOn(globalThis,"fetch").mockResolvedValueOnce(json({sub:"stable-member",name:"Nana Example",given_name:"Nana",family_name:"Example",picture:"https://example.com/avatar.jpg"}));await expect(fetchLinkedInIdentity("access")).resolves.toMatchObject({externalAccountId:"stable-member",displayName:"Nana Example",profileUrl:"https://www.linkedin.com/",avatarUrl:"https://example.com/avatar.jpg",metadata:{identityType:"member",profileUrlAvailable:false,audienceMetricSupported:false}});});
  it("requires only the pairwise subject and tolerates absent optional profile claims",async()=>{vi.spyOn(globalThis,"fetch").mockResolvedValueOnce(json({sub:"pairwise-subject"}));await expect(fetchLinkedInIdentity("access")).resolves.toMatchObject({externalAccountId:"pairwise-subject",displayName:"LinkedIn member",avatarUrl:null,metadata:{oidcIdentitySource:"userinfo",oidcSubjectType:"pairwise"}});});
  it("ignores malformed optional avatar and profile URLs",async()=>{vi.spyOn(globalThis,"fetch").mockResolvedValueOnce(json({sub:"stable-member",name:null,picture:"javascript:alert(1)",profile:"https://attacker.example/profile"}));await expect(fetchLinkedInIdentity("access")).resolves.toMatchObject({externalAccountId:"stable-member",displayName:"LinkedIn member",profileUrl:"https://www.linkedin.com/",avatarUrl:null});});
  it.each([{}, {sub:""}, {sub:null}, {sub:123}])("fails closed without a stable OIDC subject: %j",async body=>{vi.spyOn(console,"warn").mockImplementation(()=>{});vi.spyOn(globalThis,"fetch").mockResolvedValueOnce(json(body));await expect(fetchLinkedInIdentity("access")).rejects.toMatchObject({code:"malformed_provider_object",provider:"linkedin"});});
  it("emits shape-only diagnostics without credentials",async()=>{const warn=vi.spyOn(console,"warn").mockImplementation(()=>{}),token="access-token-never-log";vi.spyOn(globalThis,"fetch").mockResolvedValueOnce(json({name:"Member",picture:"bad"}));await expect(fetchLinkedInIdentity(token)).rejects.toMatchObject({code:"malformed_provider_object"});const output=JSON.stringify(warn.mock.calls);for(const key of["traceId","operation","httpStatus","responseKeys","present","type","validationCategory"])expect(output).toContain(key);expect(output).not.toContain(token);expect(output).not.toContain("authorization");});
  it("validates signed state, nonce, expiry, and provider binding",()=>{const now=Date.now(),state=createOAuthState({creatorId:"creator",userId:"user",provider:"linkedin",nonce:"nonce",role:"backup",protectedOfficialAccountId:"11111111-1111-1111-1111-111111111111",expiresAt:now+60_000});expect(validateOAuthState(state,"linkedin","nonce",now)).toMatchObject({ok:true,state:{creatorId:"creator",userId:"user",role:"backup"}});expect(validateOAuthState(state,"linkedin","wrong",now)).toEqual({ok:false,reason:"nonce_mismatch"});expect(validateOAuthState(state,"linkedin","nonce",now+60_001)).toEqual({ok:false,reason:"state_expired"});expect(validateOAuthState(state,"spotify","nonce",now)).toEqual({ok:false,reason:"provider_mismatch"});});
  it("keeps creator binding, encrypted persistence, duplicate rejection, and exact reconnect checks in the shared callback",()=>{const callback=source("app/api/integrations/[provider]/callback/route.ts");expect(callback).toContain("state.userId!==user.id||state.creatorId!==creator.id");expect(callback).toContain("encryptSocialSecret(tokens.accessToken)");expect(callback).toContain("duplicateQuery");expect(callback).toContain("target.external_account_id!==identity.externalAccountId");expect(callback).toContain("reconnect_mismatch");});
  it.each([["manual Official → OAuth Backup",null,"oauth-backup"],["OAuth Official → Manual Backup","member-official",undefined],["Manual Official → Manual Backup",null,undefined],["OAuth Official → OAuth Backup","member-official","member-backup"]])("supports LinkedIn %s through the provider-neutral hierarchy",(_label,officialExternalId,backupId)=>{expect(canProtectBackup({backupId,backupCreatorId:"creator",backupProvider:"linkedin",backupRole:"backup",target:{id:"official",creator_id:"creator",platform:"linkedin",account_type:"official",url:"https://linkedin.com/in/official",external_account_id:officialExternalId,connection_health:officialExternalId?"healthy":"disconnected",provider_status:officialExternalId?"ready":"configuration_pending"}})).toBe(true);});
  it("rejects LinkedIn cross-provider, cross-creator, self, and backup parents",()=>{const backup={backupId:"backup",backupCreatorId:"creator",backupProvider:"linkedin",backupRole:"backup"},target={id:"official",creator_id:"creator",platform:"linkedin",account_type:"official",url:"https://linkedin.com/in/official",external_account_id:"member",connection_health:"healthy",provider_status:"ready"};expect(canProtectBackup({...backup,target:{...target,platform:"twitch"}})).toBe(false);expect(canProtectBackup({...backup,target:{...target,creator_id:"other"}})).toBe(false);expect(canProtectBackup({...backup,target:{...target,id:"backup"}})).toBe(false);expect(canProtectBackup({...backup,target:{...target,account_type:"backup"}})).toBe(false);});
  it("keeps zero and multiple managed organizations explicit",async()=>{const fetch=vi.spyOn(globalThis,"fetch").mockResolvedValueOnce(json({elements:[]})).mockResolvedValueOnce(json({elements:[{organization:"urn:li:organization:1",role:"ADMINISTRATOR",state:"APPROVED"},{organization:"urn:li:organization:2",role:"CONTENT_ADMINISTRATOR",state:"APPROVED"}]}));await expect(discoverLinkedInOrganizations("access")).resolves.toEqual([]);await expect(discoverLinkedInOrganizations("access")).resolves.toHaveLength(2);expect(fetch).toHaveBeenCalledTimes(2);});
  it("uses shared state, exact reconnect, duplicate protection, cleanup, and local disconnect",()=>{const connect=source("app/api/integrations/[provider]/connect/route.ts"),callback=source("app/api/integrations/[provider]/callback/route.ts"),disconnect=source("app/api/integrations/[provider]/disconnect/route.ts");expect(connect).toContain('"linkedin"');expect(connect).toContain("createOAuthState");expect(connect).toContain("connectionId");expect(callback).toContain('raw==="linkedin"');expect(callback).toContain("reconnect_mismatch");expect(callback).toContain("encryptSocialSecret(tokens.accessToken)");expect(callback).toContain("if(createdId)");expect(disconnect).toContain('"linkedin"');expect(disconnect).toContain("removeCreatorConnectedAccount");});
  it("models member metrics, refresh, revocation, and permissions accurately",()=>{const adapter=getSocialProvider("linkedin"),capability=providerConnectionCapability(adapter);expect(adapter.capabilities).toMatchObject({oauth:true,tokenRefresh:false,tokenRevocation:false,polling:false});expect(adapter.requestedScopes).toEqual(["openid","profile"]);expect(capability.supportsAudienceMetrics).toBe(false);expect(providerAudienceCapabilities.linkedin).toMatchObject({supported:false,selectedAssetType:null,officialField:null,requiredScopes:[]});});
  it("keeps personal and organization labels honest in the UI",()=>{const ui=source("components/platforms-manager.tsx");expect(ui).toContain('"Organization":"Professional profile"');expect(ui).toContain("Audience metric unavailable");});
});
