import{readFileSync}from"node:fs";import{describe,expect,it}from"vitest";import{RESERVED_SLUGS,slugSchema}from"@/lib/validation";
const source=(path:string)=>readFileSync(path,"utf8");
describe("premium creator onboarding",()=>{
 it("routes signup and creator creation into onboarding",()=>{expect(source("app/(auth)/actions.ts")).toContain("/auth/callback?next=/onboarding");expect(source("app/actions/creator.ts")).toContain('redirect("/onboarding/recovery-pass")');});
 it("uses persistent resumable milestones and backfills existing creators",()=>{const migration=source("supabase/migrations/20260903000000_creator_onboarding.sql");expect(migration).toContain("create table public.creator_onboarding");expect(migration).toContain("select id,now(),now(),now(),now() from public.creators");expect(source("app/dashboard/layout.tsx")).toContain("onboardingDestination");});
 it("reserves sensitive application routes",()=>{for(const slug of["admin","api","dashboard","signup","terms","privacy","onboarding"]){expect(RESERVED_SLUGS.has(slug)).toBe(true);expect(slugSchema.safeParse(slug).success).toBe(false)}});
 it("keeps identity creation idempotent and owner constrained",()=>{const action=source("app/onboarding/actions.ts"),migration=source("supabase/migrations/20260906000000_atomic_recovery_pass_creation.sql");expect(action).toContain('db.rpc("create_recovery_pass"');expect(migration).toContain('where owner_user_id=auth.uid()');expect(migration).toContain('coalesce(recovery_pass_completed_at,now())');expect(action).toContain('check_recovery_pass_name_availability');expect(source("supabase/migrations/20260905000000_recovery_pass_name_availability.sql")).toContain('c.owner_user_id<>auth.uid()');});
 it("reuses provider metadata, capability state, and entitlements",()=>{const page=source("app/onboarding/accounts/page.tsx"),component=source("components/onboarding-accounts.tsx");expect(page).toContain("listSocialProviders");expect(page).toContain("providerConnectionCapability");expect(page).toContain("getCreatorEntitlements");expect(component).toContain("providerPickerState");expect(component).toContain("PLATFORMS.filter");});
 it("supports shared copy, Web Share, and accessible fallback",()=>{for(const file of["components/recovery-pass-setup.tsx","components/recovery-pass-actions.tsx"]){const value=source(file);expect(value).toContain("copyRecoveryPassLink");expect(value).toContain("shareRecoveryPassLink")}const utility=source("lib/recovery-pass-client.ts");expect(utility).toContain("navigator.clipboard.writeText");expect(utility).toContain("navigator.share");expect(utility).toContain('document.execCommand("copy")')});
 it("provides explicit skip, completion, dashboard, and Recovery Pass actions",()=>{expect(source("components/onboarding-accounts.tsx")).toContain("Skip for now");const ready=source("app/onboarding/ready/page.tsx");expect(ready).toContain("Continue to dashboard");expect(ready).toContain("View my Recovery Pass");const actions=source("app/onboarding/actions.ts");expect(actions).toContain('destination === "recovery-pass" ? "/dashboard/creator-page" : "/dashboard"');});
 it("keeps provider authorization inside the signed onboarding journey",()=>{for(const file of["lib/social-providers/oauth.ts","lib/youtube-oauth.ts"]){expect(source(file)).toMatch(/returnTo\?\s*:\s*\"onboarding\"/)}for(const file of["app/api/integrations/[provider]/connect/route.ts","app/api/integrations/youtube/connect/route.ts","app/api/integrations/meta/connect/route.ts"]){expect(source(file)).toContain('returnTo')}expect(source("components/onboarding-accounts.tsx")).toContain("&returnTo=onboarding");});
 it("returns OAuth success, cancellation, and channel selection to the saved account role",()=>{for(const file of["app/api/integrations/[provider]/callback/route.ts","app/api/integrations/youtube/callback/route.ts","app/api/integrations/meta/callback/route.ts"]){const callback=source(file);expect(callback).toContain("/onboarding/accounts?step=");expect(callback).toContain("authorization_failed")}const youtube=source("app/api/integrations/youtube/callback/route.ts");expect(youtube).toContain('destination.searchParams.set("pendingSelectionId"');expect(source("app/onboarding/accounts/page.tsx")).toContain('returnTo="onboarding"');});
 it("shows recoverable OAuth feedback and connected-account change controls",()=>{const page=source("app/onboarding/accounts/page.tsx"),component=source("components/onboarding-accounts.tsx");expect(page).toContain("Your progress is safe");expect(page).toMatch(/&&\s*!params\.oauth/);expect(component).toContain("onboarding-oauth-message");expect(component).toContain("Change account");});
 it("publishes a minimal Recovery Pass as soon as identity setup succeeds",()=>{const migration=source("supabase/migrations/20260906000000_atomic_recovery_pass_creation.sql"),setup=source("components/recovery-pass-setup.tsx");expect(migration).toContain("public_profile_enabled=true");expect(migration).toContain("recovery_pass_enabled=true");expect(setup).toContain("recovery-preview-url");expect(setup).toContain("even if a platform account disappears");});
});
