import { readFileSync } from "node:fs";
import { describe,expect,it } from "vitest";

const read=(path:string)=>readFileSync(path,"utf8");

describe("route performance safeguards",()=>{
  it("keeps public policy routes free of Auth and database work",()=>{for(const path of ["app/privacy/page.tsx","app/terms/page.tsx","app/refund-policy/page.tsx","app/cookie-policy/page.tsx","app/google-api-disclosure/page.tsx","app/data-deletion/page.tsx","app/trust/page.tsx"]){const source=read(path);expect(source,path).not.toMatch(/getViewer|getCreator|requireViewer|requireCreator|createClient|\.from\(|\.rpc\(/);}});
  it("keeps Proxy authentication narrowly scoped to login-origin enforcement and protected pages",()=>{const source=read("proxy.ts");expect(source).toContain('matcher: ["/login", "/dashboard/:path*", "/onboarding/:path*"]');expect(source).not.toMatch(/from\(["'](?:creators|connected_accounts|subscriptions)/);expect(source).toContain("auth.getClaims()");});
  it("reuses one provider-account projection fetch per key route",()=>{for(const path of ["app/dashboard/platforms/page.tsx","app/dashboard/settings/connected-accounts/page.tsx","lib/dashboard/creator-dashboard.ts"]){const source=read(path);expect(source.match(/getCreatorProviderAccounts\(/g),path).toHaveLength(1);}});
  it("keeps independent dashboard reads parallel and provider APIs off page requests",()=>{const source=read("lib/dashboard/creator-dashboard.ts");expect(source).toContain("await Promise.all([");expect(source).toContain("getCreatorProviderAccounts(db, creator.id)");expect(source).not.toMatch(/youtube\.googleapis|fetch\([^)]*youtube/i);});
  it("uses one canonical public-page assembler and parallelizes supplementary reads",()=>{const source=read("app/c/[slug]/page.tsx");expect(source).toContain("getPublicCreatorPage(slug)");expect(source).toContain("[viewer, ownedCreator, identityResults] = await Promise.all");expect(source).not.toMatch(/from\(["'](?:creators|connected_accounts|creator_updates|creator_emergencies)/);});
  it("delegates audience reads to one canonical service with narrow preference columns",()=>{const page=read("app/dashboard/audience/page.tsx"),service=read("lib/audience-dashboard.ts");expect(page).toContain('from "@/lib/audience-dashboard"');expect(page).toContain("getAudienceDashboardData(db,creator.id");expect(page).not.toContain('.from("follower_');expect(service).toContain('select("follower_connection_id,new_content,creator_announcements,important_account_updates")');expect(service).not.toContain('follower_notification_preferences").select("*")');});
  it("preserves route-shaped loading UI for dynamic authenticated pages",()=>{for(const path of ["app/dashboard/loading.tsx","app/dashboard/platforms/loading.tsx","app/dashboard/audience/loading.tsx","app/dashboard/creator-page/loading.tsx","app/dashboard/settings/connected-accounts/loading.tsx"]){const source=read(path);expect(source,path).toContain("animate-pulse");expect(source,path).toContain("motion-reduce:animate-none");}});
  it("keeps creator-scoped account invalidation after mutations",()=>{const source=read("lib/social-providers/creator-account-revalidation.ts");expect(source).toContain("creator-accounts:${creatorId}");expect(source).toContain("creator-dashboard:${creatorId}");expect(source).toContain('revalidatePath("/dashboard/settings/connected-accounts")');});
  it("does not ship an unused toast runtime through the root layout",()=>{const source=read("app/layout.tsx");expect(source).not.toContain("sonner");expect(source).not.toContain("<Toaster");});
});
