import {afterEach,beforeEach,describe,expect,it,vi} from "vitest";
import {readFileSync} from "node:fs";
import {exchangePinterestCode,fetchPinterestIdentity,refreshPinterestToken} from "@/lib/providers/pinterest";
import {normalizeProviderAudience} from "@/lib/platform-audience/normalize";
import {providerConnectionCapability} from "@/lib/social-providers/connection-capabilities";
import {getSocialProvider,listOAuthProviderRegistry} from "@/lib/social-providers/registry";
import {createOAuthState,validateOAuthState} from "@/lib/social-providers/oauth";

const original={...process.env},source=(path:string)=>readFileSync(path,"utf8"),json=(body:unknown,status=200,headers:HeadersInit={})=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json",...headers}});
const readScopes=["user_accounts:read","boards:read","pins:read"];
const token=(overrides:Record<string,unknown>={})=>({access_token:"pina_access",refresh_token:"pinr_refresh",token_type:"bearer",expires_in:2592000,refresh_token_expires_in:5184000,scope:readScopes.join(" "),...overrides});
describe("Stage 11.8 Pinterest OAuth",()=>{
  beforeEach(()=>{Object.assign(process.env,{SOCIAL_OAUTH_STATE_SECRET:"state",PINTEREST_APP_ID:"1600991",PINTEREST_APP_SECRET:"secret",PINTEREST_REDIRECT_URI:"https://audienceown.com/api/integrations/pinterest/callback",PINTEREST_ACCESS_STATUS:"approved"});vi.restoreAllMocks();});
  afterEach(()=>{process.env={...original};vi.restoreAllMocks();});
  it("publishes Pinterest with account-level metrics and no asset selection",()=>{expect(listOAuthProviderRegistry().find(item=>item.id==="pinterest")).toMatchObject({oauthImplemented:true,configuration:"configured",connectPath:"/api/integrations/pinterest/connect",audienceMetricSupported:true,assetSelectionSupported:false,refreshSupported:true,disconnectSupported:false});expect(providerConnectionCapability(getSocialProvider("pinterest"))).toMatchObject({implementationStatus:"implemented",connectable:true,audienceUnit:"followers"});});
  it("requires the unavailable Trial secret before becoming configured or connectable",()=>{delete process.env.PINTEREST_APP_SECRET;delete process.env.PINTEREST_ACCESS_STATUS;const adapter=getSocialProvider("pinterest");expect(adapter.readiness?.()).toMatchObject({configured:false,connectionAvailable:false,reviewStatus:"not_configured",missingConfiguration:["PINTEREST_APP_SECRET"]});expect(providerConnectionCapability(adapter)).toMatchObject({implementationStatus:"implemented",configurationStatus:"missing",connectable:false,oauthStatus:"not_configured"});});
  it("uses the exact production authorization contract without undocumented PKCE or write scopes",async()=>{const adapter=getSocialProvider("pinterest"),url=new URL((await adapter.createAuthorizationUrl!({state:"signed",codeChallenge:"must-be-ignored"})).url),scopes=url.searchParams.get("scope")?.split(" ")??[];expect(adapter.pkce).toBe(false);expect(url.origin+url.pathname).toBe("https://www.pinterest.com/oauth/");expect(url.searchParams.get("client_id")).toBe("1600991");expect(url.searchParams.get("redirect_uri")).toBe("https://audienceown.com/api/integrations/pinterest/callback");expect(url.searchParams.get("response_type")).toBe("code");expect(url.searchParams.get("state")).toBe("signed");expect(scopes).toEqual(readScopes);expect(scopes.every(scope=>scope.endsWith(":read"))).toBe(true);expect(scopes).not.toEqual(expect.arrayContaining(["ads:read","billing:read","biz_access:read","catalogs:read"]));expect(scopes.some(scope=>scope.includes(":write"))).toBe(false);expect(url.searchParams.has("code_challenge")).toBe(false);expect(url.searchParams.has("code_challenge_method")).toBe(false);});
  it("exchanges codes with Basic auth, exact redirect and no PKCE verifier",async()=>{const fetch=vi.spyOn(globalThis,"fetch").mockResolvedValueOnce(json(token()));await expect(getSocialProvider("pinterest").exchangeAuthorizationCode!({code:"code",codeVerifier:"must-be-ignored"})).resolves.toMatchObject({accessToken:"pina_access",refreshToken:"pinr_refresh",grantedScopes:readScopes});const init=fetch.mock.calls[0][1]!,body=init.body as URLSearchParams;expect(fetch.mock.calls[0][0]).toBe("https://api.pinterest.com/v5/oauth/token");expect(init.headers).toMatchObject({authorization:`Basic ${Buffer.from("1600991:secret").toString("base64")}`});expect(body.get("grant_type")).toBe("authorization_code");expect(body.get("code")).toBe("code");expect(body.get("redirect_uri")).toBe("https://audienceown.com/api/integrations/pinterest/callback");expect(body.get("continuous_refresh")).toBe("true");expect(body.get("client_secret")).toBeNull();expect(body.get("code_verifier")).toBeNull();});
  it("keeps signed state, nonce, expiry, provider, role, creator and reconnect bindings",()=>{const payload={provider:"pinterest" as const,creatorId:"creator",userId:"user",nonce:"nonce",role:"backup" as const,connectionId:"00000000-0000-4000-8000-000000000210",protectedOfficialAccountId:"00000000-0000-4000-8000-000000000211",expiresAt:2000},state=createOAuthState(payload);expect(validateOAuthState(state,"pinterest","nonce",1999)).toEqual({ok:true,state:payload});expect(validateOAuthState(state,"pinterest","wrong",1999)).toMatchObject({ok:false,reason:"nonce_mismatch"});expect(validateOAuthState(state,"pinterest","nonce",2001)).toMatchObject({ok:false,reason:"state_expired"});expect(validateOAuthState(state,"snapchat","nonce",1999)).toMatchObject({ok:false,reason:"provider_mismatch"});});
  it("rotates refresh tokens only after a complete response",async()=>{vi.spyOn(globalThis,"fetch").mockResolvedValueOnce(json(token({access_token:"next",refresh_token:"rotated",refresh_token_expires_at:1893456000})));await expect(refreshPinterestToken("old")).resolves.toMatchObject({accessToken:"next",refreshToken:"rotated",refreshTokenExpiresAt:"2030-01-01T00:00:00.000Z"});vi.mocked(globalThis.fetch).mockResolvedValueOnce(json({access_token:"partial"}));await expect(refreshPinterestToken("old")).rejects.toMatchObject({code:"malformed_provider_object"});});
  it("normalizes stable numeric account identity independently from username",async()=>{vi.spyOn(globalThis,"fetch").mockResolvedValueOnce(json({id:"2783136121146311751",username:"creator",business_name:"Creator Studio",profile_image:"https://example.com/avatar.png",account_type:"BUSINESS",follower_count:0}));await expect(fetchPinterestIdentity("access")).resolves.toMatchObject({externalAccountId:"2783136121146311751",displayName:"Creator Studio",username:"creator",profileUrl:"https://www.pinterest.com/creator/",avatarUrl:"https://example.com/avatar.png",metadata:{identityType:"user_account",followerCount:0}});});
  it.each([0,18450])("preserves an exact %i-follower account metric",count=>expect(normalizeProviderAudience("pinterest",{follower_count:count})).toEqual({count,status:"available",approximate:false}));
  it("uses shared signed state, roles, reconnect, cleanup, metrics, and local disconnect",()=>{const connect=source("app/api/integrations/[provider]/connect/route.ts"),callback=source("app/api/integrations/[provider]/callback/route.ts"),disconnect=source("app/api/integrations/[provider]/disconnect/route.ts");expect(connect).toContain('"pinterest","twitch"');expect(connect).toContain("createOAuthState");expect(callback).toContain('raw==="pinterest"');expect(callback).toContain("reconnect_mismatch");expect(callback).toContain("encryptSocialSecret(tokens.accessToken)");expect(callback).toContain('"pinterest"');expect(callback).toContain("if(createdId)");expect(disconnect).toContain('"pinterest","twitch"');expect(disconnect).toContain("removeCreatorConnectedAccount");});
  it("classifies provider failures without secret logging",async()=>{vi.spyOn(globalThis,"fetch").mockResolvedValueOnce(json({},429,{"retry-after":"30"}));await expect(exchangePinterestCode("code")).rejects.toMatchObject({code:"rate_limited",retryAfterSeconds:30});expect(source("lib/providers/pinterest.ts")).not.toMatch(/console\.(log|info|warn|error)/);});
});
