// @vitest-environment jsdom

import { act } from "react";
import { createRoot, hydrateRoot, type Root } from "react-dom/client";
import { renderToString } from "react-dom/server";
import { afterEach, describe, expect, it, vi } from "vitest";

vi.mock("@/components/billing-action",()=>({BillingAction:({kind,interval,children,className}:{kind:string;interval?:string;children:React.ReactNode;className?:string})=><button className={className} data-kind={kind} data-interval={interval}>{children}</button>}));
vi.mock("next/navigation",()=>({useRouter:()=>({refresh:vi.fn()})}));
import { PlansBillingWorkspace } from "@/components/plans-billing-workspace";

const pricing={monthly:{interval:"monthly" as const,unitAmount:1200,currency:"usd",recurringInterval:"month" as const},yearly:{interval:"yearly" as const,unitAmount:12000,currency:"usd",recurringInterval:"year" as const},savingsPercent:17};
let root:Root|undefined;
afterEach(async()=>{await act(async()=>root?.unmount());document.body.innerHTML="";vi.restoreAllMocks();root=undefined;});
async function render(plan:"free"|"pro"="free",extra:Partial<React.ComponentProps<typeof PlansBillingWorkspace>>={}){const node=document.createElement("div");document.body.append(node);root=createRoot(node);await act(async()=>root?.render(<PlansBillingWorkspace canPreviewBilling={false} canManageBilling={plan==="pro"} canCancelSubscription={plan==="pro"} plan={plan} subscriptionStatus={plan==="pro"?"active":"inactive"} billingInterval={null} pendingInterval={null} periodEnd="2026-10-01T00:00:00Z" pendingEffectiveAt={null} cancelAtPeriodEnd={false} hasBillingRelationship={plan==="pro"} pricing={pricing} {...extra}/>));return node;}

describe("Plans & Billing workspace",()=>{
  it("server-renders and hydrates the canonical FAQ without changing its text or order",async()=>{const props:React.ComponentProps<typeof PlansBillingWorkspace>={canPreviewBilling:false,canManageBilling:false,canCancelSubscription:false,plan:"free",subscriptionStatus:"inactive",billingInterval:null,pendingInterval:null,periodEnd:null,pendingEffectiveAt:null,cancelAtPeriodEnd:false,hasBillingRelationship:false,pricing};const view=<PlansBillingWorkspace {...props}/>;const server=renderToString(view);expect(server).toContain("Can I upgrade from Free at any time?");expect(server).not.toContain("Can I change plans later?");const node=document.createElement("div");node.innerHTML=server;document.body.append(node);const recoverable:unknown[]=[];await act(async()=>{root=hydrateRoot(node,view,{onRecoverableError:error=>recoverable.push(error)});});const questions=[...node.querySelectorAll<HTMLButtonElement>(".plans-faq article>button")].map(button=>button.textContent);expect(questions).toEqual(["Can I upgrade from Free at any time?","Can I switch between monthly and yearly billing?","What happens when I switch billing intervals?","Can I undo a scheduled billing change?","How do I manage or cancel my subscription?","What happens if I cancel Pro?"]);expect(node.innerHTML).toContain("Can I upgrade from Free at any time?");expect(node.innerHTML).not.toContain("Can I change plans later?");expect(recoverable).toEqual([]);});
  it("starts with the Plans & Billing eyebrow and omits the removed marketing hero copy",async()=>{const node=await render();expect(node.querySelector(".plans-hero")?.textContent).toContain("Plans & Billing");expect(node.textContent).not.toContain("Choose the plan that fits your journey");expect(node.textContent).not.toContain("Simple plans for every stage of building and protecting your audience.");expect(node.querySelector(".plans-hero + .plans-period")).not.toBeNull();});
  it("keeps price presentation and checkout interval synchronized",async()=>{const node=await render();expect(node.textContent).toContain("$12 / month");expect(node.textContent).toContain("Monthly billing");expect(node.querySelector('[data-kind="checkout"]')?.getAttribute("data-interval")).toBe("monthly");const monthly=[...node.querySelectorAll("button")].find(button=>button.textContent?.includes("Monthly billing"))!,yearly=[...node.querySelectorAll("button")].find(button=>button.textContent?.includes("Yearly billing"))!;await act(async()=>yearly.click());expect(node.textContent).toContain("$10 / month");expect(node.textContent).toContain("Billed $120 yearly");expect(node.textContent).toContain("Save 17%");expect(node.querySelector("#authenticated-pro-plan")?.getAttribute("aria-label")).toBe("$10 per month, billed $120 annually.");expect(node.querySelector('[data-kind="checkout"]')?.getAttribute("data-interval")).toBe("yearly");await act(async()=>monthly.click());expect(node.textContent).toContain("$12 / month");expect(node.textContent).not.toContain("Billed $120 yearly");expect(node.querySelector('[data-kind="checkout"]')?.getAttribute("data-interval")).toBe("monthly");});
  it("implements the Pro Monthly interval state matrix",async()=>{const node=await render("pro",{billingInterval:"monthly"});expect(node.querySelector(".plans-pro")?.textContent).toContain("Current plan");const yearly=[...node.querySelectorAll("button")].find(button=>button.textContent?.includes("Yearly billing"))!;await act(async()=>yearly.click());expect(node.querySelector(".plans-pro")?.textContent).toContain("Switch to yearly");expect(node.querySelector(".plans-pro [data-kind='checkout']")).toBeNull();});
  it("implements the Pro Yearly interval state matrix",async()=>{const node=await render("pro",{billingInterval:"yearly"});expect(node.querySelector(".plans-pro")?.textContent).toContain("Current plan");const monthly=[...node.querySelectorAll("button")].find(button=>button.textContent?.includes("Monthly billing"))!;await act(async()=>monthly.click());expect(node.querySelector(".plans-pro")?.textContent).toContain("Switch to monthly");expect(node.querySelector(".plans-pro [data-kind='checkout']")).toBeNull();});
  it("confirms a switch with real period-end copy before making a request",async()=>{const fetch=vi.spyOn(globalThis,"fetch").mockResolvedValue(new Response(JSON.stringify({pendingInterval:"yearly"}),{status:200,headers:{"content-type":"application/json"}}));const node=await render("pro",{billingInterval:"monthly",periodEnd:"2026-09-22T00:00:00Z"});const yearly=[...node.querySelectorAll("button")].find(button=>button.textContent?.includes("Yearly billing"))!;await act(async()=>yearly.click());const switchButton=[...node.querySelectorAll<HTMLButtonElement>(".plans-pro button")].find(button=>button.textContent==="Switch to yearly")!;await act(async()=>switchButton.click());const dialog=document.body.querySelector<HTMLElement>('[role="dialog"]')!;expect(dialog.textContent).toContain("Switch to yearly billing?");expect(dialog.textContent).toContain("$12/month");expect(dialog.textContent).toContain("$120/year");expect(dialog.textContent).toContain("September 22, 2026");expect(fetch).not.toHaveBeenCalled();const confirm=[...dialog.querySelectorAll("button")].find(button=>button.textContent==="Confirm switch to yearly")!;await act(async()=>confirm.click());expect(fetch).toHaveBeenCalledWith("/api/billing/interval",expect.objectContaining({method:"POST",body:JSON.stringify({interval:"yearly"})}));});
  it("shows the canonical effective date for a pending Monthly to Yearly switch",async()=>{const node=await render("pro",{billingInterval:"monthly",pendingInterval:"yearly",pendingEffectiveAt:"2026-09-22T00:00:00Z"});expect(node.querySelector(".plans-pro")?.textContent).toContain("Current plan");const yearly=[...node.querySelectorAll("button")].find(button=>button.textContent?.includes("Yearly billing"))!;await act(async()=>yearly.click());const pending=node.querySelector(".plans-pending-switch")!;expect(pending.textContent).toContain("Switch to yearly scheduled");expect(pending.textContent).toContain("Starts September 22, 2026");expect(pending.textContent).toContain("Keep monthly billing");expect(pending.getAttribute("role")).toBe("status");});
  it("shows the canonical effective date for a pending Yearly to Monthly switch",async()=>{const node=await render("pro",{billingInterval:"yearly",pendingInterval:"monthly",pendingEffectiveAt:"2027-09-22T00:00:00Z"});const yearly=[...node.querySelectorAll("button")].find(button=>button.textContent?.includes("Yearly billing"))!;await act(async()=>yearly.click());expect(node.querySelector(".plans-pro")?.textContent).toContain("Current plan");const monthly=[...node.querySelectorAll("button")].find(button=>button.textContent?.includes("Monthly billing"))!;await act(async()=>monthly.click());const pending=node.querySelector(".plans-pending-switch")!;expect(pending.textContent).toContain("Switch to monthly scheduled");expect(pending.textContent).toContain("Starts September 22, 2027");expect(pending.textContent).toContain("Keep yearly billing");});
  it("removes pending presentation after Stripe makes the new interval current",async()=>{const node=await render("pro",{billingInterval:"yearly",pendingInterval:null,pendingEffectiveAt:null});const yearly=[...node.querySelectorAll("button")].find(button=>button.textContent?.includes("Yearly billing"))!;await act(async()=>yearly.click());expect(node.querySelector(".plans-pro")?.textContent).toContain("Current plan");expect(node.querySelector(".plans-pending-switch")).toBeNull();const monthly=[...node.querySelectorAll("button")].find(button=>button.textContent?.includes("Monthly billing"))!;await act(async()=>monthly.click());expect(node.querySelector(".plans-pro")?.textContent).toContain("Switch to monthly");});
  it("uses the existing release endpoint for Keep current billing",async()=>{const fetch=vi.spyOn(globalThis,"fetch").mockResolvedValue(new Response(JSON.stringify({pendingInterval:null}),{status:200,headers:{"content-type":"application/json"}}));const node=await render("pro",{billingInterval:"monthly",pendingInterval:"yearly",pendingEffectiveAt:"2031-04-18T00:00:00Z"});const yearly=[...node.querySelectorAll("button")].find(button=>button.textContent?.includes("Yearly billing"))!;await act(async()=>yearly.click());expect(node.querySelector(".plans-pending-switch")?.textContent).toContain("Starts April 18, 2031");const keep=[...node.querySelectorAll<HTMLButtonElement>(".plans-pending-switch button")].find(button=>button.textContent==="Keep monthly billing")!;await act(async()=>keep.click());expect(fetch).toHaveBeenCalledWith("/api/billing/interval",expect.objectContaining({method:"DELETE"}));});
  it("formats a fractional yearly monthly-equivalent without misleading rounding",async()=>{const node=await render("free",{pricing:{...pricing,yearly:{...pricing.yearly,unitAmount:11900},savingsPercent:17}});const yearly=[...node.querySelectorAll("button")].find(button=>button.textContent?.includes("Yearly billing"))!;await act(async()=>yearly.click());expect(node.textContent).toContain("$9.92 / month");expect(node.textContent).toContain("Billed $119 yearly");expect(node.querySelector('[data-kind="checkout"]')?.getAttribute("data-interval")).toBe("yearly");});
  it("shows Free as current without paid subscription controls",async()=>{const node=await render();expect(node.textContent).toContain("You're on the Free plan");expect(node.textContent).not.toContain("Cancel subscription →");expect(node.querySelector('[data-kind="portal"]')).toBeNull();});
  it("shows paid controls and requires cancellation review before the portal",async()=>{const node=await render("pro",{billingInterval:"monthly"});expect(node.querySelectorAll('[data-kind="portal"]')).toHaveLength(2);const cancel=[...node.querySelectorAll("button")].find(button=>button.textContent==="Cancel subscription →")!;await act(async()=>cancel.click());const dialog=document.body.querySelector('[role="dialog"]')!;expect(dialog.textContent).toContain("Cancel your Pro subscription?");expect(dialog.textContent).toContain("Monthly");expect(dialog.textContent).toContain("October 1, 2026");expect(dialog.textContent).toContain("Confirm cancellation");});
  it("shows a truthful scheduled-cancellation state",async()=>{const node=await render("pro",{cancelAtPeriodEnd:true});expect(node.textContent).toContain("Subscription ends on");expect(node.textContent).not.toContain("Cancel subscription →");});
  it("keeps a past-due billing relationship manageable and labels it truthfully",async()=>{const node=await render("free",{subscriptionStatus:"past_due",hasBillingRelationship:true});expect(node.textContent).toContain("Billing needs attention");expect(node.querySelector('[data-kind="portal"]')).not.toBeNull();expect(node.textContent).not.toContain("You're on the Free plan");});
  it("uses accessible billing controls and stacked comparison labels",async()=>{const node=await render();expect(node.querySelector('[role="radiogroup"]')).not.toBeNull();expect(node.querySelectorAll('[role="radio"]')).toHaveLength(2);const faq=node.querySelector<HTMLButtonElement>('[aria-controls="billing-answer-0"]')!;expect(faq.getAttribute("aria-expanded")).toBe("false");await act(async()=>faq.click());expect(faq.getAttribute("aria-expanded")).toBe("true");expect(node.querySelector('[role="table"]')).not.toBeNull();});
  it("explains the verified billing system in the required FAQ order",async()=>{const node=await render();const questions=[...node.querySelectorAll<HTMLButtonElement>(".plans-faq article>button")].map(button=>button.textContent);expect(questions).toEqual(["Can I upgrade from Free at any time?","Can I switch between monthly and yearly billing?","What happens when I switch billing intervals?","Can I undo a scheduled billing change?","How do I manage or cancel my subscription?","What happens if I cancel Pro?"]);const copy=node.querySelector(".plans-faq")?.textContent??"";for(const truth of["choose monthly or yearly billing","price for each option is always shown","end of your current billing period","existing subscription","does not create a second subscription","Pro access continues throughout the transition","removes the pending billing change","does not cancel Pro","Manage Billing","through Stripe","Cancel Subscription","paid subscription is scheduled to end","Free plan limits"])expect(copy).toContain(truth);expect(copy).not.toContain("Do you offer refunds?");expect(copy).not.toMatch(/switch(?:es)? immediately|immediate(?:ly)? charge/i);});
  it("keeps static FAQ copy independent of commercial pricing",async()=>{const node=await render();const copy=node.querySelector(".plans-faq")?.textContent??"";for(const commercialValue of["$12","$120","$10","17%"]){expect(copy).not.toContain(commercialValue);}expect(copy).toContain("current price");expect(copy).toContain("applicable price shown");});
  it("never exposes billing preview controls to an ordinary creator",async()=>{const node=await render();expect(node.textContent).not.toContain("Preview billing state");expect(node.querySelector("#billing-preview-state")).toBeNull();});
  it("lets an authorized admin inspect Pro without changing FAQ copy or faking unavailable real billing actions",async()=>{const node=await render("free",{canPreviewBilling:true});const faqBefore=node.querySelector(".plans-faq")?.textContent;const select=node.querySelector<HTMLSelectElement>("#billing-preview-state")!;expect(select.value).toBe("real");await act(async()=>{select.value="pro";select.dispatchEvent(new Event("change",{bubbles:true}));});expect(node.querySelector(".plans-faq")?.textContent).toBe(faqBefore);expect(node.textContent).toContain("Admin preview · pro");expect(node.textContent).toContain("Manage billing →");expect(node.textContent).toContain("Cancel subscription →");expect(node.querySelector('[data-kind="portal"]')).toBeNull();const manage=node.querySelector<HTMLButtonElement>(".subscription-actions article:first-child button")!,cancel=node.querySelector<HTMLButtonElement>(".subscription-cancel button")!;await act(async()=>manage.click());expect(node.textContent).toContain("This preview account does not have an active billing profile yet.");await act(async()=>cancel.click());expect(document.body.querySelector('[role="dialog"]')).toBeNull();expect(node.textContent).toContain("No real paid subscription exists to cancel.");});
  it("allows real capabilities while preview remains visually active",async()=>{const node=await render("pro",{canPreviewBilling:true});const select=node.querySelector<HTMLSelectElement>("#billing-preview-state")!;await act(async()=>{select.value="pro";select.dispatchEvent(new Event("change",{bubbles:true}));});expect(node.querySelector(".subscription-actions [data-kind='portal']")).not.toBeNull();const cancel=node.querySelector<HTMLButtonElement>(".subscription-cancel button")!;await act(async()=>cancel.click());expect(document.body.querySelector('[role="dialog"]')).not.toBeNull();});
  it("previews past-due and canceling states without live portal or cancellation controls",async()=>{const node=await render("free",{canPreviewBilling:true});const select=node.querySelector<HTMLSelectElement>("#billing-preview-state")!;await act(async()=>{select.value="past_due";select.dispatchEvent(new Event("change",{bubbles:true}));});expect(node.textContent).toContain("Billing needs attention");expect(node.querySelector('[data-kind="portal"]')).toBeNull();await act(async()=>{select.value="canceling";select.dispatchEvent(new Event("change",{bubbles:true}));});expect(node.textContent).toContain("Subscription ends on");expect(node.textContent).not.toContain("Cancel subscription →");expect(node.querySelector('[data-kind="portal"]')).toBeNull();});
});
