import{readFileSync}from"node:fs";import{describe,expect,it}from"vitest";import{canonicalNetworkStatus,derivePlatformContextEvent,derivePlatformDeletionEvent,deriveRecoveryAssignmentEvent,toAiSafePlatformEvent,type CanonicalPlatformAccount,type CanonicalRecoveryNetwork}from"@/lib/intelligence/platform-context-event";
const main=(patch:Partial<CanonicalPlatformAccount>={}):CanonicalPlatformAccount=>({id:"main",platform:"youtube",label:"KwaMoon",external_account_name:"KwaMoon",account_type:"official",connection_health:"healthy",provider_status:"ready",url:"https://youtube.example/main",external_account_id:"channel",...patch});
const recovery=(patch:Partial<CanonicalPlatformAccount>={}):CanonicalPlatformAccount=>({id:"recovery",platform:"facebook",label:"WatchBoost",external_account_name:"WatchBoost",account_type:"backup",connection_health:"healthy",provider_status:"ready",url:"https://facebook.example/recovery",external_account_id:"page",...patch});
const network=(patch:Partial<CanonicalRecoveryNetwork>={}):CanonicalRecoveryNetwork=>({id:"network-a",main_connected_account_id:"main",recovery_account_ids:[],...patch});
describe("canonical Platforms context events",()=>{
 it("classifies KwaMoon from its persisted Main role despite a Recovery transport hint",()=>{const account=main(),n=network(),event=derivePlatformContextEvent({transportStatus:"connected_recovery_linked",account,network:n,accounts:[account]});expect(event).toMatchObject({type:"main_account_connected",canonicalRole:"main",title:"Main account connected",networkStatus:"needs_recovery"});expect(event?.description).toContain("KwaMoon is now the Main account");expect(event?.title).not.toContain("Recovery");});
 it("supports a replacement event only when the trusted operation supplies replacement context",()=>{const account=main(),r=recovery(),n=network({recovery_account_ids:[r.id]}),event=derivePlatformContextEvent({transportStatus:"connected_recovery_linked",account,network:n,accounts:[account,r],targetedExistingNetwork:true});expect(event).toMatchObject({type:"main_account_replaced",title:"Main account replaced",networkStatus:"protected",recoveryCount:1});});
 it("describes a new Main and recommends the allowlisted Recovery action",()=>{const account=main(),event=derivePlatformContextEvent({transportStatus:"connected",account,network:network(),accounts:[account]});expect(event).toMatchObject({type:"main_account_connected",canonicalRole:"main",actionId:"ADD_RECOVERY_ACCOUNT",tone:"main"});});
 it("keeps role separate when a Main connection needs attention",()=>{const account=main({provider_status:"asset_selection_required"}),event=derivePlatformContextEvent({transportStatus:"connected",account,network:network(),accounts:[account]});expect(event).toMatchObject({type:"connection_needs_attention",canonicalRole:"main",accountHealth:"attention",networkStatus:"attention"});});
 it("classifies healthy and attention Recovery accounts from canonical backup role",()=>{const m=main(),r=recovery(),n=network({recovery_account_ids:[r.id]});expect(derivePlatformContextEvent({transportStatus:"connected_recovery_linked",account:r,network:n,accounts:[m,r]})).toMatchObject({type:"recovery_account_connected",canonicalRole:"recovery",networkStatus:"protected"});const pending=recovery({provider_status:"asset_selection_required"});expect(derivePlatformContextEvent({transportStatus:"connected_recovery_linked",account:pending,network:n,accounts:[m,pending]})).toMatchObject({type:"connection_needs_attention",canonicalRole:"recovery",accountHealth:"attention"});});
 it("distinguishes an existing Recovery assignment from a provider connection",()=>{const m=main(),r=recovery(),n=network({recovery_account_ids:[r.id]});expect(deriveRecoveryAssignmentEvent({account:r,network:n,accounts:[m,r]})).toMatchObject({type:"recovery_account_linked",title:"Recovery account assigned"});});
 it("derives protected, needs-Recovery, and needs-Main readiness from network membership",()=>{const m=main(),r=recovery();expect(canonicalNetworkStatus(network(),[m])).toMatchObject({status:"needs_recovery",mainPresent:true,healthyRecoveryCount:0});expect(canonicalNetworkStatus(network({recovery_account_ids:[r.id]}),[m,r])).toMatchObject({status:"protected",healthyRecoveryCount:1});expect(canonicalNetworkStatus(network({main_connected_account_id:null,recovery_account_ids:[r.id]}),[r])).toMatchObject({status:"needs_main",mainPresent:false,recoveryCount:1});});
 it("describes persistent Main and global Recovery deletion without inventing counts",()=>{const r=recovery(),emptyMain=network({main_connected_account_id:null,recovery_account_ids:[r.id]});expect(derivePlatformDeletionEvent({type:"main_account_deleted",network:emptyMain,accounts:[r]}).description).toContain("Recovery accounts are still here");expect(derivePlatformDeletionEvent({type:"recovery_account_deleted",network:network(),accounts:[main()]}).description).not.toMatch(/\d/);expect(derivePlatformDeletionEvent({type:"recovery_account_deleted",network:network(),accounts:[main()],removedNetworkCount:2}).description).toContain("2 Recovery Networks");});
 it("exposes only bounded, deterministic AI facts and an allowlisted action",()=>{const account=main(),event=derivePlatformContextEvent({transportStatus:"connected",account,network:network(),accounts:[account]})!,safe=toAiSafePlatformEvent(event);expect(safe).toMatchObject({eventType:"main_account_connected",role:"main",networkStatus:"needs_recovery",mainPresent:true,persistent:true,allowedAction:"ADD_RECOVERY_ACCOUNT"});expect(JSON.stringify(safe)).not.toMatch(/token|credential|nonce|signed|contact/i);});
 it("ignores missing or foreign canonical account IDs and consumes one-time URL state",()=>{expect(derivePlatformContextEvent({transportStatus:"connected_recovery_linked",account:null,network:null,accounts:[]})).toBeNull();const page=readFileSync("app/dashboard/platforms/page.tsx","utf8"),banner=readFileSync("components/platform-context-banner.tsx","utf8");expect(page).not.toContain("Recovery destination added");expect(page).toContain("returnedAccountId?canonicalAccounts.find");expect(banner).toContain("window.history.replaceState");for(const key of["social","youtube","connectionId"])expect(banner).toContain(`\"${key}\"`);});
});
