import{createHmac}from"node:crypto";import{afterEach,describe,expect,it,vi}from"vitest";
import{discoverLinkedInOrganizations,fetchLinkedInIdentity,pollLinkedInPosts}from"@/lib/providers/linkedin";
import{canonicalExpansionThreeUrl,classifyExpansionThreeError,manualExpansionThreeContent}from"@/lib/providers/provider-expansion-three";
import{fetchThreadsIdentity,pollThreadsPosts,verifyThreadsSignature,threadsWebhookSchema}from"@/lib/providers/threads";
import{fetchXIdentity,pollXPosts,refreshXToken}from"@/lib/providers/x";
import{xProvider}from"@/lib/social-providers/providers/x";import{linkedinProvider}from"@/lib/social-providers/providers/linkedin";import{threadsProvider}from"@/lib/social-providers/providers/threads";import{providerReadiness}from"@/lib/social-providers/readiness";
const environment={...process.env};afterEach(()=>{process.env={...environment};vi.restoreAllMocks();});
const response=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json"}});

describe("Stage 8.4 exact manual URLs",()=>{it("accepts X status URLs",()=>expect(manualExpansionThreeContent("x",{url:"https://x.com/creator/status/12345",title:"Post",publishedAt:"2026-08-02T10:00:00.000Z"})).toEqual(expect.objectContaining({externalObjectId:"manual:12345",rawMetadata:expect.objectContaining({trustEligible:false})})));it("rejects X profiles as content",()=>expect(manualExpansionThreeContent("x",{url:"https://x.com/creator",title:"Profile",publishedAt:"2026-08-02T10:00:00.000Z"})).toBeNull());it("accepts LinkedIn public update URLs",()=>expect(manualExpansionThreeContent("linkedin",{url:"https://www.linkedin.com/feed/update/urn:li:activity:12345",title:"Update",publishedAt:"2026-08-02T10:00:00.000Z"})).not.toBeNull());it("accepts Threads post URLs",()=>expect(manualExpansionThreeContent("threads",{url:"https://www.threads.net/@creator/post/ABC_123",title:"Thread",publishedAt:"2026-08-02T10:00:00.000Z"})).not.toBeNull());it("rejects lookalike hosts",()=>expect(canonicalExpansionThreeUrl("threads","https://threads.net.evil.example/@creator/post/x")).toBeNull());it("requires trustworthy timestamps",()=>expect(manualExpansionThreeContent("x",{url:"https://x.com/a/status/1",title:"Post",publishedAt:"today"})).toBeNull())});

describe("provider boundaries",()=>{it("X authorization uses S256 PKCE and no write scope",async()=>{process.env.X_CLIENT_ID="id";process.env.X_REDIRECT_URI="https://example.com/callback";const url=new URL((await xProvider.createAuthorizationUrl!({state:"signed",codeChallenge:"challenge"})).url);expect(url.searchParams.get("code_challenge_method")).toBe("S256");expect(url.searchParams.get("scope")).not.toContain("write")});it("X never defaults to an approved tier",()=>{delete process.env.X_API_ACCESS_TIER;expect(providerReadiness(xProvider).contentDetectionAvailable).toBe(false)});it("LinkedIn OIDC wording is explicitly non-verifying",()=>expect(providerReadiness(linkedinProvider).limitations.join(" ")).toContain("not LinkedIn real-world identity verification"));it("LinkedIn restricted products default disabled",()=>{delete process.env.LINKEDIN_MEMBER_SOCIAL_ENABLED;delete process.env.LINKEDIN_ORGANIZATION_SOCIAL_ENABLED;expect(providerReadiness(linkedinProvider).contentDetectionAvailable).toBe(false)});it("Threads does not inherit Instagram authority",()=>expect(providerReadiness(threadsProvider).limitations.join(" ")).toContain("never inferred from Instagram"));it("all approved providers disable publishing",()=>{for(const adapter of[xProvider,linkedinProvider,threadsProvider])expect(adapter.capabilities.automaticPublishing).toBe(false)});it("all approved providers expose manual import",()=>{for(const adapter of[xProvider,linkedinProvider,threadsProvider])expect(providerReadiness(adapter).manualImportAvailable).toBe(true)});it("classifies rate limits as retryable",()=>expect(classifyExpansionThreeError(new Error("rate_limited"))).toEqual(expect.objectContaining({retryable:true})))});

describe("X API normalization",()=>{it("parses refresh tokens",async()=>{process.env.X_CLIENT_ID="id";process.env.X_CLIENT_SECRET="secret";vi.stubGlobal("fetch",vi.fn().mockResolvedValue(response({token_type:"bearer",access_token:"next",refresh_token:"refresh-next",expires_in:3600,scope:"tweet.read users.read"})));await expect(refreshXToken("refresh-old")).resolves.toEqual(expect.objectContaining({accessToken:"next",refreshToken:"refresh-next",grantedScopes:["tweet.read","users.read"]}))});it("normalizes stable identity independently of username",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(response({data:{id:"12345",name:"Creator",username:"renamed",protected:false}})));await expect(fetchXIdentity("token")).resolves.toEqual(expect.objectContaining({id:"12345",metadata:expect.objectContaining({handle:"renamed"})}))});it("normalizes posts and pagination",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(response({data:[{id:"10",text:"Hello",created_at:"2026-08-02T10:00:00.000Z",author_id:"12345"}],meta:{next_token:"next"}})));await expect(pollXPosts("token","12345","creator")).resolves.toEqual(expect.objectContaining({cursor:"next",items:[expect.objectContaining({externalObjectId:"10"})]}))});it("requires a stable numeric account ID",async()=>await expect(pollXPosts("token","creator","creator")).rejects.toThrow("stable_identity_required"));it("classifies provider rate limits",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(response({},429)));await expect(fetchXIdentity("token")).rejects.toThrow("rate_limited")})});

describe("LinkedIn boundaries",()=>{it("parses OIDC without asserting real-world verification",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(response({sub:"member-1",name:"Creator"})));await expect(fetchLinkedInIdentity("token")).resolves.toEqual(expect.objectContaining({id:"member-1",metadata:expect.objectContaining({realWorldIdentityVerified:false})}))});it("filters organizations by approved authority",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(response({elements:[{organization:"urn:li:organization:1",role:"ADMINISTRATOR",state:"APPROVED"},{organization:"urn:li:organization:2",role:"CURATOR",state:"APPROVED"}]})));await expect(discoverLinkedInOrganizations("token")).resolves.toHaveLength(1)});it("uses versioned Rest.li headers and normalizes posts",async()=>{process.env.LINKEDIN_API_VERSION="202603";const mocked=vi.fn().mockResolvedValue(response({elements:[{id:"urn:li:share:1",author:"urn:li:organization:1",commentary:"Update",lifecycleState:"PUBLISHED",createdAt:1785664800000}],paging:{start:0,count:1,total:2}}));vi.stubGlobal("fetch",mocked);const result=await pollLinkedInPosts("token","urn:li:organization:1");expect(result.cursor).toBe("1");expect(result.items[0].canonicalUrl).toContain("urn%3Ali%3Ashare%3A1");expect(mocked.mock.calls[0][1].headers).toEqual(expect.objectContaining({"LinkedIn-Version":"202603","X-Restli-Protocol-Version":"2.0.0"}))});it("rejects malformed post identifiers",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(response({elements:[{id:"https://evil.example/post",author:"member",lifecycleState:"PUBLISHED",createdAt:1785664800000}]})));await expect(pollLinkedInPosts("token","member")).rejects.toThrow()})});

describe("Threads boundaries",()=>{it("normalizes dedicated Threads identity",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(response({id:"threads-1",username:"creator",name:"Creator"})));await expect(fetchThreadsIdentity("threads-token")).resolves.toEqual(expect.objectContaining({id:"threads-1",metadata:expect.objectContaining({providerProduct:"threads"})}))});it("normalizes posts and pagination",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(response({data:[{id:"post-1",text:"Hello",timestamp:"2026-08-02T10:00:00.000Z",permalink:"https://www.threads.net/@creator/post/ABC"}],paging:{cursors:{after:"next"}}})));await expect(pollThreadsPosts("threads-token","threads-1")).resolves.toEqual(expect.objectContaining({cursor:"next",items:[expect.objectContaining({externalObjectId:"post-1"})]}))});it("verifies signed webhooks",()=>{process.env.THREADS_CLIENT_SECRET="secret";const body='{"object":"threads","entry":[]}',signature=`sha256=${createHmac("sha256","secret").update(body).digest("hex")}`;expect(verifyThreadsSignature(body,signature)).toBe(true);expect(verifyThreadsSignature(`${body}x`,signature)).toBe(false)});it("rejects unrelated webhook fields",()=>expect(threadsWebhookSchema.safeParse({object:"threads",entry:[{id:"1",time:1,changes:[{field:"messages"}]}]}).success).toBe(false))});
