import{readFileSync}from"node:fs";import{describe,expect,it}from"vitest";
import{providerPickerState}from"@/components/platforms-manager";
import type{ProviderConnectionCapability}from"@/lib/social-providers/types";
const source=(path:string)=>readFileSync(path,"utf8");
const capability={provider:"youtube",displayName:"YouTube",description:"YouTube",implementationStatus:"implemented",configurationStatus:"configured",reviewStatus:"not_applicable",connectable:true,connectPath:"/api/integrations/youtube/connect",oauthSupported:true,oauthStatus:"available",manualSupported:false,manualInput:"channel_url",supportsAudienceMetrics:true,audienceUnit:"subscribers",supportsAutomaticVerification:true,supportsManualVerification:false,supportsWebhooks:false,supportsPolling:true} satisfies ProviderConnectionCapability;
describe("provider connection entitlements",()=>{
  it("keeps connected cards visible and gives locked cards an actionable upgrade label",()=>{expect(providerPickerState(capability,true,"official",true)).toMatchObject({disabled:true,label:"Connected"});expect(providerPickerState(capability,false,"official",true)).toMatchObject({disabled:true,label:"Upgrade to Pro",href:null});});
  it("keeps provider setup blockers truthful at the plan limit",()=>{expect(providerPickerState({...capability,connectable:false,configurationStatus:"missing"},false,"official",true)).toMatchObject({disabled:true,label:"Setup required",tone:"setup",href:null});});
  it("enforces new OAuth at connect and callback while preserving reconnect",()=>{for(const file of["app/api/integrations/[provider]/connect/route.ts","app/api/integrations/[provider]/callback/route.ts","app/api/integrations/youtube/connect/route.ts","app/api/integrations/meta/connect/route.ts"])expect(source(file)).toContain("canCreateProviderConnection");expect(source("lib/provider-entitlements.ts")).toContain('operation==="reconnect"||slot.allowed');});
  it("normalizes database races and manual creation",()=>{expect(source("app/actions/creator.ts")).toContain('"connection_limit_reached"');expect(source("app/api/integrations/[provider]/manual-import/route.ts")).toContain('error:"connection_limit_reached"');expect(source("supabase/migrations/20260831000000_provider_connection_entitlements.sql")).toContain("pg_advisory_xact_lock");});
  it("keeps billing state service-role-only and fails closed",()=>{const migration=source("supabase/migrations/20260831000000_provider_connection_entitlements.sql");expect(migration).toContain("revoke all on public.creator_plan_entitlements from public, anon, authenticated");expect(migration).toContain("else 'free'");expect(migration).toContain("resolved_status in ('trialing', 'active')");});
});
