import { readFileSync } from "node:fs";
import { describe,expect,it } from "vitest";
import { providerPickerState } from "@/components/platforms-manager";
import { providerConnectionCapability } from "@/lib/social-providers/connection-capabilities";
import { getSocialProvider,listOAuthProviderRegistry } from "@/lib/social-providers/registry";

describe("Stage 11.11 provider launch readiness",()=>{
  it("contains exactly the eleven implemented OAuth providers",()=>{const expected=["youtube","instagram","facebook","tiktok","x","spotify","twitch","linkedin","snapchat","pinterest","discord"];const registry=listOAuthProviderRegistry();expect(registry.map(item=>item.id)).toEqual(expected);expect(registry.every(item=>item.oauthImplemented&&item.connectPath===`/api/integrations/${item.id}/connect`)).toBe(true);});
  it("preserves exact official and backup picker roles without global disabling",()=>{const previous=[process.env.GOOGLE_YOUTUBE_CLIENT_ID,process.env.GOOGLE_YOUTUBE_CLIENT_SECRET,process.env.GOOGLE_YOUTUBE_REDIRECT_URI,process.env.YOUTUBE_OAUTH_STATE_SECRET];Object.assign(process.env,{GOOGLE_YOUTUBE_CLIENT_ID:"id",GOOGLE_YOUTUBE_CLIENT_SECRET:"secret",GOOGLE_YOUTUBE_REDIRECT_URI:"https://app.test/api/integrations/youtube/callback",YOUTUBE_OAUTH_STATE_SECRET:"state"});const capability=providerConnectionCapability(getSocialProvider("youtube"));expect(providerPickerState(capability,false,"official").href).toContain("role=official");expect(providerPickerState(capability,false,"backup").href).toContain("role=backup");expect(providerPickerState(capability,true,"official")).toMatchObject({disabled:true,label:"Connected"});expect(providerPickerState(capability,false,"backup").disabled).toBe(false);[process.env.GOOGLE_YOUTUBE_CLIENT_ID,process.env.GOOGLE_YOUTUBE_CLIENT_SECRET,process.env.GOOGLE_YOUTUBE_REDIRECT_URI,process.env.YOUTUBE_OAUTH_STATE_SECRET]=previous;});
  it("does not schedule unsupported audience metrics",()=>{const worker=readFileSync("app/api/internal/providers/audience-metrics/sync/route.ts","utf8");expect(worker).toContain('p_next_sync_at:capability.supported?new Date(0).toISOString():null');expect(worker).toContain('p_next_sync_at:usable?new Date(0).toISOString():null');});
  it("keeps exact-account credential, metric, reconnect, and removal boundaries",()=>{const refresh=readFileSync("lib/social-providers/authorized-credential.ts","utf8"),callback=readFileSync("app/api/integrations/[provider]/callback/route.ts","utf8"),removal=readFileSync("lib/connected-account-removal.ts","utf8"),metric=readFileSync("supabase/migrations/20260827000000_platform_audience_metrics.sql","utf8");expect(refresh).toContain('eq("platform_connection_id",connectionId)');expect(refresh).toContain("token.refreshToken??oldRefresh");expect(callback).toContain("reconnect_mismatch");expect(removal).toContain('eq("id", connectionId).eq("creator_id", creatorId)');expect(metric).toContain("provider_audience_metrics_connection_uidx");});
  it("keeps sensitive diagnostics redacted",()=>{const debug=readFileSync("lib/debug.ts","utf8"),oauth=readFileSync("lib/social-providers/oauth.ts","utf8");expect(debug).toContain("SENSITIVE_KEY");for(const term of["access_?token","refresh_?token","authorization_?code","signed_?state","code_?verifier","client_?secret"])expect(debug).toContain(term);expect(oauth).toContain("timingSafeEqual");expect(oauth).toContain("payload.nonce===nonce");});
});
