import { describe, expect, it } from "vitest";
import { buildPublicVerifiedIdentity } from "@/lib/public-verified-identity";
import type { AuthenticityRecord } from "@/lib/authenticity/types";

const creator = { id:"creator-a", profile_image_path: null, recovery_pass_enabled: true } as never;
const record: AuthenticityRecord = { creator: { slug: "nana", displayName: "Nana", profileUrl: "/c/nana" }, authenticity: { state: "verified_identity", label: "Verified identity", summary: "Verified presence", lastUpdatedAt: "2026-01-01", verificationUrl: "/verify/nana", title: "Creator · Entrepreneur · Host", publicSummary: "I'm Nana Kwame and I am a YouTuber.", embedEnabled: false, qrEnabled: false, showVerifiedTimestamps: false, showRelationshipHistory: false }, accounts: [], domains: [], relationships: [], emergency: null, continuity: [], assertion: null };
const connection = (id:string,type:"official"|"backup",position:number,overrides:Record<string,unknown>={}) => ({ id, creator_id:"creator-a", platform:"youtube", account_type:type, label:id, external_account_id:id, external_account_name:id, external_account_url:`https://youtube.com/@${id}`, url:`https://youtube.com/@${id}`, is_public:true, connection_health:"healthy", provider_status:"ready", position, ...overrides });
const identity = (id:string,verified=true) => ({ source_connection_id:id, verification_status:verified?"verified":"pending", public_visible:true, official:true, display_name:id, display_handle:`@${id}`, canonical_profile_url:`https://youtube.com/@${id}` });
const network = (id:string,main:string,recoveries:string[],position:number) => ({ id, main_connected_account_id:main, position, recovery_network_destinations:recoveries.map((recovery_connected_account_id,index)=>({recovery_connected_account_id,created_at:`2026-01-0${index+1}`})) });

describe("public verified Recovery Network",()=>{
  it("exposes persisted public presentation fields without replacing them with verification copy",()=>{const model=buildPublicVerifiedIdentity({creator,record,connections:[],identities:[],networks:[],affectedAccountId:null,emergencyType:null});expect(model.presentation).toEqual({publicTitle:"Creator · Entrepreneur · Host",publicSummary:"I'm Nana Kwame and I am a YouTuber."});expect(model.presentation.publicSummary).not.toBe(model.verification.summary);});
  it("preserves two Main-scoped networks without cross-network leakage",()=>{const model=buildPublicVerifiedIdentity({creator,record,connections:[connection("KwaMoon","official",0),connection("WatchBoost","official",1),connection("nana_friggy","backup",2),connection("Lineconomy","backup",3),connection("NPA","backup",4)],identities:[identity("KwaMoon"),identity("WatchBoost"),identity("nana_friggy"),identity("Lineconomy"),identity("NPA")],networks:[network("a","KwaMoon",["nana_friggy","Lineconomy"],0),network("b","WatchBoost",["NPA"],1)],affectedAccountId:null,emergencyType:null});expect(model.creatorVerification).toMatchObject({status:"verified",verifiedMainAccountCount:2,totalMainAccountCount:2});expect(model.verification).toMatchObject({label:"Verified by AudienceOwn",summary:"AudienceOwn has verified Nana's control of 2 Main accounts."});expect(model.recoveryNetworks.map(item=>[item.mainAccount.displayName,item.recoveryAccounts.map(account=>account.displayName)])).toEqual([["KwaMoon",["nana_friggy","Lineconomy"]],["WatchBoost",["NPA"]]]);});
  it("allows one recovery account in multiple networks, dedupes it within one, and retains empty Mains",()=>{const model=buildPublicVerifiedIdentity({creator,record,connections:[connection("KwaMoon","official",0),connection("WatchBoost","official",1),connection("Lineconomy","backup",2)],identities:[identity("KwaMoon"),identity("WatchBoost"),identity("Lineconomy")],networks:[network("a","KwaMoon",["Lineconomy","Lineconomy"],0),network("b","WatchBoost",["Lineconomy"],1)],affectedAccountId:null,emergencyType:null});expect(model.recoveryNetworks.map(item=>item.recoveryAccounts.length)).toEqual([1,1]);expect(model.recoveryNetworks.map(item=>item.mainAccount.displayName)).toEqual(["KwaMoon","WatchBoost"]);});
  it("keeps unverified public accounts visible and promotes only the affected network",()=>{const emergencyRecord:AuthenticityRecord={...record,emergency:{active:true,title:"Account unavailable",message:"Use recovery",activatedAt:"2026-01-01",replacement:null},authenticity:{...record.authenticity,state:"emergency_recovery_active"}};const model=buildPublicVerifiedIdentity({creator,record:emergencyRecord,connections:[connection("KwaMoon","official",0),connection("WatchBoost","official",1),connection("pending","backup",2),connection("NPA","backup",3,{external_account_id:null,connection_health:"disconnected",provider_status:"disconnected"})],identities:[identity("KwaMoon",false),identity("WatchBoost"),identity("pending",false)],networks:[network("b","WatchBoost",["NPA"],0),network("a","KwaMoon",["pending"],1)],affectedAccountId:"KwaMoon",emergencyType:"account_inaccessible"});expect(model.recoveryNetworks[0].mainAccount).toMatchObject({displayName:"KwaMoon",verificationStatus:"pending",connectionStatus:"connected"});expect(model.recoveryNetworks[0].recoveryAccounts[0]).toMatchObject({displayName:"pending",verificationStatus:"pending"});expect(model.recoveryNetworks[1].recoveryAccounts[0]).toMatchObject({displayName:"NPA",verificationStatus:"not_verified",connectionStatus:"not_connected"});});
  it("never lets verification override privacy or canonical suppression",()=>{const model=buildPublicVerifiedIdentity({creator,record,connections:[connection("public-pending","official",0),connection("private-verified","official",1,{is_public:false}),connection("suppressed","official",2),connection("revoked-connection","official",3,{connection_health:"revoked"})],identities:[identity("public-pending",false),identity("private-verified"),{...identity("suppressed"),public_visible:false},identity("revoked-connection")],networks:[],affectedAccountId:null,emergencyType:null});expect(model.officialAccounts.map(account=>account.displayName)).toEqual(["public-pending"]);expect(model.officialAccounts[0].verificationStatus).toBe("pending");});
  it("rejects cross-creator accounts even if a malicious relationship references them",()=>{const model=buildPublicVerifiedIdentity({creator,record,connections:[connection("main","official",0),connection("foreign","backup",1,{creator_id:"creator-b"})],identities:[identity("main"),identity("foreign")],networks:[network("a","main",["foreign"],0)],affectedAccountId:null,emergencyType:null});expect(model.recoveryNetworks).toHaveLength(1);expect(model.recoveryNetworks[0].recoveryAccounts).toEqual([]);});
});
