import { readFileSync } from "node:fs";
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";
import { PublicVerifiedIdentityView } from "@/components/authenticity/public-verified-identity";
import type { PublicVerifiedIdentity } from "@/lib/public-verified-identity";

const main = { provider:"youtube", displayName:"KwaMoon", handle:"@kwamoon", profileUrl:"https://youtube.com/@kwamoon", verificationStatus:"verified", connectionStatus:"connected" } as const;
const recovery = { provider:"instagram", displayName:"nana_friggy", handle:"@nana_friggy", profileUrl:"https://instagram.com/nana_friggy", verificationStatus:"not_verified", connectionStatus:"not_connected" } as const;
const identity:PublicVerifiedIdentity={creator:{displayName:"Nana",slug:"nana",avatar:null},creatorVerification:{status:"verified",verified:true,verifiedMainAccountCount:1,totalMainAccountCount:1,basis:"verified_main_account_control",verifiedMainAccountIds:["main"]},verification:{verified:true,label:"Verified by AudienceOwn",summary:"AudienceOwn has verified Nana's control of 1 Main account."},officialAccounts:[main],recoveryNetworks:[{mainAccount:main,recoveryAccounts:[recovery],affected:false}],activeEmergencyState:null,recoveryPass:{enabled:true,url:"https://audienceown.com/c/nana"},presentation:{publicTitle:"Creator · Entrepreneur · Host",publicSummary:"I'm Nana Kwame and I am a YouTuber."}};

describe("public Verified Identity status presentation",()=>{
  it("keeps verification and connection in separate semantic chips",()=>{const html=renderToStaticMarkup(<PublicVerifiedIdentityView identity={identity}/>);expect(html).toContain('data-status-kind="verification"');expect(html).toContain('data-status-kind="connection"');expect(html).not.toContain("Verified · Connected");expect(html).not.toContain("Not verified · Not connected");expect((html.match(/data-status-kind="verification"/g)??[]).length).toBe((html.match(/data-status-kind="connection"/g)??[]).length);});
  it("ends the primary follower flow with Recovery Pass and the footer",()=>{const html=renderToStaticMarkup(<PublicVerifiedIdentityView identity={identity}/>),network=html.indexOf("Recovery Network"),pass=html.indexOf("Stay connected with Nana"),footer=html.indexOf("AudienceOwn · Verified recovery network");expect(network).toBeGreaterThan(0);expect(pass).toBeGreaterThan(network);expect(footer).toBeGreaterThan(pass);for(const removed of["How AudienceOwn verification works","Verification statuses","Learn what AudienceOwn has verified","Account status legend"])expect(html).not.toContain(removed);});
  it("provides wrapping, spacing, and overflow protection for narrow mobile widths",()=>{const css=readFileSync("components/authenticity/public-verified-identity.module.css","utf8");expect(css).toContain("flex-wrap:wrap");expect(css).toMatch(/\.statusChips\{[^}]*gap:6px/);expect(css).toMatch(/\.page\{[^}]*overflow:hidden/);expect(css).toMatch(/\.account strong\{[^}]*text-overflow:ellipsis/);});
  it("places the canonical public title and summary between verification and Creator accounts",()=>{const html=renderToStaticMarkup(<PublicVerifiedIdentityView identity={identity}/>),status=html.indexOf("Verified by AudienceOwn"),title=html.indexOf("Creator · Entrepreneur · Host"),summary=html.indexOf("I&#x27;m Nana Kwame and I am a YouTuber."),accounts=html.indexOf("Creator accounts");expect(status).toBeGreaterThan(0);expect(title).toBeGreaterThan(status);expect(summary).toBeGreaterThan(title);expect(accounts).toBeGreaterThan(summary);});
  it("omits empty presentation fields without placeholders",()=>{const empty={...identity,presentation:{publicTitle:null,publicSummary:null}};const html=renderToStaticMarkup(<PublicVerifiedIdentityView identity={empty}/>);expect(html).not.toContain("publicTitle");expect(html).not.toContain("publicSummary");expect(html).not.toContain(identity.verification.summary);});
  it("renders public presentation text safely",()=>{const unsafe={...identity,presentation:{publicTitle:"<script>alert(1)</script>",publicSummary:'<img src=x onerror="alert(2)">'}};const html=renderToStaticMarkup(<PublicVerifiedIdentityView identity={unsafe}/>);expect(html).toContain("&lt;script&gt;alert(1)&lt;/script&gt;");expect(html).toContain("&lt;img src=x onerror=&quot;alert(2)&quot;&gt;");expect(html).not.toContain("<script>");expect(html).not.toContain("<img src=x");});
});
