import{readFileSync}from"node:fs";import{describe,expect,it}from"vitest";import{creatorProfileSettingsSchema}from"@/lib/creator-profile-settings";
describe("canonical Recovery Pass profile",()=>{
 it("normalizes and bounds every editable public field",()=>{expect(creatorProfileSettingsSchema.parse({display_name:" Creator ",public_tagline:" ",public_bio:" Bio "})).toEqual({display_name:"Creator",public_tagline:null,public_bio:"Bio"});expect(creatorProfileSettingsSchema.safeParse({display_name:"Creator",public_tagline:"x".repeat(161),public_bio:""}).success).toBe(false);expect(creatorProfileSettingsSchema.safeParse({display_name:"Creator",public_tagline:"",public_bio:"x".repeat(501)}).success).toBe(false)});
 it("rejects unknown fields and control characters",()=>{expect(creatorProfileSettingsSchema.safeParse({display_name:"Creator",public_tagline:"",public_bio:"",owner_user_id:"attacker"}).success).toBe(false);expect(creatorProfileSettingsSchema.safeParse({display_name:"Creator\nInjected",public_tagline:"",public_bio:""}).success).toBe(false)});
 it("keeps the use-server module limited to one async function export",()=>{const action=readFileSync("app/actions/recovery-pass-profile.ts","utf8");expect(action).toContain('"use server"');expect(action.match(/export\s+(?:const|let|var|class|default|\{)/g)??[]).toHaveLength(0);expect(action.match(/export\s+async\s+function\s+\w+/g)).toEqual(["export async function updateRecoveryPassProfile"])});
 it("derives ownership server-side and returns the saved canonical record",()=>{const action=readFileSync("app/actions/recovery-pass-profile.ts","utf8");expect(action).toContain("requireCreator()");expect(action).toContain('.eq("id", creator.id)');expect(action).toContain('.eq("owner_user_id", creator.owner_user_id)');expect(action).toContain("saved");expect(action).not.toContain("creator_id: formData")});
 it("updates only creator profile fields and refreshes canonical identity consumers",()=>{const action=readFileSync("app/actions/recovery-pass-profile.ts","utf8"),form=readFileSync("components/creator-form.tsx","utf8");expect(action).not.toContain('recovery_pass_name: formData.get');expect(form).not.toContain('name="recovery_pass_name"');expect(action).toContain('revalidatePath("/dashboard", "layout")');expect(action).toContain('revalidatePath("/dashboard/settings/profile")');expect(action).toContain('revalidatePath(`/c/${saved.slug}`)');expect(action).toContain('revalidatePath(`/verify/${saved.slug}`)')});
 it("keeps the handle read-only and the follower preview non-writing",()=>{const page=readFileSync("app/dashboard/creator-page/page.tsx","utf8"),form=readFileSync("components/creator-form.tsx","utf8");expect(form).toContain("Permanent URL");expect(form).not.toContain('name="public_slug"');expect(page).toContain("disabled");expect(page).toContain("Coming soon");expect(page).not.toContain("follower_connections");expect(page).not.toContain("setRecoveryPassDestination")});
 it("uses the public-safe RPC and preserves publication gating",()=>{const migration=readFileSync("supabase/migrations/20260916000000_canonical_recovery_pass_profile.sql","utf8");expect(migration).toContain("get_public_recovery_pass_profile");expect(migration).toContain("public_profile_enabled is true");expect(migration).not.toContain("owner_user_id',")});
});
