import {readFileSync} from "node:fs";
import {describe,expect,it} from "vitest";
import {buildDeliveryMessage,type ClaimedDelivery} from "@/lib/delivery-message";
import {recoveryDestinationGuidance,selectedRecoveryDestinationIdsFrom,toggleRecoveryDestinationId} from "@/lib/recovery-communication";

const studio=readFileSync("components/broadcast-studio/broadcast-studio.tsx","utf8");
const actions=readFileSync("app/dashboard/updates/actions.ts","utf8");
const page=readFileSync("app/dashboard/updates/[id]/page.tsx","utf8");
const migration=readFileSync("supabase/migrations/20260925000000_creator_update_recovery_destinations.sql","utf8");
const recoveryContract=readFileSync("lib/recovery-communication.ts","utf8");

describe("Recovery communication multi-destination contract",()=>{
 it("toggles destinations independently",()=>{let state:string[]=[];state=toggleRecoveryDestinationId(state,"instagram");expect(state).toEqual(["instagram"]);state=toggleRecoveryDestinationId(state,"youtube");expect(state).toEqual(["instagram","youtube"]);state=toggleRecoveryDestinationId(state,"instagram");expect(state).toEqual(["youtube"]);});
 it("serializes repeated fields and deduplicates",()=>{const data=new FormData();data.append("selected_recovery_account_ids","instagram");data.append("selected_recovery_account_ids","youtube");data.append("selected_recovery_account_ids","instagram");expect(selectedRecoveryDestinationIdsFrom(data)).toEqual(["instagram","youtube"]);});
 it("uses plural checkbox UI and reload state",()=>{expect(studio).toContain('useState<string[]>(() => update?.recovery_destination_ids');expect(studio).toContain('role="checkbox" aria-checked={checked}');expect(studio).toContain('name="selected_recovery_account_ids"');expect(studio).not.toContain('name="selected_recovery_account_id"');expect(page).toContain('creator_update_recovery_destinations');expect(page).toContain('recovery_destination_ids:');});
 it("parses all values and validates the complete set",()=>{expect(recoveryContract).toContain('data.getAll("selected_recovery_account_ids")');expect(actions).toContain("resolveRecoveryCommunicationDestinations");expect(actions).toContain("p_destination_ids:values.selected_recovery_account_ids");});
 it("persists atomically with ownership, role, network, RLS and uniqueness invariants",()=>{for(const marker of ["primary key (update_id, connected_account_id)","account.account_type='backup'","destination.recovery_connected_account_id=new.connected_account_id","force row level security","owners read update Recovery destinations","create_recovery_communication_draft","update_recovery_communication_draft"])expect(migration).toContain(marker);});
 it("uses count-aware grounded guidance and persists safe AI context",()=>{expect(recoveryDestinationGuidance([{provider:"Instagram",displayName:"Nana"}])).toContain("verified Instagram");expect(recoveryDestinationGuidance([{provider:"Instagram",displayName:"Nana"},{provider:"YouTube",displayName:"Lineconomy"},{provider:"Twitch",displayName:"AO"}])).toContain("3 trusted Recovery destinations");expect(actions).toContain("selected_recovery_destination_count:destinations.length");expect(actions).toContain("recovery_destination_providers:destinations.map");expect(actions).toContain("recovery_destination_display_names:destinations.map");expect(actions).toContain("affected_main_account:{provider:main.provider");expect(actions).toContain("description:`Affected Main account:");});
 it("renders every structured destination once in text and HTML",()=>{const delivery:ClaimedDelivery={delivery_id:"d",update_id:"u",creator_id:"c",transport:"email",destination:"fan@example.com",attempt_count:1,broadcast_type:"account_update",title:"Alert",subject:"Alert",preview_text:"",content:"Safe update",cta_label:"Find me safely here",cta_url:"https://legacy.example",creator_display_name:"Creator",creator_public_slug:"creator",recovery_destinations:[{connected_account_id:"i",provider:"Instagram",display_name:"nana_friggy",url:"https://instagram.example/nana"},{connected_account_id:"y",provider:"YouTube",display_name:"Lineconomy",url:"https://youtube.example/lineconomy"}]};const message=buildDeliveryMessage(delivery,"https://audienceown.example");for(const url of delivery.recovery_destinations!.map(item=>item.url)){expect(message.text.match(new RegExp(url.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),"g"))).toHaveLength(1);expect((message.html??"").match(new RegExp(url.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),"g"))).toHaveLength(1);}expect(message.text).not.toContain("https://legacy.example");});
});
