import{readFileSync}from"node:fs";
import{describe,expect,it}from"vitest";
import{eligibleRecoveryNetworkOptions}from"@/components/recovery-networks-page";
const source=readFileSync("components/recovery-networks-page.tsx","utf8"),css=readFileSync("components/recovery-network-manager.module.css","utf8");
describe("Recovery Networks page presentation",()=>{
 it("keeps canonical roles and one card per Main-owned network",()=>{expect(source).toContain('account.account_type==="official"');expect(source).toContain('account.account_type==="backup"');expect(source).toContain("visibleNetworks.map((network,index)=>");expect(source).toContain("network.main_connected_account_id");expect(source).toContain("network.recovery_account_ids.map");});
 it("does not turn unavailable audience data into zero",()=>{expect(source).toContain('account.audience_count!=null&&account.audience_unit');expect(source).toContain('return "Audience metric unavailable"');expect(source).not.toContain('account.audience_count??0');});
 it("renders real health and missing-Recovery states",()=>{for(const copy of ["Protected","Needs Recovery Account","Needs Attention","Protect {main.label}","Add a trusted account where followers can find you"])expect(source).toContain(copy);expect(source).toContain("mainHealth.actionRequired");expect(source).toContain("linked.some(account=>health(account).actionRequired)");});
 it("uses one assignment trigger",()=>{expect(source.match(/>Assign to Network <ArrowDown\/>/g)).toHaveLength(1);expect(source).toContain('role="menu" aria-label={`Assign ${recovery.label} to`}');expect(source).toContain("assignmentTargets.map(network=>");expect(source).not.toContain("Assign to {main");});
 it.each([1,3,10])("keeps one trigger while exposing %i eligible options",count=>{const networks=Array.from({length:count},(_,index)=>({id:`network-${index}`,main_connected_account_id:`main-${index}`,position:index,recovery_account_ids:[]}));expect(eligibleRecoveryNetworkOptions(networks)).toHaveLength(count);expect(source.match(/>Assign to Network <ArrowDown\/>/g)).toHaveLength(1);});
 it("deduplicates repeated canonical network and Main identifiers",()=>{const networks=[{id:"network-a",main_connected_account_id:"main-a",position:0,recovery_account_ids:[]},{id:"network-a",main_connected_account_id:"main-a",position:0,recovery_account_ids:[]},{id:"network-b",main_connected_account_id:"main-a",position:1,recovery_account_ids:[]},{id:"network-c",main_connected_account_id:"main-c",position:2,recovery_account_ids:[]}];expect(eligibleRecoveryNetworkOptions(networks).map(network=>network.id)).toEqual(["network-a","network-c"]);});
 it("offers setup instead of an empty assignment menu when no target exists",()=>{expect(eligibleRecoveryNetworkOptions([])).toEqual([]);expect(source).toContain('assignmentTargets.length?');expect(source).toContain('Set Up a Recovery Network <ArrowRight/>');});
 it("preserves canonical assignment and deletion",()=>{expect(source).toContain("savePersistentRecoveryNetwork(previous,formData)");expect(source).toContain("removeMainAccount(deleting.account.id)");expect(source).toContain("removeRecoveryAccount(deleting.account.id)");expect(source).toContain('name="recovery_network_id"');expect(source).toContain('name="recovery_account_ids"');});
 it("subordinates and confirms destructive actions",()=>{expect(source).toContain("destructiveMenuItem");expect(source).toContain('role="dialog"');expect(source).toContain("It does not delete your {deleting.account.platform} account.");expect(source).toContain("will be removed from every Recovery Network");expect(source).not.toContain('className={styles.deleteMain}');});
 it("supports keyboard menus and dialogs",()=>{for(const contract of ['aria-haspopup="menu"','aria-expanded={','event.key==="Escape"','returnFocus.current?.focus()','event.key!=="Tab"','aria-modal="true"'])expect(source).toContain(contract);});
 it("contains empty, setup, responsive, and motion states",()=>{for(const copy of ["No Recovery Networks Yet","No Main Account","Why Use a Recovery Network?","Learn More"])expect(source).toContain(copy);for(const contract of ["grid-template-columns:repeat(2",".setupContent","@media(max-width:680px)","prefers-reduced-motion:reduce","translateY(-2px)"])expect(css).toContain(contract);});
});
