import {readFileSync} from "node:fs";
import {describe,expect,it} from "vitest";
const source=(path:string)=>readFileSync(path,"utf8");
describe("persistent Recovery Network architecture",()=>{
 const migration=source("supabase/migrations/20260920000000_persistent_recovery_networks.sql"),ownership=source("supabase/migrations/20260921000000_exclusive_recovery_network_ownership.sql"),manager=source("components/recovery-network-manager.tsx"),recoveryPass=source("lib/recovery-pass-destinations.ts"),platforms=source("components/platforms-manager.tsx"),connect=source("app/api/integrations/[provider]/connect/route.ts"),autoLink=source("lib/social-providers/recovery-auto-link.ts"),action=source("app/actions/persistent-recovery-network.ts");
 it("owns stable slots independently from replaceable Main accounts",()=>{expect(migration).toContain("create table public.recovery_networks");expect(migration).toContain("on delete set null");expect(migration).toContain("create table public.recovery_network_destinations");expect(migration).toContain("assign_main_to_recovery_network");});
 it("backfills every Main including networks without destinations",()=>{expect(migration).toContain("from public.connected_accounts a where a.account_type='official'");expect(migration).toContain("from public.main_account_recovery_destinations legacy");});
 it("renders empty slots with their destinations and replacement action",()=>{for(const copy of ["Your recovery networks","Set up this Recovery Network","Needs Main account","Add Main account","Recovery accounts"])expect(manager).toContain(copy);expect(manager).toContain('onConfigure("official",undefined,n.id)');});
 it("uses network membership for Recovery Pass and targeting",()=>{expect(recoveryPass).toContain("recovery_network_destinations");expect(recoveryPass).toContain("recovery_networks");expect(recoveryPass).not.toContain('from("main_account_recovery_destinations")');});
 it("carries a validated network intent through existing OAuth",()=>{expect(platforms).toContain("recoveryNetworkId");expect(connect).toContain("validateEmptyRecoveryNetwork");expect(connect).toContain("recoveryNetworkId");});
 it("enforces exclusive Recovery ownership across UI, server, and concurrent writes",()=>{expect(ownership).toContain("unique(recovery_connected_account_id)");expect(ownership).toContain("recovery_account_already_assigned");expect(ownership).toContain("exception when unique_violation");expect(ownership).toContain("assign_recovery_account_to_network");expect(autoLink).toContain('db.rpc("assign_recovery_account_to_network"');expect(action).toContain("recovery_account_already_assigned");expect(manager).toContain("recoveryAccountsEligibleForNetwork");});
});
