import { afterEach,beforeEach,describe,expect,it,vi } from "vitest";
import { readFileSync } from "node:fs";
import { fetchSnapchatIdentity } from "@/lib/providers/snapchat";
import { providerAudienceCapabilities } from "@/lib/platform-audience/capabilities";
import { getSocialProvider,listOAuthProviderRegistry } from "@/lib/social-providers/registry";
import { providerConnectionCapability } from "@/lib/social-providers/connection-capabilities";
import { normalizeProviderIdentity } from "@/lib/social-providers/base-oauth";
import { createOAuthState,validateOAuthState } from "@/lib/social-providers/oauth";

const original={...process.env};
beforeEach(()=>{process.env.SNAPCHAT_CLIENT_ID="client";process.env.SNAPCHAT_CLIENT_SECRET="secret";process.env.SNAPCHAT_REDIRECT_URI="https://audienceown.com/api/integrations/snapchat/callback";});
afterEach(()=>{process.env={...original};vi.restoreAllMocks();});
describe("Snapchat OAuth stage 11.10",()=>{
  it("publishes reviewed Login Kit without claiming Public Profile capabilities",()=>{expect(listOAuthProviderRegistry().find(item=>item.id==="snapchat")).toMatchObject({oauthImplemented:true,connectPath:"/api/integrations/snapchat/connect",audienceMetricSupported:false,assetSelectionSupported:false,refreshSupported:true,disconnectSupported:true});expect(providerConnectionCapability(getSocialProvider("snapchat"))).toMatchObject({implementationStatus:"implemented",oauthStatus:"review_required",supportsAudienceMetrics:false});expect(providerAudienceCapabilities.snapchat).toMatchObject({supported:false,identityObject:"Login Kit user",selectedAssetType:null,requiresSelectedAsset:false});});
  it("requests exactly stable identity and display name",()=>expect(getSocialProvider("snapchat").requestedScopes).toEqual(["https://auth.snapchat.com/oauth2/api/user.external_id","https://auth.snapchat.com/oauth2/api/user.display_name"]));
  it("uses the exact scopes and production redirect without PKCE in the authorization URL",async()=>{const adapter=getSocialProvider("snapchat"),url=new URL((await adapter.createAuthorizationUrl!({state:"signed",codeChallenge:"must-be-ignored"})).url),scopes=url.searchParams.get("scope")?.split(" ")??[];expect(adapter.pkce).toBe(false);expect(url.origin+url.pathname).toBe("https://accounts.snapchat.com/accounts/oauth2/auth");expect(url.searchParams.get("client_id")).toBe("client");expect(url.searchParams.get("redirect_uri")).toBe("https://audienceown.com/api/integrations/snapchat/callback");expect(url.searchParams.get("response_type")).toBe("code");expect(url.searchParams.get("state")).toBe("signed");expect(scopes).toEqual(["https://auth.snapchat.com/oauth2/api/user.external_id","https://auth.snapchat.com/oauth2/api/user.display_name"]);expect(scopes).not.toContain("https://auth.snapchat.com/oauth2/api/user.bitmoji.avatar");expect(url.searchParams.has("code_challenge")).toBe(false);expect(url.searchParams.has("code_challenge_method")).toBe(false);});
  it("uses confidential client credentials without a PKCE verifier in token exchange",async()=>{const fetchMock=vi.fn().mockResolvedValue(new Response(JSON.stringify({access_token:"access",refresh_token:"refresh",expires_in:3600}),{status:200}));vi.stubGlobal("fetch",fetchMock);await getSocialProvider("snapchat").exchangeAuthorizationCode!({code:"authorization-code",codeVerifier:"must-be-ignored"});const body=fetchMock.mock.calls[0]?.[1]?.body as URLSearchParams;expect(body.get("client_id")).toBe("client");expect(body.get("client_secret")).toBe("secret");expect(body.get("redirect_uri")).toBe("https://audienceown.com/api/integrations/snapchat/callback");expect(body.get("code")).toBe("authorization-code");expect(body.has("code_verifier")).toBe(false);});
  it("keeps the app-scoped external ID canonical without relying on Bitmoji",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(new Response(JSON.stringify({data:{me:{externalId:"app-scoped-id",displayName:"Creator"}}}),{status:200})));const identity=await fetchSnapchatIdentity("token"),normalized=normalizeProviderIdentity(identity);expect(identity).toMatchObject({id:"app-scoped-id",name:"Creator",url:"https://www.snapchat.com/",metadata:{identityType:"login_kit_user",publicProfileAuthority:false,publicUrlRequired:true}});expect(normalized.externalAccountId).toBe("app-scoped-id");});
  it("tolerates malformed presentation metadata and never requests or stores Bitmoji",async()=>{const fetchMock=vi.fn().mockResolvedValue(new Response(JSON.stringify({data:{me:{externalId:"stable-id",displayName:{unexpected:true},bitmoji:{avatar:"https://example.com/avatar.png"}}}}),{status:200}));vi.stubGlobal("fetch",fetchMock);const identity=await fetchSnapchatIdentity("token");expect(identity).toMatchObject({id:"stable-id",name:"Snapchat account"});expect(identity.metadata).not.toHaveProperty("bitmojiAvatar");expect(String(fetchMock.mock.calls[0]?.[0])).not.toContain("bitmoji");});
  it("enforces signature, expiry, nonce, provider, creator, user, role, reconnect, and protected-official bindings",()=>{process.env.SOCIAL_OAUTH_STATE_SECRET="state-secret-for-snapchat-regression";const payload={provider:"snapchat" as const,creatorId:"creator-a",userId:"user-a",nonce:"nonce-a",role:"backup" as const,connectionId:"00000000-0000-4000-8000-000000000110",protectedOfficialAccountId:"00000000-0000-4000-8000-000000000111",expiresAt:2000},state=createOAuthState(payload);expect(validateOAuthState(state,"snapchat","nonce-a",1999)).toEqual({ok:true,state:payload});expect(validateOAuthState(state,"snapchat","wrong-nonce",1999)).toMatchObject({ok:false,reason:"nonce_mismatch"});expect(validateOAuthState(state,"x","nonce-a",1999)).toMatchObject({ok:false,reason:"provider_mismatch"});expect(validateOAuthState(state,"snapchat","nonce-a",2001)).toMatchObject({ok:false,reason:"state_expired"});expect(validateOAuthState(`${state}tampered`,"snapchat","nonce-a",1999)).toMatchObject({ok:false,reason:"state_signature_invalid"});});
  it("keeps configured Staging connections connectable while external review remains required",()=>{expect(getSocialProvider("snapchat").readiness?.()).toMatchObject({configured:true,connectionAvailable:true,reviewStatus:"required"});expect(providerConnectionCapability(getSocialProvider("snapchat"))).toMatchObject({configurationStatus:"configured",connectable:true,reviewStatus:"required"});});
  it("keeps nonce/state binding, other-provider PKCE, Official/Backup, and reconnect protection unchanged",()=>{const connect=readFileSync("app/api/integrations/[provider]/connect/route.ts","utf8"),callback=readFileSync("app/api/integrations/[provider]/callback/route.ts","utf8");expect(connect).toContain("adapter.pkce?createPkce():null");expect(connect).toContain("JSON.stringify({nonce,verifier:pkce?.verifier})");expect(callback).toContain('reason:"nonce_cookie_missing"');expect(callback).toContain("validateOAuthState(stateValue,raw,saved.nonce)");expect(connect).toContain("protectedOfficialAccountId");expect(callback).toContain("target.external_account_id!==identity.externalAccountId");expect(callback).toContain("reconnect_mismatch");expect(getSocialProvider("x").pkce).toBe(true);expect(getSocialProvider("spotify").pkce).toBe(true);});
  it("revokes the refresh token using confidential-client authentication",async()=>{const fetchMock=vi.fn().mockResolvedValue(new Response(null,{status:200}));vi.stubGlobal("fetch",fetchMock);await getSocialProvider("snapchat").revokeConnection!({accessToken:"access",refreshToken:"refresh"});expect(fetchMock).toHaveBeenCalledWith("https://accounts.snapchat.com/accounts/oauth2/revoke",expect.objectContaining({method:"POST",headers:expect.objectContaining({authorization:expect.stringMatching(/^Basic /)})}));expect(String(fetchMock.mock.calls[0]?.[1]?.body)).toContain("token=refresh");});
});
