import { describe, expect, it } from "vitest";
import { accountNeedsAttention, activityMatchesTab, activityMetrics, buildUpdatesActivity, deriveUpdateActivityInsight, deriveUpdateManagementPolicy, type AccountActivityRow, type ActivityItem, type DeliveryActivityRow, type EmergencyActivityRow, type UpdateActivityRow } from "@/lib/updates-activity";
import { classifyBroadcastIntent, type BroadcastIntent } from "@/lib/broadcast-studio";

const account=(patch:Partial<AccountActivityRow>={}):AccountActivityRow=>({id:"account-1",platform:"youtube",label:"KWA Moon",external_account_name:"KWA Moon",account_type:"official",connection_health:"healthy",provider_status:"connected",last_connection_error:null,updated_at:"2026-08-15T12:00:00Z",...patch});
const update=(patch:Partial<UpdateActivityRow>={}):UpdateActivityRow=>({id:"update-1",broadcast_type:"new_content",broadcast_intent:"new_video",status:"sent",title:"Launch",subject:"New video is live",content:"Watch the full release.",cta_url:"https://youtube.example/watch",scheduled_for:null,sent_at:"2026-08-15T12:00:00Z",queued_at:"2026-08-15T11:59:00Z",updated_at:"2026-08-15T12:00:00Z",affected_platform_connection_id:"account-1",source_provider:null,...patch});
const delivery=(patch:Partial<DeliveryActivityRow>={}):DeliveryActivityRow=>({update_id:"update-1",status:"delivered",accepted_at:"2026-08-15T12:00:05Z",delivered_at:"2026-08-15T12:00:10Z",failed_at:null,...patch});
const normalIntents=["new_video","livestream","podcast_episode","product_release","event","general_announcement","community_update"] as const;
const protectedIntents=["account_inaccessible","platform_migration"] as const;
const updateForIntent=(intent:BroadcastIntent,index:number,status:UpdateActivityRow["status"]="sent"):UpdateActivityRow=>update({id:`workflow-${index}`,broadcast_intent:intent,broadcast_type:classifyBroadcastIntent(intent).broadcastType,status,affected_platform_connection_id:null,sent_at:status==="sent"?`2026-08-15T12:${String(index).padStart(2,"0")}:00Z`:null,scheduled_for:status==="scheduled"?"2026-08-20T12:00:00Z":null,updated_at:`2026-08-15T12:${String(index).padStart(2,"0")}:00Z`});

describe("Updates & Activity read model",()=>{
 it("classifies normal communications with canonical account and aggregate delivery data",()=>{const model=buildUpdatesActivity({updates:[update()],deliveries:[delivery()],accounts:[account()],emergencies:[]});expect(model.items[0]).toMatchObject({kind:"update",subtype:"new_video",status:"delivered",platform:"youtube",accountDisplay:"KWA Moon",recipientCount:1,detailHref:"/dashboard/updates/update-1"})});
 it("keeps a protective communication and its related account problem as separate canonical activities",()=>{const issue=account({connection_health:"degraded",last_connection_error:"refresh_required"}),model=buildUpdatesActivity({updates:[update({broadcast_type:"account_update",broadcast_intent:"account_inaccessible"})],deliveries:[delivery()],accounts:[issue],emergencies:[]});expect(model.items.some(item=>item.kind==="emergency"&&item.subtype==="account_inaccessible")).toBe(true);expect(model.items.some(item=>item.kind==="account"&&item.status==="attention")).toBe(true);expect(model.attention).toHaveLength(1)});
 it("uses immutable emergency snapshots and avoids duplicating its linked creator update",()=>{const emergency:EmergencyActivityRow={id:"emergency-1",emergency_type:"account_hacked",lifecycle_status:"active",title:"Account issue",message:"Instagram was reported unavailable.",activated_at:"2026-08-15T12:00:00Z",resolved_at:null,cancelled_at:null,updated_at:"2026-08-15T12:00:00Z",creator_update_id:"update-1",affected_accounts:[{provider:"instagram",display_handle:"@original"}],replacement_accounts:[{provider:"youtube",display_handle:"Lineconomy"}]};const model=buildUpdatesActivity({updates:[update()],deliveries:[delivery()],accounts:[account()],emergencies:[emergency]});expect(model.items).toHaveLength(1);expect(model.items[0]).toMatchObject({kind:"emergency",accountDisplay:"instagram · @original",recoveryDestinationSnapshot:"youtube · Lineconomy",recipientCount:1})});
 it("counts only real period activity and current attention",()=>{const model=buildUpdatesActivity({updates:[update(),update({id:"scheduled",status:"scheduled",scheduled_for:"2026-08-20T12:00:00Z",sent_at:null}),update({id:"old",sent_at:"2026-01-01T00:00:00Z",updated_at:"2026-01-01T00:00:00Z"})],deliveries:[delivery(),delivery({update_id:"old"})],accounts:[account({connection_health:"degraded"})],emergencies:[]});expect(activityMetrics(model.items,model.attention.length,new Date("2026-08-16T12:00:00Z"),"7")).toEqual({sent:1,scheduled:1,failed:0,attention:1})});
 it("keeps upcoming schedules independent from the historical date range",()=>{const item=buildUpdatesActivity({updates:[update({id:"future",status:"scheduled",scheduled_for:"2026-09-06T00:47:00Z",sent_at:null})],deliveries:[],accounts:[],emergencies:[]}).items;for(const range of ["7","30","90","all"] as const)expect(activityMetrics(item,0,new Date("2026-08-19T00:00:00Z"),range).scheduled).toBe(1)});
 it("keeps a linked scheduled Emergency update visible and manageable",()=>{const emergency:EmergencyActivityRow={id:"emergency-1",emergency_type:"account_inaccessible",lifecycle_status:"draft",title:"Access issue",message:"Prepared",activated_at:null,resolved_at:null,cancelled_at:null,updated_at:"2026-08-18T12:00:00Z",creator_update_id:"update-1",affected_accounts:[],replacement_accounts:[]};const model=buildUpdatesActivity({updates:[update({status:"scheduled",broadcast_type:"account_update",broadcast_intent:"account_inaccessible",scheduled_for:"2026-09-08T07:00:00Z",sent_at:null})],deliveries:[],accounts:[],emergencies:[emergency]});const scheduled=model.items.find(item=>item.status==="scheduled");expect(scheduled).toMatchObject({kind:"emergency",subtype:"account_inaccessible",managementPolicy:{canCancel:true,primaryAction:"MANAGE_SCHEDULE"}})});
 it("does not flag healthy or backup accounts as attention issues",()=>{expect(accountNeedsAttention(account())).toBe(false);expect(accountNeedsAttention(account({account_type:"backup",connection_health:"degraded"}))).toBe(false)});
 it("keeps private delivery destinations and provider payloads out of the public read model",()=>{const serialized=JSON.stringify(buildUpdatesActivity({updates:[update()],deliveries:[delivery()],accounts:[account()],emergencies:[]}));expect(serialized).not.toContain("destination");expect(serialized).not.toContain("provider_metadata");expect(serialized).not.toContain("email")});
 it("filters canonical kinds and orthogonal statuses without duplicating records",()=>{const base=(patch:Partial<ActivityItem>):ActivityItem=>({id:"item",canonicalUpdateId:null,kind:"update",subtype:"new_video",occurredAt:"2026-08-16T12:00:00Z",platform:null,accountDisplay:null,title:"Title",description:"Description",status:"delivered",messagePreview:null,recipientCount:null,recoveryDestinationSnapshot:null,detailHref:null,actionHref:null,managementPolicy:null,insight:null,...patch}),items=[base({id:"normal"}),base({id:"failed-emergency",kind:"emergency",subtype:"account_inaccessible",status:"failed"}),base({id:"scheduled-emergency",kind:"emergency",subtype:"platform_migration",status:"scheduled"}),base({id:"account",kind:"account",subtype:"connection_attention",status:"attention"})];expect(items.filter(item=>activityMatchesTab(item,"all"))).toHaveLength(4);expect(items.filter(item=>activityMatchesTab(item,"updates")).map(item=>item.id)).toEqual(["normal"]);expect(items.filter(item=>activityMatchesTab(item,"emergency")).map(item=>item.id)).toEqual(["failed-emergency","scheduled-emergency"]);expect(items.filter(item=>activityMatchesTab(item,"failed")).map(item=>item.id)).toEqual(["failed-emergency"]);expect(items.filter(item=>activityMatchesTab(item,"scheduled")).map(item=>item.id)).toEqual(["scheduled-emergency"]);expect(items.filter(item=>activityMatchesTab(item,"account")).map(item=>item.id)).toEqual(["account"])});
 it("places every Share something new subtype in Updates and excludes protected workflows",()=>{const rows=[...normalIntents,...protectedIntents].map((intent,index)=>updateForIntent(intent,index)),items=buildUpdatesActivity({updates:rows,deliveries:[],accounts:[],emergencies:[]}).items,updates=items.filter(item=>activityMatchesTab(item,"updates")),emergencies=items.filter(item=>activityMatchesTab(item,"emergency"));expect(updates.map(item=>item.subtype).sort()).toEqual([...normalIntents].sort());expect(emergencies.map(item=>item.subtype).sort()).toEqual([...protectedIntents].sort());expect(updates.every(item=>item.kind==="update"&&item.title.toLowerCase().includes(item.subtype.split("_")[0]))).toBe(true)});
 it("keeps update family stable across draft, scheduled, queued, sent, and failed lifecycle states",()=>{const statuses=["draft","scheduled","queued","sent","failed"] as const;for(const [index,status] of statuses.entries()){const [item]=buildUpdatesActivity({updates:[updateForIntent("product_release",index,status)],deliveries:[],accounts:[],emergencies:[]}).items;expect(item).toMatchObject({kind:"update",subtype:"product_release"});expect(activityMatchesTab(item,"updates")).toBe(true)}});
 it("counts all seven delivered normal subtypes and excludes delivered emergencies from Updates Sent",()=>{const rows=[...normalIntents,...protectedIntents].map((intent,index)=>updateForIntent(intent,index)),items=buildUpdatesActivity({updates:rows,deliveries:[],accounts:[],emergencies:[]}).items;expect(activityMetrics(items,0,new Date("2026-08-16T12:00:00Z"),"7").sent).toBe(7)});
 it("derives lifecycle actions centrally and never exposes destructive sent or emergency actions",()=>{
  expect(deriveUpdateManagementPolicy({status:"draft",deliveryCount:0,emergency:false})).toMatchObject({canContinue:true,canDelete:true,primaryAction:"CONTINUE_DRAFT"});
  expect(deriveUpdateManagementPolicy({status:"draft",deliveryCount:1,emergency:false})).toMatchObject({canDelete:false});
  expect(deriveUpdateManagementPolicy({status:"scheduled",deliveryCount:4,emergency:false})).toMatchObject({canCancel:true,canReschedule:false,primaryAction:"MANAGE_SCHEDULE"});
  expect(deriveUpdateManagementPolicy({status:"failed",deliveryCount:1,emergency:false})).toMatchObject({canRetry:true,primaryAction:"REVIEW_FAILURE"});
  expect(deriveUpdateManagementPolicy({status:"delivered",deliveryCount:1,emergency:false})).toMatchObject({canDelete:false,canCancel:false,primaryAction:"VIEW_DETAILS"});
  expect(deriveUpdateManagementPolicy({status:"failed",deliveryCount:1,emergency:true})).toMatchObject({canDelete:false,canRetry:false,primaryAction:"VIEW_DETAILS"});
 });
 it("grounds deterministic insight in canonical destination, status, and schedule fields",()=>{
  expect(deriveUpdateActivityInsight(update({status:"draft",cta_url:null}),"draft")?.message).toContain("needs a destination link");
  expect(deriveUpdateActivityInsight(update({status:"draft",cta_url:"https://youtube.example/watch"}),"draft")?.message).toBe("Your draft is ready for review.");
  expect(deriveUpdateActivityInsight(update({status:"failed"}),"failed")?.action).toBe("REVIEW_FAILURE");
  expect(deriveUpdateActivityInsight(update({status:"scheduled",scheduled_for:"2026-08-20T12:00:00Z"}),"scheduled")?.message).toContain("time shown above");
  expect(deriveUpdateActivityInsight(update(),"delivered")).toBeNull();
 });
});
