import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";
import { UpdatesActivityCommandCenter } from "@/components/updates-activity-command-center";
import type { ActivityItem } from "@/lib/updates-activity";

const generatedAt="2026-08-16T20:00:00Z";
const item=(patch:Partial<ActivityItem>):ActivityItem=>({id:"activity-1",canonicalUpdateId:"update-1",kind:"update",subtype:"new_video",occurredAt:"2026-08-16T16:15:00Z",platform:"youtube",accountDisplay:"KWA Moon",title:"Legacy generated title",description:"New video is live.",status:"delivered",messagePreview:"Watch the full release now.",recipientCount:1240,recoveryDestinationSnapshot:null,detailHref:"/dashboard/updates/update-1",actionHref:null,managementPolicy:{canContinue:false,canDelete:false,canCancel:false,canReschedule:false,canRetry:false,canView:true,primaryAction:"VIEW_DETAILS"},insight:null,...patch});
const render=(items:ActivityItem[],attention:React.ComponentProps<typeof UpdatesActivityCommandCenter>["attention"]=[])=>renderToStaticMarkup(<UpdatesActivityCommandCenter items={items} attention={attention} generatedAt={generatedAt}/>);

describe("Updates & Activity presentation",()=>{
 it("renders a normal Update with canonical family, subtype, account, bounded preview, audience, status, and detail action",()=>{const html=render([item({})]);for(const value of ["Update","New video","youtube","KWA Moon","Watch the full release now.","1,240 recipients","Delivered","View details"])expect(html).toContain(value);expect(html).toContain('class="activity-event tone-update subtype-violet status-delivered"');expect(html).toContain('href="/dashboard/updates/update-1"');expect(html).not.toContain("Legacy generated title")});
 it("renders emergency context and immutable recovery destination only when supplied",()=>{const html=render([item({kind:"emergency",subtype:"platform_migration",platform:"instagram",accountDisplay:"instagram · @old-account",description:"Followers were guided to the verified recovery destination.",recoveryDestinationSnapshot:"youtube · Lineconomy",recipientCount:842})]);for(const value of ["Emergency","Platform migration","@old-account","Recovery destination","youtube · Lineconomy","842 recipients"])expect(html).toContain(value);expect(html).toContain("tone-emergency");const without=render([item({kind:"emergency",subtype:"account_inaccessible",recoveryDestinationSnapshot:null,recipientCount:null})]);expect(without).not.toContain("Recovery destination");expect(without).not.toContain("recipient")});
 it("renders account activity as operational state with its safe management action",()=>{const html=render([item({kind:"account",subtype:"connection_attention",platform:"snapchat",accountDisplay:"@audienceown",description:"Connection requires action",status:"attention",messagePreview:null,recipientCount:null,detailHref:null,actionHref:"/dashboard/platforms"})],[{id:"account-1",platform:"snapchat",label:"@audienceown",reason:"Connection expired",href:"/dashboard/platforms"}]);for(const value of ["Account activity","Action required","Connection requires action","Manage account","Needs attention","Connection expired"])expect(html).toContain(value);expect(html).toContain('href="/dashboard/platforms"')});
 it("renders polished truthful empty states and canonical creation actions",()=>{const html=render([]);expect(html).toContain("Your first update starts here.");expect(html).toContain("Create an update or use a recovery workflow");expect(html).toContain("Create Update");expect(html).toContain("Send Emergency Alert");expect(html.match(/href="\/dashboard\/updates\/new\?intent=update"/g)).toHaveLength(3);expect(html.match(/href="\/dashboard\/updates\/new\?intent=emergency"/g)).toHaveLength(3);expect(html).toContain("All connected accounts look good.")});
 it("renders actionable draft, scheduled, and failed cards without auto-sending",()=>{
  const draft=item({status:"draft",managementPolicy:{canContinue:true,canDelete:true,canCancel:false,canReschedule:false,canRetry:false,canView:true,primaryAction:"CONTINUE_DRAFT"},insight:{message:"Your draft is ready for review.",action:"CONTINUE_DRAFT"}});
  const scheduled=item({id:"scheduled",canonicalUpdateId:"scheduled-id",status:"scheduled",detailHref:"/dashboard/updates/scheduled-id",managementPolicy:{canContinue:false,canDelete:false,canCancel:true,canReschedule:false,canRetry:false,canView:true,primaryAction:"MANAGE_SCHEDULE"},insight:{message:"This update is scheduled for the time shown above.",action:"MANAGE_SCHEDULE"}});
  const failed=item({id:"failed",canonicalUpdateId:"failed-id",status:"failed",detailHref:"/dashboard/updates/failed-id",managementPolicy:{canContinue:false,canDelete:false,canCancel:false,canReschedule:false,canRetry:true,canView:true,primaryAction:"REVIEW_FAILURE"},insight:{message:"Review the recorded delivery status before retrying.",action:"REVIEW_FAILURE"}});
  const html=render([draft,scheduled,failed]);
  for(const value of ["Continue editing","Manage","Review &amp; retry","AI insight"])expect(html).toContain(value);
  expect(html.match(/aria-haspopup="menu"/g)).toHaveLength(3);
  expect(html).not.toContain("Retry now");expect(html).not.toContain("Send now");
  expect(html).toContain('href="/dashboard/updates/update-1"');
 });
 it("keeps sent and emergency history view-only",()=>{const html=render([item({}),item({id:"emergency",kind:"emergency",managementPolicy:{canContinue:false,canDelete:false,canCancel:false,canReschedule:false,canRetry:false,canView:true,primaryAction:"VIEW_DETAILS"}})]);expect(html.match(/View details/g)).toHaveLength(2);expect(html).not.toContain("Delete draft");expect(html).not.toContain("Cancel scheduled update")});
});
