import { readFileSync } from "node:fs";
import { describe,expect,it } from "vitest";
import { calculateIdentityStrength,scopeRecoveryNetworks,type VerifiedIdentityAccount } from "@/lib/verified-identity-dashboard";
import { canonicalPublicOrigin, getPublicRecoveryPassUrl, getPublicVerificationUrl } from "@/lib/canonical-public-url";

const account=(id:string,role:"main"|"recovery",mainAccountId:string|null=null,publicEligible=true):VerifiedIdentityAccount=>({id,role,mainAccountId,publicEligible,provider:"youtube",displayName:id,url:`https://example.com/${id}`,verificationStatus:"verified"});
describe("verified identity dashboard contracts",()=>{
  it("keeps Recovery destinations scoped to their Main account and excludes suppressed destinations",()=>{const networks=scopeRecoveryNetworks([account("main-a","main"),account("main-b","main"),account("recovery-a","recovery","main-a"),account("recovery-b","recovery","main-b"),account("hidden","recovery","main-a",false)]);expect(networks.find(item=>item.main.id==="main-a")?.recoveryAccounts.map(item=>item.id)).toEqual(["recovery-a"]);expect(networks.find(item=>item.main.id==="main-b")?.recoveryAccounts.map(item=>item.id)).toEqual(["recovery-b"]);});
  it("derives strength deterministically without a fabricated percentage",()=>{expect(calculateIdentityStrength({accountCount:0,verified:false,attention:false,allMainVerified:false,allRecoveryVerified:false,publicPage:false,recoveryPass:false})).toBe("Incomplete");expect(calculateIdentityStrength({accountCount:2,verified:true,attention:true,allMainVerified:true,allRecoveryVerified:true,publicPage:true,recoveryPass:true})).toBe("Needs attention");expect(calculateIdentityStrength({accountCount:2,verified:true,attention:false,allMainVerified:true,allRecoveryVerified:true,publicPage:true,recoveryPass:true})).toBe("Strong");expect(calculateIdentityStrength({accountCount:2,verified:true,attention:false,allMainVerified:true,allRecoveryVerified:false,publicPage:true,recoveryPass:true})).toBe("Good");});
  it("always builds production-safe share URLs, including during local development",()=>{const development={NODE_ENV:"development",APP_URL:"http://localhost:3000"} as const;expect(getPublicVerificationUrl("kwame",development)).toBe("https://audienceown.com/verify/kwame");expect(getPublicRecoveryPassUrl("kwame",development)).toBe("https://audienceown.com/c/kwame");expect(getPublicVerificationUrl("name with spaces",development)).toBe("https://audienceown.com/verify/name%20with%20spaces");});
  it("fails clearly for an insecure or non-canonical configured production origin",()=>{expect(()=>canonicalPublicOrigin({NODE_ENV:"production",APP_URL:"http://audienceown.com"})).toThrow("Canonical public origin must be https://audienceown.com.");expect(()=>canonicalPublicOrigin({NODE_ENV:"production",PUBLIC_APP_URL:"https://staging.audienceown.com"})).toThrow("Canonical public origin must be https://audienceown.com.");expect(canonicalPublicOrigin({NODE_ENV:"production"})).toBe("https://audienceown.com");});
  it("separates local preview navigation from canonical copy and QR payloads",()=>{const page=readFileSync("app/dashboard/authenticity/page.tsx","utf8"),controls=readFileSync("components/authenticity/verified-identity-controls.tsx","utf8");expect(page).toContain('href={`/verify/${data.creator.slug}`}');expect(page).toContain('CopyLinkButton value={data.publicVerification.url}');expect(page).toContain('<DownloadableVerificationQr url={data.publicVerification.url} slug={data.creator.slug}');expect(controls).toContain('<QRCodeSVG ref={ref} value={url}');expect(controls).toContain('bgColor="#ffffff" fgColor="#000000"');expect(controls).toContain('audienceown-verification-${slug}.svg');const payload=getPublicVerificationUrl("kwame",{NODE_ENV:"development",APP_URL:"http://127.0.0.1:3000"});expect(payload).toBe("https://audienceown.com/verify/kwame");expect(payload).not.toMatch(/localhost|127\.0\.0\.1|dashboard\/authenticity/);});
  it("does not derive permanent share origins from browsers, request headers, or deployments",()=>{const shareAssetFiles=["lib/canonical-public-url.ts","lib/authenticity/public.ts","lib/authenticity/lookup.ts","lib/authenticity/manifest.ts","lib/authenticity/webhook-events.ts","lib/verified-identity-dashboard.ts","components/authenticity/verified-identity-controls.tsx","app/dashboard/authenticity/page.tsx","app/verify/[slug]/page.tsx"];const source=shareAssetFiles.map(file=>readFileSync(file,"utf8")).join("\n");for(const forbidden of[/window\.location(?:\.origin)?/,/headers\(\)/,/request\.headers\.get\(["'](?:host|x-forwarded-host)["']\)/i,/NEXT_PUBLIC_VERCEL_URL|VERCEL_URL|VERCEL_BRANCH_URL/,/https?:\/\/(?:localhost|127\.0\.0\.1)/])expect(source).not.toMatch(forbidden);expect(getPublicVerificationUrl("kwame",{NODE_ENV:"development",AUTHENTICITY_PUBLIC_BASE_URL:"https://preview.example.dev"})).toBe("https://audienceown.com/verify/kwame");expect(getPublicRecoveryPassUrl("kwame",{NODE_ENV:"development",PUBLIC_APP_URL:"https://branch.vercel.app"})).toBe("https://audienceown.com/c/kwame");});
  it("keeps public SEO, Recovery Pass, health actions, and public state copy aligned",()=>{const dashboard=readFileSync("app/dashboard/authenticity/page.tsx","utf8"),publicPage=readFileSync("app/verify/[slug]/page.tsx","utf8"),publicModel=readFileSync("lib/public-verified-identity.ts","utf8");expect(publicPage).toContain("Verify ${result.data.creator.displayName} | AudienceOwn");expect(publicPage).toContain("Official accounts and trusted recovery destinations for ${result.data.creator.displayName}.");expect(publicModel).toContain("getPublicRecoveryPassUrl(input.record.creator.slug)");expect(publicPage).toContain("PublicVerifiedIdentityView");expect(dashboard).toContain("<PublicVerifiedIdentityView identity={data.publicIdentity} preview/>");expect(dashboard).toContain('href="/dashboard/platforms"');});
  it("does not ship sample reference identities or primary technical toggles",()=>{const page=readFileSync("app/dashboard/authenticity/page.tsx","utf8");for(const sample of["KwaMoon","WatchBoost","nana_friggy","Lineconomy","nana_official","Publish authenticity profile","Allow QR verification"])expect(page).not.toContain(sample);});
});
