import{z}from"zod";
export const discordGuildSchema=z.object({id:z.string().regex(/^\d{5,25}$/),name:z.string().min(1),owner:z.boolean().optional(),permissions:z.string().regex(/^\d+$/).optional(),unavailable:z.boolean().optional()});
export const discordChannelSchema=z.object({id:z.string().regex(/^\d{5,25}$/),guild_id:z.string().regex(/^\d{5,25}$/),name:z.string().min(1),type:z.number().int(),permissions:z.string().regex(/^\d+$/).optional()});
const ADMIN=BigInt(1)<<BigInt(3),MANAGE_GUILD=BigInt(1)<<BigInt(5),VIEW_CHANNEL=BigInt(1)<<BigInt(10),SEND_MESSAGES=BigInt(1)<<BigInt(11),MANAGE_CHANNELS=BigInt(1)<<BigInt(4);
function has(value:string|undefined,permission:bigint){try{return(BigInt(value??"0")&(ADMIN|permission))!==BigInt(0);}catch{return false;}}
export function discordGuildAuthority(guild:z.infer<typeof discordGuildSchema>){return{userIdentity:false,guildAuthority:Boolean(guild.owner||has(guild.permissions,MANAGE_GUILD)),stableGuildId:guild.id,unavailable:Boolean(guild.unavailable)};}
export function discordBotAuthority(permissions:string|undefined){return{installed:Boolean(permissions),canView:has(permissions,VIEW_CHANNEL),canSend:has(permissions,SEND_MESSAGES),canManageChannels:has(permissions,MANAGE_CHANNELS)};}
export function discordAnnouncementAuthority(channel:z.infer<typeof discordChannelSchema>){const bot=discordBotAuthority(channel.permissions);return{stableChannelId:channel.id,stableGuildId:channel.guild_id,announcementChannel:channel.type===5,readable:bot.canView,operational:channel.type===5&&bot.canView};}
export function validateDiscordInvite(value:string){const url=new URL(value);if(url.protocol!=="https:"||!(["discord.gg","discord.com"].includes(url.hostname))||url.username||url.password)return null;const parts=url.pathname.split("/").filter(Boolean),code=url.hostname==="discord.gg"?parts[0]:parts[0]==="invite"?parts[1]:null;return code&&/^[A-Za-z0-9-]{2,64}$/.test(code)?`https://discord.gg/${code}`:null;}
