import{z}from"zod";import type{DiscoveredProviderSource,ProviderIdentity,ProviderPollResult}from"@/lib/social-providers/types";
const oidcSchema=z.object({sub:z.string().min(1),name:z.string().min(1),given_name:z.string().optional(),family_name:z.string().optional(),picture:z.string().url().optional(),profile:z.string().url().optional()}).passthrough();
const aclSchema=z.object({elements:z.array(z.object({organization:z.string().regex(/^urn:li:organization:\d+$/),role:z.enum(["ADMINISTRATOR","DIRECT_SPONSORED_CONTENT_POSTER","LEAD_GEN_FORMS_MANAGER","CURATOR","CONTENT_ADMINISTRATOR"]).optional(),state:z.string().optional()})),paging:z.object({start:z.number(),count:z.number(),total:z.number().optional()}).optional()});
const postSchema=z.object({id:z.string().regex(/^urn:li:(share|ugcPost):\d+$/),author:z.string().min(1),commentary:z.string().optional(),lifecycleState:z.enum(["PUBLISHED","DRAFT","PROCESSING","PROCESSING_FAILED","PUBLISHED_EDITED","ARCHIVED"]),visibility:z.string().optional(),createdAt:z.number().int().positive(),publishedAt:z.number().int().positive().optional()});
const postsSchema=z.object({elements:z.array(postSchema),paging:z.object({start:z.number(),count:z.number(),total:z.number().optional()}).optional()});
function version(){const value=process.env.LINKEDIN_API_VERSION??"202603";if(!/^20\d{4}$/.test(value))throw new Error("invalid_linkedin_api_version");return value;}
async function linkedin(path:string,token:string){const response=await fetch(`https://api.linkedin.com/${path}`,{headers:{authorization:`Bearer ${token}`,accept:"application/json","LinkedIn-Version":version(),"X-Restli-Protocol-Version":"2.0.0"},cache:"no-store"}),raw:unknown=await response.json();if(!response.ok)throw new Error(response.status===401?"authentication_revoked":response.status===429?"rate_limited":response.status===403?"product_not_entitled":"linkedin_provider_failure");return raw;}
export async function fetchLinkedInIdentity(accessToken:string):Promise<ProviderIdentity>{const value=oidcSchema.parse(await linkedin("v2/userinfo",accessToken)),profile=value.profile&&new URL(value.profile).hostname.endsWith("linkedin.com")?value.profile:"https://www.linkedin.com/";return{id:value.sub,name:value.name,url:profile,metadata:{givenName:value.given_name??null,familyName:value.family_name??null,profilePictureUrl:value.picture??null,oidcSessionControl:true,realWorldIdentityVerified:false}};}
export function linkedinOrganizationAuthority(role:string|undefined,state:string|undefined){return state==="APPROVED"&&role!==undefined&&["ADMINISTRATOR","CONTENT_ADMINISTRATOR","DIRECT_SPONSORED_CONTENT_POSTER"].includes(role);}
export async function discoverLinkedInOrganizations(accessToken:string):Promise<DiscoveredProviderSource[]>{const value=aclSchema.parse(await linkedin("rest/organizationAcls?q=roleAssignee&state=APPROVED&count=100",accessToken));return value.elements.filter(item=>linkedinOrganizationAuthority(item.role,item.state)).map(item=>{const id=item.organization.split(":").at(-1)??"";return{sourceType:"linkedin_organization",stableSourceId:item.organization,displayName:"LinkedIn organization",canonicalUrl:`https://www.linkedin.com/company/${id}`,metadata:{authorityRole:item.role??null,authorityState:item.state??null}};});}
export async function pollLinkedInPosts(accessToken:string,authorUrn:string,cursor?:string|null):Promise<ProviderPollResult>{const start=cursor&&/^\d+$/.test(cursor)?Number(cursor):0,value=postsSchema.parse(await linkedin(`rest/posts?q=author&author=${encodeURIComponent(authorUrn)}&start=${start}&count=100`,accessToken)),published=value.elements.filter(item=>item.lifecycleState==="PUBLISHED"||item.lifecycleState==="PUBLISHED_EDITED");return{items:published.map(post=>({provider:"linkedin",externalObjectId:post.id,objectType:"post",eventType:post.lifecycleState==="PUBLISHED_EDITED"?"updated":"published",title:post.commentary?.slice(0,160)??null,description:post.commentary??null,canonicalUrl:`https://www.linkedin.com/feed/update/${encodeURIComponent(post.id)}/`,thumbnailUrl:null,mediaUrls:[],sourcePublishedAt:new Date(post.publishedAt??post.createdAt).toISOString(),scheduledStartAt:null,liveStatus:null,rawMetadata:{authorUrn:post.author,lifecycleState:post.lifecycleState,visibility:post.visibility??null}})),cursor:value.paging&&start+value.paging.count<(value.paging.total??0)?String(start+value.paging.count):null};}
