import{z}from"zod";import{createTraceId}from"@/lib/debug";import{SocialProviderError}from"@/lib/social-providers/errors";import type{DiscoveredProviderSource,ProviderIdentity,ProviderPollResult,ProviderTokenSet}from"@/lib/social-providers/types";
const optionalString=z.string().trim().min(1).nullable().optional().catch(undefined);
const oidcCoreSchema=z.object({sub:z.string().trim().min(1)}).passthrough();
const oidcProfileSchema=z.object({name:optionalString,given_name:optionalString,family_name:optionalString,picture:optionalString,profile:optionalString,locale:optionalString}).passthrough();
const tokenSchema=z.object({access_token:z.string().min(1),expires_in:z.number().int().positive(),refresh_token:z.string().min(1).optional(),refresh_token_expires_in:z.number().int().positive().optional(),scope:z.string().optional(),token_type:z.string().min(1).optional()}).passthrough();
const aclSchema=z.object({elements:z.array(z.object({organization:z.string().regex(/^urn:li:organization:\d+$/),role:z.enum(["ADMINISTRATOR","DIRECT_SPONSORED_CONTENT_POSTER","LEAD_GEN_FORMS_MANAGER","CURATOR","CONTENT_ADMINISTRATOR"]).optional(),state:z.string().optional()})),paging:z.object({start:z.number(),count:z.number(),total:z.number().optional()}).optional()});
const postSchema=z.object({id:z.string().regex(/^urn:li:(share|ugcPost):\d+$/),author:z.string().min(1),commentary:z.string().optional(),lifecycleState:z.enum(["PUBLISHED","DRAFT","PROCESSING","PROCESSING_FAILED","PUBLISHED_EDITED","ARCHIVED"]),visibility:z.string().optional(),createdAt:z.number().int().positive(),publishedAt:z.number().int().positive().optional()});
const postsSchema=z.object({elements:z.array(postSchema),paging:z.object({start:z.number(),count:z.number(),total:z.number().optional()}).optional()});
function version(){const value=process.env.LINKEDIN_API_VERSION??"202603";if(!/^20\d{4}$/.test(value))throw new Error("invalid_linkedin_api_version");return value;}
function wireType(value:unknown){return Array.isArray(value)?"array":value===null?"null":typeof value;}
function safeShape(raw:unknown,fields:string[]){const object=raw&&typeof raw==="object"&&!Array.isArray(raw)?raw as Record<string,unknown>:null,field=(key:string)=>({present:Boolean(object&&Object.prototype.hasOwnProperty.call(object,key)),type:object?wireType(object[key]):"undefined"});return{responseKeys:object?Object.keys(object).sort():[],fields:Object.fromEntries(fields.map(key=>[key,field(key)]))};}
function diagnostic(operation:string,response:Response,raw:unknown,validationCategory:string,fields:string[]){console.warn("linkedin_oauth_diagnostic",{traceId:createTraceId("linkedin"),provider:"linkedin",operation,httpStatus:response.status,validationCategory,...safeShape(raw,fields)});}
function safeHttpUrl(value:string|null|undefined,linkedinOnly=false){if(!value)return null;try{const url=new URL(value);if(url.protocol!=="https:"&&url.protocol!=="http:")return null;if(linkedinOnly&&url.hostname!=="linkedin.com"&&!url.hostname.endsWith(".linkedin.com"))return null;return url.toString();}catch{return null;}}
async function linkedin(path:string,token:string){const response=await fetch(`https://api.linkedin.com/${path}`,{headers:{authorization:`Bearer ${token}`,accept:"application/json","LinkedIn-Version":version(),"X-Restli-Protocol-Version":"2.0.0"},cache:"no-store"}),raw:unknown=await response.json().catch(()=>({}));if(!response.ok){diagnostic("userinfo",response,raw,"provider_http_error",["sub","name","given_name","family_name","picture","profile","locale"]);throw new SocialProviderError(response.status===401?"access_revoked":response.status===429?"rate_limited":response.status===403?"missing_approved_scope":"transient","linkedin","LinkedIn identity request failed.");}return{raw,response};}
export async function exchangeLinkedInCode(code:string):Promise<ProviderTokenSet>{const clientId=process.env.LINKEDIN_CLIENT_ID,clientSecret=process.env.LINKEDIN_CLIENT_SECRET,redirectUri=process.env.LINKEDIN_REDIRECT_URI;if(!clientId||!clientSecret||!redirectUri)throw new SocialProviderError("provider_not_configured","linkedin","LinkedIn credentials are unavailable.");const response=await fetch("https://www.linkedin.com/oauth/v2/accessToken",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"authorization_code",code,client_id:clientId,client_secret:clientSecret,redirect_uri:redirectUri}),cache:"no-store"}),raw:unknown=await response.json().catch(()=>({}));if(!response.ok){diagnostic("token_exchange",response,raw,"provider_http_error",["access_token","expires_in","refresh_token","refresh_token_expires_in","scope","token_type","id_token"]);throw new SocialProviderError(response.status===400?"invalid_grant":response.status===429?"rate_limited":"transient","linkedin","LinkedIn authorization exchange failed.");}const parsed=tokenSchema.safeParse(raw);if(!parsed.success){diagnostic("token_exchange",response,raw,"malformed_token_response",["access_token","expires_in","refresh_token","refresh_token_expires_in","scope","token_type","id_token"]);throw new SocialProviderError("malformed_provider_object","linkedin","LinkedIn token response was incomplete.");}const scopes=(parsed.data.scope??"openid profile").split(/[ ,]+/).filter(Boolean);return{accessToken:parsed.data.access_token,refreshToken:parsed.data.refresh_token??null,expiresAt:new Date(Date.now()+parsed.data.expires_in*1000).toISOString(),refreshTokenExpiresAt:parsed.data.refresh_token_expires_in?new Date(Date.now()+parsed.data.refresh_token_expires_in*1000).toISOString():null,scopes,grantedScopes:scopes,tokenType:parsed.data.token_type??"Bearer"};}
export async function fetchLinkedInIdentity(accessToken:string):Promise<ProviderIdentity>{const{raw,response}=await linkedin("v2/userinfo",accessToken),core=oidcCoreSchema.safeParse(raw);if(!core.success){diagnostic("userinfo",response,raw,"missing_stable_subject",["sub","name","given_name","family_name","picture","profile","locale"]);throw new SocialProviderError("malformed_provider_object","linkedin","LinkedIn user information did not contain a stable subject.");}const value=oidcProfileSchema.parse(raw),displayName=value.name??([value.given_name,value.family_name].filter(Boolean).join(" ")||"LinkedIn member"),profile=safeHttpUrl(value.profile,true)??"https://www.linkedin.com/",avatar=safeHttpUrl(value.picture);return{id:core.data.sub,name:displayName,url:profile,externalAccountId:core.data.sub,displayName,username:null,profileUrl:profile,avatarUrl:avatar,metadata:{identityType:"member",givenName:value.given_name??null,familyName:value.family_name??null,locale:value.locale??null,profileUrlAvailable:profile!=="https://www.linkedin.com/",oidcIdentitySource:"userinfo",oidcSubjectType:"pairwise",oidcSessionControl:true,realWorldIdentityVerified:false,audienceMetricSupported:false}};}
export function linkedinOrganizationAuthority(role:string|undefined,state:string|undefined){return state==="APPROVED"&&role!==undefined&&["ADMINISTRATOR","CONTENT_ADMINISTRATOR","DIRECT_SPONSORED_CONTENT_POSTER"].includes(role);}
export async function discoverLinkedInOrganizations(accessToken:string):Promise<DiscoveredProviderSource[]>{const{raw}=await linkedin("rest/organizationAcls?q=roleAssignee&state=APPROVED&count=100",accessToken),value=aclSchema.parse(raw);return value.elements.filter(item=>linkedinOrganizationAuthority(item.role,item.state)).map(item=>{const id=item.organization.split(":").at(-1)??"";return{sourceType:"linkedin_organization",stableSourceId:item.organization,displayName:"LinkedIn organization",canonicalUrl:`https://www.linkedin.com/company/${id}`,metadata:{authorityRole:item.role??null,authorityState:item.state??null}};});}
export async function pollLinkedInPosts(accessToken:string,authorUrn:string,cursor?:string|null):Promise<ProviderPollResult>{const start=cursor&&/^\d+$/.test(cursor)?Number(cursor):0,{raw}=await linkedin(`rest/posts?q=author&author=${encodeURIComponent(authorUrn)}&start=${start}&count=100`,accessToken),value=postsSchema.parse(raw),published=value.elements.filter(item=>item.lifecycleState==="PUBLISHED"||item.lifecycleState==="PUBLISHED_EDITED");return{items:published.map(post=>({provider:"linkedin",externalObjectId:post.id,objectType:"post",eventType:post.lifecycleState==="PUBLISHED_EDITED"?"updated":"published",title:post.commentary?.slice(0,160)??null,description:post.commentary??null,canonicalUrl:`https://www.linkedin.com/feed/update/${encodeURIComponent(post.id)}/`,thumbnailUrl:null,mediaUrls:[],sourcePublishedAt:new Date(post.publishedAt??post.createdAt).toISOString(),scheduledStartAt:null,liveStatus:null,rawMetadata:{authorUrn:post.author,lifecycleState:post.lifecycleState,visibility:post.visibility??null}})),cursor:value.paging&&start+value.paging.count<(value.paging.total??0)?String(start+value.paging.count):null};}
