import "server-only";
import {createHmac} from "node:crypto";
import {z} from "zod";
import {createAdminClient} from "@/lib/supabase/admin";
import {decryptSocialSecret,encryptSocialSecret} from "@/lib/social-secrets";
import {discoverMetaPages,fetchFacebookPageIdentity,fetchInstagramIdentity} from "./meta";
import {initializeProviderAudience} from "@/lib/social-providers/initial-audience";
import {revalidateCreatorAccounts} from "@/lib/social-providers/creator-account-revalidation";

const meSchema=z.object({id:z.string().min(1),name:z.string().min(1)});
type Role="official"|"backup";
function assetSelectionKey(provider:"facebook"|"instagram",pageId:string,instagramId?:string){const secret=process.env.SOCIAL_OAUTH_STATE_SECRET??process.env.META_APP_SECRET;if(!secret)throw new Error("provider_not_configured");return createHmac("sha256",secret).update(`${provider}:${pageId}:${instagramId??""}`).digest("base64url");}
async function connectionSecret(creatorId:string,connectionId:string){
  const db=createAdminClient();if(!db)throw new Error("provider_not_configured");
  const[{data:connection,error:connectionError},{data:secret,error:secretError}]=await Promise.all([db.from("connected_accounts").select("id,creator_id,platform,account_type,granted_scopes,provider_metadata").eq("id",connectionId).eq("creator_id",creatorId).eq("platform","facebook").eq("provider_status","asset_selection_required").single(),db.from("platform_connection_secrets").select("access_token_ciphertext").eq("platform_connection_id",connectionId).single()]);
  if(connectionError||secretError)throw connectionError??secretError;
  if(!connection||!secret)throw new Error("connection_unavailable");
  const metadata=connection.provider_metadata&&typeof connection.provider_metadata==="object"&&!Array.isArray(connection.provider_metadata)?connection.provider_metadata:{};
  return{db,token:decryptSocialSecret(secret.access_token_ciphertext),grantedScopes:connection.granted_scopes,role:connection.account_type as Role,reconnectTargetId:typeof metadata.reconnectTargetId==="string"?metadata.reconnectTargetId:null,protectedOfficialAccountId:typeof metadata.protectedOfficialAccountId==="string"?metadata.protectedOfficialAccountId:null};
}
export async function fetchMetaAppUser(accessToken:string){const response=await fetch("https://graph.facebook.com/me?fields=id,name",{headers:{authorization:`Bearer ${accessToken}`},cache:"no-store"});const value:unknown=await response.json();if(!response.ok)throw new Error("authentication_revoked");return meSchema.parse(value);}
export async function listMetaAssets(creatorId:string,connectionId:string){const{token}=await connectionSecret(creatorId,connectionId),pages=await discoverMetaPages(token);return pages.flatMap(page=>[{provider:"facebook" as const,assetType:"facebook_page",displayName:page.displayName,canonicalUrl:page.canonicalUrl,pictureUrl:typeof page.metadata.pictureUrl==="string"?page.metadata.pictureUrl:null,username:typeof page.metadata.username==="string"?page.metadata.username:null,selectionKey:assetSelectionKey("facebook",page.stableSourceId),authorityAvailable:true,linkedInstagramAvailable:Boolean(page.instagramId)},...(page.instagramId?[{provider:"instagram" as const,assetType:"instagram_professional_account",displayName:`Instagram linked to ${page.displayName}`,canonicalUrl:"https://www.instagram.com/",pictureUrl:null,username:null,selectionKey:assetSelectionKey("instagram",page.stableSourceId,page.instagramId),authorityAvailable:true,linkedInstagramAvailable:true}]:[])]);}
export async function selectMetaAsset(creatorId:string,connectionId:string,provider:"facebook"|"instagram",selectionKey:string){
  const{db,token,grantedScopes,role,reconnectTargetId,protectedOfficialAccountId}=await connectionSecret(creatorId,connectionId),pages=await discoverMetaPages(token),page=pages.find(candidate=>assetSelectionKey(provider,candidate.stableSourceId,provider==="instagram"?candidate.instagramId:undefined)===selectionKey),instagramId=provider==="instagram"?page?.instagramId:undefined;if(!page)throw new Error("page_not_managed");
  const credential=page.pageToken,credentialType="page_access";let stableId=page.stableSourceId,displayName=page.displayName??"Facebook Page",displayHandle=typeof page.metadata.username==="string"?page.metadata.username:null,canonicalUrl=page.canonicalUrl,parentId:string|null=null,assetType="facebook_page",avatarUrl=typeof page.metadata.pictureUrl==="string"?page.metadata.pictureUrl:null;
  if(provider==="facebook"){const identity=await fetchFacebookPageIdentity(credential,page.stableSourceId);stableId=identity.id;displayName=identity.displayName??"Facebook Page";displayHandle=identity.username??null;canonicalUrl=identity.profileUrl??page.canonicalUrl;avatarUrl=identity.avatarUrl??null;}
  if(provider==="instagram"){if(!instagramId||page.instagramId!==instagramId)throw new Error("account_not_professional");const identity=await fetchInstagramIdentity(page.pageToken,instagramId);stableId=identity.id;displayName=identity.name;displayHandle=typeof identity.metadata.handle==="string"?identity.metadata.handle:null;canonicalUrl=identity.url;parentId=page.stableSourceId;assetType="instagram_professional_account";}
  let targetId=reconnectTargetId;
  if(targetId){const{data:target,error:targetError}=await db.from("connected_accounts").select("id,platform,account_type,external_account_id").eq("id",targetId).eq("creator_id",creatorId).maybeSingle();if(targetError)throw targetError;if(!target||target.platform!==provider||target.account_type!==role||target.external_account_id!==stableId)throw new Error("reconnect_mismatch");}
  else{const{data:duplicate,error:duplicateError}=await db.from("connected_accounts").select("id").eq("creator_id",creatorId).eq("platform",provider).eq("account_type",role).eq("external_account_id",stableId).maybeSingle();if(duplicateError)throw duplicateError;targetId=duplicate?.id??connectionId;}
  const required=provider==="facebook"?["pages_show_list","pages_read_engagement"]:["pages_show_list","instagram_basic"],values={creator_id:creatorId,platform:provider,account_type:role,protected_official_account_id:role==="backup"?protectedOfficialAccountId:null,label:displayName,url:canonicalUrl,is_primary:false,is_public:true,external_account_id:stableId,external_account_name:displayName,external_account_url:canonicalUrl,provider_metadata:{loginMethod:"facebook_login",parentMetaConnectionId:connectionId,parentAssetId:parentId,tokenType:credentialType,pageTasks:page.tasks,avatarUrl},requested_scopes:required,granted_scopes:grantedScopes.filter(scope=>required.includes(scope)),watch_enabled:required.every(scope=>grantedScopes.includes(scope)),auto_create_drafts:true,auto_send:false,webhook_enabled:Boolean(process.env.META_WEBHOOK_VERIFY_TOKEN),connection_health:"healthy",provider_status:required.every(scope=>grantedScopes.includes(scope))?"ready":"app_review_required"};
  const selected=targetId?await db.from("connected_accounts").update(values).eq("id",targetId).eq("creator_id",creatorId).select("id").single():await db.from("connected_accounts").insert(values).select("id").single();if(selected.error)throw selected.error;
  const created=!targetId;targetId=selected.data.id;
  try{
    const saved=await db.from("platform_connection_secrets").upsert({platform_connection_id:targetId,access_token_ciphertext:encryptSocialSecret(credential),refresh_token_ciphertext:null,token_scope:(provider==="facebook"?page.tasks:["instagram_basic"]).join(" "),token_type:credentialType});if(saved.error)throw saved.error;
    const{data:assetId,error}=await db.rpc("select_provider_asset",{p_connected_account_id:targetId,p_provider:provider,p_asset_type:assetType,p_stable_asset_id:stableId,p_parent_asset_id:parentId??"",p_display_name:displayName,p_display_handle:displayHandle??"",p_canonical_url:canonicalUrl,p_metadata:{loginMethod:"facebook_login",tokenType:credentialType,authorityValidated:true}});if(error||!assetId)throw error??new Error("asset_selection_failed");
    const secret=await db.from("provider_asset_secrets").upsert({asset_binding_id:assetId,creator_id:creatorId,provider,credential_ciphertext:encryptSocialSecret(credential),credential_type:credentialType,granted_permissions:page.tasks},{onConflict:"asset_binding_id"});if(secret.error)throw secret.error;
    if(process.env.META_WEBHOOK_VERIFY_TOKEN)await db.from("meta_webhook_subscriptions").upsert({creator_id:creatorId,asset_binding_id:assetId,object_type:provider==="facebook"?"page":"instagram",subscribed_fields:provider==="facebook"?["feed","name","permissions"]:["media","account_update"],status:"pending",next_reconcile_at:new Date().toISOString()},{onConflict:"asset_binding_id,object_type"});
    await initializeProviderAudience({db,creatorId,connectionId:targetId,provider,role,accessToken:credential,stableId,loginMethod:provider==="instagram"?"facebook_login":undefined});await db.rpc("sync_identity_account_from_connection",{p_connection_id:targetId});if(connectionId!==targetId)await db.from("connected_accounts").delete().eq("id",connectionId).eq("creator_id",creatorId);revalidateCreatorAccounts(creatorId);
    return{id:assetId,connectionId:targetId,provider,displayName,displayHandle,canonicalUrl,detectionReady:required.every(scope=>grantedScopes.includes(scope))};
  }catch(error){if(created)await db.from("connected_accounts").delete().eq("id",targetId).eq("creator_id",creatorId);throw error;}
}
