import { createHmac, timingSafeEqual } from "node:crypto";
import { z } from "zod";
import type { DiscoveredProviderSource, ProviderIdentity, ProviderPollResult } from "@/lib/social-providers/types";
import { canonicalProviderUrl } from "./provider-expansion-two";

const graphEnvelope=<T extends z.ZodTypeAny>(item:T)=>z.object({data:z.array(item),paging:z.object({cursors:z.object({after:z.string().optional()}).optional(),next:z.string().url().optional()}).optional()});
const pageSchema=z.object({id:z.string().min(1),name:z.string().min(1),access_token:z.string().min(1),tasks:z.array(z.string()).default([]),category:z.string().optional(),username:z.string().optional(),link:z.string().url().optional(),instagram_business_account:z.object({id:z.string().min(1)}).optional()});
const igSchema=z.object({id:z.string().min(1),username:z.string().min(1),name:z.string().optional(),profile_picture_url:z.string().url().optional(),biography:z.string().optional(),website:z.string().url().optional(),account_type:z.enum(["BUSINESS","MEDIA_CREATOR","CREATOR"])});
const mediaSchema=z.object({id:z.string().min(1),media_type:z.enum(["IMAGE","VIDEO","CAROUSEL_ALBUM"]),media_product_type:z.string().optional(),caption:z.string().optional(),permalink:z.string().url(),timestamp:z.string().datetime(),thumbnail_url:z.string().url().optional(),children:z.object({data:z.array(z.object({id:z.string()}))}).optional(),username:z.string().optional()});
const postSchema=z.object({id:z.string().min(1),created_time:z.string().datetime(),updated_time:z.string().datetime().optional(),message:z.string().optional(),story:z.string().optional(),permalink_url:z.string().url(),is_published:z.boolean().optional()});
const instagramTokenSchema=z.object({access_token:z.string().min(1),user_id:z.union([z.string(),z.number()]).transform(String),permissions:z.array(z.string()).optional()});
export function graphVersion(){const value=process.env.META_GRAPH_API_VERSION??"v23.0";if(!/^v\d+\.\d+$/.test(value))throw new Error("invalid_meta_graph_version");return value;}
async function graph(path:string,token:string){const response=await fetch(`https://graph.facebook.com/${graphVersion()}/${path}`,{headers:{authorization:`Bearer ${token}`,accept:"application/json"},cache:"no-store"});const value:unknown=await response.json();if(!response.ok)throw new Error(response.status===401?"authentication_revoked":response.status===429?"rate_limited":"meta_provider_failure");return value;}
async function instagramGraph(path:string,token:string){const version=process.env.INSTAGRAM_GRAPH_API_VERSION??"v23.0";if(!/^v\d+\.\d+$/.test(version))throw new Error("invalid_instagram_graph_version");const response=await fetch(`https://graph.instagram.com/${version}/${path}`,{headers:{authorization:`Bearer ${token}`,accept:"application/json"},cache:"no-store"});const value:unknown=await response.json();if(!response.ok)throw new Error(response.status===401?"authentication_revoked":response.status===429?"rate_limited":"instagram_provider_failure");return value;}
export async function exchangeInstagramCode(code:string){const clientId=process.env.INSTAGRAM_CLIENT_ID,secret=process.env.INSTAGRAM_CLIENT_SECRET,redirect=process.env.INSTAGRAM_REDIRECT_URI;if(!clientId||!secret||!redirect)throw new Error("credentials_missing");const response=await fetch("https://api.instagram.com/oauth/access_token",{method:"POST",body:new URLSearchParams({client_id:clientId,client_secret:secret,grant_type:"authorization_code",redirect_uri:redirect,code}),cache:"no-store"}),raw:unknown=await response.json();if(!response.ok)throw new Error("instagram_token_exchange_failed");const value=instagramTokenSchema.parse(raw);return{accessToken:value.access_token,expiresAt:null,grantedScopes:value.permissions??["instagram_business_basic"],tokenType:"Bearer",stableIdentityId:value.user_id};}
export async function discoverMetaPages(accessToken:string):Promise<Array<DiscoveredProviderSource&{pageToken:string;tasks:string[];instagramId?:string}>>{const value=graphEnvelope(pageSchema).parse(await graph("me/accounts?fields=id,name,access_token,tasks,category,username,link,instagram_business_account",accessToken));return value.data.filter(page=>page.tasks.some(task=>["CREATE_CONTENT","MANAGE","MODERATE"].includes(task))).map(page=>({sourceType:"facebook_page",stableSourceId:page.id,displayName:page.name,canonicalUrl:canonicalProviderUrl("facebook",page.link??`https://www.facebook.com/${page.username??page.id}`)?.toString()??`https://www.facebook.com/${page.id}`,metadata:{category:page.category??null,username:page.username??null,tasks:page.tasks},pageToken:page.access_token,tasks:page.tasks,instagramId:page.instagram_business_account?.id}));}
export async function fetchInstagramIdentity(accessToken:string,id:string):Promise<ProviderIdentity>{const item=igSchema.parse(await graph(`${encodeURIComponent(id)}?fields=id,username,name,profile_picture_url,biography,website,account_type`,accessToken));return{id:item.id,name:item.name??item.username,url:`https://www.instagram.com/${item.username}/`,metadata:{handle:item.username,accountType:item.account_type,profilePictureUrl:item.profile_picture_url,biography:item.biography,website:item.website}};}
export async function fetchInstagramLoginIdentity(accessToken:string,id:string):Promise<ProviderIdentity>{const item=igSchema.parse(await instagramGraph(`${encodeURIComponent(id)}?fields=id,username,name,profile_picture_url,biography,website,account_type`,accessToken));return{id:item.id,name:item.name??item.username,url:`https://www.instagram.com/${item.username}/`,metadata:{handle:item.username,accountType:item.account_type,profilePictureUrl:item.profile_picture_url,biography:item.biography,website:item.website,loginMethod:"instagram_login"}};}
export async function pollInstagramMedia(accessToken:string,id:string,cursor?:string|null):Promise<ProviderPollResult>{const suffix=cursor?`&after=${encodeURIComponent(cursor)}`:"",value=graphEnvelope(mediaSchema).parse(await graph(`${encodeURIComponent(id)}/media?fields=id,media_type,media_product_type,caption,permalink,timestamp,thumbnail_url,children{id},username&limit=25${suffix}`,accessToken));return{items:value.data.map(item=>({provider:"instagram",externalObjectId:item.id,objectType:item.media_type==="IMAGE"?"image":item.media_type==="CAROUSEL_ALBUM"?"carousel":"video",eventType:"published",title:item.caption?.slice(0,160)??null,description:item.caption??null,canonicalUrl:canonicalProviderUrl("instagram",item.permalink)?.toString()??item.permalink,thumbnailUrl:item.thumbnail_url??null,mediaUrls:[],sourcePublishedAt:item.timestamp,scheduledStartAt:null,liveStatus:null,rawMetadata:{mediaProductType:item.media_product_type??null,carouselChildIds:item.children?.data.map(child=>child.id)??[],username:item.username??null}})),cursor:value.paging?.cursors?.after??null};}
export async function pollInstagramLoginMedia(accessToken:string,id:string,cursor?:string|null):Promise<ProviderPollResult>{const suffix=cursor?`&after=${encodeURIComponent(cursor)}`:"",value=graphEnvelope(mediaSchema).parse(await instagramGraph(`${encodeURIComponent(id)}/media?fields=id,media_type,media_product_type,caption,permalink,timestamp,thumbnail_url,children{id},username&limit=25${suffix}`,accessToken));return{items:value.data.map(item=>({provider:"instagram",externalObjectId:item.id,objectType:item.media_type==="IMAGE"?"image":item.media_type==="CAROUSEL_ALBUM"?"carousel":"video",eventType:"published",title:item.caption?.slice(0,160)??null,description:item.caption??null,canonicalUrl:item.permalink,thumbnailUrl:item.thumbnail_url??null,mediaUrls:[],sourcePublishedAt:item.timestamp,scheduledStartAt:null,liveStatus:null,rawMetadata:{mediaProductType:item.media_product_type??null,carouselChildIds:item.children?.data.map(child=>child.id)??[],username:item.username??null}})),cursor:value.paging?.cursors?.after??null};}
export async function pollFacebookPosts(accessToken:string,id:string,cursor?:string|null):Promise<ProviderPollResult>{const suffix=cursor?`&after=${encodeURIComponent(cursor)}`:"",value=graphEnvelope(postSchema).parse(await graph(`${encodeURIComponent(id)}/posts?fields=id,created_time,updated_time,message,story,permalink_url,is_published&limit=25${suffix}`,accessToken));return{items:value.data.filter(item=>item.is_published!==false).map(item=>({provider:"facebook",externalObjectId:item.id,objectType:"post",eventType:"published",title:(item.message??item.story)?.slice(0,160)??null,description:item.message??item.story??null,canonicalUrl:canonicalProviderUrl("facebook",item.permalink_url)?.toString()??item.permalink_url,thumbnailUrl:null,mediaUrls:[],sourcePublishedAt:item.created_time,scheduledStartAt:null,liveStatus:null,rawMetadata:{updatedTime:item.updated_time??null,publicationStatus:"published"}})),cursor:value.paging?.cursors?.after??null};}
export function verifyMetaSignature(body:string,header:string|null){const secret=process.env.META_APP_SECRET;if(!secret||!header?.startsWith("sha256="))return false;const expected=Buffer.from(createHmac("sha256",secret).update(body).digest("hex"),"utf8"),actual=Buffer.from(header.slice(7),"utf8");return expected.length===actual.length&&timingSafeEqual(expected,actual);}
export const metaWebhookSchema=z.object({object:z.enum(["page","instagram"]),entry:z.array(z.object({id:z.string(),time:z.number(),changes:z.array(z.object({field:z.enum(["feed","name","username","permissions","account_update","media"]),value:z.record(z.string(),z.unknown()).optional()})).default([])})).max(100)}).strict();
