import{z}from"zod";import{SocialProviderError}from"@/lib/social-providers/errors";import type{ProviderIdentity,ProviderPollResult,ProviderTokenSet}from"@/lib/social-providers/types";
const user=z.object({id:z.string().regex(/^\d+$/),username:z.string().min(1),business_name:z.string().nullable().optional(),profile_image:z.string().url().nullable().optional(),about:z.string().nullable().optional(),website_url:z.string().url().nullable().optional(),account_type:z.string().optional(),follower_count:z.number().int().nonnegative().nullable().optional()}).passthrough();
const token=z.object({access_token:z.string().min(1),refresh_token:z.string().min(1),token_type:z.string().min(1),expires_in:z.number().int().positive(),refresh_token_expires_in:z.number().int().positive(),refresh_token_expires_at:z.number().int().positive().optional(),scope:z.string()});
const board=z.object({id:z.string().min(1),name:z.string().min(1),privacy:z.string(),owner:z.object({username:z.string().optional()}).optional()}).passthrough();
const pin=z.object({id:z.string().min(1),title:z.string().nullable().optional(),description:z.string().nullable().optional(),created_at:z.string().datetime(),link:z.string().url().nullable().optional(),media:z.record(z.string(),z.unknown()).optional(),board_id:z.string().min(1),alt_text:z.string().nullable().optional()}).passthrough();
async function api(path:string,token:string){const response=await fetch(`https://api.pinterest.com/v5/${path}`,{headers:{authorization:`Bearer ${token}`,accept:"application/json"},cache:"no-store"}),raw:unknown=await response.json();if(!response.ok)throw new Error(response.status===401?"authentication_revoked":response.status===429?"rate_limited":"temporary_provider_failure");return raw;}
function credentials(){const id=process.env.PINTEREST_APP_ID,secret=process.env.PINTEREST_APP_SECRET,redirect=process.env.PINTEREST_REDIRECT_URI;if(!id||!secret||!redirect)throw new SocialProviderError("provider_not_configured","pinterest","Pinterest credentials are unavailable.");return{id,secret,redirect};}
function normalizeToken(value:unknown):ProviderTokenSet{const parsed=token.safeParse(value);if(!parsed.success)throw new SocialProviderError("malformed_provider_object","pinterest","Pinterest returned an incomplete token response.");const scopes=parsed.data.scope.split(/[ ,]+/).filter(Boolean),refreshTokenExpiresAt=parsed.data.refresh_token_expires_at?new Date(parsed.data.refresh_token_expires_at*1000).toISOString():new Date(Date.now()+parsed.data.refresh_token_expires_in*1000).toISOString();return{accessToken:parsed.data.access_token,refreshToken:parsed.data.refresh_token,expiresAt:new Date(Date.now()+parsed.data.expires_in*1000).toISOString(),refreshTokenExpiresAt,scopes,grantedScopes:scopes,tokenType:parsed.data.token_type};}
async function tokenRequest(body:URLSearchParams){const{id,secret}=credentials(),response=await fetch("https://api.pinterest.com/v5/oauth/token",{method:"POST",headers:{authorization:`Basic ${Buffer.from(`${id}:${secret}`).toString("base64")}`,"content-type":"application/x-www-form-urlencoded"},body,cache:"no-store"}),value=await response.json().catch(()=>({}));if(!response.ok)throw new SocialProviderError(response.status===400||response.status===401?"invalid_grant":response.status===429?"rate_limited":"transient","pinterest","Pinterest token request failed.",Number(response.headers.get("retry-after")??0)||undefined);return normalizeToken(value);}
export async function exchangePinterestCode(code:string){const{redirect}=credentials();return tokenRequest(new URLSearchParams({grant_type:"authorization_code",code,redirect_uri:redirect,continuous_refresh:"true"}));}
export async function refreshPinterestToken(refreshToken:string){return tokenRequest(new URLSearchParams({grant_type:"refresh_token",refresh_token:refreshToken}));}
export async function fetchPinterestIdentity(accessToken:string):Promise<ProviderIdentity>{const p=user.parse(await api("user_account",accessToken)),displayName=p.business_name||p.username,profileUrl=`https://www.pinterest.com/${encodeURIComponent(p.username)}/`;return{id:p.id,name:displayName,url:profileUrl,externalAccountId:p.id,displayName,username:p.username,profileUrl,avatarUrl:p.profile_image??null,metadata:{username:p.username,profileImageUrl:p.profile_image??null,description:p.about??null,websiteUrl:p.website_url??null,accountType:p.account_type??null,followerCount:p.follower_count??null,identityType:"user_account"}};}
export async function discoverPinterestBoards(token:string){const raw=z.object({items:z.array(board),bookmark:z.string().nullable().optional()}).parse(await api("boards?page_size=100",token));return raw.items.filter(b=>!["SECRET","PRIVATE","PROTECTED"].includes(b.privacy.toUpperCase())).map(b=>({sourceType:"pinterest_board",stableSourceId:b.id,displayName:b.name,canonicalUrl:`https://www.pinterest.com/${encodeURIComponent(b.owner?.username??"_")}/${encodeURIComponent(b.name)}/`,metadata:{privacy:b.privacy,public:true}}));}
export async function fetchPinterestClaimedWebsites(token:string){const raw=z.object({items:z.array(z.object({website:z.string().min(1),status:z.string()})).default([])}).parse(await api("user_account/websites",token));return raw.items.filter(x=>x.status.toLowerCase()==="claimed").map(x=>{const host=new URL(/^https:\/\//i.test(x.website)?x.website:`https://${x.website}`).hostname.toLowerCase();return{hostname:host,status:"claimed" as const};});}
export async function pollPinterestPins(token:string,boardId:string,cursor?:string|null):Promise<ProviderPollResult>{if(!boardId)throw new Error("asset_not_selected");const params=new URLSearchParams({page_size:"100"});if(cursor)params.set("bookmark",cursor);const raw=z.object({items:z.array(pin),bookmark:z.string().nullable().optional()}).parse(await api(`boards/${encodeURIComponent(boardId)}/pins?${params}`,token));return{items:raw.items.map(p=>({provider:"pinterest" as const,externalObjectId:p.id,objectType:"pin" as const,eventType:"published" as const,title:p.title??null,description:p.description??null,canonicalUrl:`https://www.pinterest.com/pin/${p.id}/`,thumbnailUrl:null,mediaUrls:[],sourcePublishedAt:p.created_at,scheduledStartAt:null,liveStatus:null,rawMetadata:{boardId:p.board_id,destinationLink:p.link??null,altText:p.alt_text??null,media:p.media??{},approvalRequired:true,automaticPublishing:false}})),cursor:raw.bookmark??null};}
