import{z}from"zod";import type{ProviderIdentity,ProviderPollResult}from"@/lib/social-providers/types";
const user=z.object({id:z.string().min(1),username:z.string().min(1),business_name:z.string().optional(),profile_image:z.string().url().optional(),about:z.string().optional(),website_url:z.string().url().optional(),account_type:z.string().optional()}).passthrough();
const board=z.object({id:z.string().min(1),name:z.string().min(1),privacy:z.string(),owner:z.object({username:z.string().optional()}).optional()}).passthrough();
const pin=z.object({id:z.string().min(1),title:z.string().nullable().optional(),description:z.string().nullable().optional(),created_at:z.string().datetime(),link:z.string().url().nullable().optional(),media:z.record(z.string(),z.unknown()).optional(),board_id:z.string().min(1),alt_text:z.string().nullable().optional()}).passthrough();
async function api(path:string,token:string){const response=await fetch(`https://api.pinterest.com/v5/${path}`,{headers:{authorization:`Bearer ${token}`,accept:"application/json"},cache:"no-store"}),raw:unknown=await response.json();if(!response.ok)throw new Error(response.status===401?"authentication_revoked":response.status===429?"rate_limited":"temporary_provider_failure");return raw;}
export async function fetchPinterestIdentity(token:string):Promise<ProviderIdentity>{const p=user.parse(await api("user_account",token));return{id:p.id,name:p.business_name??p.username,url:`https://www.pinterest.com/${encodeURIComponent(p.username)}/`,metadata:{username:p.username,profileImageUrl:p.profile_image??null,description:p.about??null,websiteUrl:p.website_url??null,accountType:p.account_type??null}};}
export async function discoverPinterestBoards(token:string){const raw=z.object({items:z.array(board),bookmark:z.string().nullable().optional()}).parse(await api("boards?page_size=100",token));return raw.items.filter(b=>!["SECRET","PRIVATE","PROTECTED"].includes(b.privacy.toUpperCase())).map(b=>({sourceType:"pinterest_board",stableSourceId:b.id,displayName:b.name,canonicalUrl:`https://www.pinterest.com/${encodeURIComponent(b.owner?.username??"_")}/${encodeURIComponent(b.name)}/`,metadata:{privacy:b.privacy,public:true}}));}
export async function fetchPinterestClaimedWebsites(token:string){const raw=z.object({items:z.array(z.object({website:z.string().min(1),status:z.string()})).default([])}).parse(await api("user_account/websites",token));return raw.items.filter(x=>x.status.toLowerCase()==="claimed").map(x=>{const host=new URL(/^https:\/\//i.test(x.website)?x.website:`https://${x.website}`).hostname.toLowerCase();return{hostname:host,status:"claimed" as const};});}
export async function pollPinterestPins(token:string,boardId:string,cursor?:string|null):Promise<ProviderPollResult>{if(!boardId)throw new Error("asset_not_selected");const params=new URLSearchParams({page_size:"100"});if(cursor)params.set("bookmark",cursor);const raw=z.object({items:z.array(pin),bookmark:z.string().nullable().optional()}).parse(await api(`boards/${encodeURIComponent(boardId)}/pins?${params}`,token));return{items:raw.items.map(p=>({provider:"pinterest" as const,externalObjectId:p.id,objectType:"pin" as const,eventType:"published" as const,title:p.title??null,description:p.description??null,canonicalUrl:`https://www.pinterest.com/pin/${p.id}/`,thumbnailUrl:null,mediaUrls:[],sourcePublishedAt:p.created_at,scheduledStartAt:null,liveStatus:null,rawMetadata:{boardId:p.board_id,destinationLink:p.link??null,altText:p.alt_text??null,media:p.media??{},approvalRequired:true,automaticPublishing:false}})),cursor:raw.bookmark??null};}
