import { z } from "zod"; import type { ProviderIdentity, ProviderPollResult, ProviderTokenSet } from "@/lib/social-providers/types";
const tokenSchema=z.object({access_token:z.string().min(1),token_type:z.string(),expires_in:z.number().positive().optional(),refresh_token:z.string().optional(),scope:z.string().optional()});
const meSchema=z.object({id:z.string().min(1),display_name:z.string().nullable().optional(),external_urls:z.object({spotify:z.string().url()}).optional(),images:z.array(z.object({url:z.string().url()})).optional()}).passthrough();
const episodeSchema=z.object({id:z.string().min(1),name:z.string().min(1),release_date:z.string(),release_date_precision:z.enum(["day","month","year"]),external_urls:z.object({spotify:z.string().url()}),duration_ms:z.number().nonnegative().optional(),images:z.array(z.object({url:z.string().url()})).optional()}).passthrough();
function auth(){const id=process.env.SPOTIFY_CLIENT_ID,secret=process.env.SPOTIFY_CLIENT_SECRET;if(!id||!secret)throw new Error("credentials_missing");return `Basic ${Buffer.from(`${id}:${secret}`).toString("base64")}`;}
async function tokens(body:URLSearchParams){const response=await fetch("https://accounts.spotify.com/api/token",{method:"POST",headers:{authorization:auth(),"content-type":"application/x-www-form-urlencoded"},body,cache:"no-store"}),raw:unknown=await response.json();if(!response.ok)throw new Error(response.status===401?"authentication_revoked":"token_refresh_failed");return tokenSchema.parse(raw);}
const set=(x:z.infer<typeof tokenSchema>,fallback?:string):ProviderTokenSet=>({accessToken:x.access_token,refreshToken:x.refresh_token??fallback,expiresAt:x.expires_in?new Date(Date.now()+x.expires_in*1000).toISOString():null,grantedScopes:x.scope?.split(" ").filter(Boolean)??[],tokenType:x.token_type});
export async function exchangeSpotifyCode(code:string,verifier?:string){const redirect=process.env.SPOTIFY_REDIRECT_URI;if(!redirect)throw new Error("credentials_missing");const body=new URLSearchParams({code,redirect_uri:redirect,grant_type:"authorization_code"});if(verifier)body.set("code_verifier",verifier);return set(await tokens(body));}
export async function refreshSpotifyToken(refresh:string){return set(await tokens(new URLSearchParams({refresh_token:refresh,grant_type:"refresh_token"})),refresh);}
async function api(path:string,access:string){const response=await fetch(`https://api.spotify.com/v1/${path}`,{headers:{authorization:`Bearer ${access}`},cache:"no-store"}),raw:unknown=await response.json();if(!response.ok)throw new Error(response.status===401?"authentication_revoked":response.status===429?"rate_limited":"temporary_provider_failure");return raw;}
export async function fetchSpotifyIdentity(access:string):Promise<ProviderIdentity>{const me=meSchema.parse(await api("me",access));return{id:me.id,name:me.display_name??"Spotify account",url:me.external_urls?.spotify??"https://open.spotify.com/",metadata:{profileImageUrl:me.images?.[0]?.url??null,artistOwnershipEstablished:false,showOwnershipEstablished:false,emailStored:false}};}
function date(value:string,precision:"day"|"month"|"year"){const iso=precision==="day"?`${value}T00:00:00.000Z`:precision==="month"?`${value}-01T00:00:00.000Z`:`${value}-01-01T00:00:00.000Z`;return Number.isFinite(Date.parse(iso))?iso:null;}
export async function pollSpotifyShow(access:string,showId:string,cursor?:string|null):Promise<ProviderPollResult>{if(!showId)throw new Error("asset_not_selected");const query=new URLSearchParams({limit:"50"});if(cursor)query.set("offset",cursor);const raw=z.object({items:z.array(episodeSchema),next:z.string().url().nullable().optional(),offset:z.number(),limit:z.number()}).parse(await api(`shows/${encodeURIComponent(showId)}/episodes?${query}`,access));return{items:raw.items.flatMap(e=>{const published=date(e.release_date,e.release_date_precision);return published?[{provider:"spotify" as const,externalObjectId:e.id,objectType:"podcast_episode" as const,eventType:"published" as const,title:e.name,description:null,canonicalUrl:e.external_urls.spotify,thumbnailUrl:e.images?.[0]?.url??null,mediaUrls:[],sourcePublishedAt:published,scheduledStartAt:null,liveStatus:null,rawMetadata:{spotifyAttribution:true,durationMs:e.duration_ms??null,distributionDestination:true,requiresVerifiedFeedReconciliation:true}}]:[]}),cursor:raw.next?String(raw.offset+raw.limit):null};}
