import{createHmac,timingSafeEqual}from"node:crypto";import{z}from"zod";import type{ProviderIdentity,ProviderPollResult}from"@/lib/social-providers/types";import{canonicalExpansionThreeUrl}from"./provider-expansion-three";
const identitySchema=z.object({id:z.string().min(1),username:z.string().min(1),name:z.string().optional(),threads_profile_picture_url:z.string().url().optional(),threads_biography:z.string().optional()});
const postSchema=z.object({id:z.string().min(1),text:z.string().optional(),timestamp:z.string().datetime(),media_type:z.enum(["TEXT_POST","IMAGE","VIDEO","CAROUSEL_ALBUM","REPOST_FACADE"]).optional(),media_url:z.string().url().optional(),thumbnail_url:z.string().url().optional(),permalink:z.string().url(),is_quote_post:z.boolean().optional(),reposted_post:z.object({id:z.string()}).optional()});
const feedSchema=z.object({data:z.array(postSchema),paging:z.object({cursors:z.object({after:z.string().optional()}).optional()}).optional()});
function version(){const value=process.env.THREADS_GRAPH_API_VERSION??"v1.0";if(!/^v\d+\.\d+$/.test(value))throw new Error("invalid_threads_graph_version");return value;}
async function threads(path:string,token:string){const response=await fetch(`https://graph.threads.net/${version()}/${path}`,{headers:{authorization:`Bearer ${token}`,accept:"application/json"},cache:"no-store"}),raw:unknown=await response.json();if(!response.ok)throw new Error(response.status===401?"authentication_revoked":response.status===429?"rate_limited":"threads_provider_failure");return raw;}
export async function fetchThreadsIdentity(accessToken:string):Promise<ProviderIdentity>{const value=identitySchema.parse(await threads("me?fields=id,username,name,threads_profile_picture_url,threads_biography",accessToken)),url=canonicalExpansionThreeUrl("threads",`https://www.threads.net/@${value.username}`);if(!url)throw new Error("malformed_provider_response");return{id:value.id,name:value.name??value.username,url:url.toString(),metadata:{handle:value.username,profilePictureUrl:value.threads_profile_picture_url??null,biography:value.threads_biography??null,providerProduct:"threads"}};}
export async function pollThreadsPosts(accessToken:string,userId:string,cursor?:string|null):Promise<ProviderPollResult>{const suffix=cursor?`&after=${encodeURIComponent(cursor)}`:"",value=feedSchema.parse(await threads(`${encodeURIComponent(userId)}/threads?fields=id,text,timestamp,media_type,media_url,thumbnail_url,permalink,is_quote_post,reposted_post&limit=50${suffix}`,accessToken));return{items:value.data.map(post=>{const url=canonicalExpansionThreeUrl("threads",post.permalink);if(!url)throw new Error("malformed_provider_response");return{provider:"threads",externalObjectId:post.id,objectType:"post",eventType:"published",title:post.text?.slice(0,160)??null,description:post.text??null,canonicalUrl:url.toString(),thumbnailUrl:post.thumbnail_url??null,mediaUrls:post.media_url?[post.media_url]:[],sourcePublishedAt:post.timestamp,scheduledStartAt:null,liveStatus:null,rawMetadata:{mediaType:post.media_type??null,isQuotePost:post.is_quote_post??false,repostedPostId:post.reposted_post?.id??null}}}),cursor:value.paging?.cursors?.after??null};}
export function verifyThreadsSignature(body:string,header:string|null){const secret=process.env.THREADS_CLIENT_SECRET;if(!secret||!header?.startsWith("sha256="))return false;const expected=Buffer.from(createHmac("sha256",secret).update(body).digest("hex")),actual=Buffer.from(header.slice(7));return expected.length===actual.length&&timingSafeEqual(expected,actual);}
export const threadsWebhookSchema=z.object({object:z.literal("threads"),entry:z.array(z.object({id:z.string(),time:z.number(),changes:z.array(z.object({field:z.enum(["threads","permissions","account_update"]),value:z.record(z.string(),z.unknown()).optional()}))}))}).strict();
