import { z } from "zod";
import type { NormalizedSocialContent, ProviderIdentity, ProviderPollResult, ProviderTokenSet } from "@/lib/social-providers/types";
import { canonicalProviderUrl } from "./provider-expansion-two";

const tokenSchema=z.object({access_token:z.string().min(1),refresh_token:z.string().min(1).optional(),expires_in:z.number().positive(),refresh_expires_in:z.number().positive().optional(),open_id:z.string().min(1),scope:z.string(),token_type:z.string().default("Bearer")});
const userSchema=z.object({data:z.object({user:z.object({open_id:z.string().min(1),display_name:z.string().min(1),avatar_url:z.string().url().optional(),bio_description:z.string().optional(),profile_deep_link:z.string().url(),username:z.string().optional()})}),error:z.object({code:z.string()}).passthrough().optional()});
const videoSchema=z.object({id:z.string().min(1),create_time:z.number().int().positive(),share_url:z.string().url(),title:z.string().optional(),video_description:z.string().optional(),embed_link:z.string().url().optional(),cover_image_url:z.string().url().optional(),duration:z.number().nonnegative().optional(),height:z.number().positive().optional(),width:z.number().positive().optional()});
const videosSchema=z.object({data:z.object({videos:z.array(videoSchema),cursor:z.number().int().nonnegative().optional(),has_more:z.boolean().optional()}),error:z.object({code:z.string()}).passthrough().optional()});
async function tiktok(path:string,accessToken:string,init?:RequestInit){const response=await fetch(`https://open.tiktokapis.com/v2/${path}`,{...init,headers:{authorization:`Bearer ${accessToken}`,accept:"application/json",...init?.headers},cache:"no-store"});const value:unknown=await response.json();if(!response.ok)throw new Error(response.status===401?"authentication_revoked":response.status===429?"rate_limited":"tiktok_provider_failure");return value;}
export async function exchangeTikTokCode(code:string,codeVerifier?:string):Promise<ProviderTokenSet>{const key=process.env.TIKTOK_CLIENT_KEY,secret=process.env.TIKTOK_CLIENT_SECRET,redirect=process.env.TIKTOK_REDIRECT_URI;if(!key||!secret||!redirect)throw new Error("credentials_missing");const body=new URLSearchParams({client_key:key,client_secret:secret,code,grant_type:"authorization_code",redirect_uri:redirect});if(codeVerifier)body.set("code_verifier",codeVerifier);const response=await fetch("https://open.tiktokapis.com/v2/oauth/token/",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body,cache:"no-store"});const raw:unknown=await response.json();if(!response.ok)throw new Error("tiktok_token_exchange_failed");const value=tokenSchema.parse(raw);return{accessToken:value.access_token,refreshToken:value.refresh_token,expiresAt:new Date(Date.now()+value.expires_in*1000).toISOString(),grantedScopes:value.scope.split(",").map(scope=>scope.trim()).filter(Boolean),tokenType:value.token_type};}
export async function refreshTikTokToken(refreshToken:string):Promise<ProviderTokenSet>{const key=process.env.TIKTOK_CLIENT_KEY,secret=process.env.TIKTOK_CLIENT_SECRET;if(!key||!secret)throw new Error("credentials_missing");const response=await fetch("https://open.tiktokapis.com/v2/oauth/token/",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_key:key,client_secret:secret,grant_type:"refresh_token",refresh_token:refreshToken}),cache:"no-store"});const raw:unknown=await response.json();if(!response.ok)throw new Error("token_refresh_failed");const value=tokenSchema.parse(raw);return{accessToken:value.access_token,refreshToken:value.refresh_token??refreshToken,expiresAt:new Date(Date.now()+value.expires_in*1000).toISOString(),grantedScopes:value.scope.split(",").map(scope=>scope.trim()).filter(Boolean),tokenType:value.token_type};}
export async function revokeTikTokToken(accessToken:string){const key=process.env.TIKTOK_CLIENT_KEY,secret=process.env.TIKTOK_CLIENT_SECRET;if(!key||!secret)throw new Error("credentials_missing");const response=await fetch("https://open.tiktokapis.com/v2/oauth/revoke/",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_key:key,client_secret:secret,token:accessToken}),cache:"no-store"});if(!response.ok)throw new Error("authentication_revoked");}
export async function fetchTikTokIdentity(accessToken:string):Promise<ProviderIdentity>{const value=userSchema.parse(await tiktok("user/info/?fields=open_id,display_name,avatar_url,bio_description,profile_deep_link,username",accessToken)),user=value.data.user,url=canonicalProviderUrl("tiktok",user.profile_deep_link);if(!url)throw new Error("malformed_provider_response");return{id:user.open_id,name:user.display_name,url:url.toString(),metadata:{handle:user.username??null,avatarUrl:user.avatar_url??null,bioDescription:user.bio_description??null}};}
function normalizeVideo(value:unknown):NormalizedSocialContent{const item=videoSchema.parse(value),url=canonicalProviderUrl("tiktok",item.share_url);if(!url)throw new Error("malformed_provider_response");return{provider:"tiktok",externalObjectId:item.id,objectType:"short_video",eventType:"published",title:item.title??null,description:item.video_description??null,canonicalUrl:url.toString(),thumbnailUrl:item.cover_image_url??null,mediaUrls:[],sourcePublishedAt:new Date(item.create_time*1000).toISOString(),scheduledStartAt:null,liveStatus:null,rawMetadata:{embedUrl:item.embed_link??null,duration:item.duration??null,width:item.width??null,height:item.height??null}};}
export async function pollTikTokVideos(accessToken:string,cursor?:string|null):Promise<ProviderPollResult>{const parsedCursor=cursor&&/^\d+$/.test(cursor)?Number(cursor):undefined,value=videosSchema.parse(await tiktok("video/list/?fields=id,create_time,share_url,title,video_description,embed_link,cover_image_url,duration,height,width",accessToken,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({max_count:20,...(parsedCursor===undefined?{}:{cursor:parsedCursor})})}));return{items:value.data.videos.map(normalizeVideo),cursor:value.data.has_more&&value.data.cursor!==undefined?String(value.data.cursor):null};}
export{normalizeVideo as normalizeTikTokVideo};
