import "server-only";
import {z} from "zod";
import {createTraceId} from "@/lib/debug";
import {identity} from "@/lib/social-providers/base-oauth";
import {SocialProviderError} from "@/lib/social-providers/errors";
import type {ProviderIdentity,ProviderTokenSet} from "@/lib/social-providers/types";

const tokenSchema=z.object({access_token:z.string().min(1),refresh_token:z.string().min(1),expires_in:z.number().int().positive(),scope:z.union([z.array(z.string()),z.string()]).optional(),token_type:z.string().min(1)});
const optionalValidationString=z.string().nullable().optional().catch(undefined);
const validationSchema=z.object({client_id:z.string().min(1),user_id:z.string().regex(/^\d+$/),login:optionalValidationString,scopes:z.array(z.string()).optional().catch(undefined),expires_in:z.number().int().nonnegative().optional().catch(undefined)}).passthrough();
const usersSchema=z.object({data:z.array(z.object({id:z.string().min(1),login:z.string().min(1),display_name:z.string().min(1),type:z.string(),broadcaster_type:z.string(),description:z.string(),profile_image_url:z.string(),offline_image_url:z.string(),created_at:z.string()})).min(1)});

function configuration(){const clientId=process.env.TWITCH_CLIENT_ID,clientSecret=process.env.TWITCH_CLIENT_SECRET,redirectUri=process.env.TWITCH_REDIRECT_URI;if(!clientId||!clientSecret||!redirectUri)throw new SocialProviderError("provider_not_configured","twitch","Twitch credentials are unavailable.");return{clientId,clientSecret,redirectUri};}
function normalizeScopes(value:string[]|string|undefined){return Array.isArray(value)?value:typeof value==="string"?value.split(/\s+/).filter(Boolean):[];}
function normalizeToken(value:unknown):ProviderTokenSet{const parsed=tokenSchema.safeParse(value);if(!parsed.success)throw new SocialProviderError("malformed_provider_object","twitch","Twitch returned an incomplete token response.");const grantedScopes=normalizeScopes(parsed.data.scope);return{accessToken:parsed.data.access_token,refreshToken:parsed.data.refresh_token,expiresAt:new Date(Date.now()+parsed.data.expires_in*1000).toISOString(),scopes:grantedScopes,grantedScopes,tokenType:parsed.data.token_type};}
async function tokenRequest(body:URLSearchParams){const response=await fetch("https://id.twitch.tv/oauth2/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body,cache:"no-store"}),value=await response.json().catch(()=>({}));if(!response.ok)throw new SocialProviderError(response.status===400?"invalid_grant":response.status===429?"rate_limited":"transient","twitch","Twitch token request failed.",Number(response.headers.get("retry-after")??0)||undefined);return normalizeToken(value);}

export async function exchangeTwitchCode(code:string){const{clientId,clientSecret,redirectUri}=configuration();return tokenRequest(new URLSearchParams({client_id:clientId,client_secret:clientSecret,code,grant_type:"authorization_code",redirect_uri:redirectUri}));}
export async function refreshTwitchToken(refreshToken:string){const{clientId,clientSecret}=configuration();return tokenRequest(new URLSearchParams({client_id:clientId,client_secret:clientSecret,grant_type:"refresh_token",refresh_token:refreshToken}));}
function wireType(value:unknown){return Array.isArray(value)?"array":value===null?"null":typeof value;}
function logValidationFailure(raw:unknown,response:Response,validationCategory:string){
  const object=raw&&typeof raw==="object"&&!Array.isArray(raw)?raw as Record<string,unknown>:null,field=(key:string)=>({present:Boolean(object&&Object.prototype.hasOwnProperty.call(object,key)),type:object?wireType(object[key]):"undefined"});
  console.warn("twitch_oauth_validation",{traceId:createTraceId("twitch"),provider:"twitch",validationCategory,httpStatus:response.status,responseKeys:object?Object.keys(object).sort():[],fields:Object.fromEntries(["client_id","user_id","login","scopes","expires_in"].map(key=>[key,field(key)]))});
}
export async function validateTwitchToken(accessToken:string){const response=await fetch("https://id.twitch.tv/oauth2/validate",{headers:{Authorization:`OAuth ${accessToken}`},cache:"no-store"});if(response.status===401)return null;if(!response.ok)throw new SocialProviderError(response.status===429?"rate_limited":"transient","twitch","Twitch token validation failed.",Number(response.headers.get("retry-after")??0)||undefined);const raw=await response.json().catch(()=>({})),parsed=validationSchema.safeParse(raw);if(!parsed.success){logValidationFailure(raw,response,"invalid_stable_identity");throw new SocialProviderError("malformed_provider_object","twitch","Twitch token validation response was incomplete.");}if(parsed.data.client_id!==process.env.TWITCH_CLIENT_ID)throw new SocialProviderError("access_revoked","twitch","Twitch token belongs to a different application.");return parsed.data;}
export async function fetchTwitchIdentity(accessToken:string):Promise<ProviderIdentity>{const validation=await validateTwitchToken(accessToken);if(!validation)throw new SocialProviderError("access_revoked","twitch","Twitch authorization is invalid.");const response=await fetch("https://api.twitch.tv/helix/users",{headers:{Authorization:`Bearer ${accessToken}`,"Client-Id":process.env.TWITCH_CLIENT_ID??""},cache:"no-store"}),value=await response.json().catch(()=>({}));if(!response.ok)throw new SocialProviderError(response.status===401?"access_revoked":response.status===429?"rate_limited":"transient","twitch","Twitch user request failed.",Number(response.headers.get("retry-after")??0)||undefined);const parsed=usersSchema.safeParse(value);if(!parsed.success)throw new SocialProviderError("malformed_provider_object","twitch","Twitch user response was incomplete.");const user=parsed.data.data[0];if(user.id!==validation.user_id)throw new SocialProviderError("malformed_provider_object","twitch","Twitch identity did not match the authorization.");return identity(user.id,user.display_name,`https://www.twitch.tv/${user.login}`,{username:user.login,login:user.login,avatarUrl:user.profile_image_url||null,broadcasterType:user.broadcaster_type,description:user.description,createdAt:user.created_at});}
export async function revokeTwitchToken(accessToken:string){const clientId=process.env.TWITCH_CLIENT_ID;if(!clientId)throw new SocialProviderError("provider_not_configured","twitch","Twitch client ID is unavailable.");const response=await fetch("https://id.twitch.tv/oauth2/revoke",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:clientId,token:accessToken}),cache:"no-store"});if(!response.ok&&response.status!==400)throw new SocialProviderError(response.status===429?"rate_limited":"transient","twitch","Twitch revocation failed.");}
