import{z}from"zod";import type{ProviderIdentity,ProviderPollResult,ProviderTokenSet}from"@/lib/social-providers/types";import{canonicalExpansionThreeUrl}from"./provider-expansion-three";
const tokenSchema=z.object({token_type:z.string(),expires_in:z.number().positive().optional(),access_token:z.string().min(1),scope:z.string().optional(),refresh_token:z.string().optional()});
const userSchema=z.object({data:z.object({id:z.string().regex(/^\d+$/),name:z.string().min(1),username:z.string().min(1),description:z.string().optional(),profile_image_url:z.string().url().optional(),url:z.string().url().optional(),protected:z.boolean().optional()})});
const postSchema=z.object({id:z.string().regex(/^\d+$/),text:z.string(),created_at:z.string().datetime(),author_id:z.string().regex(/^\d+$/),conversation_id:z.string().optional(),referenced_tweets:z.array(z.object({type:z.enum(["retweeted","quoted","replied_to"]),id:z.string()})).optional(),edit_history_tweet_ids:z.array(z.string()).optional()});
const timelineSchema=z.object({data:z.array(postSchema).optional(),meta:z.object({next_token:z.string().optional(),result_count:z.number().optional()}).optional()});
function clientAuth(){const id=process.env.X_CLIENT_ID,secret=process.env.X_CLIENT_SECRET;if(!id||!secret)throw new Error("credentials_missing");return{header:`Basic ${Buffer.from(`${id}:${secret}`).toString("base64")}`,id};}
async function token(body:URLSearchParams){const{header}=clientAuth(),response=await fetch("https://api.x.com/2/oauth2/token",{method:"POST",headers:{authorization:header,"content-type":"application/x-www-form-urlencoded"},body,cache:"no-store"}),raw:unknown=await response.json();if(!response.ok)throw new Error(response.status===429?"rate_limited":"x_token_failure");return tokenSchema.parse(raw);}
const tokenSet=(value:z.infer<typeof tokenSchema>,fallback?:string):ProviderTokenSet=>({accessToken:value.access_token,refreshToken:value.refresh_token??fallback,expiresAt:value.expires_in?new Date(Date.now()+value.expires_in*1000).toISOString():null,grantedScopes:value.scope?.split(" ").filter(Boolean)??[],tokenType:value.token_type});
export async function exchangeXCode(code:string,verifier?:string){const{ id}=clientAuth(),redirect=process.env.X_REDIRECT_URI;if(!redirect||!verifier)throw new Error("pkce_required");return tokenSet(await token(new URLSearchParams({code,grant_type:"authorization_code",client_id:id,redirect_uri:redirect,code_verifier:verifier})));}
export async function refreshXToken(refreshToken:string){const{id}=clientAuth();return tokenSet(await token(new URLSearchParams({refresh_token:refreshToken,grant_type:"refresh_token",client_id:id})),refreshToken);}
export async function revokeXToken(accessToken:string){const{header,id}=clientAuth(),response=await fetch("https://api.x.com/2/oauth2/revoke",{method:"POST",headers:{authorization:header,"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({token:accessToken,client_id:id}),cache:"no-store"});if(!response.ok)throw new Error("authentication_revoked");}
async function xJson(path:string,accessToken:string){const response=await fetch(`https://api.x.com/2/${path}`,{headers:{authorization:`Bearer ${accessToken}`,accept:"application/json"},cache:"no-store"}),raw:unknown=await response.json();if(!response.ok)throw new Error(response.status===401?"authentication_revoked":response.status===429?"rate_limited":"x_provider_failure");return raw;}
export async function fetchXIdentity(accessToken:string):Promise<ProviderIdentity>{const value=userSchema.parse(await xJson("users/me?user.fields=id,name,username,description,profile_image_url,url,protected",accessToken)),user=value.data,url=canonicalExpansionThreeUrl("x",`https://x.com/${user.username}`);if(!url)throw new Error("malformed_provider_response");return{id:user.id,name:user.name,url:url.toString(),metadata:{handle:user.username,description:user.description??null,profileImageUrl:user.profile_image_url??null,websiteUrl:user.url??null,protected:user.protected??false}};}
export async function pollXPosts(accessToken:string,userId:string,username:string,cursor?:string|null):Promise<ProviderPollResult>{if(!/^\d+$/.test(userId))throw new Error("stable_identity_required");const params=new URLSearchParams({"tweet.fields":"id,text,created_at,author_id,conversation_id,referenced_tweets,edit_history_tweet_ids",max_results:"100",exclude:"replies,retweets"});if(cursor)params.set("pagination_token",cursor);const value=timelineSchema.parse(await xJson(`users/${userId}/tweets?${params}`,accessToken));return{items:(value.data??[]).map(post=>({provider:"x",externalObjectId:post.id,objectType:"post",eventType:"published",title:post.text.slice(0,160),description:post.text,canonicalUrl:`https://x.com/${encodeURIComponent(username)}/status/${post.id}`,thumbnailUrl:null,mediaUrls:[],sourcePublishedAt:post.created_at,scheduledStartAt:null,liveStatus:null,rawMetadata:{authorId:post.author_id,conversationId:post.conversation_id??null,referencedPostTypes:post.referenced_tweets?.map(item=>item.type)??[],editHistoryIds:post.edit_history_tweet_ids??[]}})),cursor:value.meta?.next_token??null};}
