import Link from "next/link";
import { ArrowRight, Bell, CalendarDays, Check, CircleUserRound, KeyRound, LifeBuoy, Link2, Mail, Settings2, ShieldCheck } from "lucide-react";
import { requireCreator, requireViewer } from "@/lib/dal";
import { UnavailableState } from "@/components/product-state";
import{getCreatorEntitlements}from"@/lib/provider-entitlements";import{logPageQueryFailure}from"@/lib/data-availability";

const sectionLink = "settings-quick-card group";

export default async function SettingsPage() {
  const [user,creator]=await Promise.all([requireViewer(),requireCreator()]);
  const entitlementsResult=await getCreatorEntitlements(creator.id,user).then(data=>({data,error:null})).catch(error=>({data:null,error}));
  logPageQueryFailure("settings","entitlements",entitlementsResult.error);
  const entitlements=entitlementsResult.data;
  const sections = [
    [CircleUserRound,"Profile","Manage your canonical creator name, biography, and permanent URL.","/dashboard/settings/profile","profile"],
    [KeyRound,"Account & Security","Review sign-in details, authenticator protection, sessions, and deletion.","/dashboard/settings/account","security"],
    [Link2,"Connected Platforms","Review OAuth and manual connections, health, permissions, and available actions.","/dashboard/settings/connected-accounts","platforms"],
    [LifeBuoy,"Recovery Pass","Review status, sharing, and creator-side Recovery Pass configuration.","/dashboard/settings/recovery-pass","recovery"],
  ] as const;
  const accountRows=[[CircleUserRound,"Username",`@${creator.public_slug ?? "Unavailable"}`,"violet"],[Mail,"Email",user.email ?? "Unavailable","blue"],[CalendarDays,"Member since",new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(new Date(creator.created_at)),"indigo"],[ShieldCheck,"Recovery Pass",creator.recovery_pass_enabled ? "Active" : "Action required",creator.recovery_pass_enabled ? "emerald" : "amber"]] as const;
  return <><header className="settings-hero"><div><p className="eyebrow"><Settings2 aria-hidden size={13}/>Workspace</p><h1>Settings</h1><p>Manage your creator identity, account protection, connected platforms, and Recovery Pass.</p></div><div className="settings-hero-orbit" aria-hidden><Settings2/><ShieldCheck/><Link2/></div></header><section className="settings-account-card" aria-labelledby="creator-account-heading"><div className="settings-card-heading"><span><CircleUserRound aria-hidden/></span><div><p>Account overview</p><h2 id="creator-account-heading">Creator account</h2></div><em><Check aria-hidden/> Active</em></div><dl className="settings-account-rows">{accountRows.map(([Icon,label,value,tone])=><div key={label}><span data-tone={tone}><Icon aria-hidden/></span><div><dt>{label}</dt><dd className="break-all">{label==="Recovery Pass"?<em data-state={creator.recovery_pass_enabled?"active":"attention"}>{creator.recovery_pass_enabled&&<Check aria-hidden/>}{value}</em>:value}</dd></div></div>)}</dl></section>
    <div className="settings-quick-grid">{sections.map(([Icon,title,copy,href,tone])=><Link key={href} href={href} data-tone={tone} className={sectionLink}><div><span><Icon aria-hidden size={20}/></span><h2>{title}</h2><p>{copy}</p></div><ArrowRight aria-hidden className="settings-card-arrow" size={17}/></Link>)}</div>
    {!entitlements?<UnavailableState className="mt-10" title="Plan unavailable" description="Your current plan could not be established."/>:<section className="settings-billing-card" aria-labelledby="plan-summary-heading"><div className="settings-billing-heading"><span><ShieldCheck aria-hidden/></span><div><p className="eyebrow">Plan</p><h2 id="plan-summary-heading">{entitlements.plan==="pro"?"Pro":"Free"}</h2></div></div><p>Review plan benefits, billing periods, and subscription controls in one focused workspace.</p><div className="settings-billing-actions"><Link className="button button-secondary" href="/dashboard/settings/plans">Manage plan <ArrowRight aria-hidden size={15}/></Link></div></section>}<section className="settings-availability" aria-labelledby="availability-heading"><div><p className="eyebrow">Availability</p><h2 id="availability-heading">Feature availability</h2></div><div><UnavailableState compact icon={Bell} title="Creator notifications are not available yet" description="Recovery Pass alert choices already belong to each fan and appear in Audience reporting."/></div></section>
    <nav aria-label="Settings policies and support" className="mt-10 flex flex-wrap gap-x-5 gap-y-3 border-t border-white/[.07] pt-6 text-sm text-zinc-500"><Link className="hover:text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-violet-400" href="/privacy">Privacy</Link><Link className="hover:text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-violet-400" href="/terms">Terms</Link><Link className="hover:text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-violet-400" href="/refund-policy">Refund Policy</Link><Link className="hover:text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-violet-400" href="/cookie-policy">Cookie Policy</Link><Link className="hover:text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-violet-400" href="/data-deletion">Data deletion</Link><Link className="hover:text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-violet-400" href="/google-api-disclosure">Google API Disclosure</Link><Link className="hover:text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-violet-400" href="/contact">Support</Link></nav>
  </>;
}
