import"server-only";import{randomUUID}from"node:crypto";import{createAdminClient}from"@/lib/supabase/admin";import{decryptSocialSecret}from"@/lib/social-secrets";
import{getSocialProvider}from"@/lib/social-providers/registry";import type{SocialProvider}from"@/lib/social-providers/types";
export async function revalidateEmergencyAccounts(limit=20){const db=createAdminClient();if(!db)throw new Error("worker_not_configured");const lease=randomUUID();
 const{data:rows,error}=await db.rpc("claim_emergency_verifications",{p_limit:Math.max(1,Math.min(limit,100)),p_lease_owner:lease});if(error)throw error;const summary={claimed:rows?.length??0,healthy:0,revoked:0,failed:0};
 for(const verification of rows??[]){try{if(!verification.connected_account_id)throw new Error("connected_account_required");const{data:connection}=await db.from("connected_accounts").select("*").eq("id",verification.connected_account_id).single();
  const{data:secret}=await db.from("platform_connection_secrets").select("access_token_ciphertext,refresh_token_ciphertext").eq("platform_connection_id",verification.connected_account_id).single();
  if(!connection||!secret||connection.connection_health==="revoked"||connection.connection_health==="expired"){await db.rpc("apply_emergency_revalidation",{p_verification_id:verification.id,p_external_id:"",p_name:"",p_url:"",p_outcome:"revoked",p_error:"provider_grant_unavailable"});summary.revoked++;continue;}
  const adapter=getSocialProvider(verification.provider as SocialProvider),fetcher=adapter.fetchEmergencyAccountIdentity??adapter.fetchIdentity;if(!fetcher)throw new Error("provider_verification_unavailable");
  const providerMetadata=connection.provider_metadata;const identity=await fetcher({accessToken:decryptSocialSecret(secret.access_token_ciphertext),refreshToken:secret.refresh_token_ciphertext?decryptSocialSecret(secret.refresh_token_ciphertext):undefined,metadata:providerMetadata&&typeof providerMetadata==="object"&&!Array.isArray(providerMetadata)?providerMetadata:undefined});
  const outcome=identity.id===verification.external_account_id?"healthy":"changed";await db.rpc("apply_emergency_revalidation",{p_verification_id:verification.id,p_external_id:identity.id,p_name:identity.name,p_url:identity.url,p_outcome:outcome,p_error:outcome==="changed"?"stable_identity_changed":undefined});if(outcome==="healthy")summary.healthy++;else summary.revoked++;
 }catch{summary.failed++;await db.rpc("apply_emergency_revalidation",{p_verification_id:verification.id,p_external_id:verification.external_account_id??"",p_name:verification.external_account_name??"",p_url:verification.canonical_profile_url??"",p_outcome:"failed",p_error:"provider_revalidation_failed"});}}
 return summary;}
