import type { Metadata } from "next";
import Link from "next/link";
import { Logo } from "@/components/logo";
import { PublicFooter } from "@/components/public-footer";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Learn how AudienceOwn collects, uses, protects, and gives you control over personal information, including Google and YouTube data.",
  alternates: { canonical: "/privacy" },
  openGraph: {
    title: "Privacy Policy · AudienceOwn",
    description: "How AudienceOwn handles creator, fan, Recovery Pass, OAuth, and platform data.",
    url: "/privacy",
    siteName: "AudienceOwn",
    type: "website",
  },
};

function Section({ id, title, children }: { id: string; title: string; children: React.ReactNode }) {
  return <section id={id} aria-labelledby={`${id}-heading`} className="scroll-mt-8 border-t border-white/[.08] pt-9">
    <h2 id={`${id}-heading`} className="text-2xl font-semibold tracking-[-.025em] text-white sm:text-[1.7rem]">{title}</h2>
    <div className="mt-4 space-y-4 text-[15px] leading-7 text-zinc-300 sm:text-base sm:leading-8">{children}</div>
  </section>;
}

function Subsection({ title, children }: { title: string; children: React.ReactNode }) {
  return <div><h3 className="text-base font-semibold text-zinc-100 sm:text-lg">{title}</h3><div className="mt-2 space-y-3">{children}</div></div>;
}

export default function PrivacyPage() {
  return <main className="min-h-screen bg-[#07070b] text-white">
    <header className="border-b border-white/[.07]"><div className="mx-auto flex h-20 max-w-[1180px] items-center justify-between px-5 lg:px-8"><Logo/><Link href="/" className="text-sm text-zinc-400 transition-colors hover:text-white">Back to AudienceOwn</Link></div></header>
    <div className="mx-auto max-w-[1180px] px-5 py-12 lg:px-8 lg:py-20">
      <article className="max-w-[720px]">
        <header><h1 className="text-4xl font-semibold tracking-[-.045em] sm:text-5xl">Privacy Policy</h1><p className="mt-4 text-sm font-medium text-violet-300">Last updated: August 15, 2026</p><p className="mt-6 text-lg leading-8 text-zinc-300">AudienceOwn helps creators protect their audience, verify their presence, and maintain trusted recovery destinations across platforms. This Privacy Policy explains what information we collect, why we collect it, how we use it, when we share it, how long we retain it, and the choices available to you.</p><p className="mt-4 leading-7 text-zinc-400">We are committed to protecting personal information and building privacy controls into the product. We describe current practices here and identify optional capabilities that apply only when you choose to use them.</p></header>

        <div className="mt-12 space-y-10">
          <Section id="scope" title="Who this policy applies to"><p>This policy applies to creators who use AudienceOwn, fans who use Recovery Pass or subscribe to creator communications, visitors to public creator profiles and AudienceOwn websites, and people who contact our support team. It also applies to customers using paid plans, and will apply to enterprise workspaces when those offerings become available.</p><p>“AudienceOwn,” “we,” and “our” refer to the operator of the AudienceOwn service. The operator’s legal entity details will appear here once they are publicly established. Until then, privacy questions can be sent to <a className="text-violet-300 hover:text-violet-200" href="mailto:contact@audienceown.com">contact@audienceown.com</a>.</p></Section>

          <Section id="collection" title="Information we collect">
            <Subsection title="Information you provide"><p>We collect information you submit when creating or managing an account, such as your name, email address, profile details, creator biography, public handle, images, account URLs, recovery destinations, communication settings, support requests, and content prepared for your AudienceOwn page or audience updates.</p></Subsection>
            <Subsection title="Creator account and verification information"><p>For creator accounts, we process official and backup account details, manual and OAuth connection status, identity evidence and verification results, authenticity monitoring observations, recovery plans, drill results, alerts, and security settings. Identity verification records may include the provider account identifiers and evidence needed to establish that an account or domain belongs to the creator. We do not request more verification information than the relevant feature needs.</p></Subsection>
            <Subsection title="Information collected automatically"><p>When you use AudienceOwn, we receive technical information such as IP address, browser and device type, operating system, requested pages, referring page, approximate time of access, session events, and diagnostic or security events. We use this information to deliver the service, prevent abuse, investigate errors, and understand product performance.</p></Subsection>
            <Subsection title="Analytics and product activity"><p>We record interactions with the dashboard and product features, including platform synchronization status, Audience Protection Score inputs, aggregate protected fan counts, recovery coverage, delivery outcomes, automation activity, and feature configuration. We use operational and aggregate analytics to show creators how their recovery setup is working and to improve AudienceOwn.</p></Subsection>
            <Subsection title="Billing information"><p>If you purchase a paid subscription, our payment provider processes payment card and billing details. AudienceOwn may receive transaction identifiers, plan information, billing status, country, tax information, and limited payment method details, but does not need to store full payment card numbers.</p></Subsection>
          </Section>

          <Section id="recovery-pass" title="Recovery Pass and fan information"><p>Recovery Pass lets a fan opt in to a creator’s recovery network and choose how they want to hear from that creator. We process the fan’s contact information, consent record, notification preferences, selected recovery destinations, subscription status, and the history needed to honor preference changes and opt-outs.</p><p>A creator may use this information to send creator-initiated updates or emergency notifications through AudienceOwn. Creators receive aggregate insights wherever possible, such as protected fan counts and recovery destination coverage. Joining Recovery Pass does not automatically give a creator unrestricted access to a fan’s contact information. Sensitive contact values are protected by access controls and are disclosed or used only as needed to provide the selected communication feature.</p><p>Fans can update their Recovery Pass preferences or opt out using the preference and unsubscribe links provided with communications. We retain suppression information where needed to respect an opt-out and prevent unwanted messages.</p></Section>

          <Section id="platforms" title="Connected platforms and OAuth"><p>You can add a platform manually by submitting a public URL or, when supported, connect it through OAuth. A manual connection stores the information you enter and does not grant AudienceOwn access to the platform account. When you choose to connect a supported platform through OAuth, we receive the account identifiers, profile information, permissions, authorization status, and public or authorized data needed for the features you approve.</p><p>Supported connections may include services such as Instagram, TikTok, Facebook, X, LinkedIn, Spotify, Discord, Pinterest, Snapchat, Twitch, Bluesky, Kick, or Patreon as those integrations become available. The authorization screen for each provider identifies the permissions requested. We do not treat a future integration as active until it is offered in the product and you choose to connect it.</p><p>OAuth credentials are encrypted and stored server-side. Raw provider tokens are not sent to the browser. You can disconnect a provider from Connected Accounts, and may also revoke access through the provider’s own account settings.</p></Section>

          <Section id="google" title="Google and YouTube data">
            <Subsection title="Separate Google flows"><p>AudienceOwn uses separate flows for Google sign-in and YouTube authorization. “Continue with Google” authenticates you using basic Google identity information, such as your name, email address, profile image, and stable account identifier. It does not by itself connect your YouTube channel. “Connect YouTube” separately asks you to authorize read-only YouTube access.</p></Subsection>
            <Subsection title="What YouTube access allows"><p>AudienceOwn requests the <code className="rounded bg-white/[.06] px-1.5 py-0.5 text-sm text-zinc-200">youtube.readonly</code> scope to identify the channel you select, display public channel information, synchronize subscriber metrics, monitor public uploads, and show connection health in your audience protection dashboard. Depending on what is available for the channel, this may include the channel ID, title, handle, public URL, avatar or thumbnail, subscriber count, hidden subscriber count status, public upload metadata, granted scope, token expiration, and synchronization status.</p><p>This permission does not allow AudienceOwn to upload, edit, or delete videos, manage comments, change channel settings, or mutate playlists. We do not request your Google password, private messages, contacts, watch history, or search history. We do not request access to private videos through the current integration.</p></Subsection>
            <Subsection title="Google API Limited Use"><p>AudienceOwn’s use and transfer of information received from Google APIs will adhere to the <a className="text-violet-300 hover:text-violet-200" href="https://developers.google.com/terms/api-services-user-data-policy" target="_blank" rel="noreferrer">Google API Services User Data Policy</a>, including its Limited Use requirements. We use Google user data only to provide and improve the user-facing features you request, maintain security, comply with law, and support the permitted operational purposes described by that policy. We do not use Google user data for advertising.</p></Subsection>
            <Subsection title="Tokens, disconnection, and deletion"><p>Google access and refresh tokens are encrypted at rest, kept on the server, and limited to authorized services. When you disconnect YouTube, AudienceOwn disables further provider access, asks Google to revoke the authorization, stops synchronization and polling, and deletes encrypted credentials and stored authorized YouTube data. If Google is temporarily unavailable, provider access remains disabled while revocation is retried safely.</p><p>You may choose to retain a creator-submitted YouTube recovery URL after disconnecting. That URL is labeled as manually added and no longer carries OAuth data. You can also remove the YouTube account entirely, delete stored YouTube data, or delete your AudienceOwn account. These actions do not delete videos, channels, or other content hosted by YouTube. You can independently review or revoke Google access through <a className="text-violet-300 hover:text-violet-200" href="https://security.google.com/settings/security/permissions" target="_blank" rel="noreferrer">Google’s permissions page</a>.</p></Subsection>
          </Section>

          <Section id="emergency" title="Recovery and emergency features"><p>Creators can prepare emergency plans, verify replacement accounts, run recovery drills, monitor authenticity signals, and initiate recovery alerts. These features process the plan configuration, authorized participants, recovery destinations, approval or verification events, delivery choices, and notification history needed to coordinate and document the response.</p><p>When a creator starts an eligible notification, AudienceOwn and its delivery providers process the selected recipients, message, channel, delivery attempts, status callbacks, failures, and retries. Automation runs only under the creator’s configured rules and applicable safeguards. We use opt-out and suppression records to avoid sending communications a recipient no longer wants.</p></Section>

          <Section id="cookies" title="Cookies and browser storage"><p>AudienceOwn uses authentication and session cookies to keep you signed in, security cookies to protect login and OAuth flows, and preference cookies or browser storage to remember selected settings and interface state. Local storage may hold non-sensitive browser preferences or public feature state. We do not store raw provider access tokens in browser storage.</p><p>If we introduce optional analytics or marketing cookies, we will describe them and provide consent controls where required. You can restrict cookies through your browser, although blocking essential authentication or security cookies may prevent parts of AudienceOwn from working.</p></Section>

          <Section id="uses" title="How we use information"><p>We use information to provide creator accounts, public profiles, the dashboard, connected platforms, Audience Protection Score, Recovery Pass, protected fan insights, recovery destinations, identity verification, platform synchronization, analytics, automation, recovery drills, authenticity monitoring, and emergency communications.</p><p>We also use information to authenticate users, maintain account and connection security, detect fraud and abuse, troubleshoot errors, respond to support requests, deliver communications, measure service reliability, improve product design, enforce our terms, and comply with legal obligations. Where required by law, we rely on consent for particular communications or optional processing, and you may withdraw that consent prospectively.</p></Section>

          <Section id="ai" title="Artificial intelligence features"><p>AudienceOwn may offer optional AI assistance for tasks such as drafting or refining creator content. When you choose an AI feature, we process the prompt, relevant creator settings, source content, and generated result to provide that feature. Model providers may process this information on our behalf under service terms and access controls.</p><p>AI assistance does not publish content or send messages unless the creator separately reviews or enables the relevant workflow. Availability, provider, and data handling may vary by feature. We will present additional notices when a future AI feature needs information beyond what this policy describes.</p></Section>

          <Section id="sharing" title="How we share information"><p>We share information only as needed to operate AudienceOwn, follow your instructions, protect the service, or meet legal obligations. We do not sell personal information or Google user data.</p><p>Service providers may process information for cloud hosting, authentication, databases, storage, email, SMS, WhatsApp or browser notifications, payment processing, analytics, error monitoring, customer support, security, and optional AI features. Current infrastructure includes Supabase for authentication and data services. Other providers receive only the information needed for their role and are subject to contractual or technical restrictions appropriate to the service.</p><p>We may disclose information when we reasonably believe it is required by law, legal process, or a valid government request, or when necessary to protect users, the public, AudienceOwn, or our rights. We review requests and object when appropriate. If AudienceOwn is involved in a merger, financing, acquisition, reorganization, or sale of assets, information may transfer as part of that transaction, subject to this policy and applicable law.</p></Section>

          <Section id="transfers" title="International data transfers"><p>AudienceOwn and its service providers may process information in countries other than where you live. Privacy laws may differ across those locations. Where applicable, we use recognized safeguards for international transfers, such as adequacy decisions, contractual protections, and provider security commitments.</p></Section>

          <Section id="retention" title="Data retention"><p>We retain information for as long as needed to provide the service, maintain security and continuity, honor communication preferences, meet legal obligations, and resolve disputes. Retention depends on the information and feature rather than a single period. Account and creator content generally remains while the account is active. Security, audit, billing, and suppression records may remain longer where necessary for legitimate operational or legal purposes.</p><p>Platform data is refreshed according to the connection’s synchronization schedule or removed when it is no longer needed. For YouTube, current metrics and public upload data are refreshed through the configured synchronization process. After disconnection, revocation, or a verified deletion request, AudienceOwn stops API access and deletes or invalidates tokens, granted scopes, authorization state, subscriber snapshots, authorized channel metadata, polling checkpoints, provider health, and cached projections as required. Encrypted credentials may be retained briefly only when a provider revocation is pending retry, during which further access remains disabled.</p><p>Recovery Pass preferences and active contact records remain while the fan participates in the creator’s recovery network. Opt-out and suppression records may be retained to enforce the fan’s choice. Aggregate analytics may remain after identifiers are removed or when the data no longer identifies an individual.</p><p>Account deletion first cleans up connected provider authorization and creator-owned application data, then deletes the authentication account. If cleanup cannot complete, AudienceOwn reports a retryable state rather than silently recording success.</p></Section>

          <Section id="security" title="Security"><p>We use administrative, technical, and organizational safeguards designed to protect information. These include encryption for OAuth tokens and sensitive contact values, server-side credential processing, role-based access, least-privilege service boundaries, database row-level security, restricted administrative operations, security monitoring, and audit-oriented event records.</p><p>We avoid placing provider tokens in application logs and review systems for unintended exposure. We investigate suspected incidents, contain affected access, preserve appropriate evidence, and notify affected people or authorities when required. No online service can eliminate every risk, so we regularly review and improve these protections.</p></Section>

          <Section id="choices" title="Your choices and rights"><p>Depending on where you live, you may have rights to access, correct, delete, restrict, object to, or export personal information, and to withdraw consent. You can update much of your creator information and communication preferences directly in AudienceOwn. Fans can use Recovery Pass preference and unsubscribe links to change destinations, notification choices, or participation.</p><p>Creators can disconnect supported providers, remove manual connections, request deletion of provider-derived data, export available audience information, and delete their AudienceOwn account. Disconnecting AudienceOwn does not remove content stored by the provider. For Google, you can also revoke access from Google’s permissions page.</p><p>To make a privacy request, email <a className="text-violet-300 hover:text-violet-200" href="mailto:contact@audienceown.com">contact@audienceown.com</a>. We may need to verify your identity before fulfilling a request. Some rights and exceptions depend on applicable law, and certain records may be retained when legally required or necessary to protect the service and its users.</p></Section>

          <Section id="third-parties" title="Third-party services"><p>AudienceOwn includes connections to social platforms, payment services, messaging providers, and external creator links. Those services operate under their own terms and privacy policies. Their privacy practices are not controlled by AudienceOwn. Review the relevant provider’s policy before connecting an account, completing a payment, or following an external link.</p></Section>

          <Section id="children" title="Children"><p>AudienceOwn is not directed to children under 13, and we do not knowingly collect personal information from children under 13. Higher minimum ages may apply in some countries. If you believe a child has provided personal information inappropriately, contact us so we can investigate and take appropriate action.</p></Section>

          <Section id="changes" title="Changes to this policy"><p>We may update this policy as AudienceOwn evolves, providers change their requirements, or laws change. We will post the revised policy here and update the date at the top. If a change materially affects how we use personal information, we will provide additional notice when appropriate.</p></Section>

          <Section id="contact" title="Contact us"><p>For privacy questions, privacy requests, legal inquiries, or other general questions, email <a className="text-violet-300 hover:text-violet-200" href="mailto:contact@audienceown.com">contact@audienceown.com</a>.</p><p>For product, account, or technical support, email <a className="text-violet-300 hover:text-violet-200" href="mailto:support@audienceown.com">support@audienceown.com</a>.</p><p>AudienceOwn’s legal entity details will be added once they are publicly established. We do not publish a company address that has not been formally designated for public contact.</p></Section>
        </div>
      </article>
    </div>
    <PublicFooter/>
  </main>;
}
