import Link from "next/link";
import { ArrowDown, ArrowRight, Check, ExternalLink, HeartHandshake, Link2, ListChecks, Network, Radio, RefreshCcw, Route, ShieldCheck, Signal, UserRoundCheck, UsersRound } from "lucide-react";
import { MarketingNav } from "@/components/marketing-nav";
import { HeroProtectionScene } from "@/components/hero-protection-scene";
import { PublicFooter } from "@/components/public-footer";
import { PlatformBrandIcon } from "@/components/dashboard/platform-brand-icon";
import { FeatureIcon, PremiumFeatureIcon } from "@/components/feature-icon";
import { LandingPricing } from "@/components/landing-pricing";
import { LandingMotion } from "@/components/landing-motion";

const risks = [
  ["hacked","red","Account access","You lose access","A hacked or compromised account can cut you off from followers overnight."],
  ["suspended","orange","Platform action","A platform suspends your account","Rules, mistakes, enforcement, and appeals can interrupt access without warning."],
  ["broken-link","purple","Identity change","Your username or platform changes","Old links and profiles can leave followers searching for where you went."],
  ["restart","blue","Platform outage","A platform becomes unavailable","Your audience still needs another reliable way to find you."],
] as const;
const steps = [
  [Network,"blue","Connect","Connect your platforms","Map the accounts, websites, newsletters, podcasts, and communities your audience already uses."],
  [ShieldCheck,"purple","Protect","Protect more followers","Give followers durable ways to stay connected beyond a single platform."],
  [Signal,"green","Monitor","Monitor platform health","Know when a connection needs attention instead of discovering the problem too late."],
  [RefreshCcw,"pink","Recover","Activate your recovery path","Direct protected followers toward the places where they can still find you."],
  [Radio,"blue","Communicate","Keep followers informed","Send relevant updates to followers who chose to hear from you."],
] as const;
const providers = [["youtube","YouTube","OAuth available"],["instagram","Instagram","OAuth available"],["tiktok","TikTok","Manual connection"],["x","X","Manual connection"],["twitch","Twitch","Manual connection"],["facebook","Facebook","Manual connection"],["discord","Discord","Manual connection"],["website","Website","Manual connection"],["podcast","Podcast","Manual connection"],["newsletter","Newsletter","Direct connection"],["more","More","Coming later"]] as const;
const updates = [["video","red","New Video"],["livestream","pink","Livestream"],["podcast","purple","Podcast Episode"],["product","orange","Product Release"],["event","blue","Event"],["announcement","orange","General Announcement"],["community","purple","Community Update"],["recovery-alert","red","Recovery Alert"]] as const;
const faqs = [
  ["What is AudienceOwn?","AudienceOwn is an audience protection and continuity platform for creators. It helps you create a permanent identity, connect the platforms you use, build backup paths, monitor connection health, stay directly connected with followers who opt in, and recover when an important account becomes unavailable."],
  ["How is AudienceOwn different from a link-in-bio tool?","A link-in-bio page mainly organizes destinations. AudienceOwn uses a permanent Creator Page as one part of a broader protection system that also includes connected platforms, backup destinations, Protected Followers, platform health, creator updates, and recovery tools."],
  ["What does ‘audience protection’ mean?","Audience protection means reducing how dependent your relationship with followers is on any single platform. The goal is to give followers durable ways to find and reconnect with you when an account or platform changes."],
  ["Does AudienceOwn own my followers?","No. AudienceOwn helps creators maintain durable connections with followers who choose to stay connected. It does not turn followers on third-party platforms into property or claim ownership of them."],
  ["What happens if I lose access to an account?","Your permanent Creator Page and available backup destinations remain available. Eligible creators can use AudienceOwn’s recovery tools to help protected followers find the places where they can still reconnect."],
  ["Do I have to leave the platforms I already use?","No. AudienceOwn works alongside your channels, newsletter, website, community, and storefront. It connects them into one continuity system without asking you to migrate your audience."],
  ["Can I start for free?","Yes. The Free plan gives you the essentials for a permanent audience foundation. You can upgrade when you need more protection, scale, and recovery capabilities."],
] as const;

function Heading({eyebrow,title,body}:{eyebrow:string;title:React.ReactNode;body:React.ReactNode}){return <header className="landing-section-heading"><p className="landing-eyebrow">{eyebrow}</p><h2>{title}</h2><p>{body}</p></header>}

export default function Home(){return <main className="marketing-page-v2 protection-landing" id="top"><LandingMotion/><MarketingNav/>
  <section className="landing-hero" aria-labelledby="landing-heading"><div className="landing-hero-grid"><div className="landing-hero-copy"><p className="landing-eyebrow"><ShieldCheck aria-hidden size={15}/>Audience protection for creators</p><h1 id="landing-heading">Your audience <span>shouldn&apos;t disappear</span> when one account does.</h1><p className="landing-hero-promise">You&apos;ve been told to own your audience. Now protect it.</p><p className="landing-hero-body">AudienceOwn gives your followers a permanent way to find you, helps you monitor the platforms you depend on, and gives you a recovery path when an account is hacked, suspended, deleted, or unavailable.</p><div className="landing-actions"><Link href="/register" className="button button-primary landing-primary">Protect your audience — it&apos;s free <ArrowRight aria-hidden size={18}/></Link><Link href="#protection-system" className="button button-secondary landing-secondary">See how protection works</Link></div><ul className="landing-trust-notes">{["No credit card required","Set up in minutes","Your permanent link stays yours"].map(x=><li key={x}><Check aria-hidden/>{x}</li>)}</ul></div><HeroProtectionScene/></div></section>

  <section className="landing-section ownership-section" id="product"><Heading eyebrow="More than audience ownership" title={<>Owning a list is useful.<br/><span className="gradient-text">Protecting the connection is bigger.</span></>} body="Your audience already lives across channels, communities, newsletters, websites, and more. AudienceOwn protects the paths between those places so one platform problem doesn’t become an audience problem."/><div className="ownership-compare"><article><FeatureIcon icon={ListChecks} tone="blue"/><p className="card-kicker">Audience ownership</p><h3>Build a direct list</h3><p>Build a list of followers you can contact directly.</p><div className="concept-tags"><span>Email</span><span>Subscribers</span><span>Direct contact</span></div></article><div className="compare-plus">+</div><article className="protection-emphasis"><FeatureIcon icon={Network} tone="purple"/><p className="card-kicker">Audience protection</p><h3>Build continuity around it</h3><p>Give followers multiple ways to find, follow, and reconnect with you when something changes.</p><div className="concept-tags"><span>Permanent identity</span><span>Backups</span><span>Monitoring</span><span>Recovery</span><span>Direct updates</span></div></article></div><p className="compare-summary">Audience ownership is one layer. <strong>Audience protection is the continuity system around it.</strong></p></section>

  <section className="landing-section risk-section"><Heading eyebrow="One platform is a single point of failure" title={<>Years of audience growth shouldn&apos;t<br/>depend on one login.</>} body="Accounts get hacked. Platforms suspend creators. Usernames change. Links break. Services go offline. Creators move. Preparation keeps one change from erasing every path back to you."/><div className="problem-grid">{risks.map(([kind,tone,kicker,title,text])=><article className={`motion-card accent-${tone}`} key={title}><PremiumFeatureIcon kind={kind} label={`${title} icon`}/><p className="card-kicker">{kicker}</p><h3>{title}</h3><p>{text}</p></article>)}</div></section>

  <section className="landing-section system-section" id="protection-system"><Heading eyebrow="The AudienceOwn protection system" title={<>One protection layer around<br/><span className="gradient-text">everywhere you create.</span></>} body="AudienceOwn connects the pieces creators normally manage separately and turns them into a recovery-ready audience system."/><div className="system-grid">{steps.map(([Icon,tone,label,title,text],i)=><article key={label}><span className="system-number">0{i+1}</span><FeatureIcon icon={Icon} tone={tone}/><p className="card-kicker">{label}</p><h3>{title}</h3><p>{text}</p></article>)}</div></section>

  <section className="landing-section protected-section"><div className="split-feature"><div className="split-copy"><p className="landing-eyebrow">Don&apos;t just count followers</p><h2>Know how much of your audience is <span className="gradient-text">actually protected.</span></h2><p>Follower count tells you how large your audience is. Protection tells you how prepared that audience is when something changes.</p><div className="definition-note"><UserRoundCheck aria-hidden/><span><strong>Protected Followers</strong> are followers who have chosen a durable way to stay connected beyond relying on one platform account.</span></div></div><div className="protection-dashboard"><div className="dashboard-top"><span>Audience protection</span><small>Illustrative view</small></div><div className="metric-primary"><p>Protected Followers</p><strong aria-label="816 thousand"><span aria-hidden="true" data-protected-metric>816K</span></strong><span>durable connections</span></div><div className="metric-row"><article><p>Total audience</p><strong aria-label="1.2 million"><span aria-hidden="true" data-audience-metric>1.2M</span></strong><span>across platforms</span></article><article><p>Backup channels</p><strong>3</strong><span className="status-good">Active</span></article></div><div className="readiness-bar"><div><span>Recovery readiness</span><strong>Strong</strong></div><i><b/></i></div></div></div></section>

  <section className="landing-section" id="connected-platforms"><Heading eyebrow="Map your audience" title={<>See every place your audience<br/>depends on you.</>} body="Connect supported accounts and add public profiles, websites, newsletters, podcasts, and communities to build your audience protection map."/><div className="provider-grid">{providers.map(([provider,name,status])=><article key={name}><PlatformBrandIcon provider={provider} label={name} animated/><div><h3>{name}</h3><p>{status}</p></div><i className={status==="OAuth available"?"available":status==="Coming later"?"later":"manual"}/></article>)}</div></section>

  <section className="landing-section platform-health"><Heading eyebrow="Platform health" title={<>Spot broken connections<br/>before your followers do.</>} body="AudienceOwn keeps connected-platform status visible so you know which parts of your protection system need attention."/><p className="example-label">Example status</p><div className="health-grid">{[["youtube","YouTube","Healthy","Connected","healthy"],["instagram","Instagram","Healthy","Connected","healthy"],["tiktok","TikTok","Syncing","Checking connection","syncing"],["x","X","Action required","Reconnect","attention"],["twitch","Twitch","Disconnected","Reconnect","critical"]].map(([provider,name,state,detail,tone])=><article key={name}><div><PlatformBrandIcon provider={provider} label={name} animated/><i className={tone}/></div><h3>{name}</h3><strong>{state}</strong><p>{detail}</p></article>)}</div></section>

  <section className="landing-section backup-section"><Heading eyebrow="Creator-controlled backups" title={<>When one door closes,<br/><span className="gradient-text">followers need another one.</span></>} body={<>If your main account disappears, your audience shouldn&apos;t have to search for you.<br/>Choose backup places now so your followers always know where to find you next.</>}/><div className="backup-map"><article className="destination main-destination"><small>Main platform</small><PlatformBrandIcon provider="youtube" label="YouTube"/><div><strong>YouTube</strong><span>Primary</span></div></article><ArrowDown aria-hidden/><div className="backup-pair"><article className="destination"><small>Backup destination</small><PlatformBrandIcon provider="twitch" label="Twitch"/><div><strong>Twitch</strong><span>Backup</span></div></article><article className="destination"><small>Backup destination</small><PlatformBrandIcon provider="newsletter" label="Newsletter"/><div><strong>Newsletter</strong><span>Direct</span></div></article></div><ArrowDown aria-hidden/><article className="destination permanent-destination"><small>Permanent destination</small><ShieldCheck aria-hidden/><div><strong>audienceown.com/yourname</strong><span>Always available</span></div></article></div></section>

  <section className="landing-section recovery-showcase" id="recovery-pass"><Heading eyebrow="Recovery Pass" title={<>Your recovery plan,<br/>ready before you need it.</>} body="Recovery Pass gives protected followers a clear way to reconnect when a creator loses access to an important platform."/><div className="recovery-flow">{[["lost-access","Access changes","An account is hacked, suspended, deleted, or unavailable."],["recovery-alert","Creator activates recovery","The creator sends an eligible recovery alert."],["followers-notified","Followers receive the path forward","Followers receive recovery information through the options they chose."],["found-again","The audience reconnects","Followers reach the permanent page and available backup destinations."]].map(([kind,title,text],i)=><article key={title}><span className="flow-number">0{i+1}</span><PremiumFeatureIcon kind={kind as "lost-access"} label={`${title} icon`}/><h3>{title}</h3><p>{text}</p>{i<3&&<ArrowRight className="flow-arrow" aria-hidden/>}</article>)}</div></section>

  <section className="landing-section" id="creator-updates"><Heading eyebrow="Direct creator updates" title={<>Stay reachable even when<br/>the algorithm isn&apos;t involved.</>} body="Followers choose the updates they want to receive. You keep a direct communication path for the moments that matter."/><div className="updates-grid">{updates.map(([kind,tone,title])=><article className={`motion-card accent-${tone}`} key={title}><PremiumFeatureIcon kind={kind} label={`${title} icon`}/><h3>{title}</h3><p>{title==="Recovery Alert"?"Share eligible recovery information when an important account is unavailable.":`Keep followers who chose ${title.toLowerCase()} updates informed.`}</p><small className={`update-category-badge update-category-${kind}`}><i aria-hidden/>{title==="Recovery Alert"?"Recovery communication":"Creator update"}</small></article>)}</div></section>

  <section className="landing-section identity-section"><div className="split-feature identity-split"><div className="split-copy"><p className="landing-eyebrow">Permanent creator identity</p><h2>One address that stays yours when everything else changes.</h2><p>Your AudienceOwn Creator Page gives followers one trusted place to find your official accounts, backup destinations, and the updates they chose to receive.</p><div className="identity-url">audienceown.com/yourname <ExternalLink aria-hidden/></div></div><div className="identity-card"><div className="identity-avatar">AO</div><p className="identity-handle">@yourname <ShieldCheck aria-hidden/></p><h3>Your permanent audience home</h3>{[[Network,"Official accounts","Your identified creator destinations."],[Route,"Backup destinations","Where followers should find you next."],[UsersRound,"Direct audience","Followers who chose to stay connected."]].map(([Icon,title,text])=><article key={title as string}><FeatureIcon icon={Icon as typeof Network} tone="purple"/><div><strong>{title as string}</strong><p>{text as string}</p></div></article>)}</div></div></section>

  <section className="landing-section how-section" id="how-it-works"><Heading eyebrow="How AudienceOwn works" title={<>Protect your audience before<br/>you need to recover it.</>} body="Build your continuity system in four clear steps."/><div className="how-grid">{[[Link2,"Create your permanent page","Set up the stable destination your followers can always return to."],[Network,"Connect your audience footprint","Add the platforms, communities, websites, and channels you use."],[UsersRound,"Build your protected audience","Give followers ways to stay connected and choose the updates they want."],[ShieldCheck,"Stay recovery ready","Monitor connections, maintain backups, and activate recovery when something goes wrong."]].map(([Icon,title,text],i)=><article key={title as string}><span>0{i+1}</span><FeatureIcon icon={Icon as typeof Link2} tone={i===3?"pink":"purple"}/><h3>{title as string}</h3><p>{text as string}</p></article>)}</div></section>

  <section className="landing-section continuity-section"><Heading eyebrow="Built for continuity" title={<>Not another place to build an audience.<br/><span className="gradient-text">A way to protect the one you already have.</span></>} body="AudienceOwn works alongside the platforms and creator tools you already use. It connects them into a protection and recovery system without demanding migration."/><div className="stack-visual"><div><small>Your creator stack</small><div className="stack-platforms">{["youtube","instagram","tiktok","newsletter","website","discord"].map(p=><PlatformBrandIcon key={p} provider={p} label={p}/>)}</div></div><ArrowRight aria-hidden/><article><ShieldCheck aria-hidden/><strong>AudienceOwn</strong><span>Protection · Monitoring · Recovery · Permanent identity</span></article></div></section>

  <LandingPricing/>
  <section className="landing-section faq-v2" id="faq"><header><p className="landing-eyebrow">FAQ</p><h2>Audience protection, explained.</h2><p>What creators need to know before building a more durable connection.</p></header><div>{faqs.map(([q,a])=><details name="landing-faq" key={q}><summary>{q}<span aria-hidden>+</span></summary><p>{a}</p></details>)}</div></section>
  <section className="final-cta"><div><FeatureIcon icon={HeartHandshake} tone="pink"/><p className="landing-eyebrow">Protect what you&apos;ve built</p><h2>Your audience already follows you.<br/>Make sure they can always find you.</h2><p>Build your audience protection layer in minutes. No credit card required.</p><Link href="/register" className="button landing-final-button">Protect your audience — it&apos;s free <ArrowRight aria-hidden/></Link></div></section><PublicFooter/>
</main>}
