"use client";

import { useCallback, useEffect, useId, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { CalendarCheck, X } from "lucide-react";
import type { BillingInterval } from "@/lib/billing/stripe";

function date(value:string){return new Intl.DateTimeFormat(undefined,{dateStyle:"long"}).format(new Date(value));}
function price(interval:BillingInterval){return interval==="monthly"?"$12/month":"$120/year";}
function label(interval:BillingInterval){return interval==="monthly"?"monthly":"yearly";}

export function BillingIntervalSwitch({currentInterval,targetInterval,effectiveAt,disabled=false}:{currentInterval:BillingInterval;targetInterval:BillingInterval;effectiveAt:string;disabled?:boolean}){
  const[open,setOpen]=useState(false),[pending,setPending]=useState(false),[error,setError]=useState(""),trigger=useRef<HTMLButtonElement>(null),dialog=useRef<HTMLElement>(null),titleId=useId(),descriptionId=useId(),router=useRouter();
  const close=useCallback(()=>{if(pending)return;setOpen(false);setError("");queueMicrotask(()=>trigger.current?.focus());},[pending]);
  useEffect(()=>{if(!open)return;const node=dialog.current;node?.querySelector<HTMLButtonElement>("button")?.focus();function key(event:KeyboardEvent){if(event.key==="Escape"){event.preventDefault();close();return;}if(event.key!=="Tab"||!node)return;const focusable=[...node.querySelectorAll<HTMLElement>('button:not([disabled]),[href],input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])')];if(!focusable.length)return;const first=focusable[0],last=focusable.at(-1)!;if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}document.addEventListener("keydown",key);return()=>document.removeEventListener("keydown",key);},[open,close]);
  async function confirm(){setPending(true);setError("");try{const response=await fetch("/api/billing/interval",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({interval:targetInterval})}),value=await response.json();if(!response.ok)throw new Error(value.error??"billing_interval_change_failed");setOpen(false);queueMicrotask(()=>trigger.current?.focus());router.refresh();}catch{setError("We couldn't schedule this billing change. Your current billing remains unchanged. Please try again.");}finally{setPending(false);}}
  return <><button ref={trigger} type="button" className="button plans-upgrade" disabled={disabled} onClick={()=>setOpen(true)}>Switch to {label(targetInterval)}</button>{open&&<div className="plans-dialog-backdrop" role="presentation" onMouseDown={event=>{if(event.currentTarget===event.target)close();}}><section ref={dialog} role="dialog" aria-modal="true" aria-labelledby={titleId} aria-describedby={descriptionId} className="plans-dialog plans-switch-dialog"><button type="button" aria-label="Close billing interval confirmation" disabled={pending} onClick={close}><X aria-hidden/></button><p className="eyebrow">Confirm billing change</p><h2 id={titleId}>Switch to {label(targetInterval)} billing?</h2><p id={descriptionId}>Your {label(currentInterval)} Pro subscription remains active until {date(effectiveAt)}. After that, your subscription will switch to {label(targetInterval)} billing at {price(targetInterval)}.</p><dl className="interval-switch-details"><div><dt>Current billing</dt><dd>{price(currentInterval)}</dd></div><div><dt>New billing</dt><dd>{price(targetInterval)}</dd></div><div><dt>Effective</dt><dd>{date(effectiveAt)}</dd></div></dl>{error&&<p className="interval-switch-error" role="alert">{error}</p>}<div><button type="button" className="button button-secondary" disabled={pending} onClick={close}>Keep {label(currentInterval)} billing</button><button type="button" className="button plans-upgrade" disabled={pending} onClick={confirm}>{pending?"Scheduling switch…":`Confirm switch to ${label(targetInterval)}`}</button></div></section></div>}</>;
}

export function CancelBillingIntervalSwitch({currentInterval}:{currentInterval:BillingInterval}){const[pending,setPending]=useState(false),[message,setMessage]=useState(""),router=useRouter();async function cancel(){setPending(true);setMessage("");try{const response=await fetch("/api/billing/interval",{method:"DELETE",headers:{"content-type":"application/json"}});if(!response.ok)throw new Error();setMessage("Scheduled billing change canceled.");router.refresh();}catch{setMessage("We couldn't cancel the scheduled change. Please try again.");}finally{setPending(false);}}return <span className="pending-switch-action"><button type="button" className="button button-secondary" disabled={pending} onClick={cancel}>{pending?"Keeping current billing…":`Keep ${label(currentInterval)} billing`}</button>{message&&<small role="status">{message}</small>}</span>;}

export function PendingBillingIntervalSwitch({currentInterval,targetInterval,effectiveAt}:{currentInterval:BillingInterval;targetInterval:BillingInterval;effectiveAt:string}){return <div className="plans-pending-switch" role="status" aria-label={`Switch to ${label(targetInterval)} billing scheduled. Starts ${date(effectiveAt)}.`}><span className="plans-pending-switch-copy"><CalendarCheck aria-hidden/><span><strong>Switch to {label(targetInterval)} scheduled</strong><small>Starts {date(effectiveAt)}</small></span></span><CancelBillingIntervalSwitch currentInterval={currentInterval}/></div>;}
