import Link from "next/link";
import { ArrowUpRight, ChevronDown, RefreshCw } from "lucide-react";
import { PlatformBrandIcon } from "@/components/dashboard/platform-brand-icon";
import type { AudienceProvider } from "@/lib/platform-audience/types";
import { connectionHealthDescriptions, connectionHealthLabels, type ConnectionHealthState } from "@/lib/social-providers/connection-health";

export type ConnectedPlatformCardData = {
  id:string; provider:AudienceProvider; providerName:string; accountName:string; role:string;
  connectionType:"oauth"|"manual"; health:ConnectionHealthState; authorization:string; capabilityNotice?:string|null;
  lastSync:string|null; stale:boolean; permission:string|null; publicUrl:string|null; connectedAt:string|null;
};

const tones:Record<ConnectionHealthState,string>={healthy:"bg-emerald-400",syncing:"bg-amber-300",action_required:"bg-orange-400",temporarily_unavailable:"bg-orange-400",disconnected:"bg-red-400",manual:"bg-zinc-400"};

export function ConnectedPlatformCard({connection}:{connection:ConnectedPlatformCardData}){
  const automatic=connection.connectionType==="oauth";
  const displayedStatus=automatic?connectionHealthLabels[connection.health]:"Connected";
  return <article className="surface flex min-w-0 flex-col rounded-2xl p-5 sm:p-6" aria-labelledby={`connection-${connection.id}`}>
    <div className="flex flex-col items-start gap-4 sm:flex-row sm:justify-between"><div className="flex min-w-0 max-w-full items-center gap-3"><PlatformBrandIcon provider={connection.provider} label={connection.providerName}/><div className="min-w-0"><p className="text-xs font-medium text-zinc-500">{connection.providerName}</p><h3 id={`connection-${connection.id}`} className="mt-0.5 break-words font-semibold text-zinc-100">{connection.accountName}</h3><p className="mt-1 text-xs leading-5 text-zinc-500">{connection.role} · {automatic?"OAuth connection":"Manual account"}</p></div></div><span className="inline-flex shrink-0 items-center gap-2 rounded-full border border-white/10 bg-white/[.04] px-2.5 py-1 text-xs text-zinc-200"><i aria-hidden className={`size-2 rounded-full ${tones[connection.health]}`}/>{displayedStatus}</span></div>
    <div className="mt-5 rounded-xl border border-white/[.07] bg-white/[.025] p-4"><p className="text-sm text-zinc-200">{connectionHealthDescriptions[connection.health]}</p>{connection.capabilityNotice&&<p className="mt-2 text-xs leading-5 text-zinc-400">{connection.capabilityNotice} No action is required from you.</p>}{automatic&&connection.stale&&<p className="mt-2 text-xs leading-5 text-amber-200">Your last synchronized data may not be current.</p>}</div>
    <dl className="mt-5 grid gap-4 text-sm sm:grid-cols-2"><div><dt className="text-zinc-500">Connection status</dt><dd className="mt-1 text-zinc-200">{displayedStatus}</dd></div><div><dt className="text-zinc-500">Authorization</dt><dd className="mt-1 text-zinc-200">{connection.authorization}</dd></div>{automatic&&<><div><dt className="text-zinc-500">Last successful sync</dt><dd className="mt-1 text-zinc-200">{connection.lastSync}</dd></div><div><dt className="text-zinc-500">Permission</dt><dd className="mt-1 text-zinc-200">{connection.permission}</dd></div></>}</dl>
    <div className="mt-5 flex flex-col gap-3 sm:flex-row sm:flex-wrap">{connection.health==="action_required"&&connection.provider==="youtube"&&<a className="button button-primary min-h-11 w-full justify-center sm:w-auto" href={`/api/integrations/youtube/connect?role=${connection.role === "Backup Account" ? "backup" : "official"}&connectionId=${encodeURIComponent(connection.id)}`}><RefreshCw aria-hidden size={15}/>Reconnect YouTube</a>}{connection.publicUrl&&<a className="button button-secondary min-h-11 w-full justify-center sm:w-auto" href={connection.publicUrl} target="_blank" rel="noreferrer">View public account <ArrowUpRight aria-hidden size={14}/></a>}<Link className="button button-secondary min-h-11 w-full justify-center sm:w-auto" href="/dashboard/platforms">{automatic?"Manage account":"Edit or remove"}</Link></div>
    <details className="group mt-5 border-t border-white/[.07] pt-4"><summary className="flex cursor-pointer list-none items-center justify-between rounded-lg py-2 text-sm font-medium text-zinc-300 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-violet-400">Connection details <ChevronDown aria-hidden size={16} className="transition group-open:rotate-180 motion-reduce:transition-none"/></summary><dl className="mt-3 grid gap-4 rounded-xl bg-black/15 p-4 text-sm sm:grid-cols-2"><div><dt className="text-zinc-500">Provider</dt><dd className="mt-1">{connection.providerName}</dd></div><div><dt className="text-zinc-500">Account name</dt><dd className="mt-1">{connection.accountName}</dd></div><div><dt className="text-zinc-500">Role</dt><dd className="mt-1">{connection.role}</dd></div><div><dt className="text-zinc-500">Connection type</dt><dd className="mt-1">{automatic?"OAuth connection":"Manual connection"}</dd></div><div><dt className="text-zinc-500">Health</dt><dd className="mt-1">{displayedStatus}</dd></div>{automatic&&<><div><dt className="text-zinc-500">Permission level</dt><dd className="mt-1">{connection.permission}</dd></div><div><dt className="text-zinc-500">Last synchronization</dt><dd className="mt-1">{connection.lastSync}</dd></div></>}{connection.publicUrl&&<div><dt className="text-zinc-500">Public URL</dt><dd className="mt-1 break-all"><a className="text-violet-300 hover:text-violet-200" href={connection.publicUrl} target="_blank" rel="noreferrer">{connection.publicUrl}</a></dd></div>}{connection.connectedAt&&<div><dt className="text-zinc-500">Connected</dt><dd className="mt-1"><time dateTime={connection.connectedAt}>{new Intl.DateTimeFormat("en",{dateStyle:"medium",timeZone:"UTC"}).format(new Date(connection.connectedAt))}</time></dd></div>}</dl>{automatic&&connection.provider==="youtube"&&<p className="mt-3 text-xs leading-5 text-zinc-500">Read-only access lets AudienceOwn read public channel information and subscriber metrics. It cannot upload, edit, delete, or manage your channel.</p>}</details>
  </article>;
}
