"use client";
import { useRef, useState } from "react";
import { CONTACT_AREAS, CONTACT_EMAIL, CONTACT_SUBTOPICS, CONTACT_TOPIC_GROUPS, CONTACT_URGENCIES, SUPPORT_EMAIL, URGENT_TOPICS, contactTopicLabels, type ContactFormErrors, type ContactTopic } from "@/lib/contact-form-contract";

type Result = { status?: "success" | "invalid" | "rate_limited" | "unavailable"; errors?: ContactFormErrors };
const inputClass = "mt-2 min-h-12 w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3 text-white outline-none transition focus-visible:border-violet-400 focus-visible:ring-2 focus-visible:ring-violet-400/30";
const formatSize = (size: number) => `${(size / 1024 / 1024).toFixed(size >= 1024 * 1024 ? 1 : 2)} MB`;

export function ContactForm({ initialTopic = "" }: { initialTopic?: ContactTopic | "" }) {
  const [busy, setBusy] = useState(false), [result, setResult] = useState<Result>({}), [topic, setTopic] = useState<ContactTopic | "">(initialTopic), [files, setFiles] = useState<File[]>([]), [fileError, setFileError] = useState("");
  const fileInput = useRef<HTMLInputElement>(null); const subtopics = topic ? CONTACT_SUBTOPICS[topic as keyof typeof CONTACT_SUBTOPICS] as readonly string[] | undefined : undefined;
  function addFiles(incoming: FileList | File[]) { const next = [...files, ...Array.from(incoming)]; if (next.length > 3) return setFileError("Attach no more than 3 images."); if (next.some(file => !["image/png", "image/jpeg", "image/webp"].includes(file.type))) return setFileError("Attach only PNG, JPEG, or WEBP images."); if (next.some(file => file.size > 5 * 1024 * 1024)) return setFileError("This image is too large. Maximum size is 5 MB."); if (next.reduce((sum, file) => sum + file.size, 0) > 10 * 1024 * 1024) return setFileError("Attachments must be 10 MB or less in total."); setFiles(next); setFileError(""); }
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setResult({}); const form = event.currentTarget; const body = new FormData(form); body.delete("attachments"); files.forEach(file => body.append("attachments", file));
    try { const response = await fetch("/api/contact", { method: "POST", body }); const value = await response.json().catch(() => ({ status: "unavailable" })) as Result; setResult(value); if (response.ok && value.status === "success") { form.reset(); setTopic(""); setFiles([]); setFileError(""); } } catch { setResult({ status: "unavailable" }); } finally { setBusy(false); }
  }
  const error = (field: keyof ContactFormErrors) => result.errors?.[field];
  return <form className="surface relative rounded-2xl p-5 sm:p-7" onSubmit={submit} noValidate encType="multipart/form-data">
    <div className="grid gap-5 sm:grid-cols-2">
      <label className="block text-sm font-medium sm:col-span-2" htmlFor="topic">Topic
        <select id="topic" name="topic" className={inputClass} value={topic} onChange={event => setTopic(event.target.value as ContactTopic)} required aria-invalid={Boolean(error("topic"))} aria-describedby={error("topic") ? "topic-error" : undefined}>
          <option value="" disabled>Choose a topic</option>{CONTACT_TOPIC_GROUPS.map(group => <optgroup label={group.label.toUpperCase()} key={group.label}>{group.topics.map(value => <option value={value} key={value}>{contactTopicLabels[value]}</option>)}</optgroup>)}
        </select><ErrorText id="topic-error" value={error("topic")}/>
      </label>
      {subtopics && <SelectField name="subtopic" label={topic === "platforms_connected_accounts" ? "Platform" : "Issue type"} options={subtopics} error={error("subtopic")}/>}
      <SelectField name="area" label="Where did this happen? — optional" options={CONTACT_AREAS} error={error("area")}/>
      {topic && URGENT_TOPICS.includes(topic) && <SelectField name="urgency" label="How urgent is this?" options={CONTACT_URGENCIES} error={error("urgency")}/>}
      <Field name="pageUrl" label="Page URL — optional" type="url" placeholder="https://audienceown.com/…" maxLength={500} error={error("pageUrl")}/>
      {(topic === "security_abuse" || topic === "account_sign_in") && <div className="rounded-xl border border-amber-300/15 bg-amber-300/5 p-4 text-xs leading-5 text-amber-100 sm:col-span-2">Do not include passwords, access tokens, authentication codes, recovery secrets, or other secrets.</div>}
      {topic === "privacy_request" && <div className="rounded-xl border border-violet-300/15 bg-violet-300/5 p-4 text-xs leading-5 text-violet-100 sm:col-span-2">We may need to verify your identity before fulfilling certain privacy requests. Do not include sensitive identity documents here.</div>}
      <Field name="name" label="Name" autoComplete="name" maxLength={100} required error={error("name")}/><Field name="email" label="Email" type="email" autoComplete="email" maxLength={254} required error={error("email")}/><Field name="handle" label="AudienceOwn handle — optional" autoComplete="off" maxLength={80} error={error("handle")}/>
      <Field name="subject" label="Subject" maxLength={160} required error={error("subject")}/>
      <label className="block text-sm font-medium sm:col-span-2" htmlFor="message">Message<textarea id="message" name="message" className={`${inputClass} min-h-40 resize-y`} maxLength={5000} required placeholder="Tell us what happened, what you expected to happen, and anything else that may help." aria-invalid={Boolean(error("message"))} aria-describedby="message-help message-error"/><span id="message-help" className="mt-2 block text-xs text-zinc-500">Include steps to reproduce the issue if you can.</span><ErrorText id="message-error" value={error("message")}/></label>
      <div className="sm:col-span-2"><span className="text-sm font-medium">Attach screenshots — optional</span><div className="mt-2 rounded-xl border border-dashed border-white/15 bg-black/20 p-5 text-center transition hover:border-violet-400/50" onDragOver={event => event.preventDefault()} onDrop={event => { event.preventDefault(); addFiles(event.dataTransfer.files); }}><input ref={fileInput} id="attachments" name="attachments" className="sr-only" type="file" multiple accept="image/png,image/jpeg,image/webp" onChange={event => event.target.files && addFiles(event.target.files)}/><p className="text-sm text-zinc-300">Drag and drop screenshots here, or <button className="font-medium text-violet-300 underline underline-offset-4" type="button" onClick={() => fileInput.current?.click()}>browse files</button></p><p className="mt-2 text-xs leading-5 text-zinc-500">PNG, JPEG, or WEBP. Up to 3 images, 5 MB each, 10 MB total.</p></div>
        {files.length > 0 && <ul className="mt-3 space-y-2">{files.map((file, index) => <li className="flex min-w-0 items-center gap-3 rounded-xl border border-white/10 bg-white/[.025] px-3 py-2 text-sm" key={`${file.name}-${file.size}-${index}`}><span aria-hidden="true" className="grid size-9 shrink-0 place-items-center rounded-lg bg-violet-400/10 text-violet-200">▧</span><span className="min-w-0 flex-1"><span className="block break-all text-zinc-200">{file.name}</span><span className="text-xs text-zinc-500">{formatSize(file.size)}</span></span><button className="shrink-0 rounded-lg px-2 py-1 text-xs text-zinc-300 hover:bg-white/10" type="button" aria-label={`Remove ${file.name}`} onClick={() => setFiles(current => current.filter((_, itemIndex) => itemIndex !== index))}>Remove</button></li>)}</ul>}
        <ErrorText id="attachments-error" value={fileError || error("attachments")}/><p className="mt-3 text-xs leading-5 text-zinc-500">Screenshots may contain personal information. Remove passwords, access tokens, payment details, and other sensitive information before uploading.</p>
      </div>
    </div>
    <div className="absolute -left-[10000px] top-auto size-px overflow-hidden" aria-hidden="true"><label htmlFor="website">Website</label><input id="website" name="website" type="text" tabIndex={-1} autoComplete="off"/></div>
    <button className="button button-primary mt-6 min-h-11 w-full justify-center sm:w-auto" disabled={busy}>{busy ? "Sending…" : "Send message"}</button>
    {result.status === "success" && <div className="mt-5 rounded-xl border border-emerald-400/20 bg-emerald-400/5 p-4 text-sm text-emerald-100" role="status" aria-live="polite"><strong>Message sent</strong><p className="mt-1">Thanks for contacting AudienceOwn. Your message has been received. We’ll reply to the email address you provided.</p></div>}
    {result.status && !["success", "invalid"].includes(result.status) && <div className="mt-5 rounded-xl border border-amber-400/20 bg-amber-400/5 p-4 text-sm text-amber-100" role="alert"><p>{result.status === "rate_limited" ? "Too many messages were submitted. Please wait and try again." : "We couldn't send your message right now. Please try again."}</p><p className="mt-2">You can also email <a className="underline" href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a> or <a className="underline" href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.</p></div>}
  </form>;
}
function ErrorText({ id, value }: { id: string; value?: string }) { return value ? <span id={id} className="mt-2 block text-xs text-red-300" role="alert">{value}</span> : null; }
function SelectField({ name, label, options, error }: { name: keyof ContactFormErrors; label: string; options: readonly string[]; error?: string }) { return <label className="block text-sm font-medium" htmlFor={name}>{label}<select id={name} name={name} className={inputClass} defaultValue="" aria-invalid={Boolean(error)} aria-describedby={error ? `${name}-error` : undefined}><option value="">Choose an option</option>{options.map(option => <option key={option}>{option}</option>)}</select><ErrorText id={`${name}-error`} value={error}/></label>; }
function Field({ name, label, error, required, type = "text", ...props }: { name: keyof ContactFormErrors; label: string; error?: string; required?: boolean; type?: string; autoComplete?: string; placeholder?: string; maxLength: number }) { const errorId = `${name}-error`; return <label className="block text-sm font-medium" htmlFor={name}>{label}<input id={name} name={name} type={type} className={inputClass} required={required} aria-invalid={Boolean(error)} aria-describedby={error ? errorId : undefined} {...props}/><ErrorText id={errorId} value={error}/></label>; }
