"use client";
import {useActionState,useEffect,useState}from"react";
import{ArrowRight,CheckCircle2,LockKeyhole,ShieldCheck,UserRound}from"lucide-react";
import{updateRecoveryPassProfile}from"@/app/actions/recovery-pass-profile";
import type{CreatorProfileSettings,CreatorProfileSettingsState}from"@/lib/creator-profile-settings";
import{SubmitButton}from"./submit-button";
const initialState:CreatorProfileSettingsState={};
export function CreatorForm({profile,publicSiteUrl,ready}:{profile:CreatorProfileSettings;publicSiteUrl:string;ready:boolean}){
 const[state,formAction]=useActionState(updateRecoveryPassProfile,initialState),[values,setValues]=useState(profile),[lastSaved,setLastSaved]=useState<CreatorProfileSettings|undefined>(),canonical=state.saved??profile;
 if(state.saved&&state.saved!==lastSaved){setLastSaved(state.saved);setValues(state.saved)}
 const dirty=values.displayName!==canonical.displayName||values.tagline!==canonical.tagline||values.biography!==canonical.biography;
 useEffect(()=>{if(!dirty)return;const warn=(event:BeforeUnloadEvent)=>event.preventDefault();window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn)},[dirty]);
 const field=(name:"displayName"|"tagline"|"biography",value:string)=>setValues(current=>({...current,[name]:value})),errors=state.fieldErrors??{},inputClass="creator-profile-input",url=`${new URL(publicSiteUrl).host}/${profile.slug}`;
 return <form action={formAction} className="creator-identity-form"><div className="creator-form-grid">
  <div><label htmlFor="display_name">Display name</label><div className="creator-input-shell"><input className={inputClass} id="display_name" name="display_name" maxLength={100} value={values.displayName} onChange={event=>field("displayName",event.target.value)} aria-invalid={Boolean(errors.display_name)} aria-describedby={errors.display_name?"display_name_error":"display_name_help"} required/><UserRound aria-hidden size={16}/></div><p id="display_name_help">Your public creator name.</p>{errors.display_name?.map(error=><p id="display_name_error" role="alert" className="creator-field-error" key={error}>{error}</p>)}</div>
  <div><label htmlFor="public_tagline">Tagline <span>(optional)</span></label><input className={inputClass} id="public_tagline" name="public_tagline" maxLength={160} value={values.tagline??""} onChange={event=>field("tagline",event.target.value)}/><p className="creator-character-count">{(values.tagline??"").length} / 160</p>{errors.public_tagline?.map(error=><p role="alert" className="creator-field-error" key={error}>{error}</p>)}</div>
  <div className="creator-url-field"><span className="creator-input-label">Permanent URL</span><div><LockKeyhole aria-hidden size={16}/><strong>{url}</strong><span>Permanent</span></div><p>Your permanent Recovery Pass handle keeps shared links working.</p></div>
  <div className="creator-bio-field"><label htmlFor="public_bio">Biography <span>(optional)</span></label><textarea className={inputClass} id="public_bio" name="public_bio" maxLength={500} value={values.biography??""} onChange={event=>field("biography",event.target.value)}/><p className="creator-character-count">{(values.biography??"").length} / 500</p>{errors.public_bio?.map(error=><p role="alert" className="creator-field-error" key={error}>{error}</p>)}</div>
 </div><div className={`creator-save-strip ${ready?"ready":"incomplete"}`}><div><ShieldCheck aria-hidden size={20}/><span><strong>{ready?"Your Recovery Pass is ready":"Complete your Recovery Pass"}</strong><small>{dirty?"You have unsaved changes.":state.status==="success"?"Saved values are live across AudienceOwn.":"Identity changes publish through the canonical profile."}</small></span></div><SubmitButton className="creator-action creator-action-primary creator-save-button" pendingText="Saving…" disabled={!dirty}>Save changes <ArrowRight aria-hidden size={15}/></SubmitButton></div><p className="creator-save-state" role={state.status==="error"?"alert":"status"} aria-live="polite">{state.status==="success"?<><CheckCircle2 aria-hidden size={15}/>{state.message}</>:state.message}</p></form>;
}
