"use client";
import { useEffect, useState } from "react";
import { QRCodeSVG } from "qrcode.react";
import { createClient } from "@/lib/supabase/browser";
type Factor={id:string;friendly_name?:string;status:string};
export function MfaPanel(){const[factors,setFactors]=useState<Factor[]>([]),[enrol,setEnrol]=useState<{id:string;qr:string;secret:string}|null>(null),[code,setCode]=useState(""),[message,setMessage]=useState("");const s=createClient();async function refresh(){if(!s)return;const{data}=await s.auth.mfa.listFactors();setFactors(data?.totp??[])}useEffect(()=>{if(!s)return;s.auth.mfa.listFactors().then(({data})=>setFactors(data?.totp??[]))},[s]);
async function begin(){if(!s)return;const{data,error}=await s.auth.mfa.enroll({factorType:"totp",friendlyName:"OwnSignal authenticator"});if(error){setMessage(error.message);return}setEnrol({id:data.id,qr:data.totp.uri,secret:data.totp.secret})}
async function verify(){if(!s||!enrol)return;const{data:c,error:e}=await s.auth.mfa.challenge({factorId:enrol.id});if(e){setMessage(e.message);return}const{error}=await s.auth.mfa.verify({factorId:enrol.id,challengeId:c.id,code});if(error){setMessage("That code was not accepted.");return}setMessage("Authenticator verified.");setEnrol(null);setCode("");refresh()}
async function remove(id:string){if(!s)return;const{error}=await s.auth.mfa.unenroll({factorId:id});setMessage(error?error.message:"Authenticator removed.");refresh()}
return <div>{factors.length>0?<div className="space-y-3">{factors.map(f=><div key={f.id} className="flex items-center justify-between rounded-xl border p-4"><div><p className="font-medium">{f.friendly_name||"Authenticator app"}</p><p className="text-xs text-emerald-400">{f.status}</p></div><button onClick={()=>remove(f.id)} className="button button-secondary text-xs">Remove</button></div>)}</div>:<p className="text-sm text-zinc-400">No authenticator app is enrolled.</p>}{!enrol&&<button onClick={begin} className="button button-primary mt-5">Set up authenticator</button>}{enrol&&<div className="mt-6 rounded-xl border bg-white p-5 text-black"><QRCodeSVG value={enrol.qr} size={180}/><p className="mt-4 text-xs break-all">Manual key: {enrol.secret}</p><label className="mt-4 block text-sm font-medium" htmlFor="totp">6-digit code</label><input id="totp" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,6))} className="mt-1 w-full rounded-lg border border-zinc-300 p-2 text-black"/><button onClick={verify} className="button bg-black text-white mt-3">Verify and enable</button></div>}{message&&<p role="status" className="mt-4 text-sm text-zinc-300">{message}</p>}<p className="mt-5 text-xs leading-5 text-zinc-500">Store access to your authenticator safely. OwnSignal does not claim recovery codes that Supabase does not provide.</p></div>}
