"use client";
/* eslint-disable @next/next/no-html-link-for-pages -- pricing is the current non-checkout upgrade destination */

import { useActionState, useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { Bot, Check, ChevronRight, Link2, LockKeyhole, Plus, Search, ShieldCheck, Sparkles, Trash2, TriangleAlert, X } from "lucide-react";
import { ProviderConnectionMethodSelector, type ConnectionMethod } from "@/components/providers/provider-connection-method-selector";
import type { ProviderConnectionCapability } from "@/lib/social-providers/types";
import { removeMainAccount, savePlatformGroup, type PlatformSaveState } from "@/app/actions/creator";
import { PLATFORMS, getPlatform, normalizePlatformAccount, platformFromAccount, searchPlatforms, type PlatformId } from "@/lib/platforms";
import type {CreatorEntitlements} from "@/lib/provider-entitlements";
import {canonicalAccountConnected,resolveConnectionStatus} from "@/lib/social-providers/connection-health";
import type {RecoveryReadiness} from "@/lib/recovery-readiness";
import styles from "./platforms-manager.module.css";
import { RecoveryNetworkManager, type PersistentRecoveryNetwork } from "./recovery-network-manager";
import {PlatformBrandIcon} from "./dashboard/platform-brand-icon";

export type PlatformAccount = {
  id:string; platform:string; account_type:string; label:string; url:string; is_primary:boolean;
  is_public:boolean; position:number; connection_health?:string | null; provider_status?:string | null;
  audience_count?:number | null; audience_unit?:string | null;
  audience_unavailable?:boolean;
  protected_official_account_id?:string|null;
  external_account_id?:string|null;
};
type DraftAccount = { id?:string; platformId:PlatformId; value:string; label?:string; isPublic:boolean; audienceCount?:number|null; audienceUnit?:string|null; audienceUnavailable?:boolean; health?:string|null; providerStatus?:string|null; externalAccountId?:string|null; protectedOfficialAccountId?:string|null };
type Draft = { officials:DraftAccount[]; backups:DraftAccount[] };
type AccountFlow = { role:"official"|"backup"; index:number|null; platformId:PlatformId|null; method:ConnectionMethod; step:"picker"|"method"|"details" };

export function accountCapacityLabel(count:number,limit:number|null) {
  return limit===null?"Unlimited":`${count} of ${limit} used`;
}

export type ConfigureAccountStepState = "complete"|"current"|"future"|"attention";
export function configureAccountStepStates(input:{officialCount:number;backupCount:number;blockingIssue:boolean;recoveryHealthy:boolean}):ConfigureAccountStepState[] {
  const officialComplete=input.officialCount>0,backupComplete=input.backupCount>0;
  return [
    officialComplete?"complete":"current",
    input.blockingIssue&&officialComplete?"attention":backupComplete?"complete":officialComplete?"current":"future",
    input.recoveryHealthy?"complete":"future",
  ];
}

export function configureAccountGuidance(input:{officialCount:number;backupCount:number;blockingIssue:boolean;recoveryHealthy:boolean;issueLabel?:string;issueRole?:"official"|"backup"}) {
  if(input.blockingIssue)return{tone:"attention" as const,title:"A connection needs attention",body:`${input.issueLabel??"One of your connected accounts"} needs attention. Review it to keep your recovery setup healthy.`,action:"Review connection",role:input.issueRole??"official"};
  if(!input.officialCount)return{tone:"official" as const,title:"Build your first recovery network",body:"Start by connecting the Main account your audience already knows you from.",action:"Add Main account",role:"official" as const};
  if(!input.backupCount)return{tone:"backup" as const,title:"Add a Recovery destination",body:"Your Main account is connected, but it does not have a trusted Recovery destination yet.",action:"Add Recovery destination",role:"backup" as const};
  if(input.recoveryHealthy)return{tone:"healthy" as const,title:"Your recovery networks are protected",body:"Your Main accounts and linked Recovery destinations pass the canonical readiness checks.",action:null,role:null};
  return{tone:"review" as const,title:"Review your recovery networks",body:"Review the remaining recovery-readiness checks to keep each Main account protected.",action:null,role:null};
}

export function providerPickerState(capability:ProviderConnectionCapability|undefined,connected:boolean,role:"official"|"backup",planLocked=false){
  const implemented=capability?.implementationStatus==="implemented",connectable=Boolean(capability?.connectable),review=connectable&&(capability?.reviewStatus==="required"||capability?.reviewStatus==="unknown"),invalid=implemented&&capability?.configurationStatus==="invalid",setup=implemented&&capability?.configurationStatus==="missing";
  return{disabled:connected||planLocked||!connectable,label:connected?"Connected":invalid?"Configuration error":setup?"Setup required":planLocked?"Upgrade to Pro":review?"App review required · Connect":connectable?"Connect":"Coming soon",tone:connected?"connected":invalid||setup?"setup":planLocked?"locked":review?"review":connectable?"available":"soon",href:!planLocked&&connectable&&capability?.connectPath?`${capability.connectPath}?role=${role}`:null};
}

function accountDraft(account:PlatformAccount):DraftAccount {
  return { id:account.id, platformId:platformFromAccount(account.platform,account.url).id, value:account.url,
    label:account.label, isPublic:account.is_public, audienceCount:account.audience_count, audienceUnit:account.audience_unit, audienceUnavailable:account.audience_unavailable,
    health:account.connection_health, providerStatus:account.provider_status, externalAccountId:account.external_account_id, protectedOfficialAccountId:account.protected_official_account_id };
}
export function PlatformsManager({accounts,networks,connectionCapabilities,entitlements}:{accounts:PlatformAccount[];networks:PersistentRecoveryNetwork[];connectionCapabilities:ProviderConnectionCapability[];entitlements:CreatorEntitlements;recoveryReadiness:RecoveryReadiness}) {
  const router=useRouter();
  const savedOfficials=useMemo(()=>accounts.filter(a=>a.account_type==="official").sort((a,b)=>Number(b.is_primary)-Number(a.is_primary)||a.position-b.position),[accounts]);
  const savedBackups=useMemo(()=>accounts.filter(a=>a.account_type==="backup").sort((a,b)=>a.position-b.position),[accounts]);
  const [query,setQuery]=useState(""); const [open,setOpen]=useState(false); const [dirty,setDirty]=useState(false);
  const [draft,setDraft]=useState<Draft>({officials:savedOfficials.map(accountDraft),backups:savedBackups.map(accountDraft)});
  const [flow,setFlow]=useState<AccountFlow|null>(null); const [flowAccount,setFlowAccount]=useState<DraftAccount|null>(null);
  const [recoveryContextMainId,setRecoveryContextMainId]=useState<string|null>(null);
  const [recoveryContextNetworkId,setRecoveryContextNetworkId]=useState<string|null>(null);
  const [removing,setRemoving]=useState(false);
  const [state,action,pending]=useActionState<PlatformSaveState,FormData>(savePlatformGroup,{});
  const dialogRef=useRef<HTMLDivElement>(null); const flowDialogRef=useRef<HTMLElement>(null); const returnFocus=useRef<HTMLElement|null>(null);
  const handledSuccessfulSave=useRef(false);
  const capabilities=useMemo(()=>new Map(connectionCapabilities.map(item=>[item.provider,item])),[connectionCapabilities]);
  const connectedOfficial=new Set(draft.officials.map(a=>a.platformId));
  const connectedBackup=new Set(draft.backups.map(a=>a.platformId));
  const officialLocked=entitlements.providerConnections.official.limit!==null&&!entitlements.providerConnections.official.allowed;
  const backupLocked=entitlements.providerConnections.backup.limit!==null&&!entitlements.providerConnections.backup.allowed;
  const canonicalDrafts=[...savedOfficials,...savedBackups].map(accountDraft);
  const issueAccount=canonicalDrafts.find(account=>{const canonicalConnected=canonicalAccountConnected({health:account.health,providerStatus:account.providerStatus,hasPublicUrl:Boolean(account.value),hasExternalAccountId:Boolean(account.externalAccountId)});return resolveConnectionStatus({health:account.health,providerStatus:account.providerStatus,canonicalConnected}).actionRequired;});
  const attentionCount=canonicalDrafts.filter(account=>{const canonicalConnected=canonicalAccountConnected({health:account.health,providerStatus:account.providerStatus,hasPublicUrl:Boolean(account.value),hasExternalAccountId:Boolean(account.externalAccountId)});return resolveConnectionStatus({health:account.health,providerStatus:account.providerStatus,canonicalConnected}).actionRequired;}).length;
  const actionRequired=Boolean(issueAccount);
  const healthyRecoveryIds=new Set(savedBackups.filter(account=>{const connected=canonicalAccountConnected({health:account.connection_health,providerStatus:account.provider_status,hasPublicUrl:Boolean(account.url),hasExternalAccountId:Boolean(account.external_account_id)});return !resolveConnectionStatus({health:account.connection_health,providerStatus:account.provider_status,canonicalConnected:connected}).actionRequired;}).map(account=>account.id));
  const relationships=networks.flatMap(network=>network.main_connected_account_id?network.recovery_account_ids.map(recoveryId=>({main_connected_account_id:network.main_connected_account_id!,recovery_connected_account_id:recoveryId})):[]);
  const protectedMainCount=savedOfficials.filter(main=>relationships.some(link=>link.main_connected_account_id===main.id&&healthyRecoveryIds.has(link.recovery_connected_account_id))).length;
  const everyMainProtected=savedOfficials.length>0&&protectedMainCount===savedOfficials.length&&!actionRequired;
  const guidanceMain=savedOfficials.find(main=>!relationships.some(link=>link.main_connected_account_id===main.id&&healthyRecoveryIds.has(link.recovery_connected_account_id)));
  const setupSteps=configureAccountStepStates({officialCount:savedOfficials.length,backupCount:everyMainProtected?protectedMainCount:0,blockingIssue:actionRequired,recoveryHealthy:everyMainProtected});
  const issueRole=issueAccount&&savedBackups.some(account=>account.id===issueAccount.id)?"backup" as const:"official" as const;
  const guidance=configureAccountGuidance({officialCount:savedOfficials.length,backupCount:protectedMainCount,blockingIssue:actionRequired,recoveryHealthy:everyMainProtected,issueLabel:issueAccount?.label,issueRole});
  useEffect(()=>{if(!state.savedAccounts||handledSuccessfulSave.current)return;handledSuccessfulSave.current=true;router.push("/dashboard");},[state.savedAccounts,router]);
  useEffect(()=>{if(!open)return;const node=flowDialogRef.current??dialogRef.current;node?.querySelector<HTMLElement>('button:not([disabled]),a[href],input:not([disabled])')?.focus();const key=(event:KeyboardEvent)=>{if(event.key==="Escape"){event.preventDefault();if(flow){setFlow(null);setFlowAccount(null);}else closeModal();return;}if(event.key!=="Tab"||!node)return;const focusable=[...node.querySelectorAll<HTMLElement>('button:not([disabled]),a[href],input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])')].filter(item=>item.offsetParent!==null);if(!focusable.length)return;const first=focusable[0],last=focusable.at(-1)!;if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}};document.addEventListener("keydown",key);return()=>document.removeEventListener("keydown",key);});
  function openModal(trigger:HTMLElement){returnFocus.current=trigger;setDraft({officials:savedOfficials.map(accountDraft),backups:savedBackups.map(accountDraft)});setDirty(false);setOpen(true);}
  function closeModal(){if(dirty&&!window.confirm("Discard your unsaved changes?"))return;setOpen(false);setFlow(null);setFlowAccount(null);requestAnimationFrame(()=>returnFocus.current?.focus());}
  function change(recipe:(value:Draft)=>Draft){setDraft(recipe);setDirty(true);}
  function startFlow(role:"official"|"backup",index:number|null=null){
    if(index!==null){const item=role==="official"?draft.officials[index]:draft.backups[index];setFlowAccount({...item});setFlow({role,index,platformId:item.platformId,method:item.externalAccountId?"automatic":"manual",step:"method"});}
    else {setFlowAccount(null);setFlow({role,index:null,platformId:null,method:null,step:"picker"});}
  }
  function choosePlatform(platformId:PlatformId){const capability=capabilities.get(platformId as never);if(!capability?.connectable)return;const eligible=draft.officials.filter(item=>item.platformId===platformId&&item.id);setFlowAccount({platformId,value:"",label:"",isPublic:true,protectedOfficialAccountId:flow?.role==="backup"&&recoveryContextMainId?recoveryContextMainId:eligible.length===1?eligible[0].id:null});setFlow(current=>current?{...current,platformId,method:"automatic",step:"method"}:current);}
  function saveFlow(){if(!flow||!flowAccount)return;const list=flow.role==="official"?"officials":"backups";change(value=>({...value,[list]:flow.index===null?[...value[list],flowAccount]:value[list].map((item,index)=>index===flow.index?flowAccount:item)}));setFlow(null);setFlowAccount(null);}
  async function disconnectManagedMain(){if(!flow||flow.role!=="official"||flow.index===null)return;const account=draft.officials[flow.index];if(!account.id||!window.confirm(`Disconnect ${account.label||"Main account"}? Recovery accounts in this Recovery Network will remain connected.`))return;setRemoving(true);const result=await removeMainAccount(account.id);setRemoving(false);if(result.error){window.alert(result.error);return;}setFlow(null);setFlowAccount(null);router.refresh();}
  const filtered=searchPlatforms(query).filter(item=>item.id!=="more");
  const payload=JSON.stringify(draft);

  return <div className="platforms-workspace">
    {!open&&<RecoveryNetworkManager accounts={accounts} networks={networks} canCreateNetwork={!officialLocked} onConfigure={(role,mainAccountId,recoveryNetworkId)=>{setRecoveryContextMainId(role==="backup"?mainAccountId??null:null);setRecoveryContextNetworkId(role==="official"?recoveryNetworkId??null:null);const trigger=document.activeElement instanceof HTMLElement?document.activeElement:document.body;openModal(trigger);if(role==="official"&&mainAccountId){const index=draft.officials.findIndex(account=>account.id===mainAccountId);startFlow("official",index>=0?index:null);}else startFlow(role);}}/>}
    <section className="platform-library" aria-labelledby="platform-library-title"><div className="platform-library-heading"><div><p className="eyebrow">Platform library</p><h2 id="platform-library-title">Choose where you show up</h2></div><p>{PLATFORMS.length-1} supported destinations</p></div>
      <label className="platform-search"><Search size={20}/><span className="sr-only">Search platforms</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search platforms"/>{query&&<button type="button" aria-label="Clear search" onClick={()=>setQuery("")}><X size={16}/></button>}</label>
      <div className="platform-selector-grid">{filtered.map(platform=>{const Icon=platform.icon;const connected=accounts.some(a=>platformFromAccount(a.platform,a.url).id===platform.id);return <button key={platform.id} type="button" className="platform-option" onClick={e=>openModal(e.currentTarget)}><span className="platform-brand-icon" style={{color:platform.brandColor,background:platform.brandBackground}}><Icon size={28}/></span><span className="platform-card-copy"><strong>{platform.name}</strong><small>{platform.description}</small></span>{connected&&<span className="platform-connected-badge"><Check size={12}/> Connected</span>}</button>;})}</div>
    </section>
    <section className="connected-platforms" aria-labelledby="connected-platforms-title"><div className="connected-platforms-heading"><div><p className="eyebrow">Connected</p><h2 id="connected-platforms-title">Your platforms</h2><p>Your connected Main and Recovery accounts at a glance.</p></div><button type="button" className="button button-secondary connected-manage-accounts" onClick={e=>openModal(e.currentTarget)}><Plus size={16}/> Manage accounts <ChevronRight size={15}/></button></div>
      {accounts.length?<div className="connected-account-summary"><section className="connected-role-group is-main" aria-labelledby="connected-main-title"><header><div><small id="connected-main-title">Main accounts</small><strong>{savedOfficials.length} Main</strong></div><span className="connected-role-mark">Main</span></header>{savedOfficials.length?<ul>{savedOfficials.map(account=>{const provider=platformFromAccount(account.platform,account.url);return <li key={account.id} aria-label={`${provider.name} · ${account.label} — Main account`} title={`${provider.name} · ${account.label} — Main account`}><PlatformBrandIcon provider={provider.id} label={provider.name} size="sm"/><span><strong>{account.label}</strong><small>{provider.name}</small></span></li>;})}</ul>:<p>No Main accounts yet</p>}</section><span className="connected-summary-divider" aria-hidden/><section className="connected-role-group is-recovery" aria-labelledby="connected-recovery-title"><header><div><small id="connected-recovery-title">Recovery accounts</small><strong>{savedBackups.length} Recovery</strong></div><span className="connected-role-mark">Recovery</span></header>{savedBackups.length?<ul>{savedBackups.map(account=>{const provider=platformFromAccount(account.platform,account.url);return <li key={account.id} aria-label={`${provider.name} · ${account.label} — Recovery account`} title={`${provider.name} · ${account.label} — Recovery account`}><PlatformBrandIcon provider={provider.id} label={provider.name} size="sm"/><span><strong>{account.label}</strong><small>{provider.name}</small></span></li>;})}</ul>:<p>No Recovery accounts yet</p>}</section><p className={`connected-health-summary ${attentionCount?"needs-attention":"is-healthy"}`} role="status"><span/>{attentionCount?`${attentionCount} ${attentionCount===1?"account needs":"accounts need"} attention`:"All connected"}</p></div>:<div className="connected-empty"><span><Link2 size={20}/></span><div><strong>No connected platforms yet</strong><p>Set up a Recovery Network to connect your first Main and Recovery accounts.</p></div></div>}
    </section>

    {open&&<div className={`platform-modal-backdrop ${styles.backdrop}`} onMouseDown={e=>e.target===e.currentTarget&&closeModal()}><div ref={dialogRef} className={`platform-modal accounts-config-modal ${styles.modal}`} role="dialog" aria-modal="true" aria-labelledby="platform-editor-title" aria-describedby="platform-editor-description">
      <header className={`platform-editor-header ${styles.header}`}><div><span className={styles.headerMark} aria-hidden><ShieldCheck size={18}/></span><div><h2 id="platform-editor-title">Manage accounts <Sparkles size={14} aria-hidden/></h2><p id="platform-editor-description">Build your recovery network. Protect your audience beyond any single platform.</p></div></div><button type="button" aria-label="Close account management" onClick={closeModal}><X size={20}/></button></header>
      <div className={`platform-modal-body ${styles.body}`}>
        <section className={`setup-progress compact-progress ${styles.progress}`} aria-labelledby="setup-progress-title"><p className="account-step" id="setup-progress-title">Recovery journey</p><ol className={styles.progressTrack}>
          {[
            ["Main account","Connect the account your audience already knows."],
            ["Recovery destinations","Add trusted places followers can find you."],
            ["Protected","Your recovery network is ready."],
          ].map(([label,description],index)=><li key={label} className={`${styles.progressItem} ${styles[`step${setupSteps[index]}`]}`} aria-current={setupSteps[index]==="current"?"step":undefined}><i>{setupSteps[index]==="complete"?<Check size={18}/>:setupSteps[index]==="attention"?<TriangleAlert size={18}/>:index+1}</i><strong>{label}</strong><small>{description}</small><span className="sr-only">{setupSteps[index]}</span></li>)}
        </ol></section>
        <RecoveryNetworkManager accounts={accounts} networks={networks} canCreateNetwork={!officialLocked} onConfigure={(role,mainAccountId,recoveryNetworkId)=>{setRecoveryContextMainId(role==="backup"?mainAccountId??null:null);setRecoveryContextNetworkId(role==="official"?recoveryNetworkId??null:null);if(role==="official"&&mainAccountId){const index=draft.officials.findIndex(account=>account.id===mainAccountId);startFlow("official",index>=0?index:null);}else startFlow(role);}}/>
        {savedOfficials.length>0&&!everyMainProtected&&<aside className={`${styles.guidance} ${styles[`guidance${guidance.tone}`]}`} aria-labelledby="account-guidance-title"><span className={styles.guidanceIcon}><Bot size={22}/></span><div><p className="account-step">AudienceOwn guidance</p><h3 id="account-guidance-title">{actionRequired?guidance.title:"Complete this recovery network"}</h3><p>{actionRequired?guidance.body:`${guidanceMain?.label??"This Main account"} is connected but has no healthy Recovery destination yet. Add one to complete this recovery network.`}</p></div></aside>}
        {state.error&&<p className="platform-form-message error" role="alert">{state.error}</p>}{state.success&&<p className="platform-form-message success"><Check size={15}/>{state.success}</p>}
      </div>
      <footer className={`platform-editor-actions ${styles.footer}`}><span className={state.error?styles.footerError:dirty?styles.footerDirty:everyMainProtected?styles.footerHealthy:styles.footerIncomplete}>{state.error?<TriangleAlert size={16}/>:dirty?<Sparkles size={16}/>:everyMainProtected?<Check size={16}/>:<TriangleAlert size={16}/>} {state.error?"Unable to save account changes":dirty?"Unsaved manual account changes":everyMainProtected?"Your recovery networks are protected":savedOfficials.length?`${savedOfficials.length-protectedMainCount} Main accounts need Recovery destinations`:"Recovery setup incomplete"}</span><div><button type="button" className="button button-secondary" onClick={closeModal}>Close</button>{dirty&&<form action={action}><input type="hidden" name="payload" value={payload}/><button className="button button-primary" disabled={pending}>{pending?"Saving…":"Save manual changes"}</button></form>}</div></footer>
    {flow&&<div className="backup-flow-backdrop"><section ref={flowDialogRef} className="backup-flow-modal account-picker-modal" role="dialog" aria-modal="true" aria-labelledby="account-flow-title"><header><div>{flow.step==="method"&&<span className={`flow-header-icon ${flow.role==="official"?"is-main":"is-recovery"}`} aria-hidden><Plus/></span>}<div><h3 id="account-flow-title">{flow.step==="method"?`Add ${flow.role === "official" ? "a Main" : "a Recovery"} account`:flow.index===null?`Add ${flow.role === "official" ? "a Main" : "a Recovery"} account`:`Manage ${flow.role === "official" ? "Main" : "Recovery"} account`}</h3>{flow.step!=="method"&&<p>{flow.role==="backup"&&recoveryContextMainId?`Protecting: ${savedOfficials.find(main=>main.id===recoveryContextMainId)?.platform} · ${savedOfficials.find(main=>main.id===recoveryContextMainId)?.label}`:flow.step==="picker"?"Choose the platform you want to connect.":flow.platformId?getPlatform(flow.platformId)?.name:""}</p>}</div></div><button type="button" aria-label="Close" onClick={()=>{setFlow(null);setFlowAccount(null);}}><X size={18}/></button></header>
      {flow.step!=="picker"&&flowAccount&&(()=>{const canonicalConnected=canonicalAccountConnected({health:flowAccount.health,providerStatus:flowAccount.providerStatus,hasPublicUrl:Boolean(flowAccount.value),hasExternalAccountId:Boolean(flowAccount.externalAccountId)}),state=resolveConnectionStatus({health:flowAccount.health,providerStatus:flowAccount.providerStatus,canonicalConnected});return state.capabilityNotice?<aside className="platform-form-message" aria-label="Connection capability"><strong>Connection: {state.connectionLabel}</strong><p>{state.capabilityNotice}</p>{!state.actionRequired&&<p>No action is required from you.</p>}</aside>:null;})()}
      <div className="backup-flow-body">{flow.step==="picker"&&<>{(flow.role==="official"?officialLocked:backupLocked)&&<aside className="provider-upgrade-banner" aria-label="Free plan limit reached"><div className="provider-upgrade-status"><span className="provider-upgrade-lock" aria-hidden><LockKeyhole size={21}/></span><div><strong>You&apos;ve reached your Free plan limit.</strong><p>Free includes 1 {flow.role==="official"?"Main":"Recovery"} account.</p></div></div><p className="provider-upgrade-explanation">Upgrade to Pro to connect more Main accounts and Recovery destinations.</p><a className="button button-primary provider-upgrade-cta" href="/#pricing">Upgrade to Pro</a></aside>}<div className="official-platform-picker">{PLATFORMS.filter(p=>p.id!=="more").map(platform=>{const Icon=platform.icon,capability=capabilities.get(platform.id as never),connected=flow.role==="official"?connectedOfficial.has(platform.id):connectedBackup.has(platform.id),card=providerPickerState(capability,connected,flow.role,flow.role==="official"?officialLocked:backupLocked);return <button key={platform.id} type="button" disabled={card.disabled} data-connect-href={card.href??undefined} onClick={()=>choosePlatform(platform.id)}><span className="platform-brand-icon" style={{color:platform.brandColor,background:platform.brandBackground}}><Icon size={19}/></span><span><strong>{capability?.displayName??platform.name}</strong><small>{capability?.description??platform.description}</small></span><i className={card.tone}>{card.label==="Connected"?<><Check size={12}/> Connected</>:card.label.includes("Connect")?<>{card.label} <ChevronRight size={12}/></>:card.label}</i></button>;})}</div></>}
      {flow.step==="method"&&flow.platformId&&<ProviderConnectionMethodSelector platform={getPlatform(flow.platformId)!} capability={capabilities.get(flow.platformId as never)} value={flow.method} role={flow.role} onChange={method=>setFlow(current=>current?{...current,method}:current)}/>}
      {flow.step==="details"&&flow.platformId&&flowAccount&&<div className="manual-connection-fields"><label className="label" htmlFor="account-flow-value">{getPlatform(flow.platformId)!.fieldLabel}</label><div className="platform-url-input"><Link2 size={16}/><input id="account-flow-value" value={flowAccount.value} onChange={e=>setFlowAccount({...flowAccount,value:e.target.value})} placeholder={getPlatform(flow.platformId)!.placeholder}/></div>{flowAccount.value&&(()=>{const normalized=normalizePlatformAccount(flowAccount.platformId,flowAccount.value);return "error" in normalized?<p className="field-error">{normalized.error}</p>:null;})()}<label className="flow-label">Label <small>(optional)</small><input value={flowAccount.label??""} onChange={e=>setFlowAccount({...flowAccount,label:e.target.value})} placeholder={`e.g. ${getPlatform(flow.platformId)!.name} account`}/></label></div>}</div>
      <footer>{flow.step==="method"&&flow.platformId?<><button type="button" className="button button-secondary" onClick={()=>setFlow(current=>current?{...current,step:"picker",method:null}:current)}>Back</button><div className="provider-footer-actions"><button type="button" className="button button-secondary" onClick={()=>{setFlow(null);setFlowAccount(null);}}>Cancel</button>{flow.method==="automatic"?<a className="button button-primary provider-flow-primary" style={{"--provider-color":getPlatform(flow.platformId)!.brandColor} as React.CSSProperties} href={`${capabilities.get(flow.platformId as never)?.connectPath}?role=${flow.role}${flowAccount?.id?`&connectionId=${encodeURIComponent(flowAccount.id)}`:""}${recoveryContextMainId?`&recoveryForMainAccountId=${encodeURIComponent(recoveryContextMainId)}`:flowAccount?.protectedOfficialAccountId?`&protectedOfficialAccountId=${encodeURIComponent(flowAccount.protectedOfficialAccountId)}`:""}${recoveryContextNetworkId?`&recoveryNetworkId=${encodeURIComponent(recoveryContextNetworkId)}`:""}`}>Connect with {getPlatform(flow.platformId)!.name}<ChevronRight/></a>:<button type="button" className="button button-primary provider-flow-primary manual-primary" onClick={()=>setFlow(current=>current?{...current,step:"details"}:current)}>Continue with URL <ChevronRight/></button>}</div></>:<>{flow.role==="official"&&flow.index!==null&&<button type="button" className="button button-secondary" disabled={removing} onClick={disconnectManagedMain}><Trash2 size={15}/>{removing?"Disconnecting…":"Disconnect Main account"}</button>}<button type="button" className="button button-secondary" onClick={()=>flow.step==="picker"?(setFlow(null),setFlowAccount(null)):setFlow(current=>current?{...current,step:"method"}:current)}>{flow.step==="picker"?"Cancel":"Back"}</button>{flow.step==="details"&&<button type="button" className="button button-primary" disabled={!flowAccount?.value.trim()} onClick={saveFlow}>Save account</button>}</>}</footer>
    </section></div>}
    </div></div>}
  </div>;
}
