"use client";
import Link from "next/link";
import { useActionState, useEffect, useMemo, useRef, useState } from "react";
import { AlertTriangle, ArrowRight, CalendarClock, CalendarDays, CheckCircle2, ChevronDown, CircleAlert, Clock3, ExternalLink, FileText, Filter, Mail, MailPlus, Megaphone, Mic2, MoreHorizontal, Package, Play, Radio, Search, ShieldAlert, ShieldCheck, Siren, Sparkles, Trash2, Users, XCircle } from "lucide-react";
import { activityMatchesTab, activityMetrics, type ActivityItem, type ActivityTab } from "@/lib/updates-activity";
import { PlatformBrandIcon } from "@/components/dashboard/platform-brand-icon";
import { CREATE_EMERGENCY_ENTRY_ROUTE, CREATE_UPDATE_ENTRY_ROUTE } from "@/lib/dashboard-routes";
import { cancelScheduledUpdate, deleteDraft, type UpdateActionState } from "@/app/dashboard/updates/actions";
import "./updates-activity-command-center.css";

type Attention={id:string;platform:string;label:string;reason:string;href:string};
const tabs=["all","updates","emergency","account","scheduled","failed"] as const satisfies readonly ActivityTab[];
const labels={all:"All",updates:"Updates",emergency:"Emergency",account:"Account Activity",scheduled:"Scheduled",failed:"Failed"};
const statusLabels={delivered:"Delivered",scheduled:"Scheduled",failed:"Failed",draft:"Draft",active:"Emergency",resolved:"Resolved",cancelled:"Cancelled",attention:"Action required",pending:"Pending"};
const subtypePresentation:Record<string,{label:string;tone:string;Icon:typeof Play}>={new_video:{label:"New video",tone:"violet",Icon:Play},livestream:{label:"Livestream",tone:"pink",Icon:Radio},podcast_episode:{label:"Podcast episode",tone:"rose",Icon:Mic2},product_release:{label:"Product release",tone:"cyan",Icon:Package},event:{label:"Event",tone:"green",Icon:CalendarDays},general_announcement:{label:"General announcement",tone:"purple",Icon:Megaphone},community_update:{label:"Community update",tone:"indigo",Icon:Users},account_inaccessible:{label:"Account inaccessible",tone:"emergency",Icon:ShieldAlert},platform_migration:{label:"Platform migration",tone:"emergency",Icon:ShieldAlert},connection_attention:{label:"Account activity",tone:"account",Icon:AlertTriangle}};
const statusIcons={delivered:CheckCircle2,scheduled:Clock3,failed:XCircle,draft:FileText,active:Siren,resolved:CheckCircle2,cancelled:XCircle,attention:AlertTriangle,pending:Clock3};
function dateHeading(value:string,now:Date){const date=new Date(value),day=new Date(date.getFullYear(),date.getMonth(),date.getDate()),today=new Date(now.getFullYear(),now.getMonth(),now.getDate()),difference=Math.round((today.getTime()-day.getTime())/86400000);return difference===0?"Today":difference===1?"Yesterday":new Intl.DateTimeFormat("en",{dateStyle:"long"}).format(date)}
function time(value:string){return new Intl.DateTimeFormat("en",{hour:"numeric",minute:"2-digit",timeZoneName:"short"}).format(new Date(value))}
function contextDisplay(item:ActivityItem){if(!item.accountDisplay)return null;const prefix=item.platform?`${item.platform} · `:"";return prefix&&item.accountDisplay.toLowerCase().startsWith(prefix.toLowerCase())?item.accountDisplay.slice(prefix.length):item.accountDisplay}
const primaryLabels={CONTINUE_DRAFT:"Continue editing",MANAGE_SCHEDULE:"Manage",REVIEW_FAILURE:"Review & retry",VIEW_DETAILS:"View details"} as const;
async function unavailableDraftAction(state:UpdateActionState,data:FormData):Promise<UpdateActionState>{void state;void data;return{error:"This draft is unavailable."}}
async function unavailableScheduleAction(state:UpdateActionState,data:FormData):Promise<UpdateActionState>{void state;void data;return{error:"This scheduled update is unavailable."}}
function ActivityManagementActions({item}:{item:ActivityItem}){
 const[confirmation,setConfirmation]=useState<"delete"|"cancel"|null>(null),[menuOpen,setMenuOpen]=useState(false),policy=item.managementPolicy,updateId=item.canonicalUpdateId,confirmRef=useRef<HTMLElement>(null),menuRef=useRef<HTMLDivElement>(null),menuButtonRef=useRef<HTMLButtonElement>(null),returnFocus=useRef<HTMLElement|null>(null);
 const[deleteState,deleteAction,deleting]=useActionState<UpdateActionState,FormData>(updateId?deleteDraft.bind(null,updateId):unavailableDraftAction,{});
 const[cancelState,cancelAction,cancelling]=useActionState<UpdateActionState,FormData>(updateId?cancelScheduledUpdate.bind(null,updateId):unavailableScheduleAction,{});
 useEffect(()=>{if(!menuOpen)return;menuRef.current?.querySelector<HTMLElement>('[role="menuitem"]')?.focus();const close=(event:KeyboardEvent)=>{if(event.key==="Escape"){event.preventDefault();setMenuOpen(false);requestAnimationFrame(()=>menuButtonRef.current?.focus());}};document.addEventListener("keydown",close);return()=>document.removeEventListener("keydown",close)},[menuOpen]);
 useEffect(()=>{if(!confirmation)return;const dialog=confirmRef.current,buttons=[...(dialog?.querySelectorAll<HTMLElement>('button:not([disabled]),a[href]')??[])];buttons[0]?.focus();const close=(event:KeyboardEvent)=>{if(event.key==="Escape"){event.preventDefault();setConfirmation(null);requestAnimationFrame(()=>returnFocus.current?.focus());return}if(event.key!=="Tab"||!buttons.length)return;const first=buttons[0],last=buttons.at(-1)!;if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}};document.addEventListener("keydown",close);return()=>document.removeEventListener("keydown",close)},[confirmation]);
 function ask(kind:"delete"|"cancel"){returnFocus.current=menuButtonRef.current;setMenuOpen(false);setConfirmation(kind)}
 if(!policy||!item.detailHref)return item.actionHref?<Link href={item.actionHref}>Manage account <ArrowRight size={13}/></Link>:null;
 const primary=policy.primaryAction;
 return <><div className="event-actions">{primary&&<Link className={`event-primary action-${primary.toLowerCase()}`} href={item.detailHref}>{primaryLabels[primary]} <ArrowRight size={13}/></Link>}
  {(policy.canDelete||policy.canCancel||policy.canView)&&<div className="event-menu"><button ref={menuButtonRef} type="button" aria-haspopup="menu" aria-expanded={menuOpen} aria-label={`More actions for ${item.description}`} onClick={()=>setMenuOpen(value=>!value)}><MoreHorizontal size={17}/></button>{menuOpen&&<div ref={menuRef} role="menu">{policy.canView&&primary!=="VIEW_DETAILS"&&<Link role="menuitem" tabIndex={0} href={item.detailHref}>View details</Link>}{policy.canReschedule&&<Link role="menuitem" tabIndex={0} href={item.detailHref}>Edit schedule</Link>}{policy.canCancel&&<button role="menuitem" type="button" onClick={()=>ask("cancel")}>Cancel scheduled update</button>}{policy.canDelete&&<button role="menuitem" type="button" className="destructive" onClick={()=>ask("delete")}><Trash2 size={14}/>Delete draft</button>}</div>}</div>}
 </div>{item.insight&&<aside className="event-ai-insight"><Sparkles size={14}/><div><strong>AI insight</strong><p>{item.insight.message}</p></div></aside>}
 {confirmation&&<div className="activity-confirm-backdrop" role="presentation" onMouseDown={event=>event.target===event.currentTarget&&setConfirmation(null)}><section ref={confirmRef} className="activity-confirm" role="alertdialog" aria-modal="true" aria-labelledby={`confirm-${item.id}`} aria-describedby={`confirm-copy-${item.id}`}><span className="confirm-icon"><AlertTriangle size={20}/></span><h3 id={`confirm-${item.id}`}>{confirmation==="delete"?"Delete This Update?":"Cancel This Scheduled Update?"}</h3><p id={`confirm-copy-${item.id}`}>{confirmation==="delete"?"This removes the draft from AudienceOwn. This action cannot be undone.":"It will not be delivered at the scheduled time. The communication remains available as a draft."}</p>{(deleteState.error||cancelState.error)&&<p className="confirm-error" role="alert">{deleteState.error??cancelState.error}</p>}<div><button type="button" onClick={()=>{setConfirmation(null);requestAnimationFrame(()=>returnFocus.current?.focus())}}>{confirmation==="delete"?"Cancel":"Keep Scheduled"}</button><form action={confirmation==="delete"?deleteAction:cancelAction}><button className="destructive" disabled={deleting||cancelling}>{deleting?"Deleting…":cancelling?"Cancelling…":confirmation==="delete"?"Delete Update":"Cancel Schedule"}</button></form></div></section></div>}</>;
}
function EventCard({item}:{item:ActivityItem}){const presentation=subtypePresentation[item.subtype]??{label:item.subtype.replaceAll("_"," "),tone:item.kind,Icon:item.kind==="emergency"?ShieldAlert:item.kind==="account"?AlertTriangle:Mail},StatusIcon=statusIcons[item.status],account=contextDisplay(item),destination=item.recoveryDestinationSnapshot?.split(" · ")??[],action=item.detailHref??item.actionHref,family=item.kind==="update"?"Update":item.kind==="emergency"?"Emergency":"Account activity";return <article className={`activity-event tone-${item.kind} subtype-${presentation.tone} status-${item.status}`} aria-label={`${family}: ${presentation.label}, ${statusLabels[item.status]}`}>
 <time dateTime={item.occurredAt}>{time(item.occurredAt)}</time><span className="timeline-node" aria-hidden/><span className="event-icon" aria-hidden><presentation.Icon size={19}/></span>
 <div className="event-copy"><div className="event-topline"><p>{family}</p><span className={`event-status status-${item.status}`}><StatusIcon size={12}/>{statusLabels[item.status]}</span></div><h4>{presentation.label}</h4>
 {(item.platform||account)&&<div className="event-account">{item.platform&&<PlatformBrandIcon provider={item.platform} label={item.platform} size="sm"/>}<span>{item.platform&&<strong>{item.platform}</strong>}{account&&<small>{account}</small>}</span></div>}
 <p className="event-description">{item.description}</p>{item.messagePreview&&<blockquote>{item.messagePreview}</blockquote>}
 {(item.recoveryDestinationSnapshot||item.recipientCount!==null)&&<div className="event-detail-grid">{item.recoveryDestinationSnapshot&&<div className="event-destination"><span>Recovery destination</span><div>{destination[0]&&<PlatformBrandIcon provider={destination[0].toLowerCase()} label={destination[0]} size="sm"/>}<strong>{item.recoveryDestinationSnapshot}</strong></div></div>}{item.recipientCount!==null&&<div className="event-recipients"><span>{item.status==="delivered"?"Delivered audience":"Prepared audience"}</span><strong>{item.recipientCount.toLocaleString()} recipient{item.recipientCount===1?"":"s"}</strong></div>}</div>}
 {action&&<ActivityManagementActions item={item}/>} 
 </div></article>}
export function UpdatesActivityCommandCenter({items,attention,generatedAt,available=true,notice=null}:{items:ActivityItem[];attention:Attention[];generatedAt:string;available?:boolean;notice?:string|null}){
 const[tab,setTab]=useState<typeof tabs[number]>("all"),[range,setRange]=useState<"7"|"30"|"90"|"all">("7"),[query,setQuery]=useState(""),[platform,setPlatform]=useState("all"),[limit,setLimit]=useState(20),now=useMemo(()=>new Date(generatedAt),[generatedAt]);
 const platforms=useMemo(()=>[...new Set(items.map(item=>item.platform).filter((value):value is string=>Boolean(value)))].sort(),[items]);
 const metrics=activityMetrics(items,attention.length,now,range),cutoff=range==="all"?null:new Date(now.getTime()-Number(range)*86400000).toISOString();
 const metricCards=[
  {label:"Updates sent",value:metrics.sent,support:"Successfully sent in this period",tone:"purple",Icon:Mail},
  {label:"Scheduled",value:metrics.scheduled,support:"Upcoming communications",tone:"cyan",Icon:CalendarClock},
  {label:"Failed",value:metrics.failed,support:"Requires attention in this period",tone:"red",Icon:AlertTriangle},
  {label:"Accounts need attention",value:metrics.attention,support:"Current connection issues",tone:"amber",Icon:ShieldAlert},
 ];
 const filtered=items.filter(item=>(!cutoff||item.occurredAt>=cutoff)&&activityMatchesTab(item,tab)&&(platform==="all"||item.platform===platform)&&(!query||[item.title,item.description,item.messagePreview,item.platform,item.accountDisplay,item.subtype,item.status].some(value=>value?.toLowerCase().includes(query.toLowerCase()))));
 const grouped=new Map<string,ActivityItem[]>();for(const item of filtered.slice(0,limit)){const heading=dateHeading(item.occurredAt,now);grouped.set(heading,[...(grouped.get(heading)??[]),item])}
 return <main className="activity-command-center">
  {notice&&<p className="activity-toast" role="status"><CheckCircle2 size={15}/>{notice}</p>}
  <header className="activity-header"><div><p className="activity-eyebrow">Direct connection</p><h1>Updates &amp; <span>Activity</span></h1><p>Track your communications, account activity, and recovery events across all connected platforms.</p></div><div className="activity-header-actions"><Link prefetch={false} href={CREATE_UPDATE_ENTRY_ROUTE} className="activity-button primary"><MailPlus size={16}/>Create Update<ArrowRight size={14}/></Link><Link prefetch={false} href={CREATE_EMERGENCY_ENTRY_ROUTE} className="activity-button emergency"><Siren size={16}/>Send Emergency Alert<ArrowRight size={14}/></Link></div></header>
  <section className="activity-summary" aria-label="Activity summary">{metricCards.map(({label,value,support,tone,Icon})=><article className={`activity-metric ${tone}`} key={label}><span><Icon size={20}/></span><strong>{available?value:"—"}</strong><h2>{label}</h2><p>{available?support:"Not available yet"}</p></article>)}</section>
  <div className="activity-toolbar"><div className="activity-tabs" role="tablist" aria-label="Filter activity">{tabs.map(value=><button key={value} role="tab" aria-selected={tab===value} onClick={()=>{setTab(value);setLimit(20)}}>{labels[value]}</button>)}</div><label className="range-select"><span>Date range</span><CalendarClock size={15}/><select value={range} onChange={event=>{setRange(event.target.value as typeof range);setLimit(20)}}><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">90 days</option><option value="all">All time</option></select><ChevronDown size={14}/></label></div>
  <div className="activity-controls"><label className="activity-search"><span className="sr-only">Search activity</span><Search size={17}/><input value={query} onInput={event=>{setQuery(event.currentTarget.value);setLimit(20)}} placeholder="Search activity..."/></label><label className="activity-filter"><Filter size={15}/><span>Filter</span><select aria-label="Filter by platform" value={platform} onChange={event=>{setPlatform(event.target.value);setLimit(20)}}><option value="all">All platforms</option>{platforms.map(value=><option key={value} value={value}>{value}</option>)}</select><ChevronDown size={13}/></label></div>
  <div className="activity-layout"><section className="activity-timeline" aria-labelledby="activity-title"><div className="activity-section-title"><div><p>Activity timeline</p><h2 id="activity-title">What happened</h2></div><span>{filtered.length} events</span></div>
   {!available?<div className="activity-empty"><CircleAlert size={28}/><h3>Activity history is unavailable</h3><p>We could not load operational history right now. No saved updates were changed.</p></div>:filtered.length===0?<div className="activity-empty"><span><Mail size={28}/><Sparkles size={14}/></span><h3>{items.length?"No activity matches these filters.":"Your first update starts here."}</h3><p>{items.length?"Try another date range, platform, search, or activity type.":"Create an update or use a recovery workflow when your audience needs to hear from you."}</p><div><Link prefetch={false} href={CREATE_UPDATE_ENTRY_ROUTE} className="activity-button primary">Create Update</Link><Link prefetch={false} href={CREATE_EMERGENCY_ENTRY_ROUTE} className="activity-button emergency">Send Emergency Alert</Link></div></div>:[...grouped].map(([heading,events])=><section className="activity-day" key={heading}><h3>{heading}</h3><div>{events.map(item=><EventCard item={item} key={item.id}/>)}</div></section>)}
   {filtered.length>limit&&<button className="activity-load-more" onClick={()=>setLimit(value=>value+20)}>Load more</button>}
  </section><aside className="activity-rail"><section className="attention-panel"><header><div><p>Needs attention</p><h2>Connected accounts</h2></div><span>{attention.length}</span></header>{attention.length?<div>{attention.map(issue=><article key={issue.id}><PlatformBrandIcon provider={issue.platform} label={issue.platform} size="sm"/><div><strong>{issue.label}</strong><p>{issue.reason}</p></div><Link href={issue.href}>Manage <ExternalLink size={12}/></Link></article>)}</div>:<div className="attention-empty"><ShieldCheck size={24}/><strong>All connected accounts look good.</strong><p>No current account issues require action.</p></div>}</section><section className="quick-actions"><p>Quick actions</p><h2>Keep moving</h2><nav><Link prefetch={false} href={CREATE_UPDATE_ENTRY_ROUTE}><MailPlus size={17}/>Create Update<ArrowRight size={13}/></Link><Link prefetch={false} href={CREATE_EMERGENCY_ENTRY_ROUTE}><Siren size={17}/>Send Emergency Alert<ArrowRight size={13}/></Link><Link href="/dashboard/platforms"><ShieldAlert size={17}/>Manage Accounts<ArrowRight size={13}/></Link><Link href="/dashboard/analytics/recovery"><ExternalLink size={17}/>View Recovery Analytics<ArrowRight size={13}/></Link></nav></section></aside></div>
 </main>
}
