"use client";

import { useRef, useState } from "react";
import { CheckCircle2, CircleAlert, RefreshCw, ShieldCheck, Unplug, X } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { connectionHealthLabels, connectionHealthState, isProviderDataStale, relativeProviderUpdate } from "@/lib/social-providers/connection-health";

type Connection = { id: string; account_type: string; label: string; url: string; external_account_name: string | null; connection_health: string | null;
  external_account_id: string | null; lease_expires_at: string | null; capability_state: unknown;
  last_connection_error: string | null; last_sync_at: string | null; granted_scopes: string[] | null; watch_enabled: boolean };
type Feedback = { kind: "success"|"error"; text: string } | null;

function failureCategory(value: unknown) { const root=value&&typeof value==="object"?value as Record<string,unknown>:{};const reliability=root.reliability&&typeof root.reliability==="object"?root.reliability as Record<string,unknown>:{};return typeof reliability.lastFailureCategory==="string"?reliability.lastFailureCategory:null; }
function authorizationStatus(connection: Connection) {
  const health=connectionHealthState({externalAccountId:connection.external_account_id,health:connection.connection_health,leaseExpiresAt:connection.lease_expires_at,failureCategory:failureCategory(connection.capability_state)});
  if (health === "healthy") return { health, label: connectionHealthLabels[health], tone: "text-emerald-300", Icon: CheckCircle2 };
  if (health === "syncing") return { health, label: connectionHealthLabels[health], tone: "text-cyan-200", Icon: RefreshCw };
  return { health, label: connectionHealthLabels[health], tone: "text-amber-200", Icon: CircleAlert };
}

export function YouTubeConnectionManager({ connection }: { connection: Connection | null }) {
  const router = useRouter(); const dialog = useRef<HTMLDialogElement>(null); const [busy,setBusy]=useState(false); const [feedback,setFeedback]=useState<Feedback>(null);
  async function disconnect(mode: "keep_manual"|"remove_account") { setBusy(true); setFeedback(null);
    try { const response=await fetch("/api/integrations/youtube/disconnect",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({connectionId:connection?.id,mode})});
      const result=await response.json().catch(()=>({})) as {status?:string;error?:string};
      if(!response.ok&&response.status!==202){setFeedback({kind:"error",text:result.error??"YouTube could not be disconnected. The connection remains disabled; please retry."});return;}
      setFeedback({kind:"success",text:result.status==="revocation_pending"?"Provider access and synchronization are disabled. Google revocation is still pending, so cleanup will need to be retried.":"YouTube disconnected and authorized data was removed."}); dialog.current?.close(); router.refresh();
    } catch { setFeedback({kind:"error",text:"YouTube could not be disconnected. Check your connection and try again."}); } finally { setBusy(false); }
  }
  const status=connection?authorizationStatus(connection):null; const StatusIcon=status?.Icon;
  return <section className="surface rounded-2xl p-6 sm:p-8" aria-labelledby="youtube-connection-heading">
    <div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div><p className="eyebrow">Connection controls</p><h2 id="youtube-connection-heading" className="mt-2 text-2xl font-semibold">Manage YouTube authorization</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-zinc-400">Reconnect or securely disconnect the authorized channel. This authorization is separate from Google Sign-In.</p></div><span className="inline-flex w-fit items-center gap-2 rounded-full bg-cyan-400/10 px-3 py-2 text-sm text-cyan-200"><ShieldCheck aria-hidden size={15}/> Read-only access</span></div>
    {connection&&status&&StatusIcon ? <div className="mt-7 grid gap-4"><div className="rounded-xl border border-white/10 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><strong>{connection.external_account_name??connection.label}</strong>{connection.url&&<a className="ml-3 text-xs text-violet-300 hover:text-violet-200 focus-visible:outline focus-visible:outline-2 focus-visible:outline-violet-400" href={connection.url} target="_blank" rel="noreferrer">View channel</a>}</div><span className={`flex items-center gap-1.5 text-sm ${status.tone}`}><StatusIcon aria-hidden size={15}/> {status.label}</span></div><dl className="mt-5 grid gap-4 text-sm sm:grid-cols-3"><div><dt className="text-zinc-500">Subscriber metrics</dt><dd className="mt-1">{connection.watch_enabled?"Synchronization active":"Synchronization stopped"}</dd></div><div><dt className="text-zinc-500">Data freshness</dt><dd className="mt-1 flex flex-wrap items-center gap-2">{relativeProviderUpdate(connection.last_sync_at)}{isProviderDataStale(connection.last_sync_at)&&<span className="rounded-full bg-amber-300/10 px-2 py-0.5 text-xs text-amber-200">Stale</span>}</dd></div><div><dt className="text-zinc-500">Authorization health</dt><dd className="mt-1">{status.label}</dd></div></dl>{status.health==="action_required"&&<p className="mt-4 rounded-lg bg-amber-300/5 p-3 text-sm leading-6 text-amber-100">YouTube authorization needs attention. Reconnect the channel, or disconnect it if you no longer want to grant access.</p>}{status.health==="temporarily_unavailable"&&<p className="mt-4 rounded-lg bg-cyan-300/5 p-3 text-sm leading-6 text-cyan-100">YouTube is temporarily unavailable. Your last known data remains visible while AudienceOwn retries automatically.</p>}<details className="mt-4 text-sm"><summary className="cursor-pointer text-zinc-400 hover:text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-violet-400">Technical permission details</summary><p className="mt-2 text-zinc-500">Google scope: youtube.readonly. This permits viewing YouTube account and channel information; it does not permit uploads, edits, or deletions.</p></details></div>
      <div className="flex flex-col gap-3 sm:flex-row">{status.health==="action_required"&&<Link prefetch={false} className="button button-primary min-h-11 w-full justify-center sm:w-auto" href={`/api/integrations/youtube/connect?role=${connection.account_type === "backup" ? "backup" : "official"}&connectionId=${encodeURIComponent(connection.id)}`}><RefreshCw aria-hidden size={15}/> Reconnect YouTube</Link>}<button disabled={busy} className="button button-secondary min-h-11 w-full justify-center focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-violet-400 sm:w-auto" onClick={()=>dialog.current?.showModal()}><Unplug aria-hidden size={15}/> Disconnect YouTube</button></div>
      <dialog ref={dialog} aria-labelledby="youtube-disconnect-title" aria-describedby="youtube-disconnect-description" className="m-auto w-[calc(100%-2rem)] max-w-xl rounded-2xl border border-white/10 bg-zinc-950 p-0 text-white shadow-2xl backdrop:bg-black/75" onClose={()=>setFeedback(null)}><div className="p-6 sm:p-7"><div className="flex items-start justify-between gap-4"><h3 id="youtube-disconnect-title" className="text-xl font-semibold">Disconnect YouTube?</h3><button type="button" aria-label="Close disconnect dialog" disabled={busy} className="grid size-10 place-items-center rounded-lg text-zinc-400 hover:bg-white/5 hover:text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-violet-400" onClick={()=>dialog.current?.close()}><X aria-hidden size={18}/></button></div><p id="youtube-disconnect-description" className="mt-3 text-sm leading-6 text-zinc-400">Synchronization stops immediately. AudienceOwn asks Google to remove the authorization and deletes encrypted credentials and authorized YouTube data. Your public channel URL can remain if you choose.</p><div className="mt-6 grid gap-3"><button type="button" disabled={busy} className="button button-secondary min-h-12 justify-start text-left" onClick={()=>disconnect("keep_manual")}>{busy?"Disconnecting…":"Disconnect authorization, keep the public channel URL"}</button><button type="button" disabled={busy} className="button min-h-12 justify-start bg-red-600 text-left text-white hover:bg-red-500" onClick={()=>disconnect("remove_account")}>{busy?"Disconnecting…":"Disconnect authorization and remove the YouTube account"}</button><button type="button" disabled={busy} className="button button-secondary min-h-11" onClick={()=>dialog.current?.close()}>Cancel</button></div></div></dialog>
    </div> : <div className="mt-7 rounded-xl border border-dashed border-white/15 p-6"><p className="font-medium text-zinc-200">No authorized YouTube channel</p><p className="mt-2 text-sm leading-6 text-zinc-400">Connect YouTube for read-only channel information and supported subscriber metrics. A manually added YouTube URL remains a separate public account.</p><Link prefetch={false} className="button button-primary mt-4 min-h-11" href="/api/integrations/youtube/connect?role=official">Connect YouTube</Link></div>}
    {feedback&&<p role={feedback.kind==="error"?"alert":"status"} aria-live="polite" className={`mt-5 rounded-lg border p-3 text-sm ${feedback.kind==="error"?"border-amber-300/20 bg-amber-300/5 text-amber-100":"border-emerald-300/20 bg-emerald-300/5 text-emerald-100"}`}>{feedback.text}</p>}
    <div className="mt-8 grid gap-5 lg:grid-cols-2"><div className="rounded-xl bg-white/[.03] p-5"><h3 className="font-semibold">What read-only access allows</h3><ul className="mt-3 list-disc space-y-2 pl-5 text-sm text-zinc-400"><li>View your YouTube account</li><li>Read public channel information</li><li>Read subscriber statistics when available</li><li>Read public upload metadata</li></ul></div><div className="rounded-xl bg-white/[.03] p-5"><h3 className="font-semibold">What it never allows</h3><ul className="mt-3 list-disc space-y-2 pl-5 text-sm text-zinc-400"><li>Upload, edit, or delete videos</li><li>Manage comments</li><li>Change channel settings</li><li>Access your Google password</li></ul></div></div>
  </section>;
}
