import Link from "next/link";
import { LogOut, Mail, ShieldAlert } from "lucide-react";
import { logout } from "@/app/(auth)/actions";
import { AccountDeletionForm } from "@/components/account-deletion-form";
import { requireViewer } from "@/lib/dal";
import { SubmitButton } from "@/components/submit-button";
import { isAppAdmin } from "@/lib/app-admin";

function authenticationMethod(user: Awaited<ReturnType<typeof requireViewer>>) {
  const providers = new Set([user.app_metadata.provider, ...(user.app_metadata.providers ?? [])].filter((value): value is string => typeof value === "string"));
  if (providers.has("google") && providers.has("email")) return "Email and Google Sign-In";
  if (providers.has("google")) return "Google Sign-In";
  return "Email and password";
}

function formatAccountDate(value: string | null | undefined) {
  return value ? new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Unavailable";
}

export default async function AccountSettingsPage(){const user=await requireViewer();const admin=await isAppAdmin(user.id);return <><header><p className="eyebrow">Settings</p><h1 className="mt-2 text-3xl font-semibold">Account</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-zinc-400">Review how you sign in, when this account was created, and the controls that affect the whole account.</p>{admin&&<span className="mt-5 inline-flex rounded-full border border-violet-300/20 bg-violet-400/10 px-3 py-1 text-xs font-medium text-violet-200">AudienceOwn Admin</span>}</header>
  <section className="surface mt-8 rounded-2xl p-6 sm:p-8" aria-labelledby="account-information-heading"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-violet-400/10 text-violet-300"><Mail aria-hidden size={18}/></span><h2 id="account-information-heading" className="text-xl font-semibold">Account information</h2></div><dl className="mt-6 divide-y divide-white/[.07] text-sm"><div className="grid gap-1 py-4 sm:grid-cols-[180px_1fr]"><dt className="text-zinc-500">Email</dt><dd className="break-all text-zinc-200">{user.email??"Unavailable"}</dd></div><div className="grid gap-1 py-4 sm:grid-cols-[180px_1fr]"><dt className="text-zinc-500">Authentication</dt><dd className="text-zinc-200">{authenticationMethod(user)}</dd></div><div className="grid gap-1 py-4 sm:grid-cols-[180px_1fr]"><dt className="text-zinc-500">Account created</dt><dd className="text-zinc-200">{formatAccountDate(user.created_at)}</dd></div><div className="grid gap-1 py-4 sm:grid-cols-[180px_1fr]"><dt className="text-zinc-500">Most recent sign-in</dt><dd className="text-zinc-200">{formatAccountDate(user.last_sign_in_at)}</dd></div></dl><p className="mt-4 text-xs leading-5 text-zinc-500">Google Sign-In and a YouTube connection are separate. This page does not detach sign-in methods.</p></section>
  <section className="surface mt-6 rounded-2xl p-6 sm:p-8" aria-labelledby="account-session-heading"><h2 id="account-session-heading" className="text-xl font-semibold">Current browser session</h2><p className="mt-2 text-sm leading-6 text-zinc-400">Sign out when you are finished on a shared device. Active session management across other devices is not available.</p><form action={logout} className="mt-5"><SubmitButton pendingText="Signing out…" className="button button-secondary min-h-11 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-violet-400"><LogOut aria-hidden size={16}/> Sign out</SubmitButton></form></section>
  <section className="mt-6 rounded-2xl border border-red-500/25 bg-red-500/5 p-6 sm:p-8" aria-labelledby="danger-zone-heading"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-red-400/10 text-red-300"><ShieldAlert aria-hidden size={18}/></span><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-red-300">Danger zone</p><h2 id="danger-zone-heading" className="mt-1 text-xl font-semibold text-red-100">Delete AudienceOwn account</h2></div></div><p id="account-deletion-description" className="mt-5 max-w-2xl text-sm leading-6 text-zinc-300">Deletion is intended to be permanent. It disables and revokes connected providers, removes encrypted credentials and authorized Google and YouTube data, stops synchronization, deletes creator-owned application data, invalidates sessions, and deletes the authentication account last. Content hosted by YouTube is never deleted.</p><p className="mt-3 max-w-2xl text-sm leading-6 text-zinc-400">A sign-in from the last 15 minutes is required. If provider cleanup cannot finish, deletion stops and shows a retryable error instead of reporting success. <Link className="text-violet-300 underline-offset-4 hover:underline focus-visible:outline focus-visible:outline-2 focus-visible:outline-violet-400" href="/contact?topic=account_sign_in">Contact support</Link> if you need help.</p><AccountDeletionForm/></section>
  <nav aria-label="Account policy links" className="mt-8 flex flex-wrap gap-4 text-sm text-zinc-500"><Link className="hover:text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-violet-400" href="/data-deletion">Data deletion details</Link><Link className="hover:text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-violet-400" href="/privacy">Privacy</Link></nav></>}
