import { randomUUID } from "node:crypto";
import { createAdminClient } from "@/lib/supabase/admin";
import { isDeliveryWorkerAuthorized } from "@/lib/delivery-worker-auth";
import { audienceProviders, type AudienceProvider } from "@/lib/platform-audience/types";
import { decryptMetricCredential, fetchProviderAudienceMetric, nextAudienceSync, safeMetricError } from "@/lib/platform-audience/server";
import { providerAudienceCapabilities } from "@/lib/platform-audience/capabilities";
import { revalidateCreatorAccounts } from "@/lib/social-providers/creator-account-revalidation";

export async function POST(request:Request){
 if(!isDeliveryWorkerAuthorized(request.headers.get("authorization"),process.env.PROVIDER_AUDIENCE_METRICS_WORKER_SECRET))return Response.json({error:"Unauthorized"},{status:401});
 const db=createAdminClient();if(!db)return Response.json({error:"Unavailable"},{status:503});const limit=Math.max(1,Math.min(Number(process.env.PROVIDER_AUDIENCE_METRICS_BATCH_SIZE??20),100)),owner=randomUUID();
 const[{data:accounts},{data:assets},{data:existing}]=await Promise.all([db.from("connected_accounts").select("id,creator_id,platform,account_type").in("platform",[...audienceProviders]).in("connection_health",["healthy","degraded"]),db.from("provider_asset_bindings").select("id,creator_id,connected_account_id,provider,asset_type,authority_status").in("provider",[...audienceProviders]),db.from("provider_audience_metrics").select("connection_id,asset_binding_id")]);
 for(const account of accounts??[]){const provider=account.platform as AudienceProvider,capability=providerAudienceCapabilities[provider];if(capability.requiresSelectedAsset||(existing??[]).some(row=>row.connection_id===account.id))continue;await db.rpc("upsert_provider_audience_metric",{p_creator_id:account.creator_id,p_connection_id:account.id,p_asset_binding_id:null as unknown as string,p_provider:provider,p_account_category:account.account_type,p_count:null as unknown as number,p_unit:null as unknown as string,p_status:capability.supported?"error":"unsupported",p_approximate:false,p_source_observed_at:null as unknown as string,p_next_sync_at:new Date(0).toISOString(),p_error_code:capability.supported?"sync_pending":null as unknown as string});}
 for(const asset of assets??[]){const provider=asset.provider as AudienceProvider,capability=providerAudienceCapabilities[provider];if((existing??[]).some(row=>row.asset_binding_id===asset.id))continue;const usable=capability.supported&&asset.authority_status==="authorized"&&capability.selectedAssetType===asset.asset_type;await db.rpc("upsert_provider_audience_metric",{p_creator_id:asset.creator_id,p_connection_id:asset.connected_account_id,p_asset_binding_id:asset.id,p_provider:provider,p_account_category:asset.asset_type,p_count:null as unknown as number,p_unit:null as unknown as string,p_status:usable?"error":capability.accessRequirement==="review"?"review_required":capability.accessRequirement==="allowlist"?"access_limited":"unsupported",p_approximate:false,p_source_observed_at:null as unknown as string,p_next_sync_at:usable?new Date(0).toISOString():nextAudienceSync(provider),p_error_code:usable?"sync_pending":"provider_access_required"});}
 const{data:claimed,error}=await db.rpc("claim_provider_audience_metrics",{p_limit:limit,p_lease_owner:owner});if(error)return Response.json({error:"Claim failed"},{status:503});
 const summary={claimed:claimed?.length??0,synchronized:0,unavailable:0,failed:0};const changedCreators=new Set<string>();
 for(const row of claimed??[]){const provider=row.provider as AudienceProvider;if(!audienceProviders.includes(provider)||!providerAudienceCapabilities[provider].supported){summary.unavailable++;continue;}
  try{let ciphertext:string|undefined,stableId="";
   if(row.asset_binding_id){const[{data:asset},{data:secret}]=await Promise.all([db.from("provider_asset_bindings").select("stable_asset_id").eq("id",row.asset_binding_id).maybeSingle(),db.from("provider_asset_secrets").select("credential_ciphertext").eq("asset_binding_id",row.asset_binding_id).maybeSingle()]);stableId=asset?.stable_asset_id??"";ciphertext=secret?.credential_ciphertext;}
   else if(row.connection_id){const[{data:account},{data:secret}]=await Promise.all([db.from("connected_accounts").select("external_account_id").eq("id",row.connection_id).maybeSingle(),db.from("platform_connection_secrets").select("access_token_ciphertext").eq("platform_connection_id",row.connection_id).maybeSingle()]);stableId=account?.external_account_id??"";ciphertext=secret?.access_token_ciphertext;}
   if(provider==="discord")ciphertext=ciphertext??"bot-authority";if(!ciphertext||!stableId)throw new Error("selected_asset_unavailable");
   const normalized=await fetchProviderAudienceMetric({provider,stableId,accessToken:provider==="discord"?"":decryptMetricCredential(ciphertext)}),metricId=await db.rpc("upsert_provider_audience_metric",{p_creator_id:row.creator_id,p_connection_id:row.connection_id as string,p_asset_binding_id:row.asset_binding_id as string,p_provider:provider,p_account_category:row.account_category,p_count:normalized.count as number,p_unit:providerAudienceCapabilities[provider].audienceUnit as string,p_status:normalized.status,p_approximate:normalized.approximate,p_source_observed_at:new Date().toISOString(),p_next_sync_at:nextAudienceSync(provider),p_error_code:null as unknown as string});
   if(metricId.error)throw metricId.error;if(normalized.count!==null)await db.rpc("append_provider_audience_snapshot",{p_metric_id:metricId.data});changedCreators.add(row.creator_id);summary.synchronized++;
  }catch(cause){const safe=safeMetricError(cause);await db.rpc("upsert_provider_audience_metric",{p_creator_id:row.creator_id,p_connection_id:row.connection_id as string,p_asset_binding_id:row.asset_binding_id as string,p_provider:provider,p_account_category:row.account_category,p_count:null as unknown as number,p_unit:null as unknown as string,p_status:safe.status,p_approximate:false,p_source_observed_at:null as unknown as string,p_next_sync_at:nextAudienceSync(provider,row.consecutive_failures+1),p_error_code:safe.code});changedCreators.add(row.creator_id);summary.failed++;}
 }
 for(const creatorId of changedCreators)revalidateCreatorAccounts(creatorId);
 return Response.json(summary,{headers:{"cache-control":"no-store"}});
}
