import {canonicalAccountConnected,resolveConnectionStatus} from "@/lib/social-providers/connection-health";

export type PlatformProductRole="main"|"recovery";
export type PlatformNetworkStatus="protected"|"needs_main"|"needs_recovery"|"attention";
export type PlatformContextEventType="main_account_connected"|"main_account_replaced"|"recovery_account_connected"|"recovery_account_linked"|"recovery_account_deleted"|"main_account_deleted"|"recovery_network_protected"|"connection_needs_attention";
export type PlatformContextAction="ADD_FIRST_ACCOUNT"|"ADD_RECOVERY_ACCOUNT"|"REVIEW_ACCOUNT";
export type CanonicalPlatformAccount={id:string;platform:string;label:string;external_account_name?:string|null;account_type:"official"|"backup";connection_health?:string|null;provider_status?:string|null;url?:string|null;external_account_id?:string|null};
export type CanonicalRecoveryNetwork={id:string;main_connected_account_id:string|null;recovery_account_ids:string[]};
export type PlatformContextEvent={type:PlatformContextEventType;accountId?:string;provider?:string;displayName?:string;canonicalRole?:PlatformProductRole;accountHealth?:"healthy"|"attention";recoveryNetworkId?:string;networkStatus:PlatformNetworkStatus;recoveryCount:number;healthyRecoveryCount:number;mainPresent:boolean;persistent:true;title:string;description:string;guidance?:string;actionId?:PlatformContextAction;tone:"main"|"recovery"|"protected"|"attention"|"failure"};

function accountNeedsAttention(account:CanonicalPlatformAccount){const connected=canonicalAccountConnected({health:account.connection_health,providerStatus:account.provider_status,hasPublicUrl:Boolean(account.url),hasExternalAccountId:Boolean(account.external_account_id)});return resolveConnectionStatus({health:account.connection_health,providerStatus:account.provider_status,canonicalConnected:connected}).actionRequired;}
function displayName(account:CanonicalPlatformAccount){return(account.external_account_name?.trim()||account.label.trim()||account.platform).slice(0,80);}
export function canonicalNetworkStatus(network:CanonicalRecoveryNetwork,accounts:CanonicalPlatformAccount[]){const main=network.main_connected_account_id?accounts.find(account=>account.id===network.main_connected_account_id&&account.account_type==="official"):undefined,recoveries=network.recovery_account_ids.map(id=>accounts.find(account=>account.id===id&&account.account_type==="backup")).filter((account):account is CanonicalPlatformAccount=>Boolean(account)),healthyRecoveryCount=recoveries.filter(account=>!accountNeedsAttention(account)).length;return{mainPresent:Boolean(main),recoveryCount:recoveries.length,healthyRecoveryCount,status:!main?"needs_main"as const:accountNeedsAttention(main)||recoveries.some(account=>accountNeedsAttention(account))?"attention"as const:healthyRecoveryCount>0?"protected"as const:"needs_recovery"as const};}

export function derivePlatformContextEvent(input:{transportStatus:string|null;account:CanonicalPlatformAccount|null;network:CanonicalRecoveryNetwork|null;accounts:CanonicalPlatformAccount[];targetedExistingNetwork?:boolean}):PlatformContextEvent|null{
  const{transportStatus,account,network,accounts}=input;if(!account||!network||!transportStatus||!["connected","connected_recovery_linked","connected_recovery_link_failed"].includes(transportStatus))return null;
  const state=canonicalNetworkStatus(network,accounts),role:PlatformProductRole=account.account_type==="official"?"main":"recovery",name=displayName(account),attention=accountNeedsAttention(account),base={accountId:account.id,provider:account.platform,displayName:name,canonicalRole:role,accountHealth:attention?"attention"as const:"healthy"as const,recoveryNetworkId:network.id,networkStatus:state.status,recoveryCount:state.recoveryCount,healthyRecoveryCount:state.healthyRecoveryCount,mainPresent:state.mainPresent,persistent:true as const};
  if(attention)return{...base,type:"connection_needs_attention",title:`${role==="main"?"Main":"Recovery"} account connected`,description:`${name} is connected as a ${role==="main"?"Main":"Recovery"} account, but still needs attention.`,guidance:"Review this connection before relying on it for recovery.",actionId:"REVIEW_ACCOUNT",tone:"attention"};
  if(role==="main"){const replaced=Boolean(input.targetedExistingNetwork);return{...base,type:replaced?"main_account_replaced":"main_account_connected",title:replaced?"Main account replaced":"Main account connected",description:state.status==="protected"?`${name} is now the Main account for this Recovery Network and is protected by its existing Recovery accounts.`:`${name} is now the Main account for this Recovery Network.`,...(state.status==="needs_recovery"?{guidance:`Add a Recovery account to protect ${name}.`,actionId:"ADD_RECOVERY_ACCOUNT"as const}:{}),tone:state.status==="protected"?"protected":"main"};}
  const linked=transportStatus==="connected_recovery_linked";return{...base,type:linked?"recovery_account_connected":"recovery_account_connected",title:"Recovery account added",description:network.main_connected_account_id?`${name} was added as a Recovery account for ${displayName(accounts.find(candidate=>candidate.id===network.main_connected_account_id)??account)}.`:`${name} was added to this Recovery Network.`,...(state.status==="protected"?{guidance:`${displayName(accounts.find(candidate=>candidate.id===network.main_connected_account_id)??account)} is now protected.`}:{}),tone:state.status==="protected"?"protected":"recovery"};
}

export function deriveRecoveryAssignmentEvent(input:{account:CanonicalPlatformAccount;network:CanonicalRecoveryNetwork;accounts:CanonicalPlatformAccount[]}):PlatformContextEvent|null{if(input.account.account_type!=="backup"||!input.network.recovery_account_ids.includes(input.account.id))return null;const state=canonicalNetworkStatus(input.network,input.accounts),main=input.network.main_connected_account_id?input.accounts.find(account=>account.id===input.network.main_connected_account_id&&account.account_type==="official"):null,name=displayName(input.account);return{type:"recovery_account_linked",accountId:input.account.id,provider:input.account.platform,displayName:name,canonicalRole:"recovery",accountHealth:accountNeedsAttention(input.account)?"attention":"healthy",recoveryNetworkId:input.network.id,networkStatus:state.status,recoveryCount:state.recoveryCount,healthyRecoveryCount:state.healthyRecoveryCount,mainPresent:state.mainPresent,persistent:true,title:"Recovery account assigned",description:main?`${name} was added to ${displayName(main)}'s Recovery Network.`:`${name} was added to this Recovery Network.`,tone:state.status==="protected"?"protected":"recovery"};}

export function derivePlatformDeletionEvent(input:{type:"main_account_deleted"|"recovery_account_deleted";network:CanonicalRecoveryNetwork;accounts:CanonicalPlatformAccount[];removedNetworkCount?:number}):PlatformContextEvent{const state=canonicalNetworkStatus(input.network,input.accounts);return{type:input.type,networkStatus:state.status,recoveryCount:state.recoveryCount,healthyRecoveryCount:state.healthyRecoveryCount,mainPresent:state.mainPresent,persistent:true,title:input.type==="main_account_deleted"?"Main account removed":"Recovery account deleted",description:input.type==="main_account_deleted"?"Your Recovery accounts are still here. Add another Main account when you're ready.":input.removedNetworkCount===undefined?"The account was removed from its Recovery Networks.":`The account was removed from ${input.removedNetworkCount} Recovery Network${input.removedNetworkCount===1?"":"s"}.`,actionId:input.type==="main_account_deleted"?"ADD_FIRST_ACCOUNT":undefined,tone:state.status==="attention"||state.status==="needs_main"?"attention":"recovery"};}

export function toAiSafePlatformEvent(event:PlatformContextEvent){return{eventType:event.type,provider:event.provider??null,displayName:event.displayName??null,role:event.canonicalRole??null,accountHealth:event.accountHealth??null,networkStatus:event.networkStatus,recoveryCount:event.recoveryCount,healthyRecoveryCount:event.healthyRecoveryCount,mainPresent:event.mainPresent,persistent:event.persistent,allowedAction:event.actionId??null};}
