import type { Metadata } from "next";
import Link from "next/link";
import { Logo } from "@/components/logo";
import { PublicFooter } from "@/components/public-footer";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms governing creator accounts, Recovery Pass, connected platforms, subscriptions, recovery features, and other AudienceOwn services.",
  alternates: { canonical: "/terms" },
  openGraph: {
    title: "Terms of Service · AudienceOwn",
    description: "The terms for using AudienceOwn, including creator tools, Recovery Pass, connected platforms, and subscriptions.",
    url: "/terms",
    siteName: "AudienceOwn",
    type: "website",
  },
};

function Section({ id, title, children }: { id: string; title: string; children: React.ReactNode }) {
  return <section id={id} aria-labelledby={`${id}-heading`} className="scroll-mt-8 border-t border-white/[.08] pt-9 print:break-inside-avoid print:border-zinc-300">
    <h2 id={`${id}-heading`} className="text-2xl font-semibold tracking-[-.025em] text-white sm:text-[1.7rem] print:text-black">{title}</h2>
    <div className="mt-4 space-y-4 text-[15px] leading-7 text-zinc-300 sm:text-base sm:leading-8 print:text-zinc-800">{children}</div>
  </section>;
}

function Subsection({ id, title, children }: { id: string; title: string; children: React.ReactNode }) {
  return <section id={id} aria-labelledby={`${id}-heading`} className="scroll-mt-8">
    <h3 id={`${id}-heading`} className="text-base font-semibold text-zinc-100 sm:text-lg print:text-black">{title}</h3>
    <div className="mt-2 space-y-3">{children}</div>
  </section>;
}

const legalLink = "text-violet-300 transition-colors hover:text-violet-200 focus-visible:rounded-sm focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-violet-400 print:text-black";

export default function TermsPage() {
  return <main className="min-h-screen bg-[#07070b] text-white print:bg-white print:text-black">
    <header className="border-b border-white/[.07] print:hidden"><div className="mx-auto flex h-20 max-w-[1180px] items-center justify-between px-5 lg:px-8"><Logo/><Link href="/" className="text-sm text-zinc-400 transition-colors hover:text-white focus-visible:rounded-sm focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-violet-400">Back to AudienceOwn</Link></div></header>
    <div className="mx-auto max-w-[1180px] px-5 py-12 lg:px-8 lg:py-20">
      <article className="max-w-[760px]">
        <header>
          <h1 className="text-4xl font-semibold tracking-[-.045em] sm:text-5xl">Terms of Service</h1>
          <div className="mt-4 flex flex-wrap gap-x-6 gap-y-1 text-sm font-medium text-violet-300 print:text-zinc-700"><p>Last updated: August 5, 2026</p><p>Effective date: August 5, 2026</p></div>
          <p className="mt-6 text-lg leading-8 text-zinc-300 print:text-zinc-800">These Terms of Service explain the rules for using AudienceOwn. They apply to our websites, creator dashboard, Recovery Pass, connected platform and recovery features, public creator pages, and, when available, our mobile applications, enterprise workspaces, and APIs.</p>
        </header>

        <div className="mt-12 space-y-10">
          <Section id="introduction" title="Introduction"><p>AudienceOwn helps Creators maintain trusted audience connections and recovery destinations across platforms. In these Terms, “AudienceOwn,” “we,” “us,” and “our” refer to the operator of the AudienceOwn service. “You” means the person or organization using the service. If you use AudienceOwn for an organization, you confirm that you have authority to bind it to these Terms.</p><p>These Terms form an agreement between you and AudienceOwn. Our <Link className={legalLink} href="/privacy">Privacy Policy</Link> explains how we handle personal information. Additional terms presented for a particular plan, integration, enterprise workspace, API, or feature also apply to that offering.</p></Section>

          <Section id="summary" title="In summary"><p>These Terms describe how AudienceOwn may be used, the responsibilities of Creators, how Recovery Pass, subscriptions, and Connected Platforms work, and the rights and responsibilities of you and AudienceOwn. This summary is provided only for convenience. The full Terms below govern your use of the service.</p></Section>

          <Section id="about" title="About AudienceOwn"><p>AudienceOwn is a creator continuity platform designed to help Creators establish trusted identities, connect Official Accounts and Backup Accounts, synchronize Connected Platforms, protect audience relationships, manage Recovery Pass destinations, improve audience resilience, prepare for account disruption, monitor authenticity, and coordinate recovery communications. Available capabilities depend on the Creator’s subscription, Connected Platforms, and feature availability.</p></Section>

          <Section id="definitions" title="Definitions"><p>“AudienceOwn” means the service and its operator. A “Creator” is a person or organization using AudienceOwn to manage a creator presence or audience relationship. A “Fan” is a person who interacts with a Creator through AudienceOwn. “Recovery Pass” is the feature through which a Fan can join a Creator’s recovery network and choose available communication or recovery preferences. A “Protected Fan” is a Fan with an active Recovery Pass relationship.</p><p>A “Connected Platform” is a supported third-party service added to AudienceOwn. An “Official Account” is an account a Creator identifies as an authoritative presence. A “Backup Account” is an alternative account or destination configured for continuity. An “OAuth Connection” authorizes supported access through a provider’s OAuth process. A “Manual Connection” is account information or a public URL submitted without provider authorization.</p></Section>

          <Section id="acceptance" title="Acceptance of these Terms"><p>By creating an account, connecting a provider, joining Recovery Pass, purchasing a plan, or otherwise using AudienceOwn, you agree to these Terms. If you do not agree, do not use the service. If additional terms conflict with these Terms, the additional terms control only for the feature or plan they address.</p></Section>

          <Section id="eligibility" title="Eligibility"><p>You must be at least 18 years old, or the age of legal majority where you live, and legally able to enter this agreement. A parent, guardian, or authorized organization may establish an account for a person who cannot enter the agreement independently, where permitted by law. You may not use AudienceOwn if applicable law prohibits you from receiving the service.</p></Section>

          <Section id="account" title="Your AudienceOwn account"><p>You must provide accurate, current information and keep it updated. You are responsible for activity under your account and for ensuring that anyone you authorize follows these Terms. You may not sell, transfer, or share access in a way that misrepresents account ownership or bypasses plan limits.</p><p>Keep passwords, sign-in methods, recovery codes, and connected-provider credentials secure. Tell us promptly at <a className={legalLink} href="mailto:support@audienceown.com">support@audienceown.com</a> if you suspect unauthorized access. We may ask you to verify account ownership before changing sensitive settings or restoring access.</p></Section>

          <Section id="creator-responsibilities" title="Creator responsibilities"><p>Creators are responsible for the accuracy and legality of their profile, Official Account and Backup Account information, recovery destinations, audience communications, and other content or configuration they provide. You must have the rights and permissions needed to submit content, connect accounts, contact Fans, and instruct AudienceOwn to process information on your behalf.</p><p>Creators remain responsible for their content and communications, Connected Platforms, permissions they grant, security practices, audience relationships, and compliance with applicable platform rules and laws. AudienceOwn provides operational tools, not legal advice.</p></Section>

          <Section id="recovery-pass" title="Recovery Pass"><p>Recovery Pass allows Fans to opt in to a Creator’s recovery network and select available communication preferences or recovery destinations. Fans control their own choices and may update preferences or opt out through the controls provided with the service or a communication.</p><p>Creators are responsible for communications they initiate, including their content, timing, recipients, and legal basis. AudienceOwn processes and delivers communications according to the Creator’s configuration, Fan preferences, applicable law, and service safeguards. Delivery depends on third-party email, messaging, browser, mobile, or telecommunications providers and is not guaranteed.</p><p>You may not use Recovery Pass to send spam, deceptive promotions, unrelated bulk messages, or false emergency notices, or to override a Fan’s opt-out. Aggregate Protected Fan counts and coverage insights may be estimates and may change as preferences, delivery status, and available data change.</p><p>AudienceOwn is not a law-enforcement service, cybersecurity response provider, account recovery authority, or insurer. Recovery Pass improves Creator resilience and communication continuity, but it does not guarantee account recovery, audience migration, message delivery, platform restoration, continued access to third-party services, or verification by an external provider. Creator actions and third-party providers influence each outcome.</p></Section>

          <Section id="fan-responsibilities" title="Fan responsibilities"><p>Fans are responsible for the information they submit, keeping contact details accurate, updating Recovery Pass and communication preferences, and taking reasonable steps to protect their own devices and accounts. AudienceOwn and Creators rely on those choices when processing communications, and AudienceOwn cannot guarantee that a Fan will receive or respond to a communication.</p></Section>

          <Section id="connected-platforms" title="Connected social platforms">
            <p>AudienceOwn may let Creators add social, content, community, or membership accounts and synchronize supported profile, audience, or connection information. Available providers, data, and refresh schedules vary. You must follow each provider’s rules and maintain any permissions required for the connection.</p>
            <Subsection id="oauth-connections" title="OAuth connections"><p>When you create an OAuth Connection, you authorize AudienceOwn to access the provider account and data described on the provider’s authorization screen. You are responsible for choosing the correct account and reviewing the requested permissions. AudienceOwn uses authorized access only for the features you request and does not obtain your provider password.</p><p>You may disconnect a provider in AudienceOwn and may revoke access through the provider. Disconnection stops future synchronization after processing completes, but does not alter content hosted by the provider. A provider may revoke authorization, change its API or rules, restrict data, or experience an outage without notice to us.</p></Subsection>
            <Subsection id="manual-connections" title="Manual platform connections"><p>A Manual Connection records a public URL or other information you submit. It does not authorize AudienceOwn to access the provider account and, by itself, does not prove ownership, authenticity, or endorsement. You must keep Manual Connection information accurate and remove links you no longer control.</p></Subsection>
          </Section>

          <Section id="identity-verification" title="Identity verification"><p>When verification is available, AudienceOwn may use provider authorization, domain evidence, account information, or other reasonable signals to assess whether a Creator controls an identity or destination. You must provide truthful information and may not submit another person’s identity evidence without authorization. Verification reflects the evidence available at the time and is not a legal identity certificate or a guarantee against impersonation.</p></Section>

          <Section id="accounts-and-score" title="Official accounts, backup accounts, and protection scores">
            <Subsection id="official-accounts" title="Official accounts"><p>You may identify accounts that you control as Official Accounts. You are responsible for keeping those designations accurate. AudienceOwn may remove or qualify a designation if ownership cannot be supported, a connection expires, or credible evidence indicates that it is misleading.</p></Subsection>
            <Subsection id="backup-accounts" title="Backup accounts"><p>Backup Accounts and recovery destinations are alternatives you configure for disruption or loss of access. You must control or be authorized to use them, keep them secure, and review them regularly. Listing a Backup Account does not guarantee that a provider will recognize it or that an audience can be moved to it.</p></Subsection>
            <Subsection id="audience-protection-score" title="Audience Protection Score"><p>The Audience Protection Score and related coverage indicators summarize available signals about your setup. They are informational, may use estimates or delayed provider data, and do not measure every threat. A score is not insurance, a security certification, or a promise of recovery.</p></Subsection>
          </Section>

          <Section id="metrics" title="Metrics and analytics"><p>Dashboard information, including subscriber and follower counts, analytics, engagement, the Audience Protection Score, recovery statistics, and synchronization status, is informational. Metrics may be delayed, unavailable, estimated, or changed by provider corrections, API limitations, synchronization timing, hidden subscriber counts, temporary outages, and account activity.</p><p>Metrics should not be treated as audited records or guarantees of current platform status, and Creators should not rely on them alone for commercial or financial decisions.</p></Section>

          <Section id="emergency-recovery" title="Emergency recovery features"><p>AudienceOwn may provide emergency plans, recovery drills, recovery destinations, authenticity monitoring, automation, and notification workflows. These tools help you prepare and coordinate a response. You remain responsible for your plan, authorized participants, approvals, replacement accounts, message content, and decision to activate a workflow.</p><p>Use drills only with test-safe settings and use emergency workflows only for legitimate creator continuity or security events. Monitoring signals and automation may be incomplete or delayed. Recovery features improve resilience but cannot eliminate account loss, impersonation, provider action, delivery failure, or other risk.</p></Section>

          <Section id="creator-communications" title="Creator communications"><p>If you send updates or emergency communications through AudienceOwn, you must identify yourself accurately, honor recipient preferences, and comply with consent, unsubscribe, disclosure, and content requirements. Do not upload purchased, scraped, or unlawfully obtained contact lists. We may limit, pause, or review delivery to protect recipients, providers, and the service.</p></Section>

          <Section id="communications" title="Communications"><p>AudienceOwn may send security notices, authentication alerts, account and billing notices, product notices, legal notices, and service announcements. These operational communications are part of providing and protecting the service and are different from optional marketing communications. You may manage marketing preferences through the controls provided, but you may still receive essential operational messages while your account remains active.</p></Section>

          <Section id="electronic-communications" title="Electronic communications"><p>By creating an account, you agree to receive electronic communications about account activity, security, authentication, billing, legal notices, and service updates. Where permitted by applicable law, these communications satisfy requirements that a notice be provided in writing. This does not change your choices for optional marketing communications.</p></Section>

          <Section id="communication-delivery" title="Communication delivery"><p>Delivery of email, SMS, WhatsApp, Discord, Telegram, push notifications, browser notifications, and other communications depends on recipient devices and settings, carrier and spam filtering, network availability, and third-party providers. AudienceOwn cannot guarantee that a communication will be delivered, displayed, or read.</p></Section>

          <Section id="subscriptions" title="Subscriptions and billing">
            <Subsection id="plans" title="Free, paid, and enterprise plans"><p>AudienceOwn may offer free plans, paid plans, and, when available, enterprise plans. Features, usage limits, support, and pricing are described at purchase or in an order form. Plans, features, limits, and pricing may change over time, although existing contractual commitments will be honored where applicable. Feature availability depends on subscription level. Enterprise terms may address workspaces, administrators, security, support, and negotiated service commitments. Where an enterprise agreement expressly conflicts with self-service terms, the enterprise agreement controls for that customer.</p></Subsection>
            <Subsection id="trials" title="Trials"><p>We may offer a trial under the terms shown when it begins. Unless otherwise stated, a trial may be limited to one per customer, may exclude some features, and may end or convert to a paid plan on the date disclosed at enrollment. If payment details are required for conversion, you can avoid a charge by cancelling before the stated deadline.</p></Subsection>
            <Subsection id="billing" title="Billing and automatic renewals"><p>When you purchase a paid plan, you authorize recurring charges at the price and billing interval shown at checkout or in your order form. Unless otherwise stated, subscriptions renew automatically until cancelled. We will provide notice of price changes when required by law, and the new price applies from the next renewal identified in that notice.</p><p>Upgrades may take effect immediately and may result in a prorated charge if stated at purchase. Downgrades generally take effect at the next renewal unless otherwise stated and may reduce features, limits, storage, or access. You are responsible for keeping billing information current. If payment fails, we may retry the charge, restrict paid features, or suspend the account after any notice required by law.</p></Subsection>
            <Subsection id="taxes" title="Taxes"><p>Prices may exclude taxes. You are responsible for applicable sales, use, value-added, withholding, or similar taxes, except taxes based on AudienceOwn’s income. If you claim an exemption, you must provide valid documentation. Enterprise customers remain responsible for amounts that an order form assigns to them.</p></Subsection>
            <Subsection id="payment-providers" title="Payment providers"><p>AudienceOwn does not directly process payment cards. Payments are transmitted securely to and handled by independent third-party payment processors under their own terms and privacy policies. AudienceOwn may receive limited billing information needed to activate subscriptions, verify payment, issue applicable refunds, detect fraud, and manage invoices.</p><p>AudienceOwn does not intentionally store complete payment card numbers, CVV codes, or full banking credentials. Payment security depends on safeguards maintained by both AudienceOwn and the payment processor. To the fullest extent permitted by applicable law, AudienceOwn is not liable for losses arising from bank declines, expired cards, insufficient funds, foreign exchange charges, overdraft fees, payment network outages, banking delays, or authorization failures outside its reasonable control.</p></Subsection>
            <Subsection id="fraudulent-payments" title="Fraudulent payments"><p>To the fullest extent permitted by applicable law, AudienceOwn is not liable for losses arising from unauthorized use of a payment method caused by circumstances outside its reasonable control, including stolen cards, identity theft, compromised bank accounts, fraudulent credentials, or unauthorized use before payment reaches the payment processor. If you believe a payment method was used without authorization, contact your bank or card issuer and the applicable payment provider immediately, then notify AudienceOwn.</p><p>If a Creator reports suspected payment fraud, AudienceOwn will make reasonable efforts to assist by providing available billing information or cooperating with the payment processor where appropriate. AudienceOwn cannot investigate banking systems or reverse unauthorized financial transactions.</p></Subsection>
            <Subsection id="chargebacks" title="Chargebacks"><p>We may investigate chargebacks and temporarily restrict an account while a payment dispute is reviewed. Fraudulent or abusive chargebacks may result in suspension or termination where appropriate. This does not limit your ability to raise a legitimate payment dispute or exercise rights available under applicable law.</p></Subsection>
            <Subsection id="cancellation" title="Cancellation"><p>You may cancel a self-service subscription through the available account settings or the method stated at purchase. Cancellation stops future renewal and generally takes effect at the end of the current paid period unless otherwise stated. Enterprise cancellation and non-renewal follow the applicable order form.</p></Subsection>
            <Subsection id="refunds" title="Refunds"><p>Refund eligibility is determined by AudienceOwn’s published refund policy unless otherwise required by applicable law. Payment processors facilitate transactions but do not decide whether a refund is eligible. Unless otherwise stated at purchase or required by law, charges are non-refundable and we do not provide credits for partial billing periods, unused features, or plan downgrades. Any discretionary refund or credit does not create an obligation to provide another.</p></Subsection>
          </Section>

          <Section id="suspension-termination" title="Account suspension and termination">
            <Subsection id="account-suspension" title="Account suspension"><p>We may limit or suspend access when reasonably necessary to address a security risk, suspected fraud, harmful activity, failed payment, legal requirement, provider restriction, or material breach of these Terms. Where practical, we will give notice and an opportunity to resolve the issue. Urgent threats may require immediate action.</p></Subsection>
            <Subsection id="account-termination" title="Account termination"><p>You may stop using AudienceOwn and request account deletion through available settings. We may terminate an account for a serious or repeated breach, unlawful use, or risk that cannot reasonably be resolved. On termination, your right to use the service ends, and we may delete or retain information as described in our Privacy Policy and as required by law.</p><p>Where applicable, payment obligations, ownership, licenses, intellectual property rights, privacy obligations, disclaimers, limitations of liability, indemnification, dispute resolution, and other provisions that by their nature should continue will survive termination.</p></Subsection>
          </Section>

          <Section id="compliance-with-laws" title="Compliance with Laws"><p>You agree to comply with all laws that apply to your use of AudienceOwn, including requirements relating to privacy, consumer protection, anti-spam communications, intellectual property, export controls, and financial regulation where applicable. The <a className={legalLink} href="#export-controls">Export controls</a> section provides additional terms for restricted trade and sanctions.</p></Section>

          <Section id="acceptable-use" title="Acceptable use">
            <p>Use AudienceOwn lawfully, respectfully, and only for purposes consistent with the service. You may not interfere with other users, the security or operation of AudienceOwn, connected providers, or recipient communications.</p>
            <Subsection id="prohibited-activities" title="Prohibited activities"><p>You may not use AudienceOwn to send spam, commit fraud or phishing, impersonate others, harass or threaten people, distribute malware, facilitate illegal activity, infringe rights, or abuse Recovery Pass or emergency notifications. You may not circumvent platform or AudienceOwn protections, probe or access systems without authorization, scrape the service or its users without permission, or use credentials to bypass plan or account limits.</p><p>You may not reverse engineer, decompile, or attempt to derive source code except to the limited extent that applicable law expressly permits and does not allow that restriction. You also may not resell or provide the service as your own without written permission, or use automated means in a way that harms performance or evades documented limits.</p></Subsection>
          </Section>

          <Section id="security" title="Security responsibilities"><p>You must use reasonable safeguards for your account, Connected Platforms, authorized team members, Backup Accounts, recovery destinations, and recipient data. Maintain secure passwords, enable multi-factor authentication where available, protect connected accounts and credentials, keep contact and ownership information accurate, promptly remove access that is no longer needed, and report suspicious activity to <a className={legalLink} href="mailto:support@audienceown.com">support@audienceown.com</a>.</p><p>AudienceOwn implements commercially reasonable administrative, technical, and organizational safeguards designed to protect the service and information it processes. No internet service, software, cloud provider, or security measure can guarantee complete security.</p><p>Do not disclose vulnerabilities publicly before giving us a reasonable opportunity to investigate. Security and integration questions may be sent to <a className={legalLink} href="mailto:contact@audienceown.com">contact@audienceown.com</a>.</p></Section>

          <Section id="export-controls" title="Export controls"><p>You agree to comply with applicable export control, trade restriction, and sanctions laws when using AudienceOwn. You may not use or provide the service where doing so would cause you or AudienceOwn to violate those laws.</p></Section>

          <Section id="third-party-services" title="Third-party services"><p>AudienceOwn depends on independent providers that may include payment processors, cloud infrastructure and hosting providers, email, SMS, WhatsApp, and push notification providers, social media platforms, OAuth providers, analytics providers, mapping providers, and domain providers. Their services are governed by their own terms and policies.</p><p>AudienceOwn is independent from every Connected Platform. Connecting a platform does not imply partnership, endorsement, certification, approval, ownership, or affiliation unless we expressly state otherwise.</p><p>AudienceOwn cannot control provider outages, API removals or restrictions, OAuth failures, policy changes, account suspensions, pricing changes, or provider security incidents outside its reasonable control. These events may interrupt synchronization, metrics, verification, recovery, or delivery. We may update, modify, or discontinue an integration accordingly when needed to comply with provider terms, protect users, or maintain the service.</p></Section>

          <Section id="api-access" title="API access"><p>When API access becomes available, it may require separate credentials and will be subject to documented rate limits, security requirements, and any additional API terms. API documentation and behavior may evolve. Abuse, attempts to evade limits, or use that threatens the service may result in restricted or suspended API access.</p></Section>

          <Section id="intellectual-property" title="Intellectual property"><p>AudienceOwn and its licensors own the service, software, design, documentation, brand, and other materials we provide, excluding creator and user content. These Terms give you a limited, non-exclusive, non-transferable, revocable right to use the service for its intended purpose while your account is active. They do not transfer ownership of AudienceOwn intellectual property.</p><p>You may not copy or misuse AudienceOwn branding or trademarks, imply our endorsement, falsely represent a partnership, or register confusingly similar domains or social accounts without written permission.</p>
            <Subsection id="creator-content" title="Creator content"><p>You retain ownership of content, uploaded media, profile information, links, and communications you submit, subject to any rights held by others. Creators remain solely responsible for their content, copyright compliance, licenses, permissions, communications, campaigns, marketing claims, links, and uploaded material. AudienceOwn does not review every Creator action.</p><p>You grant AudienceOwn a worldwide, non-exclusive license to host, process, reproduce, format, transmit, and display that content only as needed to operate, secure, and improve the service and follow your instructions. This license ends when the content is deleted, except for reasonable backups, legal retention, and content already shared at your direction.</p></Subsection>
            <Subsection id="public-creator-pages" title="Public creator pages"><p>Information you publish on a public creator page can be viewed, linked to, indexed, and shared by others. You control what you submit for publication and must not present a public page in a deceptive way. Removing a page from AudienceOwn may not remove copies or links retained by third parties.</p></Subsection>
            <Subsection id="user-generated-content" title="User-generated content"><p>You are responsible for content you submit or send. We do not endorse user-generated content and may remove, restrict, or preserve it when reasonably necessary to enforce these Terms, protect rights or safety, or comply with law.</p><p>Copyright holders may submit an infringement notice to <a className={legalLink} href="mailto:contact@audienceown.com">contact@audienceown.com</a> with enough information to identify the protected work, the material at issue, and the basis for the request. We may investigate and, where appropriate, remove, restrict, or disable allegedly infringing material.</p></Subsection>
            <Subsection id="feedback" title="Feedback"><p>If you provide ideas or feedback, you give AudienceOwn permission to use them without restriction or payment. This does not transfer ownership of your creator content or permit us to identify you publicly without permission.</p></Subsection>
          </Section>

          <Section id="open-source" title="Open-source software"><p>AudienceOwn may include open-source software components. Where required, the applicable licenses and attribution notices will remain available and will govern those components.</p></Section>

          <Section id="ai-features" title="AI-assisted features"><p>When available, AI-assisted features will be optional and may help draft, organize, or refine Creator content. Outputs can be incomplete, inaccurate, or unsuitable. You remain responsible for reviewing, editing, and approving AI-generated content before publishing it or sending it to Fans.</p><p>AI output should always be reviewed by a person. AI assistance can support decision making, but it does not replace a Creator’s judgment, and the Creator remains responsible for anything published or sent.</p><p>Do not submit information to an AI feature unless you have the right to use it for that purpose. Additional notices may explain the provider, data handling, usage limits, or feature-specific restrictions.</p></Section>

          <Section id="beta-features" title="Beta and early access features"><p>We may offer beta, preview, or experimental features for evaluation. These features may change, may not be fully supported, and may be modified or discontinued without becoming generally available. They may not receive the same availability, reliability, or support commitments as generally available features. Preview APIs and AI-assisted features may evolve as we learn from their use.</p><p>Creators choose whether to use preview functionality and should avoid relying on it exclusively for critical workflows.</p></Section>

          <Section id="disclaimers" title="Disclaimers"><p>To the fullest extent permitted by applicable law, AudienceOwn is provided “as is” and “as available,” without warranties regarding availability, accuracy, compatibility, fitness for a particular purpose, continuous operation, non-infringement, or error-free operation. This does not exclude warranties or rights that applicable law does not allow us to waive.</p><p>Provider data may be delayed, estimated, restricted, or unavailable. Providers may fail or revoke access. Recovery and monitoring tools improve preparedness and resilience but cannot eliminate every security, platform, impersonation, or delivery risk.</p></Section>

          <Section id="no-guarantee" title="No Guarantee of Results"><p>AudienceOwn provides software designed to improve Creator continuity, audience protection, identity verification, and communication. It does not guarantee account recovery or the restoration of hacked, suspended, or deleted accounts. It also does not guarantee audience or subscriber growth, increased revenue, third-party verification of a Creator, uninterrupted synchronization, API access or platform availability, successful notification delivery or OAuth authorization, or the availability of third-party services.</p><p>The platform is intended to improve resilience, but it cannot eliminate every risk or control outcomes determined by Creators, Fans, recipients, or third-party providers.</p></Section>

          <Section id="professional-advice" title="Professional advice"><p>AudienceOwn provides software tools, not legal, financial, tax, or investment advice, cybersecurity consulting, insurance, or professional recovery services. Unless we expressly state otherwise, Creators remain responsible for evaluating their circumstances, seeking qualified advice when needed, and making their own decisions.</p></Section>

          <Section id="limitation-of-liability" title="Limitation of liability"><p>To the fullest extent permitted by applicable law, neither AudienceOwn nor its suppliers will be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, or for loss of profits, revenue, subscribers, followers, advertising income, sponsorship opportunities, Creator reputation, business, platform access, goodwill, or data, arising from the service or these Terms, even if advised that such harm was possible. This includes loss resulting from third-party outages, API failures, or provider actions.</p><p>To the fullest extent permitted by applicable law, our total liability for all claims arising from the service or these Terms will not exceed the greater of the amount you paid AudienceOwn for the service during the 12 months before the event giving rise to the claim or US $100. This limit does not apply to liability that cannot lawfully be limited, including liability for fraud or willful misconduct where applicable. Some jurisdictions do not allow certain exclusions, so parts of this section may not apply to you.</p></Section>

          <Section id="indemnification" title="Indemnification"><p>To the extent permitted by law, you will defend and indemnify AudienceOwn and its personnel against third-party claims, damages, and reasonable costs arising from your content, your communications, your unlawful or unauthorized use of the service, or your material breach of these Terms. We will give you reasonable notice of a covered claim and allow you to control the defense, provided that you may not settle in a way that admits fault by or imposes an obligation on AudienceOwn without our written consent. This section does not apply where prohibited by law.</p></Section>

          <Section id="force-majeure" title="Force majeure"><p>To the fullest extent permitted by applicable law, AudienceOwn is not liable for delays or failures caused by events outside our reasonable control, including natural disasters, internet or telecommunications failures, cloud outages, government actions, wars, terrorism, labor disputes, pandemics, cyber attacks, large-scale infrastructure failures, and third-party platform failures. We will use reasonable efforts to reduce disruption and resume affected services when practical.</p></Section>

          <Section id="service-changes" title="Changes to the service"><p>We may improve, add, limit, or discontinue features as AudienceOwn evolves, providers change, or security and legal needs arise. We may also temporarily suspend functionality for maintenance, security updates, platform migrations, provider changes, compliance requirements, or service improvements.</p><p>When a change materially reduces a paid service, we will provide notice when reasonably practical and honor any remedy required by law or an applicable order form. Future mobile applications, enterprise workspaces, API access, AI assistance, and other capabilities are governed by these Terms only when available.</p></Section>

          <Section id="terms-changes" title="Changes to these Terms"><p>We may update these Terms to reflect service changes, provider requirements, legal developments, or improved clarity. We will post the revised Terms and update the date above. If a change materially affects your rights, we will provide additional notice when appropriate. Changes apply prospectively from their effective date. Continuing to use the service after that date means you accept the revised Terms.</p></Section>

          <Section id="business-transfers" title="Business transfers"><p>If AudienceOwn merges, is acquired, reorganizes, or sells substantially all of its assets, user accounts and these agreements may transfer to a successor organization, subject to applicable law and the Privacy Policy. We will provide notice when required and will continue to protect personal information under the commitments that apply to the transfer.</p></Section>

          <Section id="relationship" title="Relationship of the parties"><p>Nothing in these Terms creates a partnership, agency, fiduciary, employment, or joint venture relationship between AudienceOwn and any user. Neither party may bind the other unless expressly authorized in writing.</p></Section>

          <Section id="governing-law" title="Governing law"><p>The governing law and legal entity information will be updated before public launch. Nothing in these Terms limits mandatory protections available to consumers under the law where they live.</p></Section>

          <Section id="dispute-resolution" title="Dispute resolution"><p>Before beginning formal proceedings, please contact <a className={legalLink} href="mailto:contact@audienceown.com">contact@audienceown.com</a> so we can try to resolve the concern directly. Any formal dispute will proceed under applicable law and any process the parties agree to in writing.</p></Section>

          <Section id="severability" title="Severability"><p>If a court or other competent authority finds part of these Terms unenforceable, that part will be enforced to the greatest extent permitted and the remaining terms will continue in effect.</p></Section>

          <Section id="entire-agreement" title="Entire agreement"><p>These Terms, the Privacy Policy, and any applicable order form or feature-specific terms form the entire agreement between you and AudienceOwn about the service and replace earlier agreements or representations about the same subject. A failure to enforce a term is not a waiver.</p><p>You may not assign this agreement without our written consent. AudienceOwn may assign these Terms as part of a merger, acquisition, corporate restructuring, financing, or sale of substantially all of its assets, subject to applicable law.</p><p>Headings are provided only for convenience and do not affect interpretation of these Terms.</p></Section>

          <Section id="contact" title="Contact information"><p>For service and account questions, email <a className={legalLink} href="mailto:support@audienceown.com">support@audienceown.com</a>. For legal, security, developer, and integration questions, email <a className={legalLink} href="mailto:contact@audienceown.com">contact@audienceown.com</a>.</p><p>AudienceOwn’s legal entity details will be added once they are formally established for public launch. We do not publish a company address that has not been officially designated for public contact.</p></Section>
        </div>
      </article>
    </div>
    <div className="print:hidden"><PublicFooter/></div>
  </main>;
}
