import type { AudienceProvider, PlatformAudienceUnit } from "./types";

export type ProviderAudienceCapability = { provider: AudienceProvider; supported: boolean; identityObject: string; selectedAssetType: string | null; officialField: string | null; audienceUnit: PlatformAudienceUnit | null; requiresSelectedAsset: boolean; requiredScopes: string[]; accessRequirement: "standard" | "review" | "allowlist" | "paid_tier" | "unsupported"; approximate: boolean; canBeHidden: boolean; minimumSyncMinutes: number; rateLimitClass: "low" | "standard" | "restricted"; documentationUrl: string };
const c = (value: ProviderAudienceCapability) => value;
export const providerAudienceCapabilities: Record<AudienceProvider, ProviderAudienceCapability> = {
  youtube:c({provider:"youtube",supported:true,identityObject:"channel",selectedAssetType:null,officialField:"statistics.subscriberCount",audienceUnit:"subscribers",requiresSelectedAsset:false,requiredScopes:["https://www.googleapis.com/auth/youtube.readonly"],accessRequirement:"standard",approximate:true,canBeHidden:true,minimumSyncMinutes:360,rateLimitClass:"low",documentationUrl:"https://developers.google.com/youtube/v3/docs/channels"}),
  instagram:c({provider:"instagram",supported:true,identityObject:"professional account",selectedAssetType:"instagram_professional_account",officialField:"followers_count",audienceUnit:"followers",requiresSelectedAsset:false,requiredScopes:["instagram_business_basic"],accessRequirement:"review",approximate:false,canBeHidden:false,minimumSyncMinutes:360,rateLimitClass:"standard",documentationUrl:"https://developers.facebook.com/docs/instagram-platform/instagram-api-with-instagram-login/"}),
  tiktok:c({provider:"tiktok",supported:true,identityObject:"user",selectedAssetType:"tiktok_account",officialField:"data.user.follower_count",audienceUnit:"followers",requiresSelectedAsset:true,requiredScopes:["user.info.stats"],accessRequirement:"review",approximate:false,canBeHidden:false,minimumSyncMinutes:360,rateLimitClass:"standard",documentationUrl:"https://developers.tiktok.com/doc/tiktok-api-v2-get-user-info/"}),
  x:c({provider:"x",supported:true,identityObject:"user",selectedAssetType:"x_account",officialField:"data.public_metrics.followers_count",audienceUnit:"followers",requiresSelectedAsset:true,requiredScopes:["users.read"],accessRequirement:"paid_tier",approximate:false,canBeHidden:false,minimumSyncMinutes:720,rateLimitClass:"restricted",documentationUrl:"https://docs.x.com/x-api/users/lookup/api-reference/get-users-id"}),
  spotify:c({provider:"spotify",supported:false,identityObject:"user",selectedAssetType:null,officialField:null,audienceUnit:null,requiresSelectedAsset:false,requiredScopes:["user-read-private"],accessRequirement:"standard",approximate:false,canBeHidden:false,minimumSyncMinutes:720,rateLimitClass:"low",documentationUrl:"https://developer.spotify.com/documentation/web-api/reference/get-current-users-profile"}),
  twitch:c({provider:"twitch",supported:true,identityObject:"broadcaster",selectedAssetType:null,officialField:"total",audienceUnit:"followers",requiresSelectedAsset:false,requiredScopes:[],accessRequirement:"standard",approximate:false,canBeHidden:false,minimumSyncMinutes:360,rateLimitClass:"standard",documentationUrl:"https://dev.twitch.tv/docs/api/reference#get-channel-followers"}),
  linkedin:c({provider:"linkedin",supported:false,identityObject:"OIDC member",selectedAssetType:null,officialField:null,audienceUnit:null,requiresSelectedAsset:false,requiredScopes:[],accessRequirement:"unsupported",approximate:false,canBeHidden:false,minimumSyncMinutes:1440,rateLimitClass:"low",documentationUrl:"https://learn.microsoft.com/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin-v2"}),
  facebook:c({provider:"facebook",supported:true,identityObject:"Page",selectedAssetType:"facebook_page",officialField:"followers_count",audienceUnit:"followers",requiresSelectedAsset:true,requiredScopes:["pages_read_engagement"],accessRequirement:"review",approximate:false,canBeHidden:false,minimumSyncMinutes:360,rateLimitClass:"standard",documentationUrl:"https://developers.facebook.com/docs/graph-api/reference/page"}),
  snapchat:c({provider:"snapchat",supported:false,identityObject:"Login Kit user",selectedAssetType:null,officialField:null,audienceUnit:null,requiresSelectedAsset:false,requiredScopes:["https://auth.snapchat.com/oauth2/api/user.external_id"],accessRequirement:"allowlist",approximate:false,canBeHidden:false,minimumSyncMinutes:1440,rateLimitClass:"restricted",documentationUrl:"https://developers.snap.com/snap-kit/login-kit/overview"}),
  pinterest:c({provider:"pinterest",supported:true,identityObject:"user account",selectedAssetType:null,officialField:"follower_count",audienceUnit:"followers",requiresSelectedAsset:false,requiredScopes:["user_accounts:read"],accessRequirement:"review",approximate:false,canBeHidden:false,minimumSyncMinutes:720,rateLimitClass:"standard",documentationUrl:"https://developers.pinterest.com/docs/api/v5/user_account-get"}),
  discord:c({provider:"discord",supported:true,identityObject:"guild",selectedAssetType:"discord_guild",officialField:"approximate_member_count",audienceUnit:"members",requiresSelectedAsset:true,requiredScopes:[],accessRequirement:"standard",approximate:true,canBeHidden:false,minimumSyncMinutes:360,rateLimitClass:"standard",documentationUrl:"https://discord.com/developers/docs/resources/guild#get-guild-with-counts"}),
};
