import{createHash,createPrivateKey,createPublicKey,sign,verify,KeyObject}from"node:crypto";
import{base64url,canonicalize}from"./canonical";
import type{AuthenticityAssertionPayload,SignedAuthenticityAssertion}from"./types";
function keyValue(value:string){return value.includes("BEGIN")?value:Buffer.from(value,"base64").toString("utf8");}
export function signingConfig(){const privateValue=process.env.AUTHENTICITY_SIGNING_PRIVATE_KEY,publicValue=process.env.AUTHENTICITY_SIGNING_PUBLIC_KEY,keyId=process.env.AUTHENTICITY_SIGNING_KEY_ID;if(!privateValue||!publicValue||!keyId)return null;try{const privateKey=createPrivateKey(keyValue(privateValue)),publicKey=createPublicKey(keyValue(publicValue));if(privateKey.asymmetricKeyType!=="ed25519"||publicKey.asymmetricKeyType!=="ed25519")return null;return{privateKey,publicKey,keyId};}catch{return null;}}
export function publicJwk(key:KeyObject,keyId:string){return{...key.export({format:"jwk"}),kid:keyId,use:"sig",alg:"EdDSA"};}
export function signAssertion(payload:AuthenticityAssertionPayload,config=signingConfig()):SignedAuthenticityAssertion|null{if(!config)return null;const protectedHeader={alg:"EdDSA"as const,kid:config.keyId,typ:"audienceown-authenticity+jws"as const};const input=`${base64url(canonicalize(protectedHeader))}.${base64url(canonicalize(payload))}`;return{payload,protected:protectedHeader,signature:sign(null,Buffer.from(input),config.privateKey).toString("base64url")};}
export function signPortablePayload<T extends object>(payload:T,typ:string,config=signingConfig()){if(!config)return null;const protectedHeader={alg:"EdDSA"as const,kid:config.keyId,typ};const input=`${base64url(canonicalize(protectedHeader))}.${base64url(canonicalize(payload))}`;return{payload,protected:protectedHeader,signature:sign(null,Buffer.from(input),config.privateKey).toString("base64url")};}
export function assertionHash(payload:object){return createHash("sha256").update(canonicalize(payload)).digest("hex");}
export function verifyLocalSignature(assertion:SignedAuthenticityAssertion,key:KeyObject){const input=`${base64url(canonicalize(assertion.protected))}.${base64url(canonicalize(assertion.payload))}`;return verify(null,Buffer.from(input),key,Buffer.from(assertion.signature,"base64url"));}
