import "server-only";
import {aggregateDispatchResults,dispatchClaimedDelivery} from "@/lib/delivery-dispatch-core";
import type {ClaimedDelivery} from "@/lib/delivery-message";
import {getDeliveryProvider} from "@/lib/delivery-providers";
import {createAdminClient} from "@/lib/supabase/admin";
import {canonicalAppUrl} from "@/lib/sms-readiness";
export const DELIVERY_MAX_ATTEMPTS=3,DELIVERY_STUCK_TIMEOUT_SECONDS=15*60,DELIVERY_MAX_BATCH_SIZE=25;
function logDelivery(event:string,delivery:ClaimedDelivery,details:Record<string,string|number|boolean>={}){console.info(JSON.stringify({event,deliveryId:delivery.delivery_id,updateId:delivery.update_id,creatorId:delivery.creator_id,transport:delivery.transport,attempt:delivery.attempt_count,...details}));}
export async function dispatchQueuedDeliveries({limit=10}:{limit?:number}={}){
 if(!Number.isInteger(limit)||limit<1||limit>DELIVERY_MAX_BATCH_SIZE)throw new Error(`Delivery batch limit must be between 1 and ${DELIVERY_MAX_BATCH_SIZE}.`);
 console.info(JSON.stringify({event:"dispatcher_run_start",requested_limit:limit}));const admin=createAdminClient();if(!admin)throw new Error("Delivery execution is not configured.");const appUrl=canonicalAppUrl();if(!appUrl)throw new Error("Canonical application URL is not configured.");
 const{data,error}=await admin.rpc("claim_update_deliveries",{p_limit:limit,p_max_attempts:DELIVERY_MAX_ATTEMPTS,p_stuck_timeout_seconds:DELIVERY_STUCK_TIMEOUT_SECONDS});if(error)throw new Error("Queued deliveries could not be claimed.");const claimed=(data??[])as ClaimedDelivery[];
 const updateIds=[...new Set(claimed.map(item=>item.update_id))],destinationResult=updateIds.length?await admin.from("creator_update_recovery_destinations").select("update_id,connected_account_id,provider_snapshot,account_display_snapshot,destination_url_snapshot").in("update_id",updateIds):{data:[],error:null};if(destinationResult.error)throw new Error("Recovery destinations could not be loaded for delivery.");
 for(const delivery of claimed)delivery.recovery_destinations=(destinationResult.data??[]).filter(item=>item.update_id===delivery.update_id).map(item=>({connected_account_id:item.connected_account_id,provider:item.provider_snapshot,display_name:item.account_display_snapshot,url:item.destination_url_snapshot}));
 console.info(JSON.stringify({event:"dispatcher_claimed",claimed_count:claimed.length}));const results=[];
 for(const delivery of claimed){logDelivery("delivery_claimed",delivery);try{const result=await dispatchClaimedDelivery(delivery,{appUrl,maxAttempts:DELIVERY_MAX_ATTEMPTS,resolveProvider:getDeliveryProvider,async markAccepted(deliveryId,provider,providerMessageId){const{error:markError}=await admin.rpc("mark_update_delivery_accepted",{p_delivery_id:deliveryId,p_provider:provider,p_provider_message_id:providerMessageId});if(markError)throw new Error("Accepted delivery could not be recorded.");},async markFailed(input){const{data:status,error:markError}=await admin.rpc("mark_update_delivery_failed",{p_delivery_id:input.deliveryId,p_provider:input.provider,p_code:input.code,p_reason:input.reason,p_retryable:input.retryable,p_max_attempts:input.maxAttempts});if(markError||status!=="queued"&&status!=="failed")throw new Error("Failed delivery could not be recorded.");if(delivery.transport==="sms"&&["invalid_destination","opted_out"].includes(input.code)){const{data:failed,error}=await admin.from("update_deliveries").select("destination_hash").eq("id",delivery.delivery_id).maybeSingle();if(error)throw error;if(failed?.destination_hash){const{error:revoke}=await admin.rpc("opt_out_sms_recovery_method",{p_destination_hash:failed.destination_hash,p_reason:input.code});if(revoke)throw new Error("Invalid SMS destination could not be revoked.");}}if(delivery.transport==="whatsapp"&&["invalid_destination","not_whatsapp_capable","not_opted_in"].includes(input.code)){const{data:failed,error}=await admin.from("update_deliveries").select("destination_hash").eq("id",delivery.delivery_id).maybeSingle();if(error)throw error;if(failed?.destination_hash){const{error:revoke}=await admin.rpc("opt_out_whatsapp_recovery_method",{p_destination_hash:failed.destination_hash,p_reason:input.code});if(revoke)throw new Error("Invalid WhatsApp destination could not be revoked.");}}return status;}});logDelivery(result.status==="accepted"?"provider_accepted":result.status==="queued"?"delivery_retry_scheduled":"delivery_failed",delivery,{provider:result.provider,code:result.code});results.push(result);}catch{const provider=delivery.transport==="email"?"resend":delivery.transport==="browser_notification"?"web-push":delivery.transport==="sms"?"twilio":delivery.transport==="whatsapp"?"twilio-whatsapp":"unsupported";logDelivery("delivery_state_update_failed",delivery,{provider,code:"state_update_failed"});results.push({deliveryId:delivery.delivery_id,transport:delivery.transport,status:"sending"as const,provider,retryable:true,code:"state_update_failed"});}}
 const summary=aggregateDispatchResults(results);console.info(JSON.stringify({event:"dispatcher_run_end",claimed_count:claimed.length,accepted_count:summary.accepted,failed_count:summary.failed,retrying_count:summary.retried}));return summary;
}
