"use client";
import {useState} from "react";

type Asset={provider:"facebook"|"instagram";assetType:string;displayName:string|null;canonicalUrl:string;pictureUrl:string|null;username:string|null;selectionKey:string;authorityAvailable:boolean;linkedInstagramAvailable:boolean};
export function MetaAssetSelection({connectionId}:{connectionId:string}){
  const[assets,setAssets]=useState<Asset[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
  async function discover(){setBusy(true);setMessage("");const response=await fetch(`/api/integrations/meta/assets?connectionId=${encodeURIComponent(connectionId)}`,{cache:"no-store"}),value:unknown=await response.json();if(response.ok&&typeof value==="object"&&value!==null&&"assets"in value&&Array.isArray(value.assets)){const found=(value.assets as Asset[]).filter(asset=>asset.provider==="facebook");setAssets(found);if(!found.length)setMessage("No eligible Facebook Pages were found for this account. Personal Facebook profiles are not supported.");}else setMessage("Authorized Pages could not be loaded.");setBusy(false);}
  async function select(asset:Asset){setBusy(true);const response=await fetch("/api/integrations/meta/select-facebook-page",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({connectionId,selectionKey:asset.selectionKey})});setMessage(response.ok?`${asset.displayName??"Facebook Page"} connected.`:"This Page could not be selected. Check your Page access and app review status.");setBusy(false);}
  return <section className="surface rounded-2xl p-5"><h3 className="font-semibold">Choose a Facebook Page</h3><p className="mt-2 text-sm text-zinc-400">Only the Page you choose becomes an AudienceOwn account. Page credentials and stable IDs stay server-side.</p><button className="button button-secondary mt-4" disabled={busy} onClick={discover}>{busy?"Checking…":"Show authorized Pages"}</button>{assets.length>0&&<ul className="mt-4 space-y-2">{assets.map(asset=><li className="flex items-center justify-between gap-3 rounded-xl border border-white/10 p-3" key={asset.selectionKey}><span className="flex items-center gap-3">{asset.pictureUrl&&<span aria-hidden="true" className="size-9 rounded-full bg-cover bg-center" style={{backgroundImage:`url(${asset.pictureUrl})`}}/>}<span><strong className="block text-sm">{asset.displayName??"Facebook Page"}</strong><small className="text-zinc-500">{asset.username?`@${asset.username}`:"Facebook Page"}</small></span></span><button className="button button-secondary" disabled={busy||!asset.authorityAvailable} onClick={()=>select(asset)}>Select</button></li>)}</ul>}{message&&<p className="mt-3 text-sm text-zinc-400">{message}</p>}</section>;
}
