export const IDENTITY_MONITORING_POLICY_VERSION="identity-monitoring-v1";
export type MonitoringObservationType="account_identity_confirmed"|"account_handle_changed"|"account_display_name_changed"|"account_url_changed"|"account_unavailable"|"account_restored"|"stable_identity_mismatch"|"provider_grant_revoked"|"provider_scope_missing"|"provider_review_required"|"verification_expired"|"verification_restored"|"domain_verification_failed"|"domain_verification_restored"|"domain_dns_changed"|"duplicate_primary_detected"|"sync_failure"|"sync_recovered"|"emergency_replacement_invalidated"|"emergency_replacement_restored";
export type MonitoringSeverity="informational"|"low"|"medium"|"high"|"critical";
export type MonitoringClassification={severity:MonitoringSeverity;incidentRequired:boolean;trustReevaluationRequired:boolean;publicBadgeSuppressionRequired:boolean;accountStateChange:"none"|"needs_attention"|"revoked";emergencyDraftAllowed:boolean;creatorNotificationRequired:boolean;blockers:string[];warnings:string[];policyVersion:string};
export function classifyIdentityObservation(type:MonitoringObservationType,context:{official?:boolean;primary?:boolean;publicVisible?:boolean;activeEmergency?:boolean;failureCount?:number}={}):MonitoringClassification{const highIdentity=context.official||context.primary||context.publicVisible;let severity:MonitoringSeverity="informational",accountStateChange:MonitoringClassification["accountStateChange"]="none",trust=false,badge=false,draft=false,notify=false;const blockers:string[]=[],warnings:string[]=[];
 if(type==="stable_identity_mismatch"){severity="critical";accountStateChange="needs_attention";trust=badge=draft=notify=true;blockers.push("stable_identity_mismatch");}
 else if(type==="emergency_replacement_invalidated"){severity="critical";trust=badge=notify=true;draft=false;blockers.push("active_replacement_unverified");}
 else if(type==="provider_grant_revoked"){severity="high";accountStateChange="revoked";trust=badge=notify=true;warnings.push("provider_reconnect_required");}
 else if(type==="account_unavailable"){severity=highIdentity?"high":context.failureCount&&context.failureCount>=3?"medium":"low";if(severity==="high"){accountStateChange="needs_attention";trust=badge=draft=notify=true;}else warnings.push("transient_provider_unavailable");}
 else if(type==="sync_failure"){severity=(context.failureCount??1)>=3?"medium":"informational";trust=severity==="medium";notify=severity==="medium";warnings.push("provider_sync_failed");}
 else if(type==="domain_verification_failed"||type==="domain_dns_changed"){severity=context.primary?"high":"medium";trust=badge=notify=true;warnings.push("domain_verification_invalid");}
 else if(type==="verification_expired"||type==="provider_scope_missing"||type==="provider_review_required"){severity=highIdentity?"high":"medium";accountStateChange="needs_attention";trust=badge=notify=true;warnings.push("verification_action_required");}
 else if(type==="account_url_changed"){severity=highIdentity?"medium":"low";trust=true;notify=severity==="medium";}
 else if(type==="account_handle_changed"||type==="account_display_name_changed"){severity=highIdentity?"low":"informational";}
 else if(type.endsWith("restored")||type==="sync_recovered"){severity="informational";trust=true;notify=true;}
 return{severity,incidentRequired:["medium","high","critical"].includes(severity),trustReevaluationRequired:trust,publicBadgeSuppressionRequired:badge,accountStateChange,emergencyDraftAllowed:draft,creatorNotificationRequired:notify,blockers,warnings,policyVersion:IDENTITY_MONITORING_POLICY_VERSION};}
export function preciseAccountChanges(previous:{stableId:string;handle:string|null;name:string|null;url:string},current:{stableId:string;handle:string|null;name:string|null;url:string}):MonitoringObservationType[]{if(previous.stableId!==current.stableId)return["stable_identity_mismatch"];const changes:MonitoringObservationType[]=[];if(previous.handle!==current.handle)changes.push("account_handle_changed");if(previous.name!==current.name)changes.push("account_display_name_changed");if(previous.url!==current.url)changes.push("account_url_changed");return changes.length?changes:["account_identity_confirmed"];}
