import"server-only";import{randomUUID}from"node:crypto";import{createAdminClient}from"@/lib/supabase/admin";import{decryptSocialSecret}from"@/lib/social-secrets";import{getSocialProvider}from"@/lib/social-providers/registry";import{isSocialProvider}from"@/lib/social-providers/normalize";
function metadata(value:unknown){return value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:undefined;}
export async function synchronizeIdentityGraph(limit=20){const db=createAdminClient();if(!db)throw new Error("identity_sync_not_configured");const bounded=Math.max(1,Math.min(limit,100));
const{data:newConnections}=await db.from("connected_accounts").select("id").not("external_account_id","is",null).in("connection_health",["healthy","degraded"]).eq("provider_status","ready").limit(bounded);
let projected=0;for(const connection of newConnections??[]){const result=await db.rpc("sync_identity_account_from_connection",{p_connection_id:connection.id});if(!result.error)projected++;}
const{data:accounts,error}=await db.rpc("claim_identity_accounts",{p_limit:bounded,p_lease_owner:randomUUID()});if(error)throw error;const summary={claimed:accounts?.length??0,projected,healthy:0,needsAttention:0,revoked:0,failed:0,byProvider:{}as Record<string,{healthy:number;failed:number}>};
for(const account of accounts??[]){const providerSummary=summary.byProvider[account.provider]??={healthy:0,failed:0};try{if(!account.source_connection_id||!isSocialProvider(account.provider))throw new Error("identity_provider_unavailable");const adapter=getSocialProvider(account.provider),fetcher=adapter.fetchEmergencyAccountIdentity??adapter.fetchIdentity;if(!fetcher)throw new Error("provider_verification_unavailable");const[{data:connection},{data:secret}]=await Promise.all([db.from("connected_accounts").select("*").eq("id",account.source_connection_id).single(),db.from("platform_connection_secrets").select("access_token_ciphertext,refresh_token_ciphertext").eq("platform_connection_id",account.source_connection_id).single()]);
if(!connection||!secret||["revoked","expired"].includes(connection.connection_health)){await db.rpc("apply_identity_provider_sync",{p_account_id:account.id,p_stable_id:account.stable_provider_account_id,p_handle:account.display_handle??"",p_name:account.display_name??"",p_url:account.canonical_profile_url,p_status:"revoked",p_error:"provider_grant_unavailable"});summary.revoked++;continue;}
const identity=await fetcher({accessToken:decryptSocialSecret(secret.access_token_ciphertext),refreshToken:secret.refresh_token_ciphertext?decryptSocialSecret(secret.refresh_token_ciphertext):undefined,metadata:metadata(connection.provider_metadata)});const changed=identity.id!==account.stable_provider_account_id;await db.rpc("apply_identity_provider_sync",{p_account_id:account.id,p_stable_id:identity.id,p_handle:identity.name,p_name:identity.name,p_url:identity.url,p_status:changed?"changed":"healthy",p_error:changed?"stable_identity_changed":undefined});if(changed)summary.needsAttention++;else{summary.healthy++;providerSummary.healthy++;}}
catch{summary.failed++;providerSummary.failed++;await db.rpc("apply_identity_provider_sync",{p_account_id:account.id,p_stable_id:account.stable_provider_account_id,p_handle:account.display_handle??"",p_name:account.display_name??"",p_url:account.canonical_profile_url,p_status:"failed",p_error:"provider_sync_failed"});}}
return summary;}
