export const TRUST_POLICY_VERSION="identity-trust-v1";
export type TrustState="unverified"|"partially_verified"|"verified"|"strongly_verified"|"needs_attention"|"restricted";
export type TrustSignalState="strong"|"valid"|"stale"|"weak"|"pending"|"revoked"|"conflicting"|"unavailable";
export type TrustPriority="low"|"medium"|"high"|"critical";
export type TrustSource={id:string;kind:"account"|"domain"|"emergency";provider?:string;verificationStatus:string;official?:boolean;primary?:boolean;publicVisible?:boolean;stableId?:string|null;verifiedAt?:string|null;revalidatedAt?:string|null;syncStatus?:string|null;emergencyActive?:boolean};
export type TrustSignal={sourceId:string;type:string;state:TrustSignalState;family:string;weight:number;reasonCode:string;observedAt:string|null;expiresAt:string|null};
export type TrustRecommendation={code:string;priority:TrustPriority;title:string;description:string;actionUrl:string|null};
export type TrustEvaluation={trustState:TrustState;internalScore:number;signals:TrustSignal[];recommendations:TrustRecommendation[];blockers:string[];warnings:string[];policyVersion:string;evaluatedAt:string;expiresAt:string|null};
export type TrustPolicyOptions={now?:Date;providerFreshnessHours?:number;domainFreshnessHours?:number;emergencyFreshnessHours?:number;evaluationTtlMinutes?:number};
const family:Record<string,string>={youtube:"google",google:"google",instagram:"meta",facebook:"meta",threads:"meta",tiktok:"bytedance",x:"x",twitter:"x",spotify:"spotify",twitch:"twitch",linkedin:"linkedin",pinterest:"pinterest",discord:"discord",snapchat:"snapchat"};
export function providerFamily(provider?:string){return provider?family[provider.toLowerCase()]??"other":"other";}
function hours(value:unknown,fallback:number){const n=Number(value);return Number.isFinite(n)&&n>0?n:fallback;}
function recommendation(code:string,priority:TrustPriority,title:string,description:string,actionUrl:string|null="/dashboard/identity"):TrustRecommendation{return{code,priority,title,description,actionUrl};}
export function evaluateTrust(sources:TrustSource[],options:TrustPolicyOptions={}):TrustEvaluation{const now=options.now??new Date(),providerHours=hours(options.providerFreshnessHours??process.env.TRUST_PROVIDER_FRESHNESS_HOURS,168),domainHours=hours(options.domainFreshnessHours??process.env.TRUST_DOMAIN_FRESHNESS_HOURS,720),emergencyHours=hours(options.emergencyFreshnessHours??process.env.TRUST_EMERGENCY_REPLACEMENT_FRESHNESS_HOURS,24),ttl=hours(options.evaluationTtlMinutes??process.env.TRUST_EVALUATION_TTL_MINUTES,60);const signals:TrustSignal[]=[];const seen=new Set<string>();
 for(const source of sources){const key=`${source.kind}:${source.provider??"domain"}:${source.stableId??source.id}`;if(seen.has(key))continue;seen.add(key);const isDomain=source.kind==="domain",isEmergency=source.kind==="emergency"||source.emergencyActive,freshHours=isEmergency?emergencyHours:isDomain?domainHours:providerHours,observed=source.revalidatedAt??source.verifiedAt??null,age=observed?(now.getTime()-Date.parse(observed))/36e5:Infinity,sourceFamily=isDomain?"domain":providerFamily(source.provider);let state:TrustSignalState="weak",type=isDomain?"verified_domain":"provider_oauth_verified",weight=0,reasonCode="identity_unverified";
  if(source.verificationStatus==="revoked"){state="revoked";type=isDomain?"revoked_domain":isEmergency?"revoked_emergency_replacement":"provider_identity_revoked";weight=-100;reasonCode="verification_revoked";}
  else if(source.verificationStatus==="verified"&&(!source.stableId&&!isDomain)){state="conflicting";type="stable_provider_id_missing";weight=-100;reasonCode="stable_id_missing";}
  else if(source.verificationStatus==="verified"&&age>freshHours){state="stale";type=isDomain?"stale_domain_verification":"provider_identity_stale";weight=-10;reasonCode="verification_stale";}
  else if(source.verificationStatus==="verified"){state=source.official||source.primary||isDomain||isEmergency?"strong":"valid";type=isEmergency?"verified_emergency_replacement":isDomain?"verified_domain":source.official?"official_account_verified":source.primary?"primary_account_verified":"provider_oauth_verified";weight=state==="strong"?35:25;reasonCode="authoritative_verification";}
  else if(source.verificationStatus==="pending"){state="pending";type="provider_review_required";weight=0;reasonCode="verification_pending";}
  else if(source.syncStatus==="failed"){state="unavailable";type="sync_failure";weight=-10;reasonCode="provider_sync_failed";}
  else if(source.publicVisible){state="weak";type="public_account_without_verification";weight=-5;reasonCode="public_identity_unverified";}
  signals.push({sourceId:source.id,type,state,family:sourceFamily,weight,reasonCode,observedAt:observed,expiresAt:observed?new Date(Date.parse(observed)+freshHours*36e5).toISOString():null});}
 const revoked=signals.filter(s=>s.state==="revoked"||s.state==="conflicting"),stale=signals.filter(s=>s.state==="stale"||s.state==="unavailable"),positive=signals.filter(s=>s.state==="strong"||s.state==="valid"),families=new Set(positive.map(s=>s.family)),blockers=[...new Set(revoked.map(s=>s.reasonCode))],warnings=[...new Set(stale.map(s=>s.reasonCode))],internalScore=Math.max(0,Math.min(100,signals.reduce((sum,s)=>sum+s.weight,0)));let trustState:TrustState;
 if(blockers.length)trustState="restricted";else if(warnings.length&&positive.length)trustState="needs_attention";else if(positive.length&&families.size>=2&&signals.filter(s=>s.state==="strong").length>=2)trustState="strongly_verified";else if(positive.length)trustState="verified";else if(signals.some(s=>s.state==="pending"||s.state==="weak"))trustState="partially_verified";else trustState="unverified";
 const recommendations:TrustRecommendation[]=[];if(!positive.length)recommendations.push(recommendation("verify_primary_account","high","Verify a primary account","Connect and verify the account followers should treat as authoritative."));if(!families.has("domain"))recommendations.push(recommendation("verify_domain","medium","Verify your creator domain","Add an independent creator-owned domain verification."));if(stale.some(s=>s.type.includes("domain")))recommendations.push(recommendation("refresh_stale_identity","high","Refresh stale verification","Revalidate the identity signal whose freshness window expired."));if(stale.some(s=>s.type==="provider_identity_stale"||s.type==="sync_failure"))recommendations.push(recommendation("reconnect_provider","high","Reconnect the provider","Reconnect or revalidate the provider to restore current ownership evidence."));if(positive.length&&families.size<2)recommendations.push(recommendation("add_independent_verification","medium","Add independent verification","Verify a different provider family or creator-owned domain."));if(revoked.length)recommendations.push(recommendation("archive_revoked_account","critical","Resolve revoked identity","Keep revoked identities hidden and restore authoritative verification before publishing them."));
 return{trustState,internalScore,signals,recommendations:[...new Map(recommendations.map(r=>[r.code,r])).values()],blockers,warnings,policyVersion:TRUST_POLICY_VERSION,evaluatedAt:now.toISOString(),expiresAt:new Date(now.getTime()+ttl*60e3).toISOString()};}
export const publicTrustCopy:Record<TrustState,{label:string;summary:string}>={unverified:{label:"Identity not yet verified",summary:"No verified identity signals are currently available."},partially_verified:{label:"Identity partially verified",summary:"Some identity signals are available, but authoritative verification is incomplete."},verified:{label:"Verified identity",summary:"Identity is verified through an authoritative channel."},strongly_verified:{label:"Strongly verified identity",summary:"Verified across multiple independent channels."},needs_attention:{label:"Identity verification needs attention",summary:"Verified identity evidence exists, but an important signal needs attention."},restricted:{label:"Identity verification unavailable",summary:"Verified identity badges are temporarily unavailable."}};
