import{createPublicKey,verify}from"node:crypto";import{base64url,canonicalize}from"@/lib/authenticity/canonical";import type{AuthenticityManifest,AccountLookup}from"@/lib/authenticity/network-types";
export type VerificationResult={valid:true;version:string;issuer:string;keyId:string;issuedAt:string;expiresAt:string;payload:Record<string,unknown>}|{valid:false;code:"invalid_signature"|"expired"|"unsupported_version"|"unsupported_algorithm"|"unknown_key"|"revoked_key"|"wrong_issuer"|"malformed_payload"|"network_error";message:string};
type Jwk={kid:string;kty?:string;crv?:string;x?:string;alg?:string;revoked?:boolean};type Envelope={payload:Record<string,unknown>;protected:{alg:string;kid:string;typ:string};signature:string};
const supported=new Set(["audienceown-authenticity-v1","audienceown-account-status-v1","audienceown-continuity-v1"]);
export class AudienceOwnAuthenticityClient{private keys:Jwk[]=[];private fetchedAt=0;readonly issuer:string;constructor(options:{issuer:string}){const issuer=new URL(options.issuer);if(issuer.protocol!=="https:"&&issuer.hostname!=="localhost")throw new Error("issuer must use HTTPS");this.issuer=issuer.origin;}
private async refresh(){const response=await fetch(`${this.issuer}/.well-known/audienceown-authenticity-keys.json`,{headers:{accept:"application/json"}});if(!response.ok)throw new Error("key discovery failed");const value=await response.json();if(!value||!Array.isArray(value.keys))throw new Error("invalid key set");this.keys=value.keys;this.fetchedAt=Date.now();}
async verify(value:unknown):Promise<VerificationResult>{if(!value||typeof value!=="object")return invalid("malformed_payload","Malformed signed response");const envelope=value as Envelope,p=envelope.payload;if(!p||!envelope.protected||typeof envelope.signature!=="string"||typeof p.version!=="string"||typeof p.issuer!=="string"&&typeof p.iss!=="string")return invalid("malformed_payload","Malformed signed response");const issuer=String(p.issuer??p.iss);if(issuer!==this.issuer)return invalid("wrong_issuer","Issuer does not match configured AudienceOwn issuer");if(!supported.has(p.version))return invalid("unsupported_version","Unsupported assertion version");if(envelope.protected.alg!=="EdDSA")return invalid("unsupported_algorithm","Unsupported signature algorithm");const issuedAt=String(p.issuedAt??""),expiresAt=String(p.expiresAt??""),expires=Date.parse(expiresAt);if(!Number.isFinite(expires))return invalid("malformed_payload","Invalid assertion time");if(expires<=Date.now())return invalid("expired","Assertion has expired");try{if(!this.keys.length||Date.now()-this.fetchedAt>300_000)await this.refresh();let key=this.keys.find(k=>k.kid===envelope.protected.kid);if(!key){await this.refresh();key=this.keys.find(k=>k.kid===envelope.protected.kid);}if(!key)return invalid("unknown_key","Signing key is unknown");if(key.revoked)return invalid("revoked_key","Signing key is revoked");const input=`${base64url(canonicalize(envelope.protected))}.${base64url(canonicalize(p))}`,valid=verify(null,Buffer.from(input),createPublicKey({key:key as import("node:crypto").JsonWebKey,format:"jwk"}),Buffer.from(envelope.signature,"base64url"));return valid?{valid:true,version:p.version,issuer,keyId:key.kid,issuedAt,expiresAt,payload:p}:invalid("invalid_signature","Signature verification failed");}catch{return invalid("network_error","Unable to verify assertion");}}
async manifest(slug:string){const response=await fetch(`${this.issuer}/api/public/creators/${encodeURIComponent(slug)}/manifest`);if(!response.ok)throw new Error("manifest unavailable");return parseManifest(await response.json());}
async lookupAccount(url:string):Promise<AccountLookup>{const response=await fetch(`${this.issuer}/api/public/authenticity/lookup?url=${encodeURIComponent(url)}`);if(!response.ok)throw new Error("lookup unavailable");return response.json();}}
function invalid(code:Extract<VerificationResult,{valid:false}>["code"],message:string):VerificationResult{return{valid:false,code,message};}
export function parseManifest(value:unknown):AuthenticityManifest{if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("malformed manifest");const m=value as Partial<AuthenticityManifest>;if(m.version!=="audienceown-manifest-v1"||typeof m.issuer!=="string"||!m.creator||!m.authenticity||!Array.isArray(m.accounts)||!Array.isArray(m.domains)||!Array.isArray(m.relationships))throw new Error("malformed manifest");return m as AuthenticityManifest;}
export{canonicalize};
