import { capabilities } from "../capabilities";import { oauthProvider } from "../provider-factory";
import { classifyExpansionTwoError,manualProviderContent,reviewStatus } from "@/lib/providers/provider-expansion-two";
import { exchangeTikTokCode,fetchTikTokIdentity,pollTikTokVideos,refreshTikTokToken,revokeTikTokToken } from "@/lib/providers/tiktok";
const requiredScopes=["user.info.basic","user.info.profile","video.list"],configured=()=>Boolean(process.env.TIKTOK_CLIENT_KEY&&process.env.TIKTOK_CLIENT_SECRET&&process.env.TIKTOK_REDIRECT_URI),review=()=>reviewStatus(process.env.TIKTOK_APP_REVIEW_STATUS);
export const tiktokProvider=oauthProvider({displayName:"TikTok",availability:"provider_review_required",unavailableReason:"Display API video.list requires TikTok approval and a user grant.",capabilities:capabilities({oauth:true,tokenRefresh:true,tokenRevocation:true,polling:true,webhooks:false,contentDetection:true,automaticDrafts:true,automaticPublishing:false,manualImport:true}),config:{provider:"tiktok",clientIdEnv:"TIKTOK_CLIENT_KEY",clientSecretEnv:"TIKTOK_CLIENT_SECRET",redirectEnv:"TIKTOK_REDIRECT_URI",clientIdParam:"client_key",authorizeUrl:"https://www.tiktok.com/v2/auth/authorize/",tokenUrl:"https://open.tiktokapis.com/v2/oauth/token/",scopes:requiredScopes},adapter:{
 exchangeAuthorizationCode:({code,codeVerifier})=>exchangeTikTokCode(code,codeVerifier),refreshAccessToken:({refreshToken})=>{if(!refreshToken)throw new Error("token_refresh_failed");return refreshTikTokToken(refreshToken);},revokeConnection:({accessToken})=>revokeTikTokToken(accessToken),fetchIdentity:({accessToken})=>fetchTikTokIdentity(accessToken),pollContent:({accessToken,cursor})=>pollTikTokVideos(accessToken,cursor),fetchContent:({accessToken,cursor})=>pollTikTokVideos(accessToken,cursor),
 readiness:()=>{const credentialsPresent=configured(),reviewStatus=review(),approved=reviewStatus==="approved";return{configured:credentialsPresent,credentialsPresent,productConfigured:credentialsPresent,requiredScopes,grantedScopes:[],missingScopes:requiredScopes,accessLevel:approved?"approved":credentialsPresent?"development":"none",reviewStatus,connectionAvailable:credentialsPresent,identityAvailable:credentialsPresent,assetDiscoveryAvailable:false,contentDetectionAvailable:credentialsPresent&&approved,webhookAvailable:false,pollingAvailable:credentialsPresent&&approved,manualImportAvailable:true,manualVerificationAvailable:true,verificationAvailable:true,manualFallbackAvailable:true,missingConfiguration:["TIKTOK_CLIENT_KEY","TIKTOK_CLIENT_SECRET","TIKTOK_REDIRECT_URI"].filter(name=>!process.env[name]),limitations:[...(!approved?["TikTok video.list approval is not available; automatic detection is disabled."]:[]),"No new-video webhook is available for Display API; polling is authoritative.","TikTok publishing is not supported."]};},
 manualImport:async value=>manualProviderContent("tiktok",value),manualVerification:async()=>({verified:false,reason:"A profile URL alone does not establish ownership; complete an expiring public proof or authoritative OAuth verification."}),calculateNextSync:()=>new Date(Date.now()+15*60_000),classifyError:classifyExpansionTwoError,
}});
