import{z}from"zod";import{capabilities}from"../capabilities";import{oauthProvider}from"../provider-factory";import{verifyTwitchWebhook}from"../webhooks";import{bearerJson,identity}from"../base-oauth";import type{NormalizedSocialContent}from"../types";
const userSchema=z.object({id:z.string().regex(/^\d+$/),login:z.string().min(1),display_name:z.string().min(1),profile_image_url:z.string().url().optional(),broadcaster_type:z.string().optional()});
const streamSchema=z.object({id:z.string(),user_id:z.string(),user_login:z.string(),user_name:z.string(),title:z.string(),started_at:z.string().datetime(),thumbnail_url:z.string().optional()});
const videoSchema=z.object({id:z.string(),user_id:z.string(),user_login:z.string(),title:z.string(),description:z.string().optional(),url:z.string().url(),thumbnail_url:z.string().url().optional(),published_at:z.string().datetime(),type:z.string()});
function streamContent(item:z.infer<typeof streamSchema>):NormalizedSocialContent{return{provider:"twitch",externalObjectId:item.id,objectType:"livestream",eventType:"live_started",title:item.title,description:null,canonicalUrl:`https://www.twitch.tv/${item.user_login}`,thumbnailUrl:item.thumbnail_url?.replace("{width}","640").replace("{height}","360")??null,mediaUrls:[],sourcePublishedAt:item.started_at,scheduledStartAt:null,liveStatus:"live",rawMetadata:{broadcasterUserId:item.user_id}};}
export const twitchProvider=oauthProvider({displayName:"Twitch",availability:"implemented_credentials_required",capabilities:capabilities({oauth:true,tokenRefresh:true,tokenRevocation:true,polling:true,webhooks:true,contentDetection:true,livestreamDetection:true,scheduledContentDetection:true,automaticDrafts:true,automaticPublishing:false,manualImport:true}),config:{provider:"twitch",clientIdEnv:"TWITCH_CLIENT_ID",clientSecretEnv:"TWITCH_CLIENT_SECRET",redirectEnv:"TWITCH_REDIRECT_URI",authorizeUrl:"https://id.twitch.tv/oauth2/authorize",tokenUrl:"https://id.twitch.tv/oauth2/token",revokeUrl:"https://id.twitch.tv/oauth2/revoke",scopes:[]},adapter:{
 readiness(){const required=["TWITCH_CLIENT_ID","TWITCH_CLIENT_SECRET","TWITCH_REDIRECT_URI"],missingConfiguration=required.filter(x=>!process.env[x]);return{configured:missingConfiguration.length===0,connectionAvailable:missingConfiguration.length===0,verificationAvailable:missingConfiguration.length===0,contentDetectionAvailable:missingConfiguration.length===0,webhookAvailable:Boolean(process.env.TWITCH_EVENTSUB_SECRET&&process.env.TWITCH_EVENTSUB_CALLBACK_URL),pollingAvailable:missingConfiguration.length===0,manualFallbackAvailable:true,missingConfiguration,limitations:["EventSub is disabled without callback and signing secret.","No chat, moderation, or provider publishing is performed."]};},
 async fetchIdentity({accessToken}){const body=await bearerJson("twitch","https://api.twitch.tv/helix/users",accessToken,{"Client-Id":process.env.TWITCH_CLIENT_ID??""}),parsed=z.object({data:z.array(userSchema).min(1)}).parse(body),user=parsed.data[0];return identity(user.id,user.display_name,`https://www.twitch.tv/${user.login}`,{login:user.login,profileImageUrl:user.profile_image_url??null,broadcasterType:user.broadcaster_type??null});},
 async pollContent({accessToken,metadata,signal}){const broadcasterId=typeof metadata?.externalAccountId==="string"?metadata.externalAccountId:"";if(!/^\d+$/.test(broadcasterId))throw new Error("twitch_stable_user_id_required");const headers={Authorization:`Bearer ${accessToken}`,"Client-Id":process.env.TWITCH_CLIENT_ID??""},[streams,videos]=await Promise.all([fetch(`https://api.twitch.tv/helix/streams?user_id=${encodeURIComponent(broadcasterId)}`,{headers,signal}),fetch(`https://api.twitch.tv/helix/videos?user_id=${encodeURIComponent(broadcasterId)}&first=20&type=archive`,{headers,signal})]);if(!streams.ok||!videos.ok)throw new Error(streams.status===401||videos.status===401?"twitch_authorization_revoked":"twitch_api_failure");const streamData=z.object({data:z.array(streamSchema)}).parse(await streams.json()),videoData=z.object({data:z.array(videoSchema)}).parse(await videos.json()),items=[...streamData.data.map(streamContent),...videoData.data.map(v=>({provider:"twitch"as const,externalObjectId:v.id,objectType:"video"as const,eventType:"published"as const,title:v.title,description:v.description??null,canonicalUrl:v.url,thumbnailUrl:v.thumbnail_url??null,mediaUrls:[],sourcePublishedAt:v.published_at,scheduledStartAt:null,liveStatus:null,rawMetadata:{broadcasterUserId:v.user_id,videoType:v.type}}))];return{items,cursor:null};},
 verifyWebhook:verifyTwitchWebhook,async normalizeWebhook(event){const value=event.payload.event;if(typeof value!=="object"||value===null)return[];const get=(key:string)=>key in value&&typeof value[key as keyof typeof value]==="string"?String(value[key as keyof typeof value]):"",broadcaster=get("broadcaster_user_login"),timestamp=get("started_at")||String(event.payload._provider_event_timestamp??"");if(event.eventType==="authorization.revoke")return[];if(!broadcaster||!timestamp||Number.isNaN(Date.parse(timestamp))||!["stream.online","stream.offline","channel.update","user.update","authorization.revoke"].includes(event.eventType))return[];return[{provider:"twitch",externalObjectId:get("id")||`${get("broadcaster_user_id")}:${event.eventType}`,externalEventId:event.eventId,objectType:"livestream",eventType:event.eventType==="stream.online"?"live_started":event.eventType==="stream.offline"?"live_ended":"updated",title:get("title")||null,description:null,canonicalUrl:`https://www.twitch.tv/${broadcaster}`,thumbnailUrl:null,mediaUrls:[],sourcePublishedAt:new Date(timestamp).toISOString(),scheduledStartAt:null,liveStatus:event.eventType==="stream.online"?"live":event.eventType==="stream.offline"?"offline":null,rawMetadata:{authorizationRevoked:event.eventType==="authorization.revoke"}}];},
 async manualVerification(){return{verified:false,reason:"A Twitch URL alone remains unverified; connect OAuth or complete constrained public proof."};},calculateNextSync(){return new Date(Date.now()+15*60_000);},classifyError(error){const message=error instanceof Error?error.message:"";return{code:message.includes("revoked")?"authentication_revoked":"temporary_provider_failure",retryable:!message.includes("revoked")};}
}});
