import{capabilities}from"../capabilities";
import{oauthProvider}from"../provider-factory";
import{classifyExpansionThreeError,manualExpansionThreeContent}from"@/lib/providers/provider-expansion-three";
import{exchangeXCode,fetchXIdentity,pollXPosts,refreshXToken,revokeXToken}from"@/lib/providers/x";

const scopes=["tweet.read","users.read","offline.access"],tier=()=>process.env.X_API_ACCESS_TIER??"unavailable",configured=()=>Boolean(process.env.X_CLIENT_ID&&process.env.X_CLIENT_SECRET&&process.env.X_REDIRECT_URI);
export const xProvider=oauthProvider({displayName:"X",availability:"provider_review_required",unavailableReason:"X API reads require an enabled developer app and pay-per-use credits.",capabilities:capabilities({oauth:true,tokenRefresh:true,tokenRevocation:true,polling:true,contentDetection:true,automaticDrafts:true,automaticPublishing:false,manualImport:true}),config:{provider:"x",clientIdEnv:"X_CLIENT_ID",clientSecretEnv:"X_CLIENT_SECRET",redirectEnv:"X_REDIRECT_URI",authorizeUrl:"https://x.com/i/oauth2/authorize",tokenUrl:"https://api.x.com/2/oauth2/token",revokeUrl:"https://api.x.com/2/oauth2/revoke",scopes,pkce:true},adapter:{
 exchangeAuthorizationCode:({code,codeVerifier})=>exchangeXCode(code,codeVerifier),refreshAccessToken:({refreshToken})=>{if(!refreshToken)throw new Error("offline_access_scope_missing");return refreshXToken(refreshToken);},revokeConnection:({accessToken,refreshToken})=>revokeXToken(refreshToken??accessToken),fetchIdentity:({accessToken})=>fetchXIdentity(accessToken),
 pollContent:({accessToken,cursor,metadata})=>{if(metadata?.protected===true)throw new Error("protected_account_not_public");const id=typeof metadata?.externalAccountId==="string"?metadata.externalAccountId:"",username=typeof metadata?.handle==="string"?metadata.handle:"";return pollXPosts(accessToken,id,username,cursor);},fetchContent:({accessToken,cursor,metadata})=>{const id=typeof metadata?.externalAccountId==="string"?metadata.externalAccountId:"",username=typeof metadata?.handle==="string"?metadata.handle:"";return pollXPosts(accessToken,id,username,cursor);},
 readiness:()=>{const credentialsPresent=configured(),accessTier=tier(),entitled=!['unavailable','none','not_configured'].includes(accessTier),stream=process.env.X_STREAM_ENABLED==="true"&&["enterprise","pro_stream"].includes(accessTier);return{configured:credentialsPresent,credentialsPresent,productConfigured:entitled,requiredScopes:scopes,grantedScopes:[],missingScopes:scopes,accessLevel:entitled?"approved":credentialsPresent?"development":"none",accessTier,reviewStatus:entitled?"approved":credentialsPresent?"required":"not_configured",connectionAvailable:credentialsPresent,identityAvailable:credentialsPresent,assetDiscoveryAvailable:false,contentDetectionAvailable:false,webhookAvailable:false,streamAvailable:stream,pollingAvailable:false,manualImportAvailable:true,manualVerificationAvailable:true,verificationAvailable:true,manualFallbackAvailable:true,missingConfiguration:["X_CLIENT_ID","X_CLIENT_SECRET","X_REDIRECT_URI"].filter(name=>!process.env[name]),limitations:[...(!entitled?["X API pay-per-use credits and an enabled app are required for user reads."]:[]),...(!entitled?["Automatic post detection remains disabled until the configured X API tier permits timeline reads."]:[]),...(!stream?["Official stream access is unavailable for the configured access level."]:[]),"X publishing is disabled."]};},
 manualImport:async value=>manualExpansionThreeContent("x",value),manualVerification:async()=>({verified:false,reason:"An X URL alone does not prove ownership; use X OAuth."}),calculateNextSync:()=>new Date(Date.now()+12*60*60_000),classifyError:classifyExpansionThreeError
}});
