import{ecosystemDestinationTypes,type EcosystemDestinationType}from"./types";
const providerHosts:Record<string,string[]>={discord:["discord.com","discord.gg"],github:["github.com"],patreon:["patreon.com"],newsletter:[],podcast:[],rss:[],website:[],application:[],other:[]};
export function normalizeHostname(value:string){return value.trim().toLowerCase().replace(/\.$/,"");}
export function parsePublicHttpsUrl(value:string){try{const url=new URL(value);if(url.protocol!=="https:"||url.username||url.password||url.port)return null;url.hash="";return url;}catch{return null;}}
export function isAllowedProviderHostname(provider:string,hostname:string,verifiedDomains:string[]=[]){const host=normalizeHostname(hostname),allowed=providerHosts[provider]??[];return allowed.some(x=>host===x||host.endsWith(`.${x}`))||verifiedDomains.some(x=>host===normalizeHostname(x)||host.endsWith(`.${normalizeHostname(x)}`));}
export function validateManualImport(input:{provider:string;type:string;name:string;url:string},verifiedDomains:string[]=[]){const url=parsePublicHttpsUrl(input.url);if(!url)return{ok:false as const,error:"A canonical HTTPS URL is required"};if(!ecosystemDestinationTypes.includes(input.type as EcosystemDestinationType))return{ok:false as const,error:"Unsupported destination type"};if(!input.name.trim()||input.name.length>200)return{ok:false as const,error:"A valid public title is required"};if(!isAllowedProviderHostname(input.provider,url.hostname,verifiedDomains))return{ok:false as const,error:"Hostname is not authoritative for this provider"};return{ok:true as const,value:{provider:input.provider.toLowerCase(),type:input.type as EcosystemDestinationType,name:input.name.trim(),url:url.toString(),hostname:normalizeHostname(url.hostname)}};}
export function canPresentDestination(d:{verificationStatus:string;official:boolean;publicVisible:boolean;revokedAt?:string|null;archivedAt?:string|null}){return d.verificationStatus==="verified"&&d.official&&d.publicVisible&&!d.revokedAt&&!d.archivedAt;}
export function stableIdentityMatches(previous:string|null,next:string|null){return previous===null||next===null||previous===next;}

