import Link from "next/link";
import { Download, MailCheck, ShieldCheck, TrendingUp, Users, UserCheck, ArrowLeft, ArrowRight, ExternalLink } from "lucide-react";
import { requireCreator } from "@/lib/dal";
import { createClient } from "@/lib/supabase/server";
import { canonicalRecoveryPassUrl } from "@/lib/recovery-pass";
import { CopyLinkButton } from "@/components/copy-link-button";
import { ErrorState } from "@/components/product-state";
import { appUrl } from "@/lib/app-url";
import { PlatformBrandIcon } from "@/components/dashboard/platform-brand-icon";
import { AUDIENCE_FILTERS, getAudienceDashboardData, type AudienceFilter, type AudienceRange } from "@/lib/audience-dashboard";
import { debugError, debugLog } from "@/lib/debug";
import { resolvePrivateAudienceMatches } from "@/lib/audience-search";
import { AudienceControls } from "@/components/dashboard/audience-controls";
import "./audience.css";

const preferenceLabels:Record<string,string>={recovery:"Recovery",videos:"Video",livestreams:"Livestreams",podcast:"Podcast",products:"Products",announcements:"Announcements"};
const filterLabels:Record<AudienceFilter,string>={all:"All",main:"Main-account origin",recovery:"Recovery-account origin",videos:"Video updates",livestreams:"Livestreams",podcast:"Podcast updates",products:"Products",announcements:"Announcements",email:"Email verified",sms:"SMS verified","needs-verification":"Needs verification"};
const fmt=(n:number)=>new Intl.NumberFormat("en").format(n);
const qs=(current:Record<string,string>,patch:Record<string,string|number>)=>{const params=new URLSearchParams({...current,...Object.fromEntries(Object.entries(patch).map(([k,v])=>[k,String(v)]))});for(const key of ["search","filter","range"])if(!params.get(key)||key==="filter"&&params.get(key)==="all"||key==="range"&&params.get(key)==="30d")params.delete(key);return params.size?`?${params}`:"/dashboard/audience";};

export default async function Page({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
  const raw=await searchParams,one=(key:string)=>typeof raw[key]==="string"?raw[key] as string:"";
  const page=Math.max(1,Number.parseInt(one("page"),10)||1),query=(one("search")||one("q")).slice(0,80),filter=AUDIENCE_FILTERS.includes(one("filter")as AudienceFilter)?one("filter")as AudienceFilter:"all",range=(["30d","90d","12m"]as const).includes(one("range")as AudienceRange)?one("range")as AudienceRange:"30d";
  const current={search:query,filter,range},creator=await requireCreator(),db=await createClient(),passUrl=canonicalRecoveryPassUrl(appUrl(),creator.public_slug??"");
  debugLog("database",{route:"/dashboard/audience",stage:"audience.creator_resolution",status:"SUCCESS",creator_resolved:true});
  if(!db)return <ErrorState title="Audience data couldn’t be loaded." description="The data service is not configured." primaryAction={{label:"Try again",href:"/dashboard/audience"}}/>;
  let data;try{const privateSearch=await resolvePrivateAudienceMatches(creator.id,query);debugLog("database",{route:"/dashboard/audience",stage:"audience.search",status:"SUCCESS",searchMode:privateSearch.mode,matchedCount:privateSearch.matchedFollowerContactIds.size,creatorScoped:true});data=await getAudienceDashboardData(db,creator.id,{page,pageSize:20,query,filter,range,privateMatchPersonIds:privateSearch.matchedFollowerContactIds});}catch(error){debugError("database",error,{route:"/dashboard/audience",stage:"audience.dashboard_load"});return <ErrorState title="Audience data couldn’t be loaded." description="Your saved audience was not changed. Please try again." primaryAction={{label:"Try again",href:"/dashboard/audience"}}/>;}
  if(data.summary.protectedFollowers===0)return <div className="audience-page"><Header passUrl={passUrl}/><section className="audience-zero"><NetworkVisual/><p className="eyebrow">Your recovery network</p><h2>Your protected audience starts here</h2><p>Share your Recovery Pass so followers can stay connected even if a platform disappears tomorrow.</p><div><CopyLinkButton value={passUrl} label="Copy Recovery Pass link"/><Link className="button button-secondary" href={`/c/${creator.public_slug}`}><ExternalLink size={15}/>Open Creator Page</Link></div><Link href="/dashboard/platforms">Manage platforms →</Link></section></div>;
  const maxGrowth=Math.max(1,...data.growth.map(point=>point.activeAudience)),pages=Math.max(1,Math.ceil(data.followers.total/data.followers.pageSize));
  return <div className="audience-page"><Header passUrl={passUrl}/>
    <section aria-label="Audience summary" className="audience-kpis"><Metric icon={<Users/>} tone="violet" label="Protected followers" value={fmt(data.summary.protectedFollowers)} copy="Unique people currently protected through Recovery Pass."/><Metric icon={<UserCheck/>} tone="emerald" label="Reachable now" value={fmt(data.summary.reachableNow)} copy="People with at least one verified delivery route."/><Metric icon={<TrendingUp/>} tone="cyan" label="New this month" value={fmt(data.summary.newThisMonth)} copy={data.summary.newThisMonthChange===null?"Canonical joins this calendar month (UTC).":`${data.summary.newThisMonthChange>=0?"+":""}${data.summary.newThisMonthChange}% vs previous month`}/><Metric icon={<ShieldCheck/>} tone="amber" label="Verified reachability" value={`${data.summary.reachabilityRate}%`} copy="Of protected followers have a verified route."/></section>
    <div className="audience-middle"><Panel eyebrow="Audience sources" title="Accounts building your protected audience" copy="Per-account audiences can overlap; the total below is identity-deduplicated."><div className="source-list">{data.sources.length?data.sources.map(source=><div className={`source-row provider-${source.provider}`} key={source.accountId}><PlatformBrandIcon provider={source.provider} label={source.displayName}/><div><strong>{source.displayName}</strong><span>{source.provider}</span></div><span className={`account-badge ${source.accountRole}`}>{source.accountRole} account</span><div className="source-number"><strong>{fmt(source.protectedFollowerCount)}</strong><span>+{fmt(source.newThisMonth)} this month</span></div></div>):<p className="audience-muted">No account membership attribution is recorded yet.</p>}</div><div className="unique-summary"><Users size={18}/><strong>{fmt(data.summary.protectedFollowers)} unique protected followers</strong><span>AudienceOwn removes duplicate follower identities across accounts.</span></div></Panel><Panel eyebrow="Update preferences" title="What your audience wants to hear about" copy="Eligible unique followers as a share of your protected audience."><div className="preference-list">{data.preferences.length?data.preferences.map(item=><div className={`preference-row pref-${item.key}`} key={item.key}><div><span>{item.label}</span><strong>{fmt(item.followerCount)} <small>{item.percentage}%</small></strong></div><i><span style={{width:`${item.percentage}%`}}/></i></div>):<p className="audience-muted">No optional update preferences have been selected yet.</p>}</div></Panel></div>
    <section className="delivery-section"><Panel eyebrow="Delivery health" title="How your audience can be reached" copy="Channel counts overlap and are never summed as unique audience."><div className="delivery-grid"><Delivery label="Email verified" value={data.deliveryHealth.emailVerified}/><Delivery label="SMS verified" value={data.deliveryHealth.smsVerified}/><Delivery label="Email + SMS" value={data.deliveryHealth.bothVerified}/><Delivery label="Needs verification" value={data.deliveryHealth.needsVerification}/></div><div className="reach-insight"><MailCheck/><strong>{data.deliveryHealth.reachablePercentage}% of your protected audience is reachable through at least one verified channel.</strong></div></Panel></section>
    <section className="audience-growth surface"><div className="panel-heading"><div><p className="eyebrow">Protected audience growth</p><h2>Recovery Pass growth</h2><p>Active audience means unique identities with an active canonical consent relationship.</p></div><nav aria-label="Growth range">{(["30d","90d","12m"]as const).map(value=><Link className={range===value?"active":""} href={qs(current,{range:value,page:1})} key={value}>{value==="30d"?"30 days":value==="90d"?"90 days":"12 months"}</Link>)}</nav></div><div className="growth-chart" role="img" aria-label={`Active protected audience over ${range}`}><div className="chart-grid"/>{data.growth.map((point,index)=><i key={point.date} title={`${point.date}: ${point.activeAudience} active, ${point.newJoins} joins, ${point.unsubscribes} revoked`} style={{height:`${Math.max(2,point.activeAudience/maxGrowth*100)}%`,left:`${index/data.growth.length*100}%`,width:`${Math.max(.15,100/data.growth.length)}%`}}/>)}</div><div className="chart-legend"><span><b className="violet"/>Active protected audience</span><span><b className="cyan"/>Latest: {fmt(data.growth.at(-1)?.activeAudience??0)}</span></div></section>
    <section className="audience-followers surface"><div className="panel-heading"><div><p className="eyebrow">Protected followers</p><h2>People who joined your Recovery Pass</h2></div><span>{fmt(data.followers.total)} result{data.followers.total===1?"":"s"}</span></div><AudienceControls filter={filter} range={range} filters={AUDIENCE_FILTERS} labels={filterLabels}/><div role="region" aria-label="Protected fans table" tabIndex={0} className="followers-wrap"><table><thead><tr><th>Follower</th><th>Joined through</th><th>Preferences</th><th>Delivery</th><th>Joined</th></tr></thead><tbody>{data.followers.rows.map(row=><tr key={row.id}><td><strong>{row.identity}</strong></td><td>{row.sources.length?<div className="source-cell"><PlatformBrandIcon size="sm" provider={row.sources[0].provider} label={row.sources[0].name}/><span>{row.sources[0].name}{row.sources.length>1&&<small>+{row.sources.length-1} more</small>}</span></div>:<span className="audience-muted">Direct Recovery Pass</span>}</td><td><div className="chips">{row.preferences.filter(key=>preferenceLabels[key]).map(key=><span key={key}>{preferenceLabels[key]}</span>)}</div></td><td>{row.delivery.length?row.delivery.map(method=><span className="delivery-pill" key={method}>{method} ✓</span>):<span className="needs-pill">Needs verification</span>}</td><td>{new Intl.DateTimeFormat("en",{dateStyle:"medium",timeZone:"UTC"}).format(new Date(row.joined))}</td></tr>)}</tbody></table>{!data.followers.rows.length&&<p className="table-empty">No followers match this search and filter.</p>}</div><nav className="pagination" aria-label="Audience pages"><Link aria-disabled={page<=1} href={qs(current,{page:Math.max(1,page-1)})}><ArrowLeft/>Previous</Link><span>Page {page} of {pages}</span><Link aria-disabled={page>=pages} href={qs(current,{page:Math.min(pages,page+1)})}>Next<ArrowRight/></Link></nav></section>
    <section className="growth-cta"><div><p className="eyebrow">Recovery Pass</p><h2>Grow your protected audience</h2><p>Your Recovery Pass is the bridge that keeps you connected, no matter what happens.</p><code>{passUrl}</code><div><CopyLinkButton value={passUrl} label="Copy Recovery Pass link"/><Link className="button button-secondary" href={`/c/${creator.public_slug}`}>Open Creator Page</Link></div></div><NetworkVisual/></section></div>;
}
function Header({passUrl}:{passUrl:string}){return <header className="audience-header"><div><p className="eyebrow">Protected audience</p><h1>Audience</h1><p>People who chose to stay connected with you beyond any single platform.</p></div><div><CopyLinkButton value={passUrl} label="Copy Recovery Pass link"/><Link href="/api/audience/export" className="button button-secondary"><Download size={15}/>Export audience</Link></div></header>}
function Metric({icon,tone,label,value,copy}:{icon:React.ReactNode;tone:string;label:string;value:string;copy:string}){return <article className={`audience-metric ${tone}`}><span>{icon}</span><p>{label}</p><strong>{value}</strong><small>{copy}</small></article>}
function Panel({eyebrow,title,copy,children}:{eyebrow:string;title:string;copy:string;children:React.ReactNode}){return <section className="audience-panel surface"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2><p>{copy}</p>{children}</section>}
function Delivery({label,value}:{label:string;value:number}){return <div><span>{label}</span><strong>{fmt(value)}</strong></div>}
function NetworkVisual(){return <div className="network-visual" aria-hidden><span className="network-shield"><ShieldCheck/></span><i/><i/><i/><i/><b/><b/><b/></div>}
