"use client";

import { useState } from "react";

type Account={id:string;platform:string;label:string};
type Template={id:string;name:string;emergency_type:string;severity:string;title_template:string;message_template:string;default_affected_account_id:string|null;active:boolean};
type Plan={id:string;name:string;affected_account_id:string|null;emergency_type:string;severity:string;title:string;message:string;proposed_replacement_provider:string|null;proposed_replacement_handle:string|null;proposed_replacement_url:string|null;readiness_status:string;readiness_result:{blockers?:string[];warnings?:string[]};last_validated_at:string|null};
type Drill={id:string;source_plan_id:string|null;drill_mode:string;status:string;completed_at:string|null;result:{blockers?:string[];warnings?:string[];transportSummary?:Record<string,number>;recipientSummary?:{eligibleRecoveryPassHolders:number};approvalChecks?:{separateApproverAvailable:boolean}}};

const types=["account_hacked","account_banned","account_suspended","account_changed","fake_account_warning","scam_warning","other"];
const severities=["informational","important","critical"];

export function PreparednessCenter({accounts,templates,plans,drills}:{accounts:Account[];templates:Template[];plans:Plan[];drills:Drill[]}){
  const[busy,setBusy]=useState(false),[message,setMessage]=useState<string|null>(null);
  async function request(path:string,method="POST",body?:unknown){setBusy(true);setMessage(null);try{const response=await fetch(path,{method,headers:body?{"content-type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined});if(!response.ok)throw new Error("request_failed");window.location.reload();}catch{setMessage("We could not complete that action. Check your connection and try again.");setBusy(false);}}
  async function createTemplate(form:FormData){const raw=Object.fromEntries(form);await request("/api/emergency-templates","POST",{...raw,default_affected_account_id:raw.default_affected_account_id||null});}
  async function createPlan(form:FormData){const raw=Object.fromEntries(form);const template=templates.find(item=>item.id===raw.template_id);await request("/api/emergency-plans","POST",{template_id:raw.template_id||null,name:raw.name,affected_account_id:raw.affected_account_id,emergency_type:template?.emergency_type??raw.emergency_type,severity:template?.severity??raw.severity,title:template?.title_template??raw.title,message:template?.message_template??raw.message,proposed_replacement_provider:raw.proposed_replacement_provider||null,proposed_replacement_handle:raw.proposed_replacement_handle||null,proposed_replacement_url:raw.proposed_replacement_url||null,notes:raw.notes||null});}
  async function editTemplate(id:string,form:FormData){await request(`/api/emergency-templates/${id}`,"PATCH",Object.fromEntries(form));}
  return <div className="space-y-6">
    <section className="surface rounded-xl p-5"><p className="eyebrow">Message templates</p><h2 className="mt-2 text-xl font-semibold">Reusable verified messaging</h2><p className="mt-1 text-sm text-zinc-400">Templates are private working content. Using one copies its content into a new incident.</p>
      <form action={createTemplate} className="mt-5 grid gap-3 md:grid-cols-2"><input name="name" placeholder="Template name" required/><select name="emergency_type" defaultValue="account_hacked">{types.map(type=><option key={type}>{type}</option>)}</select><select name="severity" defaultValue="important">{severities.map(severity=><option key={severity}>{severity}</option>)}</select><select name="default_affected_account_id" defaultValue=""><option value="">No default account</option>{accounts.map(account=><option value={account.id} key={account.id}>{account.platform} · {account.label}</option>)}</select><input className="md:col-span-2" name="title_template" placeholder="Alert title" required maxLength={160}/><textarea className="md:col-span-2" name="message_template" placeholder="Verified public message" required rows={3} maxLength={5000}/><button className="button button-secondary w-fit" disabled={busy}>Save template</button></form>
      <div className="mt-5 grid gap-3">{templates.map(template=><details className="rounded-lg border border-white/10 p-3" key={template.id}><summary className="cursor-pointer text-sm font-medium">{template.name} · {template.severity}{!template.active?" · archived":""}</summary><form action={(form)=>editTemplate(template.id,form)} className="mt-3 grid gap-2 md:grid-cols-2"><input name="name" defaultValue={template.name}/><select name="severity" defaultValue={template.severity}>{severities.map(severity=><option key={severity}>{severity}</option>)}</select><input className="md:col-span-2" name="title_template" defaultValue={template.title_template}/><textarea className="md:col-span-2" name="message_template" defaultValue={template.message_template}/><button className="button button-secondary w-fit" disabled={busy}>Save changes</button>{template.active&&<button type="button" className="button button-secondary w-fit" disabled={busy} onClick={()=>request(`/api/emergency-templates/${template.id}/archive`)}>Archive</button>}</form></details>)}</div>
    </section>
    <section className="surface rounded-xl p-5"><p className="eyebrow">Prepared plans</p><h2 className="mt-2 text-xl font-semibold">Incident playbooks</h2><p className="mt-1 text-sm text-zinc-400">A plan binds copied message content to an official account. Each card shows that plan&apos;s server-validated execution status, separate from Recovery setup completion. Proposed replacement details are not verification.</p>
      <form action={createPlan} className="mt-5 grid gap-3 md:grid-cols-2"><input name="name" placeholder="Plan name" required/><select name="affected_account_id" required defaultValue=""><option value="" disabled>Official affected account</option>{accounts.map(account=><option value={account.id} key={account.id}>{account.platform} · {account.label}</option>)}</select><select name="template_id" defaultValue=""><option value="">Blank content</option>{templates.filter(item=>item.active).map(template=><option value={template.id} key={template.id}>{template.name}</option>)}</select><select name="emergency_type" defaultValue="account_hacked">{types.map(type=><option key={type}>{type}</option>)}</select><select name="severity" defaultValue="important">{severities.map(severity=><option key={severity}>{severity}</option>)}</select><input name="title" placeholder="Title (used without template)"/><textarea className="md:col-span-2" name="message" placeholder="Message (used without template)"/><input name="proposed_replacement_provider" placeholder="Proposed provider (unverified)"/><input name="proposed_replacement_handle" placeholder="Proposed handle (unverified)"/><input className="md:col-span-2" type="url" name="proposed_replacement_url" placeholder="https:// proposed replacement (unverified)"/><textarea className="md:col-span-2" name="notes" placeholder="Private preparation notes"/><button className="button button-primary w-fit" disabled={busy}>Save plan</button></form>
      <div className="mt-5 grid gap-4 md:grid-cols-2">{plans.map(plan=>{const last=drills.find(drill=>drill.source_plan_id===plan.id);return <article className="rounded-xl border border-white/10 p-4" key={plan.id}><div className="flex flex-wrap items-start justify-between gap-2"><div><h3 className="font-semibold">{plan.name}</h3><p className="text-xs uppercase text-zinc-400">{plan.readiness_status.replaceAll("_"," ")} · {plan.severity}</p></div>{plan.last_validated_at&&<span className="text-xs text-zinc-500">Checked {new Date(plan.last_validated_at).toLocaleString()}</span>}</div>{plan.proposed_replacement_url&&<p className="mt-2 text-sm text-amber-300">Proposed replacement — not verified</p>}<IssueList title="Blockers" items={plan.readiness_result.blockers}/><IssueList title="Warnings" items={plan.readiness_result.warnings}/><div className="mt-3 flex flex-wrap gap-2"><button className="button button-secondary" disabled={busy} onClick={()=>request(`/api/emergency-plans/${plan.id}/validate`)}>Validate plan</button><button className="button button-primary" disabled={busy||plan.readiness_status!=="ready"} onClick={()=>request(`/api/emergency-plans/${plan.id}/create-incident`)}>Create real incident</button><button className="button button-secondary" disabled={busy} onClick={async()=>{const response=await fetch("/api/emergency-drills",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({source_plan_id:plan.id,drill_mode:"full_activation",idempotency_key:crypto.randomUUID()})});const data=await response.json();if(response.ok)await request(`/api/emergency-drills/${data.drill.id}/run`);else setMessage(data.error);}}>Run drill</button></div>{last&&<p className="mt-3 text-xs text-zinc-400">Last drill: {last.status}{last.completed_at?` · ${new Date(last.completed_at).toLocaleString()}`:""}</p>}</article>})}</div>
    </section>
    <section className="rounded-xl border-2 border-sky-400/50 bg-sky-500/10 p-5"><p className="eyebrow text-sky-300">Drill mode</p><h2 className="mt-2 text-xl font-semibold">Simulation only — no audience notifications will be sent.</h2><p className="mt-1 text-sm text-zinc-300">Drills never activate an incident, publish a banner, create a delivery queue, or contact a provider.</p><div className="mt-4 grid gap-3">{drills.map(drill=><article className="rounded-lg bg-black/20 p-4" key={drill.id}><div className="flex justify-between gap-3"><strong>{drill.drill_mode.replaceAll("_"," ")}</strong><span className="uppercase">{drill.status}</span></div>{drill.result.recipientSummary&&<p className="mt-2 text-sm">Eligible Recovery Pass holders: {drill.result.recipientSummary.eligibleRecoveryPassHolders}</p>}{drill.result.transportSummary&&<p className="text-sm">Transport estimate: {Object.entries(drill.result.transportSummary).map(([key,value])=>`${key.replaceAll("_"," ")} ${value}`).join(" · ")}</p>}{drill.result.approvalChecks&&<p className="text-sm">Separate approver: {drill.result.approvalChecks.separateApproverAvailable?"available":"missing"}</p>}<IssueList title="Blockers" items={drill.result.blockers}/><IssueList title="Warnings" items={drill.result.warnings}/></article>)}</div></section>
    {message&&<p role="status" className="text-sm text-amber-300">{message}</p>}
  </div>;
}

function IssueList({title,items=[]}:{title:string;items?:string[]}){return items.length?<div className="mt-3"><strong className="text-xs uppercase text-zinc-400">{title}</strong><ul className="mt-1 list-disc pl-5 text-sm text-zinc-300">{items.map(item=><li key={item}>{item}</li>)}</ul></div>:null;}
