begin;

create table public.creator_authenticity_profiles(
 id uuid primary key default gen_random_uuid(),creator_id uuid not null unique references public.creators(id) on delete cascade,
 identity_profile_id uuid not null unique references public.creator_identity_profiles(id) on delete cascade,public_slug text not null unique,
 display_enabled boolean not null default true,embed_enabled boolean not null default true,qr_enabled boolean not null default true,
 show_verified_timestamps boolean not null default true,show_relationship_history boolean not null default true,
 public_title text check(public_title is null or char_length(btrim(public_title)) between 1 and 100),
 public_summary text check(public_summary is null or char_length(btrim(public_summary)) between 1 and 280),
 presentation_revision bigint not null default 1,issuance_lease_owner uuid,issuance_lease_expires_at timestamptz,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now());
insert into public.creator_authenticity_profiles(creator_id,identity_profile_id,public_slug)
 select p.creator_id,p.id,c.public_slug from public.creator_identity_profiles p join public.creators c on c.id=p.creator_id;
create or replace function public.create_authenticity_profile_from_identity()returns trigger language plpgsql set search_path=''as $$begin insert into public.creator_authenticity_profiles(creator_id,identity_profile_id,public_slug)select new.creator_id,new.id,c.public_slug from public.creators c where c.id=new.creator_id on conflict(creator_id)do nothing;return new;end$$;
create trigger identity_profile_creates_authenticity after insert on public.creator_identity_profiles for each row execute function public.create_authenticity_profile_from_identity();
revoke all on function public.create_authenticity_profile_from_identity()from public,anon,authenticated;
create or replace function public.sync_authenticity_public_slug()returns trigger language plpgsql set search_path=''as $$begin if new.public_slug is distinct from old.public_slug then update public.creator_authenticity_profiles set public_slug=new.public_slug,presentation_revision=presentation_revision+1 where creator_id=new.id;end if;return new;end$$;
create trigger creator_slug_syncs_authenticity after update of public_slug on public.creators for each row execute function public.sync_authenticity_public_slug();
revoke all on function public.sync_authenticity_public_slug()from public,anon,authenticated;

create table public.authenticity_signing_keys(
 key_id text primary key,algorithm text not null default 'EdDSA' check(algorithm in('EdDSA')),
 public_jwk jsonb not null check(jsonb_typeof(public_jwk)='object'),active boolean not null default false,
 not_before timestamptz not null default now(),retire_after timestamptz,revoked_at timestamptz,created_at timestamptz not null default now());
create unique index authenticity_one_active_key_idx on public.authenticity_signing_keys(active) where active and revoked_at is null;
create or replace function public.activate_authenticity_signing_key()returns trigger language plpgsql set search_path=''as $$begin if new.active and new.revoked_at is null then update public.authenticity_signing_keys set active=false where key_id<>new.key_id and active;end if;return new;end$$;
create trigger authenticity_key_activation before insert or update of active on public.authenticity_signing_keys for each row execute function public.activate_authenticity_signing_key();
revoke all on function public.activate_authenticity_signing_key()from public,anon,authenticated;

create table public.creator_authenticity_assertions(
 id uuid primary key default gen_random_uuid(),creator_id uuid not null references public.creators(id) on delete restrict,
 identity_profile_id uuid not null references public.creator_identity_profiles(id) on delete restrict,
 authenticity_profile_id uuid not null references public.creator_authenticity_profiles(id) on delete restrict,
 assertion_version text not null check(assertion_version='audienceown-authenticity-v1'),presentation_revision bigint not null,identity_revision bigint not null,
 trust_policy_version text not null,trust_state text not null check(trust_state in('unverified','partially_verified','verified','strongly_verified','needs_attention','restricted')),
 payload jsonb not null check(jsonb_typeof(payload)='object'),payload_hash text not null,key_id text not null,
 algorithm text not null default 'EdDSA' check(algorithm='EdDSA'),signature text not null,issued_at timestamptz not null,expires_at timestamptz not null,
 revoked_at timestamptz,superseded_at timestamptz,created_at timestamptz not null default now(),check(expires_at>issued_at));
create unique index authenticity_current_assertion_idx on public.creator_authenticity_assertions(authenticity_profile_id) where revoked_at is null and superseded_at is null;
create index authenticity_assertion_expiry_idx on public.creator_authenticity_assertions(expires_at) where revoked_at is null and superseded_at is null;

create table public.creator_authenticity_events(
 id bigint generated always as identity primary key,creator_id uuid not null references public.creators(id) on delete restrict,
 identity_profile_id uuid not null references public.creator_identity_profiles(id) on delete restrict,
 authenticity_profile_id uuid not null references public.creator_authenticity_profiles(id) on delete restrict,
 assertion_id uuid references public.creator_authenticity_assertions(id) on delete set null,event_type text not null,
 source text not null check(char_length(source) between 1 and 60),actor_user_id uuid references auth.users(id) on delete set null,
 metadata jsonb not null default '{}' check(jsonb_typeof(metadata)='object'),created_at timestamptz not null default now());
create index authenticity_events_profile_idx on public.creator_authenticity_events(authenticity_profile_id,id desc);

create table public.creator_authenticity_views(
 creator_id uuid not null references public.creators(id) on delete cascade,authenticity_profile_id uuid not null references public.creator_authenticity_profiles(id) on delete cascade,
 day date not null,page_views bigint not null default 0,card_views bigint not null default 0,badge_views bigint not null default 0,qr_resolutions bigint not null default 0,
 api_requests bigint not null default 0,verification_clicks bigint not null default 0,official_account_clicks bigint not null default 0,domain_clicks bigint not null default 0,
 emergency_replacement_clicks bigint not null default 0,assertion_requests bigint not null default 0,assertion_verification_failures bigint not null default 0,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),primary key(authenticity_profile_id,day));

create trigger authenticity_profiles_updated before update on public.creator_authenticity_profiles for each row execute function public.set_updated_at();
create trigger authenticity_views_updated before update on public.creator_authenticity_views for each row execute function public.set_updated_at();
create trigger authenticity_events_immutable before update or delete on public.creator_authenticity_events for each row execute function public.prevent_emergency_history_mutation();
create trigger authenticity_assertion_immutable before delete on public.creator_authenticity_assertions for each row execute function public.prevent_emergency_history_mutation();

create or replace function public.ensure_creator_authenticity_profile()returns uuid language plpgsql security definer set search_path=''as $$declare c public.creators%rowtype;p public.creator_identity_profiles%rowtype;a uuid;begin
 select*into c from public.creators where owner_user_id=auth.uid();if not found then raise exception'creator required'using errcode='42501';end if;
 select*into p from public.creator_identity_profiles where creator_id=c.id;if not found then raise exception'identity profile required'using errcode='23514';end if;
 insert into public.creator_authenticity_profiles(creator_id,identity_profile_id,public_slug)values(c.id,p.id,c.public_slug)
 on conflict(creator_id)do update set public_slug=excluded.public_slug returning id into a;return a;end$$;
revoke all on function public.ensure_creator_authenticity_profile()from public,anon;grant execute on function public.ensure_creator_authenticity_profile()to authenticated;

create or replace function public.update_creator_authenticity_profile(p_display_enabled boolean,p_embed_enabled boolean,p_qr_enabled boolean,p_show_verified_timestamps boolean,p_show_relationship_history boolean,p_public_title text default null,p_public_summary text default null)returns void language plpgsql security definer set search_path=''as $$declare a public.creator_authenticity_profiles%rowtype;begin
 select*into a from public.creator_authenticity_profiles where public.has_creator_permission(creator_id,'emergency_manage')for update;if not found then raise exception'access denied'using errcode='42501';end if;
 update public.creator_authenticity_profiles set display_enabled=p_display_enabled,embed_enabled=p_embed_enabled,qr_enabled=p_qr_enabled,show_verified_timestamps=p_show_verified_timestamps,show_relationship_history=p_show_relationship_history,public_title=nullif(btrim(p_public_title),''),public_summary=nullif(btrim(p_public_summary),''),presentation_revision=presentation_revision+1 where id=a.id;
 insert into public.creator_authenticity_events(creator_id,identity_profile_id,authenticity_profile_id,event_type,source,actor_user_id)values(a.creator_id,a.identity_profile_id,a.id,'presentation_updated','creator_dashboard',auth.uid());end$$;
revoke all on function public.update_creator_authenticity_profile(boolean,boolean,boolean,boolean,boolean,text,text)from public,anon;grant execute on function public.update_creator_authenticity_profile(boolean,boolean,boolean,boolean,boolean,text,text)to authenticated;

create or replace function public.request_authenticity_assertion_refresh()returns void language plpgsql security definer set search_path=''as $$declare a public.creator_authenticity_profiles%rowtype;begin select*into a from public.creator_authenticity_profiles where public.has_creator_permission(creator_id,'emergency_manage')for update;if not found then raise exception'access denied'using errcode='42501';end if;update public.creator_authenticity_profiles set presentation_revision=presentation_revision+1,issuance_lease_expires_at=null where id=a.id;insert into public.creator_authenticity_events(creator_id,identity_profile_id,authenticity_profile_id,event_type,source,actor_user_id)values(a.creator_id,a.identity_profile_id,a.id,'assertion_refresh_requested','creator_dashboard',auth.uid());end$$;
revoke all on function public.request_authenticity_assertion_refresh()from public,anon;grant execute on function public.request_authenticity_assertion_refresh()to authenticated;

create or replace function public.get_public_creator_authenticity(p_slug text)returns jsonb language plpgsql stable security definer set search_path=''as $$declare a public.creator_authenticity_profiles%rowtype;p public.creator_identity_profiles%rowtype;c public.creators%rowtype;t public.creator_trust_evaluations%rowtype;e public.creator_emergencies%rowtype;state text;updated timestamptz;begin
 select ap.* into a from public.creator_authenticity_profiles ap join public.creator_identity_profiles ip on ip.id=ap.identity_profile_id join public.creators cr on cr.id=ap.creator_id where ap.public_slug=p_slug and ap.display_enabled and cr.public_profile_enabled and ip.identity_status<>'archived';if not found then return null;end if;select*into p from public.creator_identity_profiles where id=a.identity_profile_id;
 select*into c from public.creators where id=a.creator_id;select*into t from public.creator_trust_evaluations where identity_profile_id=p.id and source_revision=p.identity_revision and(expires_at is null or expires_at>now())order by evaluated_at desc limit 1;
 select*into e from public.creator_emergencies where creator_id=a.creator_id and lifecycle_status='active'limit 1;
 state:=case when p.identity_status='restricted'or coalesce(t.trust_state,'unverified')='restricted'then'verification_restricted'when found then'emergency_recovery_active'when t.trust_state='strongly_verified'then'strongly_verified_identity'when t.trust_state='verified'then'verified_identity'when t.trust_state='needs_attention'then'verification_needs_attention'else'identity_unverified'end;
 updated:=greatest(a.updated_at,p.updated_at,coalesce(t.evaluated_at,'epoch'),coalesce(e.updated_at,'epoch'));
 return jsonb_build_object('creator',jsonb_build_object('slug',c.public_slug,'displayName',p.public_display_name,'profileUrl','/c/'||c.public_slug),
 'authenticity',jsonb_build_object('state',state,'label',case state when'strongly_verified_identity'then'Strongly verified identity'when'verified_identity'then'Verified identity'when'verification_needs_attention'then'Verification needs attention'when'emergency_recovery_active'then'Emergency recovery active'when'verification_restricted'then'Verification unavailable'else'Not yet verified'end,'summary',case state when'strongly_verified_identity'then'This identity is verified across multiple independent channels.'when'verified_identity'then'These accounts and domains are currently verified as belonging to this creator.'when'verification_needs_attention'then'Some identity signals require revalidation. Use the official links shown here with care.'when'emergency_recovery_active'then'A verified recovery notice is active. Use the replacement information shown here.'when'verification_restricted'then'Public verification is temporarily unavailable.'else'No current verified identity claim is available.'end,'lastUpdatedAt',updated,'verificationUrl','/verify/'||c.public_slug,'title',a.public_title,'publicSummary',a.public_summary,'embedEnabled',a.embed_enabled,'qrEnabled',a.qr_enabled,'showVerifiedTimestamps',a.show_verified_timestamps,'showRelationshipHistory',a.show_relationship_history),
 'accounts',case when state='verification_restricted'then'[]'::jsonb else(select coalesce(jsonb_agg(jsonb_strip_nulls(jsonb_build_object('provider',x.provider,'handle',x.display_handle,'displayName',x.display_name,'url',x.canonical_profile_url,'official',x.official,'primary',x.primary_for_provider,'verifiedAt',case when a.show_verified_timestamps then x.last_verified_at end))order by x.primary_for_provider desc,x.provider),'[]')from public.creator_identity_accounts x where x.identity_profile_id=p.id and x.verification_status='verified'and x.public_visible and x.official)end,
 'domains',case when state='verification_restricted'then'[]'::jsonb else(select coalesce(jsonb_agg(jsonb_strip_nulls(jsonb_build_object('hostname',d.hostname,'url',d.canonical_url,'official',d.official,'primary',d.primary_domain,'verifiedAt',case when a.show_verified_timestamps then d.last_verified_at end))order by d.primary_domain desc,d.hostname),'[]')from public.creator_identity_domains d where d.identity_profile_id=p.id and d.verification_status='verified'and d.public_visible and d.official)end,
 'relationships',case when not a.show_relationship_history or state='verification_restricted'then'[]'::jsonb else(select coalesce(jsonb_agg(jsonb_build_object('type',r.relationship_type,'verifiedAt',case when a.show_verified_timestamps then r.verified_at end)order by r.created_at desc),'[]')from public.creator_identity_relationships r where r.identity_profile_id=p.id and r.status='active'and r.relationship_type in('replacement_for','migrated_from','migrated_to','emergency_replacement_for'))end,
 'emergency',case when e.id is null then null else jsonb_build_object('active',true,'title',e.title,'message',e.message,'activatedAt',e.activated_at,'replacement',(select jsonb_build_object('provider',r.provider,'handle',r.display_handle,'url',r.canonical_profile_url,'verifiedAt',r.verified_at)from public.emergency_replacement_accounts r where r.emergency_id=e.id and r.verification_state='verified'and r.official order by r.verified_at desc limit 1))end,
 'continuity',(select coalesce(jsonb_agg(jsonb_build_object('type',z.event_type,'label',case z.event_type when'account_verified'then'Account identity verified'when'handle_changed'then'Account handle updated; identity unchanged'when'account_primary_changed'then'Primary account changed'when'domain_verified'then'Primary domain verified'when'emergency_replacement_linked'then'Official replacement account verified'else'Identity continuity updated'end,'at',z.created_at)order by z.created_at desc),'[]')from(select event_type,created_at from public.creator_identity_events where identity_profile_id=p.id and event_type in('account_verified','handle_changed','account_primary_changed','domain_verified','emergency_replacement_linked')order by id desc limit 20)z),
 'assertion',(select jsonb_build_object('url','/api/public/creators/'||c.public_slug||'/authenticity/assertion','expiresAt',s.expires_at,'keyId',s.key_id)from public.creator_authenticity_assertions s join public.authenticity_signing_keys k on k.key_id=s.key_id where s.authenticity_profile_id=a.id and s.revoked_at is null and s.superseded_at is null and s.expires_at>now()and k.revoked_at is null order by s.issued_at desc limit 1));end$$;
revoke all on function public.get_public_creator_authenticity(text)from public;grant execute on function public.get_public_creator_authenticity(text)to anon,authenticated,service_role;

create or replace function public.claim_authenticity_issuance(p_limit integer default 20,p_lease_owner uuid default gen_random_uuid())returns setof public.creator_authenticity_profiles language plpgsql security definer set search_path=''as $$begin if auth.role()<>'service_role'then raise exception'service role required'using errcode='42501';end if;return query with candidates as(select a.id from public.creator_authenticity_profiles a join public.creator_identity_profiles p on p.id=a.identity_profile_id left join lateral(select s.identity_revision,s.presentation_revision,s.expires_at,s.key_id from public.creator_authenticity_assertions s where s.authenticity_profile_id=a.id and s.revoked_at is null and s.superseded_at is null order by s.issued_at desc limit 1)s on true left join public.authenticity_signing_keys k on k.active and k.revoked_at is null where a.display_enabled and(a.issuance_lease_expires_at is null or a.issuance_lease_expires_at<now())and(s.identity_revision is distinct from p.identity_revision or s.presentation_revision is distinct from a.presentation_revision or s.expires_at<now()+interval'15 minutes'or s.key_id is distinct from k.key_id)order by a.updated_at for update of a skip locked limit greatest(1,least(p_limit,100)))update public.creator_authenticity_profiles a set issuance_lease_owner=p_lease_owner,issuance_lease_expires_at=now()+interval'3 minutes'from candidates c where a.id=c.id returning a.*;end$$;
revoke all on function public.claim_authenticity_issuance(integer,uuid)from public,anon,authenticated;grant execute on function public.claim_authenticity_issuance(integer,uuid)to service_role;

create or replace function public.store_authenticity_assertion(p_profile_id uuid,p_identity_revision bigint,p_presentation_revision bigint,p_trust_policy_version text,p_trust_state text,p_payload jsonb,p_payload_hash text,p_key_id text,p_signature text,p_issued_at timestamptz,p_expires_at timestamptz)returns uuid language plpgsql security definer set search_path=''as $$declare a public.creator_authenticity_profiles%rowtype;p public.creator_identity_profiles%rowtype;sid uuid;begin if auth.role()<>'service_role'then raise exception'service role required'using errcode='42501';end if;select*into a from public.creator_authenticity_profiles where id=p_profile_id for update;select*into p from public.creator_identity_profiles where id=a.identity_profile_id;if not found or p.identity_revision<>p_identity_revision or a.presentation_revision<>p_presentation_revision then raise exception'stale authenticity revision'using errcode='40001';end if;if not exists(select 1 from public.authenticity_signing_keys where key_id=p_key_id and revoked_at is null)then raise exception'active public key required'using errcode='23514';end if;update public.creator_authenticity_assertions set superseded_at=coalesce(superseded_at,now())where authenticity_profile_id=a.id and revoked_at is null and superseded_at is null;insert into public.creator_authenticity_assertions(creator_id,identity_profile_id,authenticity_profile_id,assertion_version,presentation_revision,identity_revision,trust_policy_version,trust_state,payload,payload_hash,key_id,signature,issued_at,expires_at)values(a.creator_id,a.identity_profile_id,a.id,'audienceown-authenticity-v1',p_presentation_revision,p_identity_revision,p_trust_policy_version,p_trust_state,p_payload,p_payload_hash,p_key_id,p_signature,p_issued_at,p_expires_at)returning id into sid;insert into public.creator_authenticity_events(creator_id,identity_profile_id,authenticity_profile_id,assertion_id,event_type,source,metadata)values(a.creator_id,a.identity_profile_id,a.id,sid,'assertion_issued','authenticity_worker',jsonb_build_object('keyId',p_key_id,'expiresAt',p_expires_at));update public.creator_authenticity_profiles set issuance_lease_owner=null,issuance_lease_expires_at=null where id=a.id;return sid;end$$;
revoke all on function public.store_authenticity_assertion(uuid,bigint,bigint,text,text,jsonb,text,text,text,timestamptz,timestamptz)from public,anon,authenticated;grant execute on function public.store_authenticity_assertion(uuid,bigint,bigint,text,text,jsonb,text,text,text,timestamptz,timestamptz)to service_role;

create or replace function public.record_authenticity_view(p_slug text,p_kind text)returns void language plpgsql security definer set search_path=''as $$declare a public.creator_authenticity_profiles%rowtype;begin if p_kind not in('page','card','badge','qr','api','verification_click','official_account_click','domain_click','emergency_replacement_click','assertion_request','assertion_verification_failure')then return;end if;select*into a from public.creator_authenticity_profiles where public_slug=p_slug and display_enabled;if not found then return;end if;insert into public.creator_authenticity_views(creator_id,authenticity_profile_id,day)values(a.creator_id,a.id,current_date)on conflict do nothing;execute format('update public.creator_authenticity_views set %I=%I+1 where authenticity_profile_id=$1 and day=current_date',case p_kind when'page'then'page_views'when'card'then'card_views'when'badge'then'badge_views'when'qr'then'qr_resolutions'when'api'then'api_requests'when'verification_click'then'verification_clicks'when'official_account_click'then'official_account_clicks'when'domain_click'then'domain_clicks'when'emergency_replacement_click'then'emergency_replacement_clicks'when'assertion_request'then'assertion_requests'else'assertion_verification_failures'end,case p_kind when'page'then'page_views'when'card'then'card_views'when'badge'then'badge_views'when'qr'then'qr_resolutions'when'api'then'api_requests'when'verification_click'then'verification_clicks'when'official_account_click'then'official_account_clicks'when'domain_click'then'domain_clicks'when'emergency_replacement_click'then'emergency_replacement_clicks'when'assertion_request'then'assertion_requests'else'assertion_verification_failures'end)using a.id;end$$;
revoke all on function public.record_authenticity_view(text,text)from public;grant execute on function public.record_authenticity_view(text,text)to anon,authenticated,service_role;

alter table public.creator_authenticity_profiles enable row level security;alter table public.creator_authenticity_profiles force row level security;
alter table public.authenticity_signing_keys enable row level security;alter table public.authenticity_signing_keys force row level security;
alter table public.creator_authenticity_assertions enable row level security;alter table public.creator_authenticity_assertions force row level security;
alter table public.creator_authenticity_events enable row level security;alter table public.creator_authenticity_events force row level security;
alter table public.creator_authenticity_views enable row level security;alter table public.creator_authenticity_views force row level security;
create policy"creator authenticity profile reads"on public.creator_authenticity_profiles for select to authenticated using(public.has_creator_permission(creator_id,'emergency_manage'));
create policy"creator authenticity assertion reads"on public.creator_authenticity_assertions for select to authenticated using(public.has_creator_permission(creator_id,'emergency_manage'));
create policy"creator authenticity event reads"on public.creator_authenticity_events for select to authenticated using(public.has_creator_permission(creator_id,'emergency_manage'));
create policy"creator authenticity analytics reads"on public.creator_authenticity_views for select to authenticated using(public.has_creator_permission(creator_id,'emergency_manage'));
revoke all on public.creator_authenticity_profiles,public.authenticity_signing_keys,public.creator_authenticity_assertions,public.creator_authenticity_events,public.creator_authenticity_views from public,anon,authenticated;
grant select on public.creator_authenticity_profiles,public.creator_authenticity_assertions,public.creator_authenticity_events,public.creator_authenticity_views to authenticated;
grant select,insert,update,delete on public.creator_authenticity_profiles,public.authenticity_signing_keys,public.creator_authenticity_assertions,public.creator_authenticity_events,public.creator_authenticity_views to service_role;
commit;
