begin;

create table public.creator_identity_profiles(
 id uuid primary key default gen_random_uuid(),creator_id uuid not null unique references public.creators(id) on delete cascade,
 public_display_name text not null check(char_length(btrim(public_display_name)) between 1 and 160),
 identity_status text not null default 'incomplete' check(identity_status in('incomplete','verified','needs_attention','restricted','archived')),
 primary_domain_id uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());

create table public.creator_identity_accounts(
 id uuid primary key default gen_random_uuid(),identity_profile_id uuid not null references public.creator_identity_profiles(id) on delete cascade,
 creator_id uuid not null references public.creators(id) on delete cascade,provider text not null check(char_length(btrim(provider)) between 1 and 40),
 stable_provider_account_id text not null check(char_length(btrim(stable_provider_account_id)) between 1 and 255),display_handle text,display_name text,
 canonical_profile_url text not null check(canonical_profile_url~'^https://'),account_kind text not null check(account_kind in('creator_account','organization_account','page','channel','artist','show','guild','board','domain_identity','replacement_account')),
 verification_status text not null default 'unverified' check(verification_status in('unverified','pending','verified','needs_attention','revoked','unavailable','archived')),
 verification_method text,verification_confidence text check(verification_confidence is null or verification_confidence in('low','medium','high')),
 source_connection_id uuid references public.connected_accounts(id) on delete set null,source_replacement_account_id uuid references public.emergency_replacement_accounts(id) on delete set null,
 official boolean not null default false,primary_for_provider boolean not null default false,public_visible boolean not null default true,
 first_verified_at timestamptz,last_verified_at timestamptz,last_revalidated_at timestamptz,revoked_at timestamptz,archived_at timestamptz,
 metadata jsonb not null default '{}',last_synced_at timestamptz,next_sync_at timestamptz,sync_status text not null default 'not_due' check(sync_status in('not_due','due','claimed','healthy','needs_attention','revoked','failed','archived')),
 last_sync_error text,lease_owner uuid,lease_expires_at timestamptz,sync_attempts integer not null default 0,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 unique(creator_id,provider,stable_provider_account_id),check(jsonb_typeof(metadata)='object'),
 check(not official or verification_status='verified'),check(not primary_for_provider or verification_status='verified'),
 check(verification_status<>'revoked' or(not official and not primary_for_provider and not public_visible)),
 check(verification_status<>'archived' or(not official and not primary_for_provider and not public_visible)));
create unique index identity_one_primary_provider_idx on public.creator_identity_accounts(creator_id,provider) where primary_for_provider;
create index identity_accounts_profile_idx on public.creator_identity_accounts(identity_profile_id,provider,updated_at desc);
create index identity_accounts_sync_idx on public.creator_identity_accounts(next_sync_at nulls first) where verification_status='verified' and sync_status<>'archived';

create table public.creator_identity_domains(
 id uuid primary key default gen_random_uuid(),identity_profile_id uuid not null references public.creator_identity_profiles(id) on delete cascade,
 creator_id uuid not null references public.creators(id) on delete cascade,hostname text not null,canonical_url text not null check(canonical_url~'^https://'),
 verification_status text not null default 'unverified' check(verification_status in('unverified','pending','verified','needs_attention','revoked','unavailable','archived')),
 verification_method text,verification_confidence text check(verification_confidence is null or verification_confidence in('low','medium','high')),
 first_verified_at timestamptz,last_verified_at timestamptz,last_checked_at timestamptz,revoked_at timestamptz,
 official boolean not null default false,primary_domain boolean not null default false,public_visible boolean not null default true,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(creator_id,hostname),
 check(hostname=lower(hostname) and hostname~'^(?=.{1,253}$)([a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$'),
 check(not official or verification_status='verified'),check(not primary_domain or verification_status='verified'),
 check(verification_status not in('revoked','archived') or(not official and not primary_domain and not public_visible)));
create unique index identity_one_primary_domain_idx on public.creator_identity_domains(creator_id) where primary_domain;
alter table public.creator_identity_profiles add constraint identity_primary_domain_fk foreign key(primary_domain_id) references public.creator_identity_domains(id) on delete set null;

create table public.creator_identity_relationships(
 id uuid primary key default gen_random_uuid(),creator_id uuid not null references public.creators(id) on delete cascade,
 identity_profile_id uuid not null references public.creator_identity_profiles(id) on delete cascade,
 source_account_id uuid references public.creator_identity_accounts(id) on delete restrict,target_account_id uuid references public.creator_identity_accounts(id) on delete restrict,
 source_domain_id uuid references public.creator_identity_domains(id) on delete restrict,target_domain_id uuid references public.creator_identity_domains(id) on delete restrict,
 relationship_type text not null check(relationship_type in('same_creator','replacement_for','migrated_from','migrated_to','managed_by','member_of','official_domain_of','verified_by_domain','verified_by_provider','emergency_replacement_for')),
 status text not null default 'active' check(status in('active','revoked','archived')),confidence text check(confidence is null or confidence in('low','medium','high')),
 evidence_source text,created_at timestamptz not null default now(),verified_at timestamptz,revoked_at timestamptz,
 check(num_nonnulls(source_account_id,source_domain_id)=1),check(num_nonnulls(target_account_id,target_domain_id)=1),
 check(source_account_id is distinct from target_account_id or source_account_id is null),check(source_domain_id is distinct from target_domain_id or source_domain_id is null));
create unique index identity_relationship_unique_idx on public.creator_identity_relationships(creator_id,relationship_type,coalesce(source_account_id,'00000000-0000-0000-0000-000000000000'),coalesce(target_account_id,'00000000-0000-0000-0000-000000000000'),coalesce(source_domain_id,'00000000-0000-0000-0000-000000000000'),coalesce(target_domain_id,'00000000-0000-0000-0000-000000000000')) where status='active';

create table public.creator_identity_events(
 id bigint generated always as identity primary key,creator_id uuid not null references public.creators(id) on delete restrict,
 identity_profile_id uuid not null references public.creator_identity_profiles(id) on delete restrict,account_id uuid references public.creator_identity_accounts(id) on delete set null,
 domain_id uuid references public.creator_identity_domains(id) on delete set null,relationship_id uuid references public.creator_identity_relationships(id) on delete set null,
 event_type text not null check(event_type in('identity_profile_created','account_added','account_verified','account_updated','handle_changed','canonical_url_changed','stable_identity_changed','account_revoked','account_archived','account_restored','account_marked_official','account_primary_changed','domain_added','domain_verified','domain_revoked','domain_primary_changed','relationship_created','relationship_revoked','emergency_replacement_linked','provider_sync_failed','provider_sync_recovered')),
 actor_user_id uuid references auth.users(id) on delete set null,source text not null check(char_length(source) between 1 and 60),metadata jsonb not null default '{}',created_at timestamptz not null default now(),check(jsonb_typeof(metadata)='object'));
create index identity_events_profile_idx on public.creator_identity_events(identity_profile_id,id desc);

create trigger identity_profiles_updated before update on public.creator_identity_profiles for each row execute function public.set_updated_at();
create trigger identity_accounts_updated before update on public.creator_identity_accounts for each row execute function public.set_updated_at();
create trigger identity_domains_updated before update on public.creator_identity_domains for each row execute function public.set_updated_at();
create trigger identity_events_immutable before update or delete on public.creator_identity_events for each row execute function public.prevent_emergency_history_mutation();

create or replace function public.validate_identity_relationship_scope() returns trigger language plpgsql set search_path='' as $$begin
 if not exists(select 1 from public.creator_identity_profiles p where p.id=new.identity_profile_id and p.creator_id=new.creator_id)then raise exception 'identity profile scope invalid' using errcode='23514';end if;
 if new.source_account_id is not null and not exists(select 1 from public.creator_identity_accounts a where a.id=new.source_account_id and a.creator_id=new.creator_id and a.identity_profile_id=new.identity_profile_id)then raise exception 'source account scope invalid' using errcode='23514';end if;
 if new.target_account_id is not null and not exists(select 1 from public.creator_identity_accounts a where a.id=new.target_account_id and a.creator_id=new.creator_id and a.identity_profile_id=new.identity_profile_id)then raise exception 'target account scope invalid' using errcode='23514';end if;
 if new.source_domain_id is not null and not exists(select 1 from public.creator_identity_domains d where d.id=new.source_domain_id and d.creator_id=new.creator_id and d.identity_profile_id=new.identity_profile_id)then raise exception 'source domain scope invalid' using errcode='23514';end if;
 if new.target_domain_id is not null and not exists(select 1 from public.creator_identity_domains d where d.id=new.target_domain_id and d.creator_id=new.creator_id and d.identity_profile_id=new.identity_profile_id)then raise exception 'target domain scope invalid' using errcode='23514';end if;return new;end$$;
create trigger identity_relationship_scope before insert or update on public.creator_identity_relationships for each row execute function public.validate_identity_relationship_scope();
revoke all on function public.validate_identity_relationship_scope()from public,anon,authenticated;

create or replace function public.append_identity_event(p_profile_id uuid,p_event_type text,p_source text,p_account_id uuid default null,p_domain_id uuid default null,p_relationship_id uuid default null,p_metadata jsonb default '{}') returns void
language plpgsql security definer set search_path='' as $$declare p public.creator_identity_profiles%rowtype;begin select * into p from public.creator_identity_profiles where id=p_profile_id;
 if not found then raise exception 'identity profile not found' using errcode='P0002';end if;
 insert into public.creator_identity_events(creator_id,identity_profile_id,account_id,domain_id,relationship_id,event_type,actor_user_id,source,metadata) values(p.creator_id,p.id,p_account_id,p_domain_id,p_relationship_id,p_event_type,auth.uid(),p_source,coalesce(p_metadata,'{}'));
end$$;revoke all on function public.append_identity_event(uuid,text,text,uuid,uuid,uuid,jsonb) from public,anon,authenticated;

create or replace function public.ensure_creator_identity_profile() returns uuid language plpgsql security definer set search_path='' as $$declare c public.creators%rowtype;p_id uuid;created boolean:=false;begin
 select * into c from public.creators where owner_user_id=auth.uid();if not found then raise exception 'creator required' using errcode='42501';end if;
 insert into public.creator_identity_profiles(creator_id,public_display_name) values(c.id,coalesce(nullif(btrim(c.display_name),''),c.public_slug,'Creator')) on conflict(creator_id) do update set public_display_name=excluded.public_display_name returning id,(xmax=0) into p_id,created;
 if created then perform public.append_identity_event(p_id,'identity_profile_created','creator_profile');end if;return p_id;end$$;
revoke all on function public.ensure_creator_identity_profile() from public,anon;grant execute on function public.ensure_creator_identity_profile() to authenticated;

create or replace function public.sync_identity_account_from_connection(p_connection_id uuid) returns uuid language plpgsql security definer set search_path='' as $$declare c public.connected_accounts%rowtype;p public.creator_identity_profiles%rowtype;a public.creator_identity_accounts%rowtype;old_handle text;existed boolean;begin
 if auth.role()<>'service_role' then raise exception 'service role required' using errcode='42501';end if;select * into c from public.connected_accounts where id=p_connection_id for update;
 if not found or c.external_account_id is null or c.connection_health not in('healthy','degraded') or c.provider_status<>'ready' then raise exception 'authoritative connection unavailable' using errcode='23514';end if;
 insert into public.creator_identity_profiles(creator_id,public_display_name) select x.id,coalesce(nullif(btrim(x.display_name),''),x.public_slug,'Creator') from public.creators x where x.id=c.creator_id on conflict(creator_id) do update set public_display_name=excluded.public_display_name returning * into p;
 select exists(select 1 from public.creator_identity_accounts where creator_id=c.creator_id and provider=c.platform and stable_provider_account_id=c.external_account_id)into existed;select display_handle into old_handle from public.creator_identity_accounts where creator_id=c.creator_id and provider=c.platform and stable_provider_account_id=c.external_account_id;
 insert into public.creator_identity_accounts(identity_profile_id,creator_id,provider,stable_provider_account_id,display_handle,display_name,canonical_profile_url,account_kind,verification_status,verification_method,verification_confidence,source_connection_id,first_verified_at,last_verified_at,last_revalidated_at,last_synced_at,next_sync_at,sync_status)
 values(p.id,c.creator_id,c.platform,c.external_account_id,c.label,c.external_account_name,coalesce(c.external_account_url,c.url),case c.platform when 'youtube' then 'channel' when 'facebook' then 'page' when 'spotify' then 'artist' when 'discord' then 'guild' when 'pinterest' then 'board' else 'creator_account' end,'verified','existing_connected_account','high',c.id,coalesce(c.token_refreshed_at,c.created_at),now(),now(),now(),now()+interval '24 hours','healthy')
 on conflict(creator_id,provider,stable_provider_account_id) do update set display_handle=excluded.display_handle,display_name=excluded.display_name,canonical_profile_url=excluded.canonical_profile_url,source_connection_id=excluded.source_connection_id,last_verified_at=now(),last_revalidated_at=now(),last_synced_at=now(),next_sync_at=now()+interval '24 hours',sync_status='healthy',last_sync_error=null,verification_status='verified',revoked_at=null,archived_at=null returning * into a;
 update public.creator_identity_profiles set identity_status='verified' where id=p.id and identity_status in('incomplete','needs_attention');perform public.append_identity_event(p.id,case when not existed then 'account_added' when old_handle is distinct from a.display_handle then 'handle_changed' else 'account_updated' end,'connected_account',a.id,null,null,jsonb_build_object('provider',a.provider));return a.id;end$$;
revoke all on function public.sync_identity_account_from_connection(uuid) from public,anon,authenticated;grant execute on function public.sync_identity_account_from_connection(uuid) to service_role;

create or replace function public.sync_identity_account_from_emergency_replacement(p_replacement_id uuid) returns uuid language plpgsql security definer set search_path='' as $$declare r public.emergency_replacement_accounts%rowtype;v public.emergency_account_verifications%rowtype;p public.creator_identity_profiles%rowtype;a public.creator_identity_accounts%rowtype;affected public.emergency_affected_accounts%rowtype;source_id uuid;rel_id uuid;existed boolean;begin
 if auth.role()<>'service_role' then raise exception 'service role required' using errcode='42501';end if;select * into r from public.emergency_replacement_accounts where id=p_replacement_id for update;select * into v from public.emergency_account_verifications where id=r.active_verification_id;
 if not found or r.verification_state<>'verified' or v.status<>'verified' or v.external_account_id is distinct from r.stable_provider_account_id then raise exception 'verified replacement required' using errcode='23514';end if;
 insert into public.creator_identity_profiles(creator_id,public_display_name) select c.id,coalesce(nullif(btrim(c.display_name),''),c.public_slug,'Creator') from public.creators c where c.id=r.creator_id on conflict(creator_id) do update set public_display_name=excluded.public_display_name returning * into p;
 select exists(select 1 from public.creator_identity_accounts where creator_id=r.creator_id and provider=r.provider and stable_provider_account_id=r.stable_provider_account_id)into existed;insert into public.creator_identity_accounts(identity_profile_id,creator_id,provider,stable_provider_account_id,display_handle,display_name,canonical_profile_url,account_kind,verification_status,verification_method,verification_confidence,source_replacement_account_id,official,first_verified_at,last_verified_at,last_revalidated_at,last_synced_at,next_sync_at,sync_status)
 values(p.id,r.creator_id,r.provider,r.stable_provider_account_id,r.display_handle,v.external_account_name,r.canonical_profile_url,'replacement_account','verified',v.method,v.confidence,r.id,r.official,v.verified_at,v.verified_at,v.last_revalidated_at,now(),coalesce(v.next_revalidation_at,now()+interval '24 hours'),'healthy')
 on conflict(creator_id,provider,stable_provider_account_id) do update set display_handle=excluded.display_handle,display_name=excluded.display_name,canonical_profile_url=excluded.canonical_profile_url,source_replacement_account_id=excluded.source_replacement_account_id,verification_status='verified',verification_method=excluded.verification_method,verification_confidence=excluded.verification_confidence,official=excluded.official,last_verified_at=excluded.last_verified_at,last_revalidated_at=excluded.last_revalidated_at,last_synced_at=now(),sync_status='healthy',revoked_at=null,archived_at=null returning * into a;
 select * into affected from public.emergency_affected_accounts where emergency_id=r.emergency_id order by created_at limit 1;select id into source_id from public.creator_identity_accounts where creator_id=r.creator_id and provider=affected.provider and stable_provider_account_id=affected.stable_provider_account_id;
 if source_id is not null and source_id<>a.id then insert into public.creator_identity_relationships(creator_id,identity_profile_id,source_account_id,target_account_id,relationship_type,status,confidence,evidence_source,verified_at) values(r.creator_id,p.id,a.id,source_id,'emergency_replacement_for','active',v.confidence,'emergency_verification',v.verified_at) on conflict do nothing returning id into rel_id;
  if rel_id is not null then perform public.append_identity_event(p.id,'emergency_replacement_linked','emergency_verification',a.id,null,rel_id,'{}');end if;end if;
 update public.creator_identity_profiles set identity_status='verified' where id=p.id and identity_status in('incomplete','needs_attention');perform public.append_identity_event(p.id,case when not existed then 'account_added' else 'account_updated' end,'emergency_verification',a.id);return a.id;end$$;
revoke all on function public.sync_identity_account_from_emergency_replacement(uuid) from public,anon,authenticated;grant execute on function public.sync_identity_account_from_emergency_replacement(uuid) to service_role;

create or replace function public.set_identity_account_presentation(p_account_id uuid,p_official boolean,p_primary boolean,p_public_visible boolean) returns jsonb language plpgsql security definer set search_path='' as $$declare a public.creator_identity_accounts%rowtype;begin select * into a from public.creator_identity_accounts where id=p_account_id for update;
 if not found or not public.has_creator_permission(a.creator_id,'emergency_manage') then raise exception 'access denied' using errcode='42501';end if;
 if(p_official or p_primary)and a.verification_status<>'verified' then raise exception 'verified account required' using errcode='23514';end if;if a.verification_status in('revoked','archived')and(p_official or p_primary or p_public_visible)then raise exception 'inactive account cannot be presented' using errcode='23514';end if;
 if p_primary then update public.creator_identity_accounts set primary_for_provider=false where creator_id=a.creator_id and provider=a.provider and id<>a.id;end if;
 update public.creator_identity_accounts set official=p_official,primary_for_provider=p_primary,public_visible=p_public_visible where id=a.id;
 perform public.append_identity_event(a.identity_profile_id,case when p_primary then 'account_primary_changed' when p_official then 'account_marked_official' else 'account_updated' end,'creator_action',a.id);return jsonb_build_object('status','updated');end$$;
revoke all on function public.set_identity_account_presentation(uuid,boolean,boolean,boolean) from public,anon;grant execute on function public.set_identity_account_presentation(uuid,boolean,boolean,boolean) to authenticated;

create or replace function public.archive_identity_account(p_account_id uuid) returns void language plpgsql security definer set search_path='' as $$declare a public.creator_identity_accounts%rowtype;begin select * into a from public.creator_identity_accounts where id=p_account_id for update;if not found or not public.has_creator_permission(a.creator_id,'emergency_manage') then raise exception 'access denied' using errcode='42501';end if;
 update public.creator_identity_accounts set verification_status='archived',official=false,primary_for_provider=false,public_visible=false,archived_at=now(),sync_status='archived' where id=a.id;perform public.append_identity_event(a.identity_profile_id,'account_archived','creator_action',a.id);end$$;
revoke all on function public.archive_identity_account(uuid) from public,anon;grant execute on function public.archive_identity_account(uuid) to authenticated;

create or replace function public.queue_identity_account_sync(p_account_id uuid)returns void language plpgsql security definer set search_path='' as $$declare a public.creator_identity_accounts%rowtype;begin select*into a from public.creator_identity_accounts where id=p_account_id for update;if not found or not public.has_creator_permission(a.creator_id,'emergency_manage')then raise exception 'access denied' using errcode='42501';end if;if a.source_connection_id is null or a.verification_status not in('verified','needs_attention')then raise exception 'account cannot be synchronized' using errcode='23514';end if;update public.creator_identity_accounts set next_sync_at=now(),sync_status='due'where id=a.id;end$$;
revoke all on function public.queue_identity_account_sync(uuid)from public,anon;grant execute on function public.queue_identity_account_sync(uuid)to authenticated;

create or replace function public.sync_identity_domain(p_verification_id uuid) returns uuid language plpgsql security definer set search_path='' as $$declare v public.emergency_account_verifications%rowtype;p public.creator_identity_profiles%rowtype;d public.creator_identity_domains%rowtype;host text;existed boolean;begin
 if auth.role()<>'service_role' then raise exception 'service role required' using errcode='42501';end if;select * into v from public.emergency_account_verifications where id=p_verification_id and method='domain_challenge' and status='verified';if not found then raise exception 'verified domain required' using errcode='23514';end if;
 host:=lower(btrim(v.evidence_metadata->>'domain'));if host is null or host!~'^(?=.{1,253}$)([a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$' then raise exception 'domain invalid' using errcode='23514';end if;
 select * into p from public.creator_identity_profiles where creator_id=v.creator_id for update;
 select exists(select 1 from public.creator_identity_domains where creator_id=v.creator_id and hostname=host)into existed;insert into public.creator_identity_domains(identity_profile_id,creator_id,hostname,canonical_url,verification_status,verification_method,verification_confidence,first_verified_at,last_verified_at,last_checked_at,official)
 values(p.id,v.creator_id,host,'https://'||host,'verified','domain_challenge',v.confidence,v.verified_at,v.verified_at,coalesce(v.last_revalidated_at,v.verified_at),true)
 on conflict(creator_id,hostname)do update set verification_status='verified',verification_method='domain_challenge',verification_confidence=excluded.verification_confidence,last_verified_at=excluded.last_verified_at,last_checked_at=excluded.last_checked_at,revoked_at=null returning * into d;
 perform public.append_identity_event(p.id,case when not existed then'domain_added'else'domain_verified'end,'domain_verification',null,d.id);return d.id;end$$;
revoke all on function public.sync_identity_domain(uuid) from public,anon,authenticated;grant execute on function public.sync_identity_domain(uuid) to service_role;

create or replace function public.set_primary_identity_domain(p_domain_id uuid,p_public_visible boolean default true) returns void language plpgsql security definer set search_path='' as $$declare d public.creator_identity_domains%rowtype;begin select * into d from public.creator_identity_domains where id=p_domain_id for update;if not found or not public.has_creator_permission(d.creator_id,'emergency_manage')then raise exception 'access denied' using errcode='42501';end if;if d.verification_status<>'verified'then raise exception 'verified domain required' using errcode='23514';end if;
 update public.creator_identity_domains set primary_domain=false where creator_id=d.creator_id and id<>d.id;update public.creator_identity_domains set primary_domain=true,official=true,public_visible=p_public_visible where id=d.id;update public.creator_identity_profiles set primary_domain_id=d.id where id=d.identity_profile_id;perform public.append_identity_event(d.identity_profile_id,'domain_primary_changed','creator_action',null,d.id);end$$;
revoke all on function public.set_primary_identity_domain(uuid,boolean)from public,anon;grant execute on function public.set_primary_identity_domain(uuid,boolean)to authenticated;

create or replace function public.get_creator_identity_graph() returns jsonb language plpgsql stable security definer set search_path='' as $$declare p public.creator_identity_profiles%rowtype;begin select * into p from public.creator_identity_profiles where public.has_creator_permission(creator_id,'emergency_manage') limit 1;if not found then raise exception 'identity access denied' using errcode='42501';end if;
 return jsonb_build_object('profile',to_jsonb(p),'accounts',(select coalesce(jsonb_agg(to_jsonb(a) order by a.provider,a.created_at),'[]') from public.creator_identity_accounts a where a.identity_profile_id=p.id),'domains',(select coalesce(jsonb_agg(to_jsonb(d) order by d.primary_domain desc,d.hostname),'[]') from public.creator_identity_domains d where d.identity_profile_id=p.id),'relationships',(select coalesce(jsonb_agg(to_jsonb(r) order by r.created_at),'[]') from public.creator_identity_relationships r where r.identity_profile_id=p.id),'events',(select coalesce(jsonb_agg(to_jsonb(e) order by e.id desc),'[]') from(select * from public.creator_identity_events x where x.identity_profile_id=p.id order by x.id desc limit 50)e));end$$;
revoke all on function public.get_creator_identity_graph() from public,anon;grant execute on function public.get_creator_identity_graph() to authenticated;

create or replace function public.get_public_creator_identity_graph(p_slug text) returns jsonb language plpgsql stable security definer set search_path='' as $$declare p public.creator_identity_profiles%rowtype;c public.creators%rowtype;begin select * into c from public.creators where public_slug=p_slug and public_profile_enabled;if not found then return null;end if;select * into p from public.creator_identity_profiles where creator_id=c.id;if not found then return jsonb_build_object('creator',jsonb_build_object('slug',c.public_slug,'displayName',c.display_name),'identityStatus','incomplete','accounts','[]'::jsonb,'domains','[]'::jsonb,'relationships','[]'::jsonb,'lastUpdatedAt',c.updated_at);end if;
 return jsonb_build_object('creator',jsonb_build_object('slug',c.public_slug,'displayName',p.public_display_name),'identityStatus',p.identity_status,
 'accounts',(select coalesce(jsonb_agg(jsonb_build_object('provider',a.provider,'displayHandle',a.display_handle,'displayName',a.display_name,'canonicalProfileUrl',a.canonical_profile_url,'accountKind',a.account_kind,'verificationStatus',a.verification_status,'official',a.official,'primary',a.primary_for_provider,'verifiedAt',a.last_verified_at)order by a.provider,a.primary_for_provider desc),'[]') from public.creator_identity_accounts a where a.identity_profile_id=p.id and a.public_visible and a.verification_status='verified' and a.revoked_at is null and a.archived_at is null),
 'domains',(select coalesce(jsonb_agg(jsonb_build_object('hostname',d.hostname,'canonicalUrl',d.canonical_url,'official',d.official,'primary',d.primary_domain,'verifiedAt',d.last_verified_at)order by d.primary_domain desc,d.hostname),'[]') from public.creator_identity_domains d where d.identity_profile_id=p.id and d.public_visible and d.verification_status='verified' and d.revoked_at is null),
 'relationships',(select coalesce(jsonb_agg(jsonb_build_object('relationshipType',r.relationship_type,'sourceProvider',sa.provider,'sourceUrl',sa.canonical_profile_url,'targetProvider',ta.provider,'targetUrl',ta.canonical_profile_url,'verifiedAt',r.verified_at)order by r.created_at),'[]') from public.creator_identity_relationships r left join public.creator_identity_accounts sa on sa.id=r.source_account_id left join public.creator_identity_accounts ta on ta.id=r.target_account_id where r.identity_profile_id=p.id and r.status='active' and r.relationship_type in('replacement_for','migrated_from','migrated_to','emergency_replacement_for') and coalesce(sa.public_visible,true) and coalesce(ta.public_visible,true)),
 'lastUpdatedAt',p.updated_at);end$$;
revoke all on function public.get_public_creator_identity_graph(text) from public;grant execute on function public.get_public_creator_identity_graph(text) to anon,authenticated,service_role;

create or replace function public.claim_identity_accounts(p_limit integer default 20,p_lease_owner uuid default gen_random_uuid()) returns setof public.creator_identity_accounts language plpgsql security definer set search_path='' as $$begin if auth.role()<>'service_role' then raise exception 'service role required' using errcode='42501';end if;
 return query with c as(select a.id from public.creator_identity_accounts a where a.verification_status='verified' and a.source_connection_id is not null and(a.next_sync_at is null or a.next_sync_at<=now())and(a.lease_expires_at is null or a.lease_expires_at<now()) order by a.next_sync_at nulls first for update skip locked limit greatest(1,least(p_limit,100)))update public.creator_identity_accounts a set lease_owner=p_lease_owner,lease_expires_at=now()+interval '3 minutes',sync_status='claimed' from c where a.id=c.id returning a.*;end$$;
revoke all on function public.claim_identity_accounts(integer,uuid) from public,anon,authenticated;grant execute on function public.claim_identity_accounts(integer,uuid) to service_role;

create or replace function public.apply_identity_provider_sync(p_account_id uuid,p_stable_id text,p_handle text,p_name text,p_url text,p_status text,p_error text default null) returns jsonb language plpgsql security definer set search_path='' as $$declare a public.creator_identity_accounts%rowtype;event text;begin if auth.role()<>'service_role' then raise exception 'service role required' using errcode='42501';end if;select * into a from public.creator_identity_accounts where id=p_account_id for update;if not found then raise exception 'identity account not found' using errcode='P0002';end if;
 if p_status='healthy' and p_stable_id=a.stable_provider_account_id then event:=case when a.display_handle is distinct from p_handle then 'handle_changed' when a.canonical_profile_url is distinct from p_url then 'canonical_url_changed' else 'provider_sync_recovered' end;update public.creator_identity_accounts set display_handle=p_handle,display_name=p_name,canonical_profile_url=p_url,last_synced_at=now(),next_sync_at=now()+interval '24 hours',sync_status='healthy',last_sync_error=null,lease_owner=null,lease_expires_at=null,sync_attempts=0 where id=a.id;
 elsif p_status='revoked' then event:='account_revoked';update public.creator_identity_accounts set verification_status='revoked',official=false,primary_for_provider=false,public_visible=false,revoked_at=now(),sync_status='revoked',last_sync_error=left(p_error,120),lease_owner=null,lease_expires_at=null where id=a.id;
 elsif p_stable_id is distinct from a.stable_provider_account_id then event:='stable_identity_changed';update public.creator_identity_accounts set verification_status='needs_attention',official=false,primary_for_provider=false,public_visible=false,sync_status='needs_attention',last_sync_error='stable_identity_changed',lease_owner=null,lease_expires_at=null where id=a.id;
 else event:='provider_sync_failed';update public.creator_identity_accounts set verification_status='needs_attention',official=false,primary_for_provider=false,sync_status='failed',last_sync_error=left(p_error,120),sync_attempts=sync_attempts+1,next_sync_at=now()+interval '1 hour',lease_owner=null,lease_expires_at=null where id=a.id;end if;
 perform public.append_identity_event(a.identity_profile_id,event,'provider_sync',a.id,null,null,jsonb_build_object('provider',a.provider));return jsonb_build_object('status',event);end$$;
revoke all on function public.apply_identity_provider_sync(uuid,text,text,text,text,text,text) from public,anon,authenticated;grant execute on function public.apply_identity_provider_sync(uuid,text,text,text,text,text,text) to service_role;

alter table public.creator_identity_profiles enable row level security;alter table public.creator_identity_profiles force row level security;
alter table public.creator_identity_accounts enable row level security;alter table public.creator_identity_accounts force row level security;
alter table public.creator_identity_domains enable row level security;alter table public.creator_identity_domains force row level security;
alter table public.creator_identity_relationships enable row level security;alter table public.creator_identity_relationships force row level security;
alter table public.creator_identity_events enable row level security;alter table public.creator_identity_events force row level security;
create policy "authorized identity profile reads" on public.creator_identity_profiles for select to authenticated using(public.has_creator_permission(creator_id,'emergency_manage'));
create policy "authorized identity account reads" on public.creator_identity_accounts for select to authenticated using(public.has_creator_permission(creator_id,'emergency_manage'));
create policy "authorized identity domain reads" on public.creator_identity_domains for select to authenticated using(public.has_creator_permission(creator_id,'emergency_manage'));
create policy "authorized identity relationship reads" on public.creator_identity_relationships for select to authenticated using(public.has_creator_permission(creator_id,'emergency_manage'));
create policy "authorized identity event reads" on public.creator_identity_events for select to authenticated using(public.has_creator_permission(creator_id,'emergency_manage'));
revoke all on public.creator_identity_profiles,public.creator_identity_accounts,public.creator_identity_domains,public.creator_identity_relationships,public.creator_identity_events from public,anon,authenticated;
grant select on public.creator_identity_profiles,public.creator_identity_accounts,public.creator_identity_domains,public.creator_identity_relationships,public.creator_identity_events to authenticated;
grant select,insert,update,delete on public.creator_identity_profiles,public.creator_identity_accounts,public.creator_identity_domains,public.creator_identity_relationships,public.creator_identity_events to service_role;

-- Backfill only identities with an authoritative stable provider ID.
insert into public.creator_identity_profiles(creator_id,public_display_name)select id,coalesce(nullif(btrim(display_name),''),public_slug,'Creator')from public.creators on conflict(creator_id)do nothing;
insert into public.creator_identity_accounts(identity_profile_id,creator_id,provider,stable_provider_account_id,display_handle,display_name,canonical_profile_url,account_kind,verification_status,verification_method,verification_confidence,source_connection_id,first_verified_at,last_verified_at,last_revalidated_at,last_synced_at,next_sync_at,sync_status)
select p.id,c.creator_id,c.platform,c.external_account_id,c.label,c.external_account_name,coalesce(c.external_account_url,c.url),case c.platform when'youtube'then'channel'when'facebook'then'page'when'spotify'then'artist'when'discord'then'guild'when'pinterest'then'board'else'creator_account'end,'verified','existing_connected_account','high',c.id,coalesce(c.token_refreshed_at,c.created_at),coalesce(c.token_refreshed_at,c.updated_at),c.last_sync_at,now(),coalesce(c.next_sync_at,now()+interval'24 hours'),'healthy' from public.connected_accounts c join public.creator_identity_profiles p on p.creator_id=c.creator_id where c.external_account_id is not null and c.connection_health in('healthy','degraded')and c.provider_status='ready' and coalesce(c.external_account_url,c.url)~'^https://' on conflict(creator_id,provider,stable_provider_account_id)do nothing;
insert into public.creator_identity_accounts(identity_profile_id,creator_id,provider,stable_provider_account_id,display_handle,display_name,canonical_profile_url,account_kind,verification_status,verification_method,verification_confidence,source_replacement_account_id,official,first_verified_at,last_verified_at,last_revalidated_at,last_synced_at,next_sync_at,sync_status)
select p.id,r.creator_id,r.provider,r.stable_provider_account_id,r.display_handle,v.external_account_name,r.canonical_profile_url,'replacement_account','verified',v.method,v.confidence,r.id,r.official,v.verified_at,v.verified_at,v.last_revalidated_at,now(),v.next_revalidation_at,'healthy' from public.emergency_replacement_accounts r join public.emergency_account_verifications v on v.id=r.active_verification_id and v.status='verified' join public.creator_identity_profiles p on p.creator_id=r.creator_id where r.verification_state='verified' on conflict(creator_id,provider,stable_provider_account_id)do update set source_replacement_account_id=excluded.source_replacement_account_id,verification_status='verified',verification_method=excluded.verification_method,verification_confidence=excluded.verification_confidence;
insert into public.creator_identity_relationships(creator_id,identity_profile_id,source_account_id,target_account_id,relationship_type,status,confidence,evidence_source,verified_at)
select r.creator_id,p.id,replacement.id,affected_identity.id,'emergency_replacement_for','active',v.confidence,'emergency_verification',v.verified_at from public.emergency_replacement_accounts r join public.emergency_account_verifications v on v.id=r.active_verification_id and v.status='verified' join public.creator_identity_profiles p on p.creator_id=r.creator_id join public.creator_identity_accounts replacement on replacement.source_replacement_account_id=r.id join public.emergency_affected_accounts affected on affected.emergency_id=r.emergency_id join public.creator_identity_accounts affected_identity on affected_identity.creator_id=r.creator_id and affected_identity.provider=affected.provider and affected_identity.stable_provider_account_id=affected.stable_provider_account_id where replacement.id<>affected_identity.id on conflict do nothing;
update public.creator_identity_profiles p set identity_status=case when exists(select 1 from public.creator_identity_accounts a where a.identity_profile_id=p.id and a.verification_status='verified')then'verified'else'incomplete'end;

commit;
