begin;

alter table public.creator_identity_profiles add column identity_revision bigint not null default 1 check(identity_revision>0),add column trust_lease_owner uuid,add column trust_lease_expires_at timestamptz;

create table public.creator_trust_evaluations(
 id uuid primary key default gen_random_uuid(),creator_id uuid not null references public.creators(id) on delete cascade,identity_profile_id uuid not null references public.creator_identity_profiles(id) on delete cascade,
 trust_state text not null check(trust_state in('unverified','partially_verified','verified','strongly_verified','needs_attention','restricted')),policy_version text not null,internal_score integer not null check(internal_score between 0 and 100),
 strong_signal_count integer not null,valid_signal_count integer not null,stale_signal_count integer not null,warning_count integer not null,blocker_count integer not null,evaluated_at timestamptz not null,expires_at timestamptz,source_revision bigint not null,created_at timestamptz not null default now(),unique(identity_profile_id,source_revision,policy_version));
create index trust_evaluations_current_idx on public.creator_trust_evaluations(identity_profile_id,evaluated_at desc);
create table public.creator_trust_signals(
 id uuid primary key default gen_random_uuid(),evaluation_id uuid not null references public.creator_trust_evaluations(id) on delete cascade,creator_id uuid not null references public.creators(id) on delete cascade,identity_account_id uuid references public.creator_identity_accounts(id) on delete cascade,identity_domain_id uuid references public.creator_identity_domains(id) on delete cascade,
 signal_type text not null,signal_state text not null check(signal_state in('strong','valid','stale','weak','pending','revoked','conflicting','unavailable')),provider_family text not null,weight integer not null,reason_code text not null,first_observed_at timestamptz,last_observed_at timestamptz,expires_at timestamptz,metadata jsonb not null default '{}',created_at timestamptz not null default now(),check(num_nonnulls(identity_account_id,identity_domain_id)<=1),check(jsonb_typeof(metadata)='object'));
create unique index trust_signal_dedupe_idx on public.creator_trust_signals(evaluation_id,signal_type,coalesce(identity_account_id,'00000000-0000-0000-0000-000000000000'),coalesce(identity_domain_id,'00000000-0000-0000-0000-000000000000'));
create table public.creator_trust_recommendations(
 id uuid primary key default gen_random_uuid(),evaluation_id uuid not null references public.creator_trust_evaluations(id) on delete cascade,creator_id uuid not null references public.creators(id) on delete cascade,recommendation_code text not null,priority text not null check(priority in('low','medium','high','critical')),title text not null,description text not null,action_url text,resolved_at timestamptz,created_at timestamptz not null default now(),unique(evaluation_id,recommendation_code));
create table public.creator_trust_events(
 id bigint generated always as identity primary key,creator_id uuid not null references public.creators(id) on delete restrict,identity_profile_id uuid not null references public.creator_identity_profiles(id) on delete restrict,evaluation_id uuid references public.creator_trust_evaluations(id) on delete set null,event_type text not null,previous_state text,new_state text,policy_version text not null,metadata jsonb not null default '{}',created_at timestamptz not null default now(),check(jsonb_typeof(metadata)='object'));
create trigger trust_events_immutable before update or delete on public.creator_trust_events for each row execute function public.prevent_emergency_history_mutation();

create or replace function public.bump_identity_revision() returns trigger language plpgsql set search_path='' as $$declare pid uuid;begin pid:=coalesce(new.identity_profile_id,old.identity_profile_id);update public.creator_identity_profiles set identity_revision=identity_revision+1 where id=pid;return coalesce(new,old);end$$;
create trigger identity_accounts_revision after insert or update or delete on public.creator_identity_accounts for each row execute function public.bump_identity_revision();
create trigger identity_domains_revision after insert or update or delete on public.creator_identity_domains for each row execute function public.bump_identity_revision();
create trigger identity_relationships_revision after insert or update or delete on public.creator_identity_relationships for each row execute function public.bump_identity_revision();
revoke all on function public.bump_identity_revision() from public,anon,authenticated;

create or replace function public.bump_identity_revision_from_replacement()returns trigger language plpgsql set search_path=''as $$declare cid uuid;begin cid:=coalesce(new.creator_id,old.creator_id);update public.creator_identity_profiles set identity_revision=identity_revision+1 where creator_id=cid;return coalesce(new,old);end$$;
create trigger emergency_replacement_identity_revision after insert or update or delete on public.emergency_replacement_accounts for each row execute function public.bump_identity_revision_from_replacement();
revoke all on function public.bump_identity_revision_from_replacement()from public,anon,authenticated;

create or replace function public.trust_provider_family(p_provider text) returns text language sql immutable set search_path='' as $$select case lower(coalesce(p_provider,'')) when'youtube'then'google'when'google'then'google'when'instagram'then'meta'when'facebook'then'meta'when'threads'then'meta'when'tiktok'then'bytedance'when'x'then'x'when'twitter'then'x'when'spotify'then'spotify'when'twitch'then'twitch'when'linkedin'then'linkedin'when'pinterest'then'pinterest'when'discord'then'discord'when'snapchat'then'snapchat'else'other'end$$;
revoke all on function public.trust_provider_family(text) from public,anon,authenticated;

create or replace function public.evaluate_creator_trust(p_profile_id uuid,p_policy_version text default 'identity-trust-v1',p_provider_freshness_hours integer default 168,p_domain_freshness_hours integer default 720,p_emergency_freshness_hours integer default 24,p_ttl_minutes integer default 60) returns uuid language plpgsql security definer set search_path='' as $$
declare p public.creator_identity_profiles%rowtype;eid uuid;previous_state text;v_score integer:=0;v_strong_count integer:=0;v_valid_count integer:=0;v_stale_count integer:=0;v_warning_count integer:=0;v_blocker_count integer:=0;v_family_count integer:=0;new_state text;now_at timestamptz:=clock_timestamp();
begin
 if auth.role()<>'service_role' then raise exception 'service role required' using errcode='42501';end if;
 if p_policy_version<>'identity-trust-v1' then raise exception 'unsupported trust policy' using errcode='22023';end if;
 select * into p from public.creator_identity_profiles where id=p_profile_id for update;if not found then raise exception 'identity profile not found' using errcode='P0002';end if;
 select id into eid from public.creator_trust_evaluations where identity_profile_id=p.id and source_revision=p.identity_revision and policy_version=p_policy_version;if eid is not null then update public.creator_identity_profiles set trust_lease_owner=null,trust_lease_expires_at=null where id=p.id;return eid;end if;
 select trust_state into previous_state from public.creator_trust_evaluations where identity_profile_id=p.id order by source_revision desc,evaluated_at desc limit 1;
 insert into public.creator_trust_evaluations(creator_id,identity_profile_id,trust_state,policy_version,internal_score,strong_signal_count,valid_signal_count,stale_signal_count,warning_count,blocker_count,evaluated_at,expires_at,source_revision)values(p.creator_id,p.id,'unverified',p_policy_version,0,0,0,0,0,0,now_at,now_at+make_interval(mins=>greatest(5,p_ttl_minutes)),p.identity_revision)returning id into eid;
 insert into public.creator_trust_signals(evaluation_id,creator_id,identity_account_id,signal_type,signal_state,provider_family,weight,reason_code,first_observed_at,last_observed_at,expires_at)
 select eid,p.creator_id,a.id,
 case when a.verification_status='revoked'then'provider_identity_revoked' when a.verification_status='verified'and a.stable_provider_account_id is null then'stable_provider_id_missing' when a.verification_status='verified'and coalesce(a.last_revalidated_at,a.last_verified_at) < now_at-make_interval(hours=>p_provider_freshness_hours)then'provider_identity_stale' when a.verification_status='verified'and a.account_kind='replacement_account'then'verified_emergency_replacement' when a.verification_status='verified'and a.official then'official_account_verified' when a.verification_status='verified'and a.primary_for_provider then'primary_account_verified' when a.verification_status='verified'then'provider_oauth_verified' when a.sync_status='failed'then'sync_failure' when a.public_visible then'public_account_without_verification'else'provider_review_required'end,
 case when a.verification_status='revoked'then'revoked' when a.verification_status='verified'and a.stable_provider_account_id is null then'conflicting' when a.verification_status='verified'and coalesce(a.last_revalidated_at,a.last_verified_at) < now_at-make_interval(hours=>p_provider_freshness_hours)then'stale' when a.verification_status='verified'and(a.official or a.primary_for_provider or a.account_kind='replacement_account')then'strong' when a.verification_status='verified'then'valid' when a.sync_status='failed'then'unavailable' when a.verification_status='pending'then'pending'else'weak'end,
 public.trust_provider_family(a.provider),case when a.verification_status='revoked'or(a.verification_status='verified'and a.stable_provider_account_id is null)then -100 when a.verification_status='verified'and coalesce(a.last_revalidated_at,a.last_verified_at)<now_at-make_interval(hours=>p_provider_freshness_hours)then -10 when a.verification_status='verified'and(a.official or a.primary_for_provider or a.account_kind='replacement_account')then 35 when a.verification_status='verified'then 25 when a.sync_status='failed'then -10 when a.public_visible then -5 else 0 end,
 case when a.verification_status='revoked'then'verification_revoked'when a.verification_status='verified'and a.stable_provider_account_id is null then'stable_id_missing'when a.verification_status='verified'and coalesce(a.last_revalidated_at,a.last_verified_at)<now_at-make_interval(hours=>p_provider_freshness_hours)then'verification_stale'when a.sync_status='failed'then'provider_sync_failed'when a.verification_status='verified'then'authoritative_verification'else'public_identity_unverified'end,a.first_verified_at,coalesce(a.last_revalidated_at,a.last_verified_at),coalesce(a.last_revalidated_at,a.last_verified_at)+make_interval(hours=>p_provider_freshness_hours)
 from public.creator_identity_accounts a where a.identity_profile_id=p.id and a.verification_status<>'archived'
 on conflict do nothing;
 insert into public.creator_trust_signals(evaluation_id,creator_id,identity_domain_id,signal_type,signal_state,provider_family,weight,reason_code,first_observed_at,last_observed_at,expires_at)
 select eid,p.creator_id,d.id,case when d.verification_status='revoked'then'revoked_domain'when d.verification_status='verified'and coalesce(d.last_checked_at,d.last_verified_at)<now_at-make_interval(hours=>p_domain_freshness_hours)then'stale_domain_verification'when d.verification_status='verified'then'verified_domain'else'provider_review_required'end,case when d.verification_status='revoked'then'revoked'when d.verification_status='verified'and coalesce(d.last_checked_at,d.last_verified_at)<now_at-make_interval(hours=>p_domain_freshness_hours)then'stale'when d.verification_status='verified'then'strong'when d.verification_status='pending'then'pending'else'weak'end,'domain',case when d.verification_status='revoked'then -100 when d.verification_status='verified'and coalesce(d.last_checked_at,d.last_verified_at)<now_at-make_interval(hours=>p_domain_freshness_hours)then -10 when d.verification_status='verified'then 35 else 0 end,case when d.verification_status='revoked'then'verification_revoked'when d.verification_status='verified'and coalesce(d.last_checked_at,d.last_verified_at)<now_at-make_interval(hours=>p_domain_freshness_hours)then'verification_stale'when d.verification_status='verified'then'authoritative_verification'else'verification_pending'end,d.first_verified_at,coalesce(d.last_checked_at,d.last_verified_at),coalesce(d.last_checked_at,d.last_verified_at)+make_interval(hours=>p_domain_freshness_hours) from public.creator_identity_domains d where d.identity_profile_id=p.id and d.verification_status<>'archived' on conflict do nothing;
 insert into public.creator_trust_signals(evaluation_id,creator_id,signal_type,signal_state,provider_family,weight,reason_code,last_observed_at,expires_at)
 select eid,p.creator_id,'active_emergency_unverified_replacement','conflicting','other',-100,'active_emergency_replacement_unverified',e.activated_at,e.activated_at+make_interval(hours=>p_emergency_freshness_hours)from public.creator_emergencies e where e.creator_id=p.creator_id and e.lifecycle_status='active'and not exists(select 1 from public.emergency_replacement_accounts r join public.emergency_account_verifications v on v.id=r.active_verification_id where r.emergency_id=e.id and r.official and r.verification_state='verified'and v.status='verified'and coalesce(v.last_revalidated_at,v.verified_at)>=now_at-make_interval(hours=>p_emergency_freshness_hours))limit 1;
 select coalesce(sum(weight),0),count(*)filter(where signal_state='strong'),count(*)filter(where signal_state='valid'),count(*)filter(where signal_state in('stale','unavailable')),count(*)filter(where signal_state in('stale','unavailable')),count(*)filter(where signal_state in('revoked','conflicting')),count(distinct provider_family)filter(where signal_state in('strong','valid')) into v_score,v_strong_count,v_valid_count,v_stale_count,v_warning_count,v_blocker_count,v_family_count from public.creator_trust_signals where evaluation_id=eid;
 v_score:=greatest(0,least(100,v_score));new_state:=case when v_blocker_count>0 then'restricted'when v_warning_count>0 and v_strong_count+v_valid_count>0 then'needs_attention'when v_strong_count>=2 and v_family_count>=2 then'strongly_verified'when v_strong_count+v_valid_count>0 then'verified'when exists(select 1 from public.creator_trust_signals where evaluation_id=eid and signal_state in('weak','pending'))then'partially_verified'else'unverified'end;
 update public.creator_trust_evaluations set trust_state=new_state,internal_score=v_score,strong_signal_count=v_strong_count,valid_signal_count=v_valid_count,stale_signal_count=v_stale_count,warning_count=v_warning_count,blocker_count=v_blocker_count where id=eid;
 if v_strong_count+v_valid_count=0 then insert into public.creator_trust_recommendations(evaluation_id,creator_id,recommendation_code,priority,title,description,action_url)values(eid,p.creator_id,'verify_primary_account','high','Verify a primary account','Connect and verify the account followers should treat as authoritative.','/dashboard/identity');end if;
 if not exists(select 1 from public.creator_trust_signals where evaluation_id=eid and provider_family='domain'and signal_state in('strong','valid'))then insert into public.creator_trust_recommendations(evaluation_id,creator_id,recommendation_code,priority,title,description,action_url)values(eid,p.creator_id,'verify_domain','medium','Verify your creator domain','Add an independent creator-owned domain verification.','/dashboard/identity');end if;
 if v_stale_count>0 then insert into public.creator_trust_recommendations(evaluation_id,creator_id,recommendation_code,priority,title,description,action_url)values(eid,p.creator_id,'refresh_stale_identity','high','Refresh stale verification','Revalidate identity evidence whose freshness window expired.','/dashboard/identity');end if;
 if v_strong_count+v_valid_count>0 and v_family_count<2 then insert into public.creator_trust_recommendations(evaluation_id,creator_id,recommendation_code,priority,title,description,action_url)values(eid,p.creator_id,'add_independent_verification','medium','Add independent verification','Verify a different provider family or creator-owned domain.','/dashboard/identity');end if;
 if v_blocker_count>0 then insert into public.creator_trust_recommendations(evaluation_id,creator_id,recommendation_code,priority,title,description,action_url)values(eid,p.creator_id,'archive_revoked_account','critical','Resolve revoked identity','Keep revoked identities hidden until authoritative verification is restored.','/dashboard/identity');end if;
 if previous_state is distinct from new_state then insert into public.creator_trust_events(creator_id,identity_profile_id,evaluation_id,event_type,previous_state,new_state,policy_version,metadata)values(p.creator_id,p.id,eid,'trust_state_changed',previous_state,new_state,p_policy_version,jsonb_build_object('warningCount',v_warning_count,'blockerCount',v_blocker_count));end if;
 update public.creator_identity_profiles set trust_lease_owner=null,trust_lease_expires_at=null where id=p.id;return eid;
end$$;
revoke all on function public.evaluate_creator_trust(uuid,text,integer,integer,integer,integer) from public,anon,authenticated;grant execute on function public.evaluate_creator_trust(uuid,text,integer,integer,integer,integer) to service_role;

create or replace function public.get_creator_trust() returns jsonb language plpgsql stable security definer set search_path='' as $$declare p public.creator_identity_profiles%rowtype;e public.creator_trust_evaluations%rowtype;begin select * into p from public.creator_identity_profiles where public.has_creator_permission(creator_id,'emergency_manage')limit 1;if not found then raise exception'access denied'using errcode='42501';end if;select * into e from public.creator_trust_evaluations where identity_profile_id=p.id order by source_revision desc,evaluated_at desc limit 1;return jsonb_build_object('evaluation',to_jsonb(e)-'internal_score','signals',(select coalesce(jsonb_agg(to_jsonb(s)-'weight'-'metadata'),'[]')from public.creator_trust_signals s where s.evaluation_id=e.id),'recommendations',(select coalesce(jsonb_agg(to_jsonb(r)order by r.created_at),'[]')from public.creator_trust_recommendations r where r.evaluation_id=e.id),'events',(select coalesce(jsonb_agg(to_jsonb(t)order by t.id desc),'[]')from(select * from public.creator_trust_events x where x.identity_profile_id=p.id order by x.id desc limit 50)t));end$$;
revoke all on function public.get_creator_trust()from public,anon;grant execute on function public.get_creator_trust()to authenticated;

create or replace function public.get_public_creator_trust(p_slug text) returns jsonb language plpgsql stable security definer set search_path='' as $$declare e public.creator_trust_evaluations%rowtype;begin select t.* into e from public.creator_trust_evaluations t join public.creator_identity_profiles p on p.id=t.identity_profile_id join public.creators c on c.id=p.creator_id where c.public_slug=p_slug and c.public_profile_enabled and t.source_revision=p.identity_revision and(t.expires_at is null or t.expires_at>now())order by t.evaluated_at desc limit 1;if not found then return jsonb_build_object('state','unverified','label','Identity not yet verified','summary','No verified identity signals are currently available.','signals','[]'::jsonb,'lastEvaluatedAt',null);end if;return jsonb_build_object('state',e.trust_state,'label',case e.trust_state when'strongly_verified'then'Strongly verified identity'when'verified'then'Verified identity'when'needs_attention'then'Identity verification needs attention'when'restricted'then'Identity verification unavailable'else'Identity not yet verified'end,'summary',case e.trust_state when'strongly_verified'then'Verified across multiple independent channels.'when'verified'then'Identity is verified through an authoritative channel.'when'needs_attention'then'Verified identity evidence exists, but an important signal needs attention.'when'restricted'then'Verified identity badges are temporarily unavailable.'else'No verified identity signals are currently available.'end,'signals',case when e.trust_state='restricted'then'[]'::jsonb else(select coalesce(jsonb_agg(jsonb_build_object('type',case when s.provider_family='domain'then'verified_domain'else'verified_provider'end,'label',case when s.provider_family='domain'then'Creator domain verified'else initcap(s.provider_family)||' identity verified'end)order by s.provider_family),'[]')from(select distinct on(provider_family)provider_family from public.creator_trust_signals where evaluation_id=e.id and signal_state in('strong','valid')order by provider_family)s)end,'lastEvaluatedAt',e.evaluated_at);end$$;
revoke all on function public.get_public_creator_trust(text)from public;grant execute on function public.get_public_creator_trust(text)to anon,authenticated,service_role;

create or replace function public.claim_trust_evaluations(p_limit integer default 20,p_lease_owner uuid default gen_random_uuid())returns setof public.creator_identity_profiles language plpgsql security definer set search_path=''as $$begin if auth.role()<>'service_role'then raise exception'service role required'using errcode='42501';end if;return query with c as(select p.id from public.creator_identity_profiles p left join lateral(select e.source_revision,e.expires_at from public.creator_trust_evaluations e where e.identity_profile_id=p.id and e.policy_version='identity-trust-v1'order by e.source_revision desc,e.evaluated_at desc limit 1)e on true where(e.source_revision is distinct from p.identity_revision or e.expires_at is null or e.expires_at<=now())and(p.trust_lease_expires_at is null or p.trust_lease_expires_at<now())order by p.updated_at for update of p skip locked limit greatest(1,least(p_limit,100)))update public.creator_identity_profiles p set trust_lease_owner=p_lease_owner,trust_lease_expires_at=now()+interval'3 minutes'from c where p.id=c.id returning p.*;end$$;
revoke all on function public.claim_trust_evaluations(integer,uuid)from public,anon,authenticated;grant execute on function public.claim_trust_evaluations(integer,uuid)to service_role;

create or replace function public.mark_trust_recommendation_resolved(p_recommendation_id uuid)returns void language plpgsql security definer set search_path=''as $$declare r public.creator_trust_recommendations%rowtype;begin select * into r from public.creator_trust_recommendations where id=p_recommendation_id for update;if not found or not public.has_creator_permission(r.creator_id,'emergency_manage')then raise exception'access denied'using errcode='42501';end if;update public.creator_trust_recommendations set resolved_at=coalesce(resolved_at,now())where id=r.id;end$$;
revoke all on function public.mark_trust_recommendation_resolved(uuid)from public,anon;grant execute on function public.mark_trust_recommendation_resolved(uuid)to authenticated;

alter table public.creator_trust_evaluations enable row level security;alter table public.creator_trust_evaluations force row level security;alter table public.creator_trust_signals enable row level security;alter table public.creator_trust_signals force row level security;alter table public.creator_trust_recommendations enable row level security;alter table public.creator_trust_recommendations force row level security;alter table public.creator_trust_events enable row level security;alter table public.creator_trust_events force row level security;
create policy "owner trust evaluation reads"on public.creator_trust_evaluations for select to authenticated using(public.has_creator_permission(creator_id,'emergency_manage'));create policy "owner trust signal reads"on public.creator_trust_signals for select to authenticated using(public.has_creator_permission(creator_id,'emergency_manage'));create policy "owner trust recommendation reads"on public.creator_trust_recommendations for select to authenticated using(public.has_creator_permission(creator_id,'emergency_manage'));create policy "owner trust event reads"on public.creator_trust_events for select to authenticated using(public.has_creator_permission(creator_id,'emergency_manage'));
revoke all on public.creator_trust_evaluations,public.creator_trust_signals,public.creator_trust_recommendations,public.creator_trust_events from public,anon,authenticated;grant select on public.creator_trust_evaluations,public.creator_trust_signals,public.creator_trust_recommendations,public.creator_trust_events to authenticated;grant select,insert,update,delete on public.creator_trust_evaluations,public.creator_trust_signals,public.creator_trust_recommendations,public.creator_trust_events to service_role;

commit;
