-- Stage 8.5 Provider Expansion IV: Spotify, Snapchat, Pinterest, and constrained manual services.
begin;

alter table public.provider_asset_bindings drop constraint if exists provider_asset_bindings_provider_check;
alter table public.provider_asset_bindings add constraint provider_asset_bindings_provider_check check(provider in('tiktok','instagram','facebook','x','linkedin','threads','spotify','snapchat','pinterest'));
alter table public.provider_asset_bindings drop constraint if exists provider_asset_bindings_asset_type_check;
alter table public.provider_asset_bindings add constraint provider_asset_bindings_asset_type_check check(asset_type in('tiktok_account','instagram_professional_account','facebook_page','x_account','linkedin_member','linkedin_organization','threads_account','spotify_user','spotify_artist','spotify_show','snapchat_user','snapchat_public_profile','pinterest_user','pinterest_board','pinterest_claimed_website'));
alter table public.provider_asset_secrets drop constraint if exists provider_asset_secrets_provider_check;
alter table public.provider_asset_secrets add constraint provider_asset_secrets_provider_check check(provider in('instagram','facebook','x','linkedin','threads','spotify','snapchat','pinterest'));
alter table public.provider_access_reviews drop constraint if exists provider_access_reviews_provider_check;
alter table public.provider_access_reviews add constraint provider_access_reviews_provider_check check(provider in('tiktok','instagram','facebook','x','linkedin','threads','spotify','snapchat','pinterest'));
alter table public.provider_product_entitlements drop constraint if exists provider_product_entitlements_provider_check;
alter table public.provider_product_entitlements add constraint provider_product_entitlements_provider_check check(provider in('x','linkedin','threads','spotify','snapchat','pinterest'));
alter table public.provider_content_sources drop constraint if exists provider_content_sources_provider_check;
alter table public.provider_content_sources add constraint provider_content_sources_provider_check check(provider in('twitch','discord','podcast','rss','tiktok','instagram','facebook','x','linkedin','threads','spotify','snapchat','pinterest'));
alter table public.provider_content_sources drop constraint if exists provider_content_sources_source_type_check;
alter table public.provider_content_sources add constraint provider_content_sources_source_type_check check(source_type in('twitch_channel','twitch_videos','twitch_streams','discord_guild','discord_announcement_channel','podcast_feed','rss_feed','atom_feed','tiktok_account','instagram_professional_account','facebook_page','x_account','linkedin_member','linkedin_organization','threads_account','spotify_artist','spotify_show','snapchat_public_profile','pinterest_account','pinterest_board'));
alter table public.provider_verification_challenges drop constraint if exists provider_verification_challenges_provider_check;
alter table public.provider_verification_challenges add constraint provider_verification_challenges_provider_check check(provider in('tiktok','instagram','facebook','spotify','snapchat','pinterest','manual_service'));

create table public.manual_service_connections(
 id uuid primary key default gen_random_uuid(),creator_id uuid not null references public.creators(id)on delete cascade,identity_profile_id uuid not null references public.creator_identity_profiles(id)on delete cascade,
 service_name text not null check(char_length(btrim(service_name))between 1 and 100),service_category text not null check(service_category in('social','video','audio','music','podcast','community','newsletter','membership','commerce','booking','portfolio','developer','application','website','other')),
 canonical_url text not null check(canonical_url~'^https://'),normalized_hostname text not null check(normalized_hostname=lower(normalized_hostname)),public_handle text,display_name text not null check(char_length(btrim(display_name))between 1 and 200),
 verification_status text not null default'unverified'check(verification_status in('unverified','pending','verified','needs_attention','unavailable','revoked','archived')),verification_method text,verification_confidence text check(verification_confidence is null or verification_confidence in('low','medium','high')),
 public_visible boolean not null default true,official boolean not null default false,primary_for_category boolean not null default false,source_domain_id uuid references public.creator_identity_domains(id)on delete set null,current_challenge_id uuid,
 last_verified_at timestamptz,verification_expires_at timestamptz,revoked_at timestamptz,archived_at timestamptz,metadata jsonb not null default'{}'check(jsonb_typeof(metadata)='object'),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 unique(creator_id,canonical_url),check(not official or verification_status='verified'),check(not primary_for_category or(official and verification_status='verified'))
);
create table public.manual_service_challenges(
 id uuid primary key default gen_random_uuid(),creator_id uuid not null references public.creators(id)on delete cascade,manual_service_id uuid not null references public.manual_service_connections(id)on delete cascade,
 method text not null check(method in('verified_domain','well_known_manifest','public_challenge','signed_authenticity_statement','operator_review')),exact_url text not null check(exact_url~'^https://'),token_hash text not null,status text not null default'pending'check(status in('pending','verified','expired','failed','superseded')),
 expires_at timestamptz not null,attempt_count integer not null default 0 check(attempt_count>=0),max_attempts integer not null default 5 check(max_attempts between 1 and 20),verified_at timestamptz,created_at timestamptz not null default now()
);
alter table public.manual_service_connections add constraint manual_service_current_challenge_fkey foreign key(current_challenge_id)references public.manual_service_challenges(id)on delete set null;
create unique index manual_service_pending_challenge_idx on public.manual_service_challenges(manual_service_id)where status='pending';
create trigger manual_service_connections_updated before update on public.manual_service_connections for each row execute function public.set_updated_at();

create or replace function public.create_manual_service(p_service_name text,p_category text,p_canonical_url text,p_hostname text,p_public_handle text,p_display_name text)returns uuid language plpgsql security definer set search_path=''as $$declare p public.creator_identity_profiles%rowtype;result uuid;begin select*into p from public.creator_identity_profiles where public.has_creator_permission(creator_id,'emergency_manage')limit 1;if not found then raise exception'access denied'using errcode='42501';end if;if p_canonical_url!~'^https://'or lower(p_hostname)in('localhost','metadata.google.internal')then raise exception'unsafe remote destination'using errcode='23514';end if;insert into public.manual_service_connections(creator_id,identity_profile_id,service_name,service_category,canonical_url,normalized_hostname,public_handle,display_name,verification_status,official,metadata)values(p.creator_id,p.id,btrim(p_service_name),p_category,p_canonical_url,lower(p_hostname),nullif(btrim(p_public_handle),''),btrim(p_display_name),'unverified',false,jsonb_build_object('automaticSynchronization',false,'contentScraping',false))returning id into result;return result;end$$;
create or replace function public.update_manual_service_presentation(p_id uuid,p_public_visible boolean)returns void language plpgsql security definer set search_path=''as $$begin update public.manual_service_connections set public_visible=p_public_visible where id=p_id and public.has_creator_permission(creator_id,'emergency_manage');if not found then raise exception'access denied'using errcode='42501';end if;end$$;
create or replace function public.archive_manual_service(p_id uuid)returns void language plpgsql security definer set search_path=''as $$begin update public.manual_service_connections set verification_status='archived',official=false,primary_for_category=false,public_visible=false,archived_at=now()where id=p_id and public.has_creator_permission(creator_id,'emergency_manage');if not found then raise exception'access denied'using errcode='42501';end if;end$$;
create or replace function public.verify_manual_service(p_id uuid,p_challenge_id uuid,p_method text,p_confidence text)returns void language plpgsql security definer set search_path=''as $$declare d public.manual_service_connections%rowtype;c public.manual_service_challenges%rowtype;begin if auth.role()<>'service_role'then raise exception'service role required'using errcode='42501';end if;select*into d from public.manual_service_connections where id=p_id for update;select*into c from public.manual_service_challenges where id=p_challenge_id and manual_service_id=p_id for update;if not found or c.status<>'pending'or c.expires_at<=now()or c.attempt_count>=c.max_attempts then raise exception'invalid or expired challenge'using errcode='23514';end if;update public.manual_service_challenges set status='verified',verified_at=now()where id=c.id;update public.manual_service_connections set verification_status='verified',verification_method=p_method,verification_confidence=p_confidence,last_verified_at=now(),verification_expires_at=c.expires_at,current_challenge_id=null where id=d.id;end$$;

create or replace function public.claim_expansion_four_connections(p_limit integer default 20,p_lease_owner uuid default gen_random_uuid())returns setof public.connected_accounts language plpgsql security definer set search_path=''as $$begin if auth.role()<>'service_role'then raise exception'service role required'using errcode='42501';end if;return query with c as(select a.id from public.connected_accounts a where a.platform in('spotify','snapchat','pinterest')and a.watch_enabled and a.provider_status='ready'and a.connection_health in('healthy','degraded')and(a.next_sync_at is null or a.next_sync_at<=now())and(a.lease_expires_at is null or a.lease_expires_at<now())order by a.next_sync_at nulls first,a.last_sync_at nulls first for update skip locked limit greatest(1,least(p_limit,100)))update public.connected_accounts a set lease_owner=p_lease_owner,lease_expires_at=now()+interval'3 minutes',poll_claimed_until=now()+interval'3 minutes'from c where a.id=c.id returning a.*;end$$;

create or replace function public.trust_provider_family(p_provider text)returns text language sql immutable set search_path=''as $$select case lower(coalesce(p_provider,''))when'youtube'then'google'when'google'then'google'when'instagram'then'meta'when'facebook'then'meta'when'threads'then'meta'when'tiktok'then'bytedance'when'x'then'x'when'twitter'then'x'when'spotify'then'spotify'when'snapchat'then'snap'when'pinterest'then'pinterest'when'twitch'then'twitch'when'linkedin'then'linkedin'when'discord'then'discord'when'manual_service'then'manual'else'other'end$$;

alter table public.manual_service_connections enable row level security;alter table public.manual_service_connections force row level security;
alter table public.manual_service_challenges enable row level security;alter table public.manual_service_challenges force row level security;
create policy"creator manual service reads"on public.manual_service_connections for select to authenticated using(public.has_creator_permission(creator_id,'emergency_manage'));
create policy"creator manual challenge reads"on public.manual_service_challenges for select to authenticated using(public.has_creator_permission(creator_id,'emergency_manage'));
revoke all on public.manual_service_connections,public.manual_service_challenges from public,anon,authenticated;grant select on public.manual_service_connections,public.manual_service_challenges to authenticated;grant select,insert,update,delete on public.manual_service_connections,public.manual_service_challenges to service_role;
revoke all on function public.create_manual_service(text,text,text,text,text,text),public.update_manual_service_presentation(uuid,boolean),public.archive_manual_service(uuid)from public,anon;grant execute on function public.create_manual_service(text,text,text,text,text,text),public.update_manual_service_presentation(uuid,boolean),public.archive_manual_service(uuid)to authenticated;
revoke all on function public.verify_manual_service(uuid,uuid,text,text),public.claim_expansion_four_connections(integer,uuid)from public,anon,authenticated;grant execute on function public.verify_manual_service(uuid,uuid,text,text),public.claim_expansion_four_connections(integer,uuid)to service_role;
commit;
