begin;

alter table public.creator_identity_accounts add column monitoring_fingerprint text,add column next_monitor_at timestamptz,add column monitor_lease_owner uuid,add column monitor_lease_expires_at timestamptz,add column monitor_attempts integer not null default 0;
alter table public.creator_identity_domains add column monitoring_fingerprint text,add column next_monitor_at timestamptz,add column monitor_lease_owner uuid,add column monitor_lease_expires_at timestamptz,add column monitor_attempts integer not null default 0;

create table public.identity_monitoring_observations(
 id uuid primary key default gen_random_uuid(),creator_id uuid not null references public.creators(id)on delete cascade,identity_profile_id uuid not null references public.creator_identity_profiles(id)on delete cascade,identity_account_id uuid references public.creator_identity_accounts(id)on delete cascade,identity_domain_id uuid references public.creator_identity_domains(id)on delete cascade,provider text,
 observation_type text not null check(observation_type in('account_identity_confirmed','account_handle_changed','account_display_name_changed','account_url_changed','account_unavailable','account_restored','stable_identity_mismatch','provider_grant_revoked','provider_scope_missing','provider_review_required','verification_expired','verification_restored','domain_verification_failed','domain_verification_restored','domain_dns_changed','duplicate_primary_detected','sync_failure','sync_recovered','emergency_replacement_invalidated','emergency_replacement_restored')),
 observation_status text not null default'new'check(observation_status in('new','processed','ignored','superseded','expired')),severity text not null check(severity in('informational','low','medium','high','critical')),source text not null check(source in('identity_sync_worker','trust_worker','emergency_verification_worker','provider_webhook','domain_verification_worker','operator','creator_report')),source_event_id text,previous_fingerprint text,current_fingerprint text,observed_at timestamptz not null,processed_at timestamptz,expires_at timestamptz,metadata jsonb not null default'{}',created_at timestamptz not null default now(),check(num_nonnulls(identity_account_id,identity_domain_id)<=1),check(jsonb_typeof(metadata)='object'));
create unique index monitoring_observation_source_event_idx on public.identity_monitoring_observations(source,source_event_id)where source_event_id is not null;
create index monitoring_observation_pending_idx on public.identity_monitoring_observations(observation_status,observed_at)where observation_status='new';

create table public.identity_monitoring_incidents(
 id uuid primary key default gen_random_uuid(),creator_id uuid not null references public.creators(id)on delete cascade,identity_profile_id uuid not null references public.creator_identity_profiles(id)on delete cascade,observation_id uuid not null references public.identity_monitoring_observations(id)on delete restrict,correlation_key text not null,incident_type text not null,severity text not null check(severity in('informational','low','medium','high','critical')),status text not null default'open'check(status in('open','acknowledged','investigating','resolved','dismissed','escalated')),title text not null,summary text not null,affected_account_id uuid references public.creator_identity_accounts(id)on delete set null,affected_domain_id uuid references public.creator_identity_domains(id)on delete set null,trust_evaluation_id uuid references public.creator_trust_evaluations(id)on delete set null,emergency_id uuid references public.creator_emergencies(id)on delete set null,assigned_to uuid references auth.users(id)on delete set null,acknowledged_by uuid references auth.users(id)on delete set null,acknowledged_at timestamptz,resolved_at timestamptz,resolution_code text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index monitoring_open_incident_correlation_idx on public.identity_monitoring_incidents(correlation_key)where status in('open','acknowledged','investigating','escalated');

create table public.identity_monitoring_actions(
 id uuid primary key default gen_random_uuid(),creator_id uuid not null references public.creators(id)on delete cascade,monitoring_incident_id uuid not null references public.identity_monitoring_incidents(id)on delete cascade,action_type text not null check(action_type in('trust_reevaluation_requested','trust_reevaluation_completed','account_marked_needs_attention','account_revoked','public_badge_suppressed','recommendation_created','creator_alert_created','emergency_draft_created','provider_revalidation_requested','incident_acknowledged','incident_resolved','incident_dismissed')),status text not null,actor_type text not null check(actor_type in('worker','creator','operator','system')),actor_user_id uuid references auth.users(id)on delete set null,result_code text,metadata jsonb not null default'{}',created_at timestamptz not null default now(),check(jsonb_typeof(metadata)='object'));

create table public.creator_security_alerts(
 id uuid primary key default gen_random_uuid(),creator_id uuid not null references public.creators(id)on delete cascade,alert_type text not null,severity text not null check(severity in('informational','low','medium','high','critical')),title text not null,message text not null,action_url text,source_incident_id uuid references public.identity_monitoring_incidents(id)on delete cascade,read_at timestamptz,dismissed_at timestamptz,created_at timestamptz not null default now(),unique(source_incident_id,alert_type));

create trigger monitoring_incidents_updated before update on public.identity_monitoring_incidents for each row execute function public.set_updated_at();
create trigger monitoring_observations_immutable before update of creator_id,identity_profile_id,identity_account_id,identity_domain_id,provider,observation_type,severity,source,source_event_id,previous_fingerprint,current_fingerprint,observed_at,metadata or delete on public.identity_monitoring_observations for each row execute function public.prevent_emergency_history_mutation();
create trigger monitoring_actions_immutable before update or delete on public.identity_monitoring_actions for each row execute function public.prevent_emergency_history_mutation();

create or replace function public.ingest_identity_observation(p_profile_id uuid,p_observation_type text,p_severity text,p_source text,p_source_event_id text default null,p_account_id uuid default null,p_domain_id uuid default null,p_previous_fingerprint text default null,p_current_fingerprint text default null,p_observed_at timestamptz default now(),p_metadata jsonb default'{}')returns jsonb language plpgsql security definer set search_path=''as $$declare p public.creator_identity_profiles%rowtype;o public.identity_monitoring_observations%rowtype;authoritative boolean:=p_source<>'creator_report';begin
 if authoritative and auth.role()<>'service_role'then raise exception'service role required'using errcode='42501';end if;select*into p from public.creator_identity_profiles where id=p_profile_id;if not found then raise exception'identity profile not found'using errcode='P0002';end if;
 if not authoritative and not public.has_creator_permission(p.creator_id,'emergency_manage')then raise exception'access denied'using errcode='42501';end if;if not authoritative and p_observation_type not in('account_unavailable','domain_verification_failed','sync_failure')then raise exception'creator report cannot assert authoritative state'using errcode='23514';end if;
 if p_account_id is not null and not exists(select 1 from public.creator_identity_accounts a where a.id=p_account_id and a.identity_profile_id=p.id)then raise exception'account scope invalid'using errcode='23514';end if;if p_domain_id is not null and not exists(select 1 from public.creator_identity_domains d where d.id=p_domain_id and d.identity_profile_id=p.id)then raise exception'domain scope invalid'using errcode='23514';end if;
 if coalesce(p_metadata,'{}')-array['handle','display_name','canonical_url','stable_id','provider_health','verification_status','failure_count','report_note']::text[]<>'{}'::jsonb then raise exception'unsafe observation metadata'using errcode='22023';end if;
 insert into public.identity_monitoring_observations(creator_id,identity_profile_id,identity_account_id,identity_domain_id,provider,observation_type,severity,source,source_event_id,previous_fingerprint,current_fingerprint,observed_at,metadata)values(p.creator_id,p.id,p_account_id,p_domain_id,(select provider from public.creator_identity_accounts where id=p_account_id),p_observation_type,p_severity,p_source,p_source_event_id,p_previous_fingerprint,p_current_fingerprint,p_observed_at,coalesce(p_metadata,'{}'))on conflict(source,source_event_id)where source_event_id is not null do nothing returning*into o;
 if not found then select*into o from public.identity_monitoring_observations where source=p_source and source_event_id=p_source_event_id;return jsonb_build_object('observation_id',o.id,'inserted',false);end if;return jsonb_build_object('observation_id',o.id,'inserted',true);end$$;
revoke all on function public.ingest_identity_observation(uuid,text,text,text,text,uuid,uuid,text,text,timestamptz,jsonb)from public,anon;grant execute on function public.ingest_identity_observation(uuid,text,text,text,text,uuid,uuid,text,text,timestamptz,jsonb)to authenticated,service_role;

create or replace function public.process_identity_observation(p_observation_id uuid)returns uuid language plpgsql security definer set search_path=''as $$declare o public.identity_monitoring_observations%rowtype;i public.identity_monitoring_incidents%rowtype;key text;requires_incident boolean;title text;summary text;badge boolean:=false;begin if auth.role()<>'service_role'then raise exception'service role required'using errcode='42501';end if;select*into o from public.identity_monitoring_observations where id=p_observation_id for update;if not found then raise exception'observation not found'using errcode='P0002';end if;if o.observation_status<>'new'then select*into i from public.identity_monitoring_incidents where observation_id=o.id limit 1;return i.id;end if;
 requires_incident:=o.severity in('medium','high','critical')or o.observation_type in('stable_identity_mismatch','provider_grant_revoked','account_unavailable','domain_verification_failed','emergency_replacement_invalidated');title:=replace(initcap(replace(o.observation_type,'_',' ')),'Provider Grant','Provider access');summary:=case when o.observation_type='stable_identity_mismatch'then'The provider returned a different stable identity. Existing verification was suppressed pending review.'when o.observation_type='provider_grant_revoked'then'Provider access was revoked and must be reconnected.'when o.observation_type='emergency_replacement_invalidated'then'An emergency replacement requires authoritative re-verification.'else'An authoritative identity change requires review.'end;
 if o.observation_type='account_handle_changed'and o.identity_account_id is not null then update public.creator_identity_accounts set display_handle=o.metadata->>'handle',monitoring_fingerprint=o.current_fingerprint,last_synced_at=o.observed_at where id=o.identity_account_id;
 elsif o.observation_type='account_display_name_changed'and o.identity_account_id is not null then update public.creator_identity_accounts set display_name=o.metadata->>'display_name',monitoring_fingerprint=o.current_fingerprint,last_synced_at=o.observed_at where id=o.identity_account_id;
 elsif o.observation_type='account_url_changed'and o.identity_account_id is not null and(o.metadata->>'canonical_url')~'^https://'then update public.creator_identity_accounts set canonical_profile_url=o.metadata->>'canonical_url',monitoring_fingerprint=o.current_fingerprint,last_synced_at=o.observed_at where id=o.identity_account_id;
 elsif o.observation_type in('stable_identity_mismatch','provider_grant_revoked','verification_expired','account_unavailable')and o.identity_account_id is not null then badge:=true;update public.creator_identity_accounts set verification_status=case when o.observation_type='provider_grant_revoked'then'revoked'else'needs_attention'end,official=false,primary_for_provider=false,public_visible=false,sync_status=case when o.observation_type='provider_grant_revoked'then'revoked'else'needs_attention'end,last_sync_error=o.observation_type where id=o.identity_account_id;
 elsif o.observation_type in('domain_verification_failed','domain_dns_changed')and o.identity_domain_id is not null then badge:=true;update public.creator_identity_domains set verification_status='needs_attention',official=false,primary_domain=false,public_visible=false where id=o.identity_domain_id;end if;
 if requires_incident then key:=concat(o.creator_id,':',coalesce(o.identity_account_id::text,o.identity_domain_id::text,'profile'),':',o.observation_type);select*into i from public.identity_monitoring_incidents where correlation_key=key and status in('open','acknowledged','investigating','escalated')for update;
  if not found then insert into public.identity_monitoring_incidents(creator_id,identity_profile_id,observation_id,correlation_key,incident_type,severity,status,title,summary,affected_account_id,affected_domain_id)values(o.creator_id,o.identity_profile_id,o.id,key,o.observation_type,o.severity,case when o.severity='critical'then'escalated'else'open'end,title,summary,o.identity_account_id,o.identity_domain_id)returning*into i;else update public.identity_monitoring_incidents set severity=case when o.severity='critical'then'critical'else i.severity end,updated_at=now()where id=i.id returning*into i;end if;
  insert into public.creator_security_alerts(creator_id,alert_type,severity,title,message,action_url,source_incident_id)values(o.creator_id,o.observation_type,o.severity,title,summary,'/dashboard/identity',i.id)on conflict(source_incident_id,alert_type)do nothing;
  insert into public.identity_monitoring_actions(creator_id,monitoring_incident_id,action_type,status,actor_type,result_code)values(o.creator_id,i.id,'creator_alert_created','completed','system','private_dashboard_alert');
  if badge then insert into public.identity_monitoring_actions(creator_id,monitoring_incident_id,action_type,status,actor_type,result_code)values(o.creator_id,i.id,'public_badge_suppressed','completed','system','authoritative_verification_lost');end if;
  insert into public.identity_monitoring_actions(creator_id,monitoring_incident_id,action_type,status,actor_type,result_code)values(o.creator_id,i.id,'trust_reevaluation_requested','completed','system','identity_revision_advanced');
 end if;update public.identity_monitoring_observations set observation_status='processed',processed_at=now()where id=o.id;return i.id;end$$;
revoke all on function public.process_identity_observation(uuid)from public,anon,authenticated;grant execute on function public.process_identity_observation(uuid)to service_role;

create or replace function public.claim_identity_monitoring(p_limit integer default 20,p_lease_owner uuid default gen_random_uuid())returns setof public.creator_identity_accounts language plpgsql security definer set search_path=''as $$begin if auth.role()<>'service_role'then raise exception'service role required'using errcode='42501';end if;return query with c as(select a.id from public.creator_identity_accounts a where a.verification_status in('verified','needs_attention')and a.source_connection_id is not null and(a.next_monitor_at is null or a.next_monitor_at<=now())and(a.monitor_lease_expires_at is null or a.monitor_lease_expires_at<now())order by a.official desc,a.next_monitor_at nulls first for update skip locked limit greatest(1,least(p_limit,100)))update public.creator_identity_accounts a set monitor_lease_owner=p_lease_owner,monitor_lease_expires_at=now()+interval'3 minutes'from c where a.id=c.id returning a.*;end$$;
revoke all on function public.claim_identity_monitoring(integer,uuid)from public,anon,authenticated;grant execute on function public.claim_identity_monitoring(integer,uuid)to service_role;

create or replace function public.update_monitoring_incident(p_incident_id uuid,p_action text,p_resolution_code text default null)returns void language plpgsql security definer set search_path=''as $$declare i public.identity_monitoring_incidents%rowtype;next_status text;action_name text;begin select*into i from public.identity_monitoring_incidents where id=p_incident_id for update;if not found or not public.has_creator_permission(i.creator_id,'emergency_manage')then raise exception'access denied'using errcode='42501';end if;if p_action='dismiss'and i.severity in('high','critical')then raise exception'high-risk incidents cannot be dismissed'using errcode='42501';end if;next_status:=case p_action when'acknowledge'then'acknowledged'when'dismiss'then'dismissed'when'resolve'then'resolved'else null end;if next_status is null then raise exception'invalid incident action'using errcode='22023';end if;action_name:=case p_action when'acknowledge'then'incident_acknowledged'when'dismiss'then'incident_dismissed'else'incident_resolved'end;update public.identity_monitoring_incidents set status=next_status,acknowledged_by=case when p_action='acknowledge'then auth.uid()else acknowledged_by end,acknowledged_at=case when p_action='acknowledge'then now()else acknowledged_at end,resolved_at=case when p_action in('resolve','dismiss')then now()else resolved_at end,resolution_code=p_resolution_code where id=i.id;insert into public.identity_monitoring_actions(creator_id,monitoring_incident_id,action_type,status,actor_type,actor_user_id,result_code)values(i.creator_id,i.id,action_name,'completed','creator',auth.uid(),p_resolution_code);end$$;
revoke all on function public.update_monitoring_incident(uuid,text,text)from public,anon;grant execute on function public.update_monitoring_incident(uuid,text,text)to authenticated;

create or replace function public.prepare_monitoring_emergency(p_incident_id uuid)returns uuid language plpgsql security definer set search_path=''as $$declare i public.identity_monitoring_incidents%rowtype;eid uuid;connected_id uuid;begin select*into i from public.identity_monitoring_incidents where id=p_incident_id for update;if not found or not public.has_creator_permission(i.creator_id,'emergency_manage')then raise exception'access denied'using errcode='42501';end if;if i.severity not in('high','critical')then raise exception'high-risk incident required'using errcode='23514';end if;if i.emergency_id is not null then return i.emergency_id;end if;select source_connection_id into connected_id from public.creator_identity_accounts where id=i.affected_account_id;if connected_id is null then raise exception'connected account unavailable'using errcode='23514';end if;eid:=public.create_emergency(case when i.incident_type='stable_identity_mismatch'then'account_changed'else'account_suspended'end,case when i.severity='critical'then'critical'else'important'end,'Prepared identity incident',i.summary,connected_id);update public.identity_monitoring_incidents set emergency_id=eid where id=i.id;insert into public.identity_monitoring_actions(creator_id,monitoring_incident_id,action_type,status,actor_type,actor_user_id,result_code)values(i.creator_id,i.id,'emergency_draft_created','completed','creator',auth.uid(),'draft_only');return eid;end$$;
revoke all on function public.prepare_monitoring_emergency(uuid)from public,anon;grant execute on function public.prepare_monitoring_emergency(uuid)to authenticated;

create or replace function public.update_security_alert(p_alert_id uuid,p_action text)returns void language plpgsql security definer set search_path=''as $$declare a public.creator_security_alerts%rowtype;begin select*into a from public.creator_security_alerts where id=p_alert_id for update;if not found or not public.has_creator_permission(a.creator_id,'emergency_manage')then raise exception'access denied'using errcode='42501';end if;if p_action='dismiss'and a.severity='critical'then raise exception'critical alert cannot be dismissed'using errcode='42501';end if;update public.creator_security_alerts set read_at=case when p_action='read'then coalesce(read_at,now())else read_at end,dismissed_at=case when p_action='dismiss'then coalesce(dismissed_at,now())else dismissed_at end where id=a.id;end$$;
revoke all on function public.update_security_alert(uuid,text)from public,anon;grant execute on function public.update_security_alert(uuid,text)to authenticated;

alter table public.identity_monitoring_observations enable row level security;alter table public.identity_monitoring_observations force row level security;alter table public.identity_monitoring_incidents enable row level security;alter table public.identity_monitoring_incidents force row level security;alter table public.identity_monitoring_actions enable row level security;alter table public.identity_monitoring_actions force row level security;alter table public.creator_security_alerts enable row level security;alter table public.creator_security_alerts force row level security;
create policy"creator observation reads"on public.identity_monitoring_observations for select to authenticated using(public.has_creator_permission(creator_id,'emergency_manage'));create policy"creator incident reads"on public.identity_monitoring_incidents for select to authenticated using(public.has_creator_permission(creator_id,'emergency_manage'));create policy"creator action reads"on public.identity_monitoring_actions for select to authenticated using(public.has_creator_permission(creator_id,'emergency_manage'));create policy"creator alert reads"on public.creator_security_alerts for select to authenticated using(public.has_creator_permission(creator_id,'emergency_manage'));
revoke all on public.identity_monitoring_observations,public.identity_monitoring_incidents,public.identity_monitoring_actions,public.creator_security_alerts from public,anon,authenticated;grant select on public.identity_monitoring_observations,public.identity_monitoring_incidents,public.identity_monitoring_actions,public.creator_security_alerts to authenticated;grant select,insert,update,delete on public.identity_monitoring_observations,public.identity_monitoring_incidents,public.creator_security_alerts to service_role;grant select,insert,update,delete on public.identity_monitoring_actions to service_role;

commit;
