begin;

create table public.creator_ecosystem_destinations(
 id uuid primary key default gen_random_uuid(),creator_id uuid not null references public.creators(id) on delete cascade,identity_profile_id uuid not null references public.creator_identity_profiles(id) on delete cascade,
 provider text not null check(char_length(btrim(provider))between 1 and 60),destination_type text not null check(destination_type in('community','announcement_channel','developer_profile','organization','repository','package','membership','newsletter','website','application','podcast','feed','merchandise','commerce','booking','contact','donation','event','other')),
 stable_external_id text,display_name text not null check(char_length(btrim(display_name))between 1 and 200),display_handle text,canonical_url text not null check(canonical_url~'^https://'),hostname text not null,
 verification_status text not null default'unverified'check(verification_status in('unverified','pending','verified','needs_attention','revoked','unavailable','archived')),verification_method text,verification_confidence text check(verification_confidence is null or verification_confidence in('low','medium','high')),
 source_connection_id uuid references public.connected_accounts(id)on delete set null,source_identity_account_id uuid references public.creator_identity_accounts(id)on delete set null,
 official boolean not null default false,primary_for_type boolean not null default false,public_visible boolean not null default true,capabilities jsonb not null default'{}',
 first_verified_at timestamptz,last_verified_at timestamptz,last_revalidated_at timestamptz,next_revalidation_at timestamptz,verification_expires_at timestamptz,revoked_at timestamptz,archived_at timestamptz,
 sync_status text not null default'not_due'check(sync_status in('not_due','due','claimed','healthy','needs_attention','revoked','failed','archived')),last_sync_error_code text,metadata jsonb not null default'{}',last_synced_at timestamptz,lease_owner uuid,lease_expires_at timestamptz,sync_attempts integer not null default 0,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 check(hostname=lower(hostname)),check(jsonb_typeof(capabilities)='object'),check(jsonb_typeof(metadata)='object'),
 check(not official or verification_status='verified'),check(not primary_for_type or(verification_status='verified'and official)),
 check(verification_status not in('revoked','archived')or(not official and not primary_for_type and not public_visible)));
create unique index ecosystem_stable_identity_idx on public.creator_ecosystem_destinations(creator_id,provider,stable_external_id)where stable_external_id is not null and archived_at is null;
create unique index ecosystem_canonical_fallback_idx on public.creator_ecosystem_destinations(creator_id,provider,canonical_url)where stable_external_id is null and archived_at is null;
create unique index ecosystem_one_primary_type_idx on public.creator_ecosystem_destinations(creator_id,destination_type)where primary_for_type;
create index ecosystem_sync_idx on public.creator_ecosystem_destinations(next_revalidation_at nulls first)where verification_status in('verified','needs_attention')and sync_status<>'archived';

create table public.creator_ecosystem_relationships(
 id uuid primary key default gen_random_uuid(),creator_id uuid not null references public.creators(id)on delete cascade,identity_profile_id uuid not null references public.creator_identity_profiles(id)on delete cascade,
 source_destination_id uuid references public.creator_ecosystem_destinations(id)on delete cascade,target_destination_id uuid references public.creator_ecosystem_destinations(id)on delete cascade,identity_account_id uuid references public.creator_identity_accounts(id)on delete cascade,identity_domain_id uuid references public.creator_identity_domains(id)on delete cascade,
 relationship_type text not null check(relationship_type in('owned_by_creator','managed_by_creator','official_community_of','official_organization_of','official_application_of','official_membership_of','official_repository_of','official_package_of','official_newsletter_of','official_commerce_of','linked_from_verified_domain','verified_by_provider','verified_by_domain','replaces','migrated_from','mirrors')),
 status text not null default'active'check(status in('pending','active','revoked','archived')),confidence text check(confidence is null or confidence in('low','medium','high')),source text not null,created_at timestamptz not null default now(),verified_at timestamptz,revoked_at timestamptz,
 check(source_destination_id is not null or target_destination_id is not null),check(source_destination_id is distinct from target_destination_id));

create table public.ecosystem_verification_records(
 id uuid primary key default gen_random_uuid(),creator_id uuid not null references public.creators(id)on delete cascade,destination_id uuid not null references public.creator_ecosystem_destinations(id)on delete cascade,provider text not null,method text not null,status text not null check(status in('pending','verified','failed','revoked','expired','unavailable')),confidence text not null check(confidence in('low','medium','high')),stable_external_id text,verification_revision bigint not null default 1 check(verification_revision>0),requested_by uuid not null,verified_by uuid,requested_at timestamptz not null default now(),verified_at timestamptz,expires_at timestamptz,failed_at timestamptz,revoked_at timestamptz,failure_code text,evidence_metadata jsonb not null default'{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(jsonb_typeof(evidence_metadata)='object'));

create table public.ecosystem_events(
 id bigint generated always as identity primary key,creator_id uuid not null references public.creators(id)on delete cascade,identity_profile_id uuid not null references public.creator_identity_profiles(id)on delete cascade,destination_id uuid references public.creator_ecosystem_destinations(id)on delete set null,relationship_id uuid references public.creator_ecosystem_relationships(id)on delete set null,verification_id uuid references public.ecosystem_verification_records(id)on delete set null,event_type text not null,actor_user_id uuid,source text not null,metadata jsonb not null default'{}',created_at timestamptz not null default now(),check(jsonb_typeof(metadata)='object'));

create trigger ecosystem_destinations_updated before update on public.creator_ecosystem_destinations for each row execute function public.set_updated_at();
create trigger ecosystem_verifications_updated before update on public.ecosystem_verification_records for each row execute function public.set_updated_at();
create trigger ecosystem_events_immutable before update or delete on public.ecosystem_events for each row execute function public.prevent_emergency_history_mutation();
create trigger ecosystem_destination_revision after insert or update or delete on public.creator_ecosystem_destinations for each row execute function public.bump_identity_revision();
create trigger ecosystem_relationship_revision after insert or update or delete on public.creator_ecosystem_relationships for each row execute function public.bump_identity_revision();

create or replace function public.ecosystem_trust_provider_family(p_provider text)returns text language sql immutable set search_path=''as $$select case lower(coalesce(p_provider,''))when'github'then'github'when'discord'then'discord'when'patreon'then'patreon'when'website'then'domain'when'newsletter'then'newsletter_provider'when'podcast'then'podcast_provider'when'rss'then'podcast_provider'when'application'then'application_store'else'other'end$$;
revoke all on function public.ecosystem_trust_provider_family(text)from public,anon,authenticated;

create or replace function public.monitor_ecosystem_suppression()returns trigger language plpgsql security definer set search_path=''as $$begin if old.verification_status='verified'and new.verification_status in('needs_attention','revoked','unavailable')then insert into public.creator_security_alerts(creator_id,alert_type,severity,title,message,action_url)values(new.creator_id,'ecosystem_verification_lost','medium','Ecosystem destination needs attention','An authoritative ecosystem destination lost verification and was removed from public presentation.','/dashboard/ecosystem');end if;return new;end$$;
create trigger ecosystem_destination_monitoring after update of verification_status on public.creator_ecosystem_destinations for each row execute function public.monitor_ecosystem_suppression();
revoke all on function public.monitor_ecosystem_suppression()from public,anon,authenticated;

create or replace function public.append_ecosystem_event(p_destination_id uuid,p_event_type text,p_source text,p_metadata jsonb default'{}')returns bigint language plpgsql security definer set search_path=''as $$declare d public.creator_ecosystem_destinations%rowtype;eid bigint;begin if auth.role()<>'service_role'then raise exception'service role required'using errcode='42501';end if;select*into d from public.creator_ecosystem_destinations where id=p_destination_id;insert into public.ecosystem_events(creator_id,identity_profile_id,destination_id,event_type,source,metadata)values(d.creator_id,d.identity_profile_id,d.id,p_event_type,p_source,coalesce(p_metadata,'{}'))returning id into eid;return eid;end$$;
revoke all on function public.append_ecosystem_event(uuid,text,text,jsonb)from public,anon,authenticated;grant execute on function public.append_ecosystem_event(uuid,text,text,jsonb)to service_role;

create or replace function public.ensure_ecosystem_destination(p_provider text,p_destination_type text,p_stable_external_id text,p_display_name text,p_display_handle text,p_canonical_url text,p_hostname text,p_source_connection_id uuid default null,p_source_identity_account_id uuid default null,p_metadata jsonb default'{}')returns uuid language plpgsql security definer set search_path=''as $$declare c public.creators%rowtype;p public.creator_identity_profiles%rowtype;d public.creator_ecosystem_destinations%rowtype;begin
 if auth.role()<>'service_role'then raise exception'service role required'using errcode='42501';end if;select*into p from public.creator_identity_profiles where id=(select identity_profile_id from public.creator_identity_accounts where id=p_source_identity_account_id)or creator_id=(select creator_id from public.connected_accounts where id=p_source_connection_id)limit 1;if not found then raise exception'authoritative creator source required'using errcode='23514';end if;select*into c from public.creators where id=p.creator_id;
 select*into d from public.creator_ecosystem_destinations where creator_id=c.id and provider=lower(p_provider)and((p_stable_external_id is not null and stable_external_id=p_stable_external_id)or(p_stable_external_id is null and stable_external_id is null and canonical_url=p_canonical_url))for update;
 if found then update public.creator_ecosystem_destinations set display_name=p_display_name,display_handle=p_display_handle,canonical_url=p_canonical_url,hostname=lower(p_hostname),source_connection_id=coalesce(p_source_connection_id,d.source_connection_id),source_identity_account_id=coalesce(p_source_identity_account_id,d.source_identity_account_id),metadata=coalesce(p_metadata,'{}'),updated_at=now()where id=d.id;return d.id;end if;
 insert into public.creator_ecosystem_destinations(creator_id,identity_profile_id,provider,destination_type,stable_external_id,display_name,display_handle,canonical_url,hostname,source_connection_id,source_identity_account_id,metadata)values(c.id,p.id,lower(p_provider),p_destination_type,p_stable_external_id,p_display_name,p_display_handle,p_canonical_url,lower(p_hostname),p_source_connection_id,p_source_identity_account_id,coalesce(p_metadata,'{}'))returning id into d.id;return d.id;end$$;
revoke all on function public.ensure_ecosystem_destination(text,text,text,text,text,text,text,uuid,uuid,jsonb)from public,anon,authenticated;grant execute on function public.ensure_ecosystem_destination(text,text,text,text,text,text,text,uuid,uuid,jsonb)to service_role;

create or replace function public.import_ecosystem_destination(p_provider text,p_destination_type text,p_display_name text,p_canonical_url text,p_hostname text)returns uuid language plpgsql security definer set search_path=''as $$declare p public.creator_identity_profiles%rowtype;d uuid;begin select*into p from public.creator_identity_profiles where public.has_creator_permission(creator_id,'emergency_manage')limit 1;if not found then raise exception'access denied'using errcode='42501';end if;if p_canonical_url!~'^https://'or lower(p_hostname)not in('github.com','discord.com','discord.gg','patreon.com')and not exists(select 1 from public.creator_identity_domains x where x.creator_id=p.creator_id and x.verification_status='verified'and(lower(p_hostname)=x.hostname or lower(p_hostname)like'%.'||x.hostname))then raise exception'hostname is not allowed'using errcode='23514';end if;insert into public.creator_ecosystem_destinations(creator_id,identity_profile_id,provider,destination_type,display_name,canonical_url,hostname,verification_status,official,primary_for_type,public_visible,sync_status,metadata)values(p.creator_id,p.id,lower(p_provider),p_destination_type,p_display_name,p_canonical_url,lower(p_hostname),'unverified',false,false,true,'not_due',jsonb_build_object('manualImport',true))returning id into d;insert into public.ecosystem_events(creator_id,identity_profile_id,destination_id,event_type,actor_user_id,source)values(p.creator_id,p.id,d,'ecosystem.destination_added',auth.uid(),'creator_manual_import');return d;end$$;
revoke all on function public.import_ecosystem_destination(text,text,text,text,text)from public,anon;grant execute on function public.import_ecosystem_destination(text,text,text,text,text)to authenticated;

create or replace function public.verify_ecosystem_destination(p_destination_id uuid,p_method text,p_confidence text,p_stable_external_id text default null,p_expires_at timestamptz default null)returns uuid language plpgsql security definer set search_path=''as $$declare d public.creator_ecosystem_destinations%rowtype;v uuid;begin if auth.role()<>'service_role'then raise exception'service role required'using errcode='42501';end if;select*into d from public.creator_ecosystem_destinations where id=p_destination_id for update;if not found then raise exception'destination not found'using errcode='P0002';end if;if d.stable_external_id is not null and p_stable_external_id is distinct from d.stable_external_id then update public.creator_ecosystem_destinations set verification_status='needs_attention',official=false,primary_for_type=false,public_visible=false,sync_status='needs_attention',last_sync_error_code='stable_id_mismatch'where id=d.id;raise exception'stable identity mismatch'using errcode='23514';end if;update public.creator_ecosystem_destinations set stable_external_id=coalesce(stable_external_id,p_stable_external_id),verification_status='verified',verification_method=p_method,verification_confidence=p_confidence,first_verified_at=coalesce(first_verified_at,now()),last_verified_at=now(),last_revalidated_at=now(),verification_expires_at=p_expires_at,revoked_at=null,sync_status='healthy',last_sync_error_code=null where id=d.id;insert into public.ecosystem_verification_records(creator_id,destination_id,provider,method,status,confidence,stable_external_id,requested_by,verified_at,expires_at)values(d.creator_id,d.id,d.provider,p_method,'verified',p_confidence,coalesce(d.stable_external_id,p_stable_external_id),auth.uid(),now(),p_expires_at)returning id into v;insert into public.ecosystem_events(creator_id,identity_profile_id,destination_id,verification_id,event_type,source)values(d.creator_id,d.identity_profile_id,d.id,v,'ecosystem.destination_verified','ecosystem_worker');return v;end$$;
revoke all on function public.verify_ecosystem_destination(uuid,text,text,text,timestamptz)from public,anon,authenticated;grant execute on function public.verify_ecosystem_destination(uuid,text,text,text,timestamptz)to service_role;

create or replace function public.revoke_ecosystem_destination(p_destination_id uuid,p_reason text default'revoked')returns void language plpgsql security definer set search_path=''as $$declare d public.creator_ecosystem_destinations%rowtype;begin if auth.role()<>'service_role'then raise exception'service role required'using errcode='42501';end if;select*into d from public.creator_ecosystem_destinations where id=p_destination_id for update;update public.creator_ecosystem_destinations set verification_status='revoked',official=false,primary_for_type=false,public_visible=false,revoked_at=now(),sync_status='revoked',last_sync_error_code=p_reason where id=d.id;update public.ecosystem_verification_records set status='revoked',revoked_at=now()where destination_id=d.id and status='verified';insert into public.ecosystem_events(creator_id,identity_profile_id,destination_id,event_type,source,metadata)values(d.creator_id,d.identity_profile_id,d.id,'ecosystem.destination_revoked','ecosystem_worker',jsonb_build_object('reasonCode',p_reason));end$$;
revoke all on function public.revoke_ecosystem_destination(uuid,text)from public,anon,authenticated;grant execute on function public.revoke_ecosystem_destination(uuid,text)to service_role;

create or replace function public.set_ecosystem_destination_presentation(p_destination_id uuid,p_official boolean,p_public_visible boolean)returns void language plpgsql security definer set search_path=''as $$declare d public.creator_ecosystem_destinations%rowtype;begin select*into d from public.creator_ecosystem_destinations where id=p_destination_id for update;if not found or not public.has_creator_permission(d.creator_id,'emergency_manage')then raise exception'access denied'using errcode='42501';end if;if p_official and d.verification_status<>'verified'then raise exception'verified destination required'using errcode='23514';end if;update public.creator_ecosystem_destinations set official=p_official,public_visible=p_public_visible,primary_for_type=case when p_official and p_public_visible then primary_for_type else false end where id=d.id;update public.creator_authenticity_profiles set presentation_revision=presentation_revision+1,issuance_lease_expires_at=null where creator_id=d.creator_id;end$$;
revoke all on function public.set_ecosystem_destination_presentation(uuid,boolean,boolean)from public,anon;grant execute on function public.set_ecosystem_destination_presentation(uuid,boolean,boolean)to authenticated;

create or replace function public.set_primary_ecosystem_destination(p_destination_id uuid)returns void language plpgsql security definer set search_path=''as $$declare d public.creator_ecosystem_destinations%rowtype;begin select*into d from public.creator_ecosystem_destinations where id=p_destination_id for update;if not found or not public.has_creator_permission(d.creator_id,'emergency_manage')then raise exception'access denied'using errcode='42501';end if;if d.verification_status<>'verified'or not d.official then raise exception'verified official destination required'using errcode='23514';end if;update public.creator_ecosystem_destinations set primary_for_type=false where creator_id=d.creator_id and destination_type=d.destination_type and primary_for_type;update public.creator_ecosystem_destinations set primary_for_type=true,public_visible=true where id=d.id;update public.creator_authenticity_profiles set presentation_revision=presentation_revision+1,issuance_lease_expires_at=null where creator_id=d.creator_id;end$$;
revoke all on function public.set_primary_ecosystem_destination(uuid)from public,anon;grant execute on function public.set_primary_ecosystem_destination(uuid)to authenticated;

create or replace function public.archive_ecosystem_destination(p_destination_id uuid)returns void language plpgsql security definer set search_path=''as $$declare d public.creator_ecosystem_destinations%rowtype;begin select*into d from public.creator_ecosystem_destinations where id=p_destination_id for update;if not found or not public.has_creator_permission(d.creator_id,'emergency_manage')then raise exception'access denied'using errcode='42501';end if;update public.creator_ecosystem_destinations set verification_status='archived',official=false,primary_for_type=false,public_visible=false,archived_at=now(),sync_status='archived'where id=d.id;insert into public.ecosystem_events(creator_id,identity_profile_id,destination_id,event_type,actor_user_id,source)values(d.creator_id,d.identity_profile_id,d.id,'ecosystem.destination_archived',auth.uid(),'creator_dashboard');end$$;
revoke all on function public.archive_ecosystem_destination(uuid)from public,anon;grant execute on function public.archive_ecosystem_destination(uuid)to authenticated;

create or replace function public.claim_ecosystem_sync(p_limit integer default 20,p_lease_owner uuid default gen_random_uuid())returns setof public.creator_ecosystem_destinations language plpgsql security definer set search_path=''as $$begin if auth.role()<>'service_role'then raise exception'service role required'using errcode='42501';end if;return query with c as(select d.id from public.creator_ecosystem_destinations d where d.verification_status in('verified','needs_attention')and d.sync_status<>'archived'and(d.next_revalidation_at is null or d.next_revalidation_at<=now())and(d.lease_expires_at is null or d.lease_expires_at<now())order by d.official desc,d.next_revalidation_at nulls first for update skip locked limit greatest(1,least(p_limit,100)))update public.creator_ecosystem_destinations d set sync_status='claimed',lease_owner=p_lease_owner,lease_expires_at=now()+interval'3 minutes',sync_attempts=sync_attempts+1 from c where d.id=c.id returning d.*;end$$;
revoke all on function public.claim_ecosystem_sync(integer,uuid)from public,anon,authenticated;grant execute on function public.claim_ecosystem_sync(integer,uuid)to service_role;

create or replace function public.get_creator_ecosystem_graph()returns jsonb language plpgsql stable security definer set search_path=''as $$declare p public.creator_identity_profiles%rowtype;begin select*into p from public.creator_identity_profiles where public.has_creator_permission(creator_id,'emergency_manage')limit 1;if not found then raise exception'access denied'using errcode='42501';end if;return jsonb_build_object('destinations',(select coalesce(jsonb_agg(to_jsonb(d)-'stable_external_id'-'metadata'-'last_sync_error_code'-'lease_owner'-'lease_expires_at'),'[]')from public.creator_ecosystem_destinations d where d.identity_profile_id=p.id),'relationships',(select coalesce(jsonb_agg(to_jsonb(r)),'[]')from public.creator_ecosystem_relationships r where r.identity_profile_id=p.id),'events',(select coalesce(jsonb_agg(to_jsonb(e)-'metadata'order by e.id desc),'[]')from(select*from public.ecosystem_events where identity_profile_id=p.id order by id desc limit 50)e));end$$;
revoke all on function public.get_creator_ecosystem_graph()from public,anon;grant execute on function public.get_creator_ecosystem_graph()to authenticated;

create or replace function public.get_public_creator_ecosystem_graph(p_slug text)returns jsonb language plpgsql stable security definer set search_path=''as $$declare p public.creator_identity_profiles%rowtype;c public.creators%rowtype;begin select ip.*into p from public.creator_identity_profiles ip join public.creators cr on cr.id=ip.creator_id join public.creator_authenticity_profiles ap on ap.identity_profile_id=ip.id where cr.public_slug=p_slug and cr.public_profile_enabled and ap.display_enabled and ip.identity_status<>'archived';if not found then return null;end if;select*into c from public.creators where id=p.creator_id;return jsonb_build_object('version','audienceown-ecosystem-v1','creator',jsonb_build_object('slug',c.public_slug,'verificationUrl','/verify/'||c.public_slug),'destinations',(select coalesce(jsonb_agg(jsonb_strip_nulls(jsonb_build_object('type',d.destination_type,'provider',d.provider,'name',d.display_name,'handle',d.display_handle,'url',d.canonical_url,'official',true,'primary',d.primary_for_type,'verifiedAt',d.last_verified_at))order by d.primary_for_type desc,d.destination_type,d.display_name),'[]')from public.creator_ecosystem_destinations d where d.identity_profile_id=p.id and d.verification_status='verified'and d.official and d.public_visible and d.revoked_at is null and d.archived_at is null),'lastUpdatedAt',(select max(d.updated_at)from public.creator_ecosystem_destinations d where d.identity_profile_id=p.id),'assertionUrl','/api/public/creators/'||c.public_slug||'/authenticity/assertion');end$$;
revoke all on function public.get_public_creator_ecosystem_graph(text)from public;grant execute on function public.get_public_creator_ecosystem_graph(text)to anon,authenticated,service_role;

alter table public.creator_authenticity_assertions drop constraint creator_authenticity_assertions_assertion_version_check;
alter table public.creator_authenticity_assertions add constraint creator_authenticity_assertions_assertion_version_check check(assertion_version in('audienceown-authenticity-v1','audienceown-authenticity-v2'));
create or replace function public.store_authenticity_assertion(p_profile_id uuid,p_identity_revision bigint,p_presentation_revision bigint,p_trust_policy_version text,p_trust_state text,p_payload jsonb,p_payload_hash text,p_key_id text,p_signature text,p_issued_at timestamptz,p_expires_at timestamptz)returns uuid language plpgsql security definer set search_path=''as $$declare a public.creator_authenticity_profiles%rowtype;p public.creator_identity_profiles%rowtype;sid uuid;version text;begin if auth.role()<>'service_role'then raise exception'service role required'using errcode='42501';end if;select*into a from public.creator_authenticity_profiles where id=p_profile_id for update;select*into p from public.creator_identity_profiles where id=a.identity_profile_id;if not found or p.identity_revision<>p_identity_revision or a.presentation_revision<>p_presentation_revision then raise exception'stale authenticity revision'using errcode='40001';end if;if not exists(select 1 from public.authenticity_signing_keys where key_id=p_key_id and revoked_at is null)then raise exception'active public key required'using errcode='23514';end if;version:=p_payload->>'version';if version not in('audienceown-authenticity-v1','audienceown-authenticity-v2')then raise exception'unsupported assertion version'using errcode='23514';end if;update public.creator_authenticity_assertions set superseded_at=coalesce(superseded_at,now())where authenticity_profile_id=a.id and revoked_at is null and superseded_at is null;insert into public.creator_authenticity_assertions(creator_id,identity_profile_id,authenticity_profile_id,assertion_version,presentation_revision,identity_revision,trust_policy_version,trust_state,payload,payload_hash,key_id,signature,issued_at,expires_at)values(a.creator_id,a.identity_profile_id,a.id,version,p_presentation_revision,p_identity_revision,p_trust_policy_version,p_trust_state,p_payload,p_payload_hash,p_key_id,p_signature,p_issued_at,p_expires_at)returning id into sid;insert into public.creator_authenticity_events(creator_id,identity_profile_id,authenticity_profile_id,assertion_id,event_type,source,metadata)values(a.creator_id,a.identity_profile_id,a.id,sid,'assertion_issued','authenticity_worker',jsonb_build_object('keyId',p_key_id,'expiresAt',p_expires_at,'version',version));update public.creator_authenticity_profiles set issuance_lease_owner=null,issuance_lease_expires_at=null where id=a.id;return sid;end$$;

alter table public.creator_ecosystem_destinations enable row level security;alter table public.creator_ecosystem_destinations force row level security;
alter table public.creator_ecosystem_relationships enable row level security;alter table public.creator_ecosystem_relationships force row level security;
alter table public.ecosystem_verification_records enable row level security;alter table public.ecosystem_verification_records force row level security;
alter table public.ecosystem_events enable row level security;alter table public.ecosystem_events force row level security;
create policy"creator ecosystem destination reads"on public.creator_ecosystem_destinations for select to authenticated using(public.has_creator_permission(creator_id,'emergency_manage'));
create policy"creator ecosystem relationship reads"on public.creator_ecosystem_relationships for select to authenticated using(public.has_creator_permission(creator_id,'emergency_manage'));
create policy"creator ecosystem verification reads"on public.ecosystem_verification_records for select to authenticated using(public.has_creator_permission(creator_id,'emergency_manage'));
create policy"creator ecosystem event reads"on public.ecosystem_events for select to authenticated using(public.has_creator_permission(creator_id,'emergency_manage'));
revoke all on public.creator_ecosystem_destinations,public.creator_ecosystem_relationships,public.ecosystem_verification_records,public.ecosystem_events from public,anon,authenticated;
grant select on public.creator_ecosystem_destinations,public.creator_ecosystem_relationships,public.ecosystem_verification_records,public.ecosystem_events to authenticated;
grant select,insert,update,delete on public.creator_ecosystem_destinations,public.creator_ecosystem_relationships,public.ecosystem_verification_records,public.ecosystem_events to service_role;
grant usage,select on sequence public.ecosystem_events_id_seq to service_role;
commit;
