"use client";
import { useActionState, useRef, useState } from "react";
import { useFormStatus } from "react-dom";
import { Download } from "lucide-react";
import { QRCodeSVG } from "qrcode.react";

export type PresentationState={success?:string;error?:string};
export function PublicIdentityForm({action,initial,creatorName}:{action:(state:PresentationState,data:FormData)=>Promise<PresentationState>;initial:{title:string;summary:string;dates:boolean;history:boolean};creatorName:string}){const[state,formAction]=useActionState(action,{}),[title,setTitle]=useState(initial.title),[summary,setSummary]=useState(initial.summary);return <form action={formAction} className="identity-presentation-form"><label>Public title<input name="title" maxLength={100} value={title} onChange={event=>setTitle(event.target.value)} placeholder="Creator · Entrepreneur · Host"/><small>{title.length}/100</small></label><label>Public summary<textarea name="summary" maxLength={280} value={summary} onChange={event=>setSummary(event.target.value)} placeholder={`Official accounts and trusted recovery destinations for ${creatorName}.`}/><small>{summary.length}/280</small></label><Toggle name="timestamps" label="Show verification dates" checked={initial.dates}/><Toggle name="history" label="Show account continuity history" checked={initial.history}/><SaveButton/>{state.success&&<p role="status" className="form-success">{state.success}</p>}{state.error&&<p role="alert" className="form-error">{state.error}</p>}</form>}
function Toggle({name,label,checked}:{name:string;label:string;checked:boolean}){return <label className="identity-toggle"><input type="checkbox" name={name} defaultChecked={checked}/><span/><b>{label}</b></label>}
function SaveButton(){const{pending}=useFormStatus();return <button disabled={pending} className="button button-primary">{pending?"Saving…":"Save public profile"}</button>}
export function DownloadableVerificationQr({url,slug}:{url:string;slug:string}){const ref=useRef<SVGSVGElement>(null);function download(){if(!ref.current)return;const blob=new Blob([new XMLSerializer().serializeToString(ref.current)],{type:"image/svg+xml"}),link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=`audienceown-verification-${slug}.svg`;link.click();URL.revokeObjectURL(link.href);}return <div className="identity-qr"><div aria-label="QR code for canonical public verification page"><QRCodeSVG ref={ref} value={url} size={154} level="M" marginSize={4} bgColor="#ffffff" fgColor="#000000"/></div><button type="button" className="button button-secondary" onClick={download}><Download/>Download QR code</button></div>}
