import Link from "next/link";
import Image from "next/image";
import { ArrowRight, ChevronRight, ExternalLink, ShieldCheck, Sparkles } from "lucide-react";
import { requireCreator } from "@/lib/dal";
import { createClient } from "@/lib/supabase/server";
import { CopyLinkButton } from "@/components/copy-link-button";
import { ErrorState } from "@/components/product-state";
import { PlatformBrandIcon } from "@/components/dashboard/platform-brand-icon";
import { DownloadableVerificationQr, PublicIdentityForm } from "@/components/authenticity/verified-identity-controls";
import { PublicVerifiedIdentityView } from "@/components/authenticity/public-verified-identity";
import { getVerifiedIdentityDashboardData, type VerifiedIdentityAccount } from "@/lib/verified-identity-dashboard";
import { saveVerifiedIdentityPresentation } from "./actions";
import "./verified-identity.css";
import "./verified-identity-hardening.css";

const initials=(name:string)=>name.split(/\s+/).slice(0,2).map(part=>part[0]).join("").toUpperCase();
const statusLabel=(value:string)=>value==="verified"?"Verified":value==="needs_attention"?"Needs attention":value==="not_connected"?"Not connected":value==="pending"?"Pending":"Needs verification";

export default async function VerifiedIdentityPage(){const creator=await requireCreator(),db=await createClient();if(!db)return <IdentityError/>;let data;try{data=await getVerifiedIdentityDashboardData(db,creator);}catch{return <IdentityError/>;}const status=data.verification.summary;return <div className="verified-identity-page">
  <header className="identity-header"><div><p className="eyebrow">Verified identity</p><h1>Your verified presence</h1><p>Prove which accounts are really yours and give your audience a trusted place to verify you.</p></div><div><CopyLinkButton value={data.publicVerification.url} label="Copy verification link"/><Link className="button button-secondary" href={`/verify/${data.creator.slug}`} target="_blank"><ExternalLink/>Open public page</Link></div></header>
  <section className={`identity-hero ${data.verification.verified?"is-verified":data.verification.attention?"is-attention":"is-pending"}`}><div className="identity-hero-copy"><p className="eyebrow">Identity network</p><Avatar name={data.creator.displayName} avatar={data.creator.avatar}/><span className="hero-status"><ShieldCheck/>{data.verification.verified?"Verified identity":data.verification.attention?"Needs attention":"Verification pending"}</span><h2>{data.accounts.length?data.creator.displayName:"Build your verified presence"}</h2><p>{data.accounts.length?status:"Connect and verify your official accounts so followers have a trusted place to confirm your identity."}</p><dl><div><dt>Main accounts</dt><dd>{data.mainAccounts.length}</dd></div><div><dt>Recovery accounts</dt><dd>{data.recoveryAccounts.length}</dd></div></dl><Link className="button button-secondary" href="/dashboard/platforms">Manage accounts<ArrowRight/></Link></div><IdentityNetwork accounts={data.accounts} name={data.creator.displayName}/><div className="status-legend"><span className="verified"><i/>Verified</span><span className="pending"><i/>Pending</span><span className="attention"><i/>Needs attention</span><span className="disconnected"><i/>Not connected</span></div></section>
  <div className="identity-columns"><Card eyebrow="Your official accounts" title="Accounts associated with your identity" copy="Main and Recovery roles stay connected to your canonical account graph." action={<Link href="/dashboard/platforms">Manage accounts</Link>}><div className="official-account-list">{data.accounts.length?data.accounts.map(account=><AccountRow key={account.id} account={account}/>):<p className="identity-muted">Connected accounts will appear after you add them in Platforms.</p>}</div></Card><Card eyebrow="Your public verification page" title="A trusted page anyone can check" copy="Official accounts, recovery destinations, and current verification state are published safely."><code className="verification-url">{data.publicVerification.url}</code><p className="qr-guidance">Use this QR in videos, livestreams, websites, profile pages, or event materials so followers can verify your official identity.</p><div className="public-card-actions"><Link className="button button-secondary" href={`/verify/${data.creator.slug}`} target="_blank">Open public page</Link><CopyLinkButton value={data.publicVerification.url} label="Copy link"/></div><DownloadableVerificationQr url={data.publicVerification.url} slug={data.creator.slug}/></Card></div>
  <section className="follower-preview-card"><div className="section-heading"><p className="eyebrow">What followers will see</p><h2>Public verification preview</h2><p>This is a preview of your public verification page.</p></div>{data.publicIdentity?<PublicVerifiedIdentityView identity={data.publicIdentity} preview/>:<p className="identity-muted">Publish your verification page to preview the follower experience.</p>}</section>
  <div className="identity-columns lower"><Card eyebrow="Public identity presentation" title="Customize your public identity" copy="Control the creator-facing title and safe continuity details shown publicly."><PublicIdentityForm action={saveVerifiedIdentityPresentation} creatorName={data.creator.displayName} initial={{title:data.publicPresentation.title,summary:data.publicPresentation.summary,dates:data.publicPresentation.showVerificationDates,history:data.publicPresentation.showContinuityHistory}}/></Card><Card eyebrow="Verification health" title="Summary of your identity verification" copy="Creator verification is based on Main-account control. Recovery completeness contributes separately to identity strength."><div className="health-grid"><Health label="Creator verification" value={data.creatorVerification.verified?"Verified":"Pending"} state={data.creatorVerification.verified?"Verified":"Pending"} href="/dashboard/platforms"/><Health label="Main accounts" value={`${data.creatorVerification.verifiedMainAccountCount} of ${data.creatorVerification.totalMainAccountCount}`} state={data.creatorVerification.verified?"Verified":"Pending"} href="/dashboard/platforms"/><Health label="Recovery accounts" value={`${data.verificationHealth.recoveryVerified} of ${data.verificationHealth.recoveryTotal}`} state={data.verificationHealth.recoveryVerified===data.verificationHealth.recoveryTotal&&data.verificationHealth.recoveryTotal>0?"Verified":"Incomplete"} href="/dashboard/platforms"/><Health label="Public page" value={data.verificationHealth.publicPage?"Published":"Not published"} state={data.verificationHealth.publicPage?"Live":"Pending"} href="/dashboard/authenticity"/><Health label="Recovery Pass" value={data.verificationHealth.recoveryPass?"Active":"Inactive"} state={data.verificationHealth.recoveryPass?"Ready":"Incomplete"} href="/dashboard/creator-page"/></div><div className={`identity-strength strength-${data.identityStrength.toLowerCase().replace(" ","-")}`}><Sparkles/><span>Identity strength<strong>{data.identityStrength}</strong></span><small>{strengthExplanation(data)}</small></div></Card></div>
  </div>}
function IdentityError(){return <ErrorState title="Verified identity couldn’t be loaded." description="Your verification data was not changed." primaryAction={{label:"Try again",href:"/dashboard/authenticity"}}/>}
function Avatar({name,avatar}:{name:string;avatar:string|null}){return avatar?<span className="identity-avatar"><Image unoptimized fill sizes="60px" src={avatar} alt=""/></span>:<span className="identity-avatar fallback" aria-label={`${name} initials`}>{initials(name)}</span>}
function IdentityNetwork({accounts,name}:{accounts:VerifiedIdentityAccount[];name:string}){return <div className="identity-network" aria-label={`Connected identity network for ${name}`}><span className="network-core"><ShieldCheck/><b>{initials(name)}</b><small>Creator identity</small></span>{accounts.slice(0,6).map((account,index)=><span className={`network-node node-${index} status-${account.verificationStatus}`} key={account.id}><PlatformBrandIcon provider={account.provider} label={account.displayName} size="sm"/><b>{account.displayName}</b><small>{account.role}</small></span>)}</div>}
function Card({eyebrow,title,copy,action,children}:{eyebrow:string;title:string;copy:string;action?:React.ReactNode;children:React.ReactNode}){return <section className="identity-card"><div className="card-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2><p>{copy}</p></div>{action}</div>{children}</section>}
function AccountRow({account}:{account:VerifiedIdentityAccount}){return <Link href="/dashboard/platforms" className="official-account-row"><PlatformBrandIcon provider={account.provider} label={account.displayName}/><span><strong>{account.provider} · {account.displayName}</strong><small>{account.role} account</small></span><b className={`status-${account.verificationStatus}`}>{statusLabel(account.verificationStatus)}</b><ChevronRight/></Link>}
function Health({label,value,state,href}:{label:string;value:string;state:string;href:string}){return <Link href={href}><span>{label}</span><strong>{value}</strong><small>{state}</small><ChevronRight/></Link>}
function strengthExplanation(data:Awaited<ReturnType<typeof getVerifiedIdentityDashboardData>>){const recoveryGap=data.verificationHealth.recoveryTotal-data.verificationHealth.recoveryVerified,officialGap=data.verificationHealth.officialTotal-data.verificationHealth.officialVerified;if(data.identityStrength==="Strong")return"All public identity safeguards are ready.";if(data.identityStrength==="Needs attention")return"One or more identity signals require review.";if(officialGap>0)return`${officialGap} Main ${officialGap===1?"account requires":"accounts require"} verification.`;if(recoveryGap>0)return`${recoveryGap} Recovery ${recoveryGap===1?"account requires":"accounts require"} verification.`;if(!data.verificationHealth.publicPage)return"Publish your verification page to strengthen your identity.";if(!data.verificationHealth.recoveryPass)return"Activate Recovery Pass to complete your public safety layer.";return"Core identity is verified; optional recovery coverage remains."}
